#! /bin/bash 
scidir="/usr/"
mkdir -p ../local/packages/NPSOL
touch    ../local/packages/NPSOL/npsolsubs.f
echo "cmake_minimum_required(VERSION 2.6)" > ../local/packages/NPSOL/CMakeLists.txt
echo "project("NPSOL" C)" >> ../local/packages/NPSOL/CMakeLists.txt
rm -rf *
#cmake ../
#cmake	-DDAKOTA_SCILAB:BOOL=ON ../
cmake   -DDAKOTA_SCILIB:BOOL=ON \
		-DSCILAB_USER_PATH=$scidir ../ || exit 1 

#cmake   -DDAKOTA_SCILIB:BOOL=ON \
#		-DSCILAB_USER_PATH=/usr/include/scilab/ \
#		-DDAKOTA_PYTHON:BOOL=ON\
#		-DDAKOTA_PYTHON_NUMPY:BOOL=ON\
 #       -DDAKOTA_HAVE_GSL:BOOL=ON \
#		-DHAVE_QUESO:BOOL=ON \
#		-DHAVE_X_GRAPHICS:BOOL=ON ../ || exit 1
ld1="-lieee -lSM -lncurses -L/usr/lib/x86_64-linux-gnu -ltk8.5 -L/usr/lib/x86_64-linux-gnu -ltcl8.5 -ldl -I/usr/include/libxml2 -I$scidir/include/scilab -L$scidir/lib/thirdparty -L$scidir/lib/scilab -lscilab -lxml2 -lpcre"
ld2="-lsciaction_binding -lsciarnoldi -lscicall_scilab -lscicommons -lscicompletion -lsciconsole -lsciconsole-minimal -lsciexternal_objects -lsciexternal_objects_java -lscifunctions  -lscihelptools -lscihistory_browser -lscihistory_manager -lsciinterpolation -lscijvm -lscilab -lscilocalization -lscimatio -lscioptimization -lsciparallel  -lscirenderer -lsciscicos -lsciscicos_blocks -lsciscicos_blocks-cli -lsciscicos-cli -lsciscinotes -lscisignal_processing -lscisound -lscispecial_functions -lscispreadsheet -lscistatistics -lscisundials -lscisymbolic -lscitclsci -lscitypes -lsciui_data -lsciumfpack -lscixcos -lscixml"

find . -type f -exec ls  {} \; 2> /dev/null | sort -t' ' -k +6,6 -k +7,7|grep link.txt >/tmp/filename
for i in $(cat /tmp/filename|tr " " "?")             
  do
  	sed -i 's/-lnpsol/-lnpsol -lgfortran/g'  "$i"
	sed -i "s!libscilab.so!libscilab.so -L/usr/lib/jni/ -L$scidir/lib/scilab -lscilab -ljavasci2 !g"  "$i"
  done
ln -s src bin
make -j32 && .release
#
