PECOS: SharedInterpPolyApproxData Class Reference
SharedInterpPolyApproxData Class Reference abstract
Derived approximation class for interpolation polynomials (global approximation).
Public Member Functions
SharedInterpPolyApproxData (short basis_type, size_t num_vars)
standard constructor
SharedInterpPolyApproxData (short basis_type, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
alternate constructor
~SharedInterpPolyApproxData ()
destructor
Public Member Functions inherited from SharedPolyApproxData
SharedPolyApproxData ()
default constructor
SharedPolyApproxData (short basis_type, size_t num_vars)
standard constructor
SharedPolyApproxData (short basis_type, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
alternate constructor with full configuration options
~SharedPolyApproxData ()
destructorboth
virtual void pre_push_data ()
restores previously popped approximation data
virtual void pre_finalize_data ()
finalizes the shared approximation data following a set of increments
virtual void post_combine_data ()
combines current and stored approximation data
bool push_available ()
test for whether current trial set requires a new approximation increment or can be restored from a previous trial
size_t retrieval_index ()
returns index of the data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex)
size_t finalization_index (size_t i)
returns index of the i-th data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex) during finalization
void configuration_options (const ExpansionConfigOptions &ec_options)
set expConfigOptions as a group (instead of per option below)
void configuration_options (const BasisConfigOptions &bc_options)
set basisConfigOptions (instead of per option below)
const BitArrayULongMap & sobol_index_map () const
return sobolIndexMap
void integration_driver_rep (IntegrationDriver *driver_rep)
set driverRep
void random_variables_key (const BitArray &random_vars_key)
set randomVarsKey
Public Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData ()
default constructor
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars)
standard constructor for envelope
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options, const RegressionConfigOptions &rc_options)
alternate constructor for envelope
SharedBasisApproxData (const SharedBasisApproxData &shared_data)
copy constructor
virtual ~SharedBasisApproxData ()
destructor
SharedBasisApproxData operator= (const SharedBasisApproxData &shared_data)
assignment operator
void assign_rep (SharedBasisApproxData *data_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
SharedBasisApproxData * data_rep () const
returns dataRep for access to derived class member functions that are not mapped to the top Approximation level
Static Public Member Functions
static bool initialize_driver_types_rules (const ShortArray &u_types, const BasisConfigOptions &bc_options, ShortArray &basis_types, ShortArray &colloc_rules)
define n-D basis types and collocation rules based on u_types and basis configuration options for use in configuring integration drivers
static void construct_basis (const ShortArray &u_types, const AleatoryDistParams &adp, const BasisConfigOptions &bc_options, std::vector< BasisPolynomial > &poly_basis)
initialize basis types and collocation rules, construct a vector of basis polynomials for driver usage (not the vector<vector<BasisPolynomial> > used herein), and initialize distribution parameters within this basis
Static Public Member Functions inherited from SharedPolyApproxData
static bool initialize_orthogonal_basis_types_rules (const ShortArray &u_types, const BasisConfigOptions &bc_options, ShortArray &basis_types, ShortArray &colloc_rules)
allocate orthogonal polynomial basis types and integration rules based on u_types and rule options
static bool initialize_orthogonal_basis_type_rule (short u_type, const BasisConfigOptions &bc_options, short &basis_type, short &colloc_rule)
assign orthogonal polynomial basis type and integration rule based on u_type and basis configuration options
static void initialize_polynomial_basis (const ShortArray &basis_types, const ShortArray &colloc_rules, std::vector< BasisPolynomial > &poly_basis)
allocate poly_basis based on basis_types and colloc_rules
static void update_basis_distribution_parameters (const ShortArray &u_types, const AleatoryDistParams &dp, std::vector< BasisPolynomial > &poly_basis)
pass distribution parameters from dp to poly_basis
static size_t total_order_terms (const UShortArray &upper_bound, short lower_bound_offset=-1)
return the number of expansion terms for a total order expansion with the provided (anisotropic) upper_bound array specification
static size_t tensor_product_terms (const UShortArray &order, bool include_upper_bound=true)
return the number of expansion terms for a tensor-product expansion with the provided (anisotropic) quadrature orders (include_upper_bound = false) or expansion orders (default)
static void tensor_product_multi_index (const UShortArray &order, UShort2DArray &multi_index, bool include_upper_bound=true)
initialize expansion multi_index using a tensor-product expansion
static void hierarchical_tensor_product_multi_index (const UShort2DArray &delta_quad, UShort2DArray &multi_index)
initialize multi_index using a hierarchical tensor-product expansion
static void total_order_multi_index (unsigned short level, size_t num_vars, UShort2DArray &multi_index)
initialize multi_index using a total-order expansion from a scalar level
static void total_order_multi_index (const UShortArray &upper_bound, UShort2DArray &multi_index, short lower_bound_offset=-1, size_t max_terms=_NPOS)
initialize expansion multi_index using a total-order expansion from an upper_bound array specification
static void increment_indices (UShortArray &indices, const UShortArray &limits, bool include_upper_bound)
utility function for incrementing a set of multidimensional indices
static void increment_terms (UShortArray &terms, size_t &last_index, size_t &prev_index, size_t term_limit, bool &order_complete)
utility function for incrementing a set of multidimensional terms
Protected Member Functions
void allocate_data (size_t index=_NPOS)
allocate the shared data prior to building the set of approximations
void increment_data (size_t index=_NPOS)
update the shared data prior to rebuilding the set of approximations
void decrement_data ()
decrement the previous increment and store its shared data for later retrieval
void post_push_data ()
restores previously popped approximation data
void post_finalize_data ()
finalizes the shared approximation data following a set of increments
size_t pre_combine_data ()
combines current and stored approximation data
void store_data (size_t index=_NPOS)
stores current approximation data for later combination
void restore_data (size_t index=_NPOS)
restores previously stored approximation data
void remove_stored_data (size_t index=_NPOS)
removes a redundant stored approximation data prior to combination
void clear_stored_data ()
clear stored approximation data
virtual void allocate_component_sobol ()=0
allocate sobolIndexMap based on collocation keys
virtual void increment_component_sobol ()=0
update sobolIndexMap based on a refinement increment
virtual void set_new_point (const RealVector &x, const UShortArray &basis_index, short order)=0
set point values within 1D basis polynomials for purposes of barycentric precomputation
virtual void set_new_point (const RealVector &x, const UShortArray &basis_index, const SizetList &subset_indices, short order)=0
set point values within subset of 1D basis polynomials for purposes of barycentric precomputation
virtual size_t barycentric_exact_index (const UShortArray &basis_index)=0
for an exact point match in all dimensions, return the tensor-product index of the matching point
virtual size_t barycentric_exact_index (const UShortArray &basis_index, const SizetList &subset_indices)=0
for an exact point match in all dimensions within subset_indices, return the tensor-product index of the matching point
virtual void precompute_keys (const UShortArray &basis_index)
if needed for efficiency, precompute the count and max values for the collocation keys
virtual void precompute_keys (const UShortArray &basis_index, const SizetList &subset_indices)
if needed for efficiency, precompute the count and max values for the collocation keys within the subset
virtual void precompute_max_keys (const UShortArray &basis_index)
if needed for efficiency, precompute the max values for the collocation keys
virtual void precompute_max_keys (const UShortArray &basis_index, const SizetList &subset_indices)
if needed for efficiency, precompute the max values for the collocation keys within the subset
virtual unsigned short tensor_product_num_key (size_t i, unsigned short level_i)
return the number of collocation keys for i^{th} variable and level_i index set
virtual unsigned short tensor_product_max_key (size_t i, unsigned short level_i)
return the maximum collocation key value for i^{th} variable and level_i index set
Real type1_interpolant_value (const RealVector &x, const UShortArray &key, const UShortArray &basis_index)
return value of type 1 interpolation polynomial using all dimensions
Real type1_interpolant_value (const RealVector &x, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return value of type 1 interpolation polynomial using interpolated (non-integrated) dimension subset
Real type1_interpolant_gradient (const RealVector &x, size_t deriv_index, const UShortArray &key, const UShortArray &basis_index)
return gradient of type 1 interpolation polynomial using all dimensions
Real type1_interpolant_gradient (const RealVector &x, size_t deriv_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return gradient of type 1 interpolation polynomial using interpolated (non-integrated) dimension subset
Real type2_interpolant_value (const RealVector &x, size_t interp_index, const UShortArray &key, const UShortArray &basis_index)
return value of type 2 interpolation polynomial using all dimensions
Real type2_interpolant_value (const RealVector &x, size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return value of type 2 interpolation polynomial using interpolated (non-integrated) dimension subset
Real type2_interpolant_gradient (const RealVector &x, size_t deriv_index, size_t interp_index, const UShortArray &key, const UShortArray &basis_index)
return gradient of type 2 interpolation polynomial using all dimensions
Real type2_interpolant_gradient (const RealVector &x, size_t deriv_index, size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return gradient of type 2 interpolation polynomial using interpolated (non-integrated) dimension subset
size_t barycentric_active_variables (const UShortArray &basis_index)
compute the number of variables that are active for barycentric interpolation
size_t barycentric_active_variables (const UShortArray &basis_index, const SizetList &subset_indices)
compute the number of variables within subset_indices that are active for barycentric interpolation
Real barycentric_value_factor (const UShortArray &key, const UShortArray &basis_index)
compute the product of 1D barycentric value factors
Real barycentric_value_factor (const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric value factors
Real barycentric_value_scaling (const UShortArray &basis_index)
compute the product of 1D barycentric weight factor sums for use in the denominator of the barycentric interpolation formula (second form)
Real barycentric_value_scaling (const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric weight factor sums for use in the denominator of the barycentric interpolation formula (second form)
Real barycentric_gradient_factor (size_t deriv_index, const UShortArray &key, const UShortArray &basis_index)
compute the product of 1D barycentric gradient factors
Real barycentric_gradient_factor (size_t deriv_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric gradient factors
Real barycentric_gradient_scaling (const UShortArray &basis_index)
compute the product of 1D barycentric gradient scalings
Real barycentric_gradient_scaling (const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric gradient scalings
Real type1_weight (const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return type 1 product weight from integration of type 1 interpolation polynomials using integrated dimension subset
void type1_weight (const UShortArray &key, const UShortArray &basis_index, const BitArray &member_bits, Real &member_t1_wt_prod, Real &nonmember_t1_wt_prod)
return type 1 product weights from integration of type 1 interpolation polynomials for both member and nonmember sets
Real type2_weight (size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return type 2 product weight from integration of type 1/2 interpolation polynomials using integrated dimension subset
void type2_weight (size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const BitArray &member_bits, Real &member_t2_wt_prod, Real &nonmember_t2_wt_prod)
return type 2 product weight from integration of type 1/2 interpolation polynomials for both member and nonmember sets
Real tensor_product_value (const RealVector &x, const RealVector &exp_t1_coeffs, const RealMatrix &exp_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index)
compute the value of a tensor interpolant on a tensor grid; contributes to value(x)
Real tensor_product_value (const RealVector &x, const RealVector &subset_t1_coeffs, const RealMatrix &subset_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &subset_key, const SizetArray &subset_colloc_index, const SizetList &subset_indices)
compute the value of a tensor interpolant on a tensor grid over a subset of the variables; contributes to value(x)
const RealVector & tensor_product_gradient_basis_variables (const RealVector &x, const RealVector &exp_t1_coeffs, const RealMatrix &exp_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are included in the polynomial basis; contributes to gradient_basis_variables(x)
const RealVector & tensor_product_gradient_basis_variables (const RealVector &x, const RealVector &subset_t1_coeffs, const RealMatrix &subset_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &subset_key, const SizetArray &subset_colloc_index, const SizetList &subset_indices)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are included in the polynomial basis; contributes to gradient_basis_variables(x)
const RealVector & tensor_product_gradient_basis_variables (const RealVector &x, const RealVector &exp_t1_coeffs, const RealMatrix &exp_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index, const SizetArray &dvv)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are included in the polynomial basis for given DVV; contributes to gradient_basis_variables(x, dvv)
const RealVector & tensor_product_gradient_nonbasis_variables (const RealVector &x, const RealMatrix &exp_t1_coeff_grads, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are not included in the polynomial basis; contributes to gradient_nonbasis_variables(x)
void resize_polynomial_basis (unsigned short max_level)
resize polynomialBasis to accomodate an update in max interpolation level
void resize_polynomial_basis (const UShortArray &lev_index)
resize polynomialBasis to accomodate an update in interpolation levels
void update_tensor_interpolation_basis (const UShortArray &lev_index, const SizetList &subset_indices)
update polynomialBasis for a subset of variables after a change in quadrature order
bool same_basis (unsigned short level, size_t v1, size_t v2)
for a particular level, test for equality between basis v2 and basis v1
Protected Member Functions inherited from SharedPolyApproxData
bool match_random_key (const UShortArray &key_1, const UShortArray &key_2) const
return true if matching key values within random variable subset
bool match_nonrandom_vars (const RealVector &vars_1, const RealVector &vars_2) const
return true if matching variable values within nonrandom variable subset
void allocate_main_sobol ()
allocate sobolIndices and sobolIndexMap for main effects only
void multi_index_to_sobol_index_map (const UShort2DArray &mi)
Define the sobolIndexMap (which defines the set of Sobol' indices) from the incoming multi-index. sobolIndexMap values are initialized to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void reset_sobol_index_map_values ()
return the sobolIndexMap values to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void assign_sobol_index_map_values ()
Define the mapping from sobolIndexMap into sobolIndices.
bool push_available (const UShortArray &trial_set)
check for the presence of trial_set within poppedLevMultiIndex
Protected Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData (BaseConstructor, short basis_type, size_t num_vars)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
std::vector< std::vector< BasisPolynomial > > polynomialBasis
2D array of one-dimensional basis polynomial objects used in constructing the multivariate orthogonal/interpolation polynomials.
bool barycentricFlag
flag indicating use of barycentric interpolation for global value-based Lagrange interpolation
Protected Attributes inherited from SharedPolyApproxData
IntegrationDriver * driverRep
pointer to integration driver instance
ExpansionConfigOptions expConfigOptions
an encapsulation of expansion configuration options
BasisConfigOptions basisConfigOptions
an encapsulation of basis configuration options
UShortArray quadOrderPrev
previous quadrature order; used for tracking need for expansion form updates
unsigned short ssgLevelPrev
previous Smolyak sparse grid level; used for tracking need for expansion form updates
RealVector ssgAnisoWtsPrev
previous Smolyak sparse grid anisotropic weighting; used for tracking need for expansion form updates
BitArray randomVarsKey
array of bits identifying the random variable subset within the active variables (used in all_variables mode)
SizetList randomIndices
list of indices identifying the random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
SizetList nonRandomIndices
list of indices identifying the non-random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
std::deque< UShortArray > poppedLevMultiIndex
popped trial sets that were computed but not selected
BitArrayULongMap sobolIndexMap
mapping to manage different global sensitivity index options (e.g. univariate/main effects only vs all effects)
Protected Attributes inherited from SharedBasisApproxData
short basisType
type of derived instance as well as sub-type for interpolation
size_t numVars
number of variables used in the approximation
Private Member Functions
void initialize_polynomial_basis_type (short &poly_type_1d, short &rule)
define the 1D basis type and collocation rule
void update_tensor_interpolation_basis (const UShortArray &lev_index)
update polynomialBasis after a change in quadrature order
void update_sparse_interpolation_basis (unsigned short max_level)
update polynomialBasis after a change in sparse grid level
void update_interpolation_basis (unsigned short lev_index, size_t var_index)
update polynomialBasis for a variable index after an update in level
bool find_basis (unsigned short level, size_t v1, size_t &v2)
for a particular level, find index of basis v2 that matches basis v1
bool barycentric_value_factor (BasisPolynomial &pb_lv, unsigned short key_lv, Real &prod)
compute the product of 1D barycentric value factors
void barycentric_partial_indexing (const UShortArray &basis_index, SizetList &pt_factors, SizetList &act_v_set, size_t &num_act_pts, size_t &pt_index)
shared utility for barycentric interpolation over a partial variable subset: define pt_factors, act_v_set, num_act_pts, and return pt_index
void barycentric_partial_indexing (const UShortArray &basis_index, const SizetList &subset_indices, SizetList &pt_factors, SizetList &act_v_set, size_t &num_act_pts, size_t &pt_index)
shared utility for barycentric interpolation over a partial variable subset: define pt_factors, act_v_set, num_act_pts, and return pt_index
void accumulate_barycentric_partial (const RealVector &t1_coeffs, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index, const SizetList &pt_factors, const SizetList &act_v_set, size_t num_act_pts, size_t pt_index, RealVector &accumulator)
shared code for barycentric interpolation over an active variable subset
void accumulate_barycentric_gradient (unsigned short bi0, unsigned short key_i0, size_t ei_0, Real *accum_0, Real t1_coeff, const RealVector &bc_vf_0, const RealVector &bc_gf_0)
shared code for barycentric gradient evaluation for active variable 0
void accumulate_barycentric_gradient (size_t j, unsigned short bij, unsigned short key_ij, BasisPolynomial &poly_j, RealMatrix &accumulator)
shared code for barycentric gradient evaluation for active variables 1:n
Private Attributes
RealVector tpGradient
the gradient of a tensor-product interpolant; a contributor to approxGradient
Friends
class InterpPolyApproximation
Detailed Description
Derived approximation class for interpolation polynomials (global approximation).
The SharedInterpPolyApproxData class provides a global approximation based on interpolation polynomials. It is used primarily for stochastic collocation approaches to uncertainty quantification.
Member Function Documentation
bool initialize_driver_types_rules (const ShortArray & u_types, const BasisConfigOptions & bc_options, ShortArray & basis_types, ShortArray & colloc_rules) static
define n-D basis types and collocation rules based on u_types and basis configuration options for use in configuring integration drivers
These basis types may include orthogonal polynomials for purposes of computing their Gauss points and weights within integration drivers; thus they differ in general from the interpolation polynomial basis used for approximation.
This version provides the polynomial types needed to retrieve collocation points and weights by an integration driver. These may involve orthogonal polynomials which will differ from the interpolation polynomial types used in the basis.
References BasisConfigOptions::equidistantRules, BasisConfigOptions::gaussRuleOverride, SharedPolyApproxData::initialize_orthogonal_basis_type_rule(), SharedInterpPolyApproxData::initialize_polynomial_basis_type(), BasisConfigOptions::nestedRules, BasisConfigOptions::openRuleOverride, BasisConfigOptions::piecewiseBasis, and BasisConfigOptions::useDerivs.
Referenced by SharedInterpPolyApproxData::construct_basis(), and IntegrationDriver::initialize_grid().
void precompute_keys (const UShortArray & basis_index) inline protected virtual
if needed for efficiency, precompute the count and max values for the collocation keys
Default implementation; overridden by HierarchInterpPolyApproxData.
Reimplemented in SharedHierarchInterpPolyApproxData.
Referenced by SharedInterpPolyApproxData::barycentric_active_variables(), and SharedInterpPolyApproxData::barycentric_partial_indexing().
void precompute_keys (const UShortArray & basis_index, const SizetList & subset_indices) inline protected virtual
if needed for efficiency, precompute the count and max values for the collocation keys within the subset
Default implementation; overridden by HierarchInterpPolyApproxData.
Reimplemented in SharedHierarchInterpPolyApproxData.
References SharedInterpPolyApproxData::precompute_max_keys().
void precompute_max_keys (const UShortArray & basis_index) inline protected virtual
if needed for efficiency, precompute the max values for the collocation keys
Default implementation; overridden by HierarchInterpPolyApproxData.
Reimplemented in SharedHierarchInterpPolyApproxData.
Referenced by SharedInterpPolyApproxData::precompute_keys(), SharedInterpPolyApproxData::tensor_product_gradient_basis_variables(), SharedInterpPolyApproxData::tensor_product_gradient_nonbasis_variables(), and SharedInterpPolyApproxData::tensor_product_value().
void precompute_max_keys (const UShortArray & basis_index, const SizetList & subset_indices) inline protected virtual
if needed for efficiency, precompute the max values for the collocation keys within the subset
Default implementation; overridden by HierarchInterpPolyApproxData.
Reimplemented in SharedHierarchInterpPolyApproxData.
References SharedInterpPolyApproxData::tensor_product_num_key().
unsigned short tensor_product_num_key (size_t i, unsigned short level_i) inline protected virtual
return the number of collocation keys for i^{th} variable and level_i index set
Default implementation; overridden by HierarchInterpPolyApproxData.
Reimplemented in SharedHierarchInterpPolyApproxData.
References SharedInterpPolyApproxData::polynomialBasis, and SharedInterpPolyApproxData::tensor_product_max_key().
Referenced by SharedInterpPolyApproxData::accumulate_barycentric_partial(), SharedInterpPolyApproxData::barycentric_partial_indexing(), SharedInterpPolyApproxData::precompute_max_keys(), and SharedInterpPolyApproxData::tensor_product_gradient_nonbasis_variables().
unsigned short tensor_product_max_key (size_t i, unsigned short level_i) inline protected virtual
return the maximum collocation key value for i^{th} variable and level_i index set
Default implementation; overridden by HierarchInterpPolyApproxData.
Reimplemented in SharedHierarchInterpPolyApproxData.
References SharedInterpPolyApproxData::barycentric_partial_indexing(), and SharedInterpPolyApproxData::polynomialBasis.
Referenced by SharedInterpPolyApproxData::accumulate_barycentric_partial(), SharedInterpPolyApproxData::tensor_product_gradient_basis_variables(), SharedInterpPolyApproxData::tensor_product_gradient_nonbasis_variables(), SharedInterpPolyApproxData::tensor_product_num_key(), and SharedInterpPolyApproxData::tensor_product_value().
Real type1_interpolant_value (const RealVector & x, const UShortArray & key, const UShortArray & basis_index, const SizetList & subset_indices) inline protected
return value of type 1 interpolation polynomial using interpolated (non-integrated) dimension subset
Combined expansion version.
References SharedInterpPolyApproxData::polynomialBasis, and SharedInterpPolyApproxData::type1_interpolant_gradient().
Real type1_interpolant_gradient (const RealVector & x, size_t deriv_index, const UShortArray & key, const UShortArray & basis_index, const SizetList & subset_indices) inline protected
return gradient of type 1 interpolation polynomial using interpolated (non-integrated) dimension subset
Combined expansion version.
References SharedInterpPolyApproxData::polynomialBasis, and SharedInterpPolyApproxData::type2_interpolant_value().
Real type2_interpolant_value (const RealVector & x, size_t interp_index, const UShortArray & key, const UShortArray & basis_index, const SizetList & subset_indices) inline protected
return value of type 2 interpolation polynomial using interpolated (non-integrated) dimension subset
Combined expansion version.
References SharedInterpPolyApproxData::polynomialBasis, and SharedInterpPolyApproxData::type2_interpolant_gradient().
Real type2_interpolant_gradient (const RealVector & x, size_t deriv_index, size_t interp_index, const UShortArray & key, const UShortArray & basis_index, const SizetList & subset_indices) inline protected
return gradient of type 2 interpolation polynomial using interpolated (non-integrated) dimension subset
Combined expansion version.
References SharedInterpPolyApproxData::barycentric_active_variables(), and SharedInterpPolyApproxData::polynomialBasis.
Real barycentric_gradient_factor (size_t deriv_index, const UShortArray & key, const UShortArray & basis_index, const SizetList & subset_indices) inline protected
compute the product of a subset of 1D barycentric gradient factors
Combined expansion version.
References BasisPolynomial::barycentric_gradient_factor(), SharedInterpPolyApproxData::barycentric_gradient_scaling(), BasisPolynomial::barycentric_value_factor(), and SharedInterpPolyApproxData::polynomialBasis.
Real type1_weight (const UShortArray & key, const UShortArray & basis_index, const SizetList & subset_indices) inline protected
return type 1 product weight from integration of type 1 interpolation polynomials using integrated dimension subset
Combined expansion partial weight.
References SharedPolyApproxData::driverRep, and IntegrationDriver::type1_collocation_weights_1d().
Referenced by SharedInterpPolyApproxData::barycentric_gradient_scaling(), HierarchInterpPolyApproximation::expectation(), HierarchInterpPolyApproximation::expectation_gradient(), HierarchInterpPolyApproximation::member_coefficients_weights(), NodalInterpPolyApproximation::tensor_product_covariance(), and NodalInterpPolyApproximation::tensor_product_variance_gradient().
void type1_weight (const UShortArray & key, const UShortArray & basis_index, const BitArray & member_bits, Real & member_t1_wt_prod, Real & nonmember_t1_wt_prod) inline protected
return type 1 product weights from integration of type 1 interpolation polynomials for both member and nonmember sets
VBD member and non-member partial weights.
References SharedPolyApproxData::driverRep, IntegrationDriver::type1_collocation_weights_1d(), and SharedInterpPolyApproxData::type2_weight().
Real type2_weight (size_t interp_index, const UShortArray & key, const UShortArray & basis_index, const SizetList & subset_indices) inline protected
return type 2 product weight from integration of type 1/2 interpolation polynomials using integrated dimension subset
Combined expansion partial weight.
References SharedPolyApproxData::driverRep, IntegrationDriver::type1_collocation_weights_1d(), and IntegrationDriver::type2_collocation_weights_1d().
Referenced by HierarchInterpPolyApproximation::expectation(), HierarchInterpPolyApproximation::expectation_gradient(), NodalInterpPolyApproximation::member_coefficients_weights(), HierarchInterpPolyApproximation::member_coefficients_weights(), and SharedInterpPolyApproxData::type1_weight().
void type2_weight (size_t interp_index, const UShortArray & key, const UShortArray & basis_index, const BitArray & member_bits, Real & member_t2_wt_prod, Real & nonmember_t2_wt_prod) inline protected
return type 2 product weight from integration of type 1/2 interpolation polynomials for both member and nonmember sets
Combined expansion partial weight.
References SharedPolyApproxData::driverRep, IntegrationDriver::type1_collocation_weights_1d(), and IntegrationDriver::type2_collocation_weights_1d().
Real tensor_product_value (const RealVector & x, const RealVector & exp_t1_coeffs, const RealMatrix & exp_t2_coeffs, const UShortArray & basis_index, const UShort2DArray & key, const SizetArray & colloc_index) protected
compute the value of a tensor interpolant on a tensor grid; contributes to value(x)
Barycentric approach is only valid for value-based global Lagrange interpolation, either nodal or hierarchical. General approach is valid for value-based or gradient-enhanced, local or global, and nodal or hierarchical.
References SharedInterpPolyApproxData::accumulate_barycentric_partial(), SharedInterpPolyApproxData::barycentric_active_variables(), SharedInterpPolyApproxData::barycentric_exact_index(), SharedInterpPolyApproxData::barycentric_partial_indexing(), SharedInterpPolyApproxData::barycentric_value_scaling(), SharedInterpPolyApproxData::barycentricFlag, SharedBasisApproxData::numVars, SharedInterpPolyApproxData::polynomialBasis, SharedInterpPolyApproxData::precompute_max_keys(), SharedInterpPolyApproxData::set_new_point(), SharedInterpPolyApproxData::tensor_product_max_key(), BasisPolynomial::type1_value(), and BasisPolynomial::type2_value().
Referenced by SharedInterpPolyApproxData::same_basis(), and HierarchInterpPolyApproximation::value().
Real tensor_product_value (const RealVector & x, const RealVector & subset_t1_coeffs, const RealMatrix & subset_t2_coeffs, const UShortArray & basis_index, const UShort2DArray & subset_key, const SizetArray & subset_colloc_index, const SizetList & subset_indices) protected
compute the value of a tensor interpolant on a tensor grid over a subset of the variables; contributes to value(x)
All variables version.
References SharedInterpPolyApproxData::accumulate_barycentric_partial(), SharedInterpPolyApproxData::barycentric_active_variables(), SharedInterpPolyApproxData::barycentric_exact_index(), SharedInterpPolyApproxData::barycentric_partial_indexing(), SharedInterpPolyApproxData::barycentric_value_scaling(), SharedInterpPolyApproxData::barycentricFlag, SharedBasisApproxData::numVars, SharedInterpPolyApproxData::polynomialBasis, SharedInterpPolyApproxData::precompute_max_keys(), SharedInterpPolyApproxData::set_new_point(), SharedInterpPolyApproxData::tensor_product_gradient_basis_variables(), SharedInterpPolyApproxData::tensor_product_max_key(), SharedInterpPolyApproxData::type1_interpolant_value(), and SharedInterpPolyApproxData::type2_interpolant_value().
Member Data Documentation
std::vector<std::vector<BasisPolynomial> > polynomialBasis protected
2D array of one-dimensional basis polynomial objects used in constructing the multivariate orthogonal/interpolation polynomials.
Each variable (inner array size = numVars) has multiple integration orders associated with it (outer array size).
Referenced by SharedNodalInterpPolyApproxData::accumulate_barycentric(), SharedNodalInterpPolyApproxData::accumulate_barycentric_gradient(), SharedInterpPolyApproxData::accumulate_barycentric_partial(), SharedNodalInterpPolyApproxData::accumulate_horners(), SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), SharedInterpPolyApproxData::barycentric_active_variables(), SharedHierarchInterpPolyApproxData::barycentric_exact_index(), SharedNodalInterpPolyApproxData::barycentric_exact_index(), SharedInterpPolyApproxData::barycentric_gradient_factor(), SharedInterpPolyApproxData::barycentric_gradient_scaling(), SharedInterpPolyApproxData::barycentric_partial_indexing(), SharedInterpPolyApproxData::barycentric_value_factor(), SharedInterpPolyApproxData::barycentric_value_scaling(), SharedNodalInterpPolyApproxData::basis_product(), SharedInterpPolyApproxData::find_basis(), SharedInterpPolyApproxData::resize_polynomial_basis(), SharedHierarchInterpPolyApproxData::set_new_point(), SharedNodalInterpPolyApproxData::set_new_point(), NodalInterpPolyApproximation::tensor_product_covariance(), SharedInterpPolyApproxData::tensor_product_gradient_basis_variables(), SharedInterpPolyApproxData::tensor_product_gradient_nonbasis_variables(), SharedInterpPolyApproxData::tensor_product_max_key(), NodalInterpPolyApproximation::tensor_product_mean(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), SharedInterpPolyApproxData::tensor_product_num_key(), SharedInterpPolyApproxData::tensor_product_value(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), SharedInterpPolyApproxData::type1_interpolant_gradient(), SharedInterpPolyApproxData::type1_interpolant_value(), SharedInterpPolyApproxData::type2_interpolant_gradient(), SharedInterpPolyApproxData::type2_interpolant_value(), SharedInterpPolyApproxData::update_interpolation_basis(), and SharedNodalInterpPolyApproxData::update_nonzero_basis_products().
The documentation for this class was generated from the following files:
SharedInterpPolyApproxData.hpp
SharedInterpPolyApproxData.cpp