PECOS: NormalRandomVariable Class Reference
NormalRandomVariable Class Reference
Derived random variable class for Gaussian random variables.
Public Member Functions
NormalRandomVariable ()
constructor
NormalRandomVariable (Real mean, Real stdev)
alternate constructor
~NormalRandomVariable ()
destructor
Real cdf (Real x) const
return the cumulative distribution function value of the random variable at x
Real ccdf (Real x) const
return the complementary cumulative distribution function value of the random variable at x
Real inverse_cdf (Real p_cdf) const
return the x value corresponding to a cumulative probability
Real inverse_ccdf (Real p_ccdf) const
return the x value corresponding to a complementary cumulative probability
Real pdf (Real x) const
return the value of the random variable's probability density function at x
Real pdf_gradient (Real x) const
return the gradient of the random variable's probability density function at x
Real pdf_hessian (Real x) const
return the hessian of the random variable's probability density function at x
Real log_pdf (Real x) const
return the value of the natural log of the random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
Real log_pdf_gradient (Real x) const
return the gradient of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
Real log_pdf_hessian (Real x) const
return the Hessian of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
Real inverse_standard_cdf (Real p_cdf) const
return the x value for a standardized probability distribution corresponding to a cumulative probability
Real standard_pdf (Real z) const
return the value of a standardized random variable's probability density function at x
Real log_standard_pdf (Real z) const
return the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
Real log_standard_pdf_gradient (Real z) const
return the gradient of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
Real log_standard_pdf_hessian (Real z) const
return the Hessian of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
Real to_standard (Real x) const
scale variable value x from current to standardized distribution
Real from_standard (Real z) const
scale variable value z from standardized to current distribution
Real parameter (short dist_param) const
return the value of the named distribution parameter
void parameter (short dist_param, Real val)
update the value of the named distribution parameter
Real mean () const
return the distribution mean
Real median () const
return the distribution mode
Real mode () const
return the distribution mode
Real standard_deviation () const
return the distribution variance
Real variance () const
return the distribution variance
RealRealPair bounds () const
return the distribution lower and upper bounds as a pair
Real correlation_warping_factor (const RandomVariable &rv, Real corr) const
compute the warping factor for correlation between the current variable and the one passed in (used in NatafTransformation)
Real dx_ds (short dist_param, short u_type, Real x, Real z) const
Real dz_ds_factor (short u_type, Real x, Real z) const
void update (Real mean, Real stdev)
Public Member Functions inherited from RandomVariable
RandomVariable ()
default constructor
RandomVariable (short ran_var_type)
standard constructor for envelope
RandomVariable (const RandomVariable &ran_var)
copy constructor
virtual ~RandomVariable ()
destructor
RandomVariable operator= (const RandomVariable &ran_var)
assignment operator
virtual RealRealPair moments () const
return the distribution mean and standard deviation as a pair
virtual Real coefficient_of_variation () const
compute the coefficient of variation (used to compute selected correlation warping factors); defined for semi-infinite distributions with nonzero mean (lognormal, exponential, gamma, frechet, weibull)
template<typename Engine >
Real draw_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
template<typename Engine >
Real draw_standard_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
void type (short ran_var_type)
set ranVarType
short type () const
get ranVarType
RandomVariable * random_variable_rep () const
returns ranVarRep for access to derived class member functions that are not mapped to the base level
Static Public Member Functions
static Real pdf (Real x, Real mean, Real std_dev)
static Real cdf (Real x, Real mean, Real std_dev)
static Real std_pdf (Real z)
static Real mvn_std_pdf (Real beta, size_t n)
static Real mvn_std_pdf (const RealVector &u)
static Real std_cdf (Real z)
static Real std_ccdf (Real z)
static Real inverse_std_cdf (Real p_cdf)
static Real inverse_std_ccdf (Real p_ccdf)
static Real log_std_pdf (Real z)
static Real log_std_pdf_gradient (Real z)
static Real log_std_pdf_hessian ()
static Real log_std_cdf (Real z)
static Real log_std_ccdf (Real z)
template<typename Engine >
static Real draw_std_sample (Engine &rng)
Protected Attributes
Real gaussMean
mean of Gaussian random variable
Real gaussStdDev
standard deviation of Gaussian random variable
Protected Attributes inherited from RandomVariable
short ranVarType
enumeration value indicating type of random variable
Additional Inherited Members
Protected Member Functions inherited from RandomVariable
RandomVariable (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Detailed Description
Derived random variable class for Gaussian random variables.
Manages mean and standard deviation.
Member Function Documentation
Real dx_ds (short dist_param, short u_type, Real x, Real z) const inline virtual
dx/ds is derived by differentiating NatafTransformation::trans_Z_to_X() with respect to distribution parameter s. dz/ds is zero if uncorrelated, while dz_ds_factor() manages contributions in the correlated case.
Reimplemented from RandomVariable.
References NormalRandomVariable::dz_ds_factor().
Referenced by NormalRandomVariable::parameter().
Real dz_ds_factor (short u_type, Real x, Real z) const inline virtual
dx/ds is derived by differentiating NatafTransformation::trans_Z_to_X() with respect to distribution parameter s. For the uncorrelated case, u and z are constants. For the correlated case, u is a constant, but z(s) = L(s) u due to Nataf dependence on s and dz/ds = dL/ds u.
Reimplemented from RandomVariable.
References NormalRandomVariable::cdf(), NormalRandomVariable::gaussMean, NormalRandomVariable::gaussStdDev, NormalRandomVariable::mean(), and NormalRandomVariable::pdf().
Referenced by NormalRandomVariable::dx_ds().
Real std_pdf (Real z) inline static
returns a cumulative probability < 0.5 for negative z and a cumulative probability > 0.5 for positive z.
Referenced by BoundedLognormalRandomVariable::dx_ds(), BoundedNormalRandomVariable::dx_ds(), LoguniformRandomVariable::dz_ds_factor(), TriangularRandomVariable::dz_ds_factor(), FrechetRandomVariable::dz_ds_factor(), WeibullRandomVariable::dz_ds_factor(), BoundedNormalRandomVariable::dz_ds_factor(), BoundedLognormalRandomVariable::dz_ds_factor(), GumbelRandomVariable::dz_ds_factor(), UniformRandomVariable::dz_ds_factor(), ExponentialRandomVariable::dz_ds_factor(), NumericGenOrthogPolynomial::hermite_unbounded_integral(), NatafTransformation::hessian_d2X_dZ2(), NatafTransformation::jacobian_dX_dZ(), NatafTransformation::jacobian_dZ_dX(), BoundedNormalRandomVariable::mean(), BoundedNormalRandomVariable::moments(), NormalRandomVariable::standard_pdf(), ProbabilityTransformation::u_pdf(), BoundedNormalRandomVariable::variance(), BoundedLognormalRandomVariable::~BoundedLognormalRandomVariable(), and BoundedNormalRandomVariable::~BoundedNormalRandomVariable().
Real std_cdf (Real z) inline static
returns a cumulative probability < 0.5 for negative z and a cumulative probability > 0.5 for positive z.
Referenced by BoundedLognormalRandomVariable::ccdf(), BoundedNormalRandomVariable::ccdf(), LoguniformRandomVariable::dx_ds(), TriangularRandomVariable::dx_ds(), BoundedNormalRandomVariable::dx_ds(), BoundedLognormalRandomVariable::dx_ds(), FrechetRandomVariable::dz_ds_factor(), BoundedLognormalRandomVariable::dz_ds_factor(), BoundedNormalRandomVariable::dz_ds_factor(), GumbelRandomVariable::dz_ds_factor(), BoundedLognormalRandomVariable::inverse_ccdf(), BoundedNormalRandomVariable::inverse_ccdf(), BoundedLognormalRandomVariable::inverse_cdf(), BoundedNormalRandomVariable::inverse_cdf(), BoundedLognormalRandomVariable::log_pdf(), BoundedNormalRandomVariable::log_pdf(), BoundedNormalRandomVariable::mean(), BoundedLognormalRandomVariable::mean(), BoundedNormalRandomVariable::moments(), BoundedLognormalRandomVariable::moments(), NatafTransformation::trans_Z_to_X(), BoundedNormalRandomVariable::variance(), BoundedLognormalRandomVariable::~BoundedLognormalRandomVariable(), and BoundedNormalRandomVariable::~BoundedNormalRandomVariable().
The documentation for this class was generated from the following file:
NormalRandomVariable.hpp