PECOS: LHSDriver Class Reference
LHSDriver Class Reference
Driver class for Latin Hypercube Sampling (LHS)
Public Member Functions
LHSDriver ()
default constructor
LHSDriver (const String &sample_type, short sample_ranks_mode=IGNORE_RANKS, bool reports=true)
constructor
~LHSDriver ()
destructor
void initialize (const String &sample_type, short sample_ranks_mode=IGNORE_RANKS, bool reports=true)
populate data when not passed through ctor
void seed (int seed)
set randomSeed
int seed () const
return randomSeed
void rng (String unif_gen)
set random number generator, passing the name of the uniform generator: rnum2 or mt19937 (default). Passed value is superceded by environment variable DAKOTA_LHS_UNIFGEN, if present
void advance_seed_sequence ()
reseed using a deterministic sequence
void generate_samples (const RealVector &cd_l_bnds, const RealVector &cd_u_bnds, const IntVector &ddr_l_bnds, const IntVector &ddr_u_bnds, const IntSetArray &ddsi_values, const StringSetArray &ddss_values, const RealSetArray &ddsr_values, const RealVector &cs_l_bnds, const RealVector &cs_u_bnds, const IntVector &dsr_l_bnds, const IntVector &dsr_u_bnds, const IntSetArray &dssi_values, const StringSetArray &dsss_values, const RealSetArray &dssr_values, const AleatoryDistParams &adp, const EpistemicDistParams &edp, int num_samples, RealMatrix &samples_array, RealMatrix &rank_array)
generates the desired set of parameter samples from within general user-specified probabilistic distributions (AleatoryDistParams and EpistemicDistParams instances augmented with design and state variables)
void generate_samples (const AleatoryDistParams &adp, const EpistemicDistParams &edp, int num_samples, RealMatrix &samples_array, bool backfill_flag=false)
generates the desired set of parameter samples from within AleatoryDistParams and EpistemicDistParams specifications
void generate_samples (const AleatoryDistParams &adp, int num_samples, RealMatrix &samples_array, bool backfill_flag=false)
generates the desired set of parameter samples from within an AleatoryDistParams specification
void generate_samples (const EpistemicDistParams &edp, int num_samples, RealMatrix &samples_array, bool backfill_flag=false)
generates the desired set of parameter samples from within a EpistemicDistParams specification
void generate_normal_samples (const RealVector &n_means, const RealVector &n_std_devs, const RealVector &n_l_bnds, const RealVector &n_u_bnds, int num_samples, RealSymMatrix &correl_matrix, RealMatrix &samples_array)
generates the desired set of parameter samples from within uncorrelated normal distributions
void generate_uniform_samples (const RealVector &u_l_bnds, const RealVector &u_u_bnds, int num_samples, RealMatrix &samples_array, bool backfill_flag=false)
generates the desired set of parameter samples from within uncorrelated uniform distributions
void generate_uniform_index_samples (const IntVector &index_l_bnds, const IntVector &index_u_bnds, int num_samples, IntMatrix &index_samples)
generates integer index samples from within uncorrelated uniform distributions
void generate_unique_index_samples (const IntVector &index_l_bnds, const IntVector &index_u_bnds, int num_samples, IntMatrix &sorted_samples)
generates unique integer index samples from within uncorrelated uniform distributions (more expensive than non-unique case)
void generate_unique_samples (const RealVector &cd_l_bnds, const RealVector &cd_u_bnds, const IntVector &ddri_l_bnds, const IntVector &ddri_u_bnds, const IntSetArray &ddsi_values, const StringSetArray &ddss_values, const RealSetArray &ddsr_values, const RealVector &cs_l_bnds, const RealVector &cs_u_bnds, const IntVector &dsri_l_bnds, const IntVector &dsri_u_bnds, const IntSetArray &dssi_values, const StringSetArray &dsss_values, const RealSetArray &dssr_values, const AleatoryDistParams &adp, const EpistemicDistParams &edp, int num_samples, RealMatrix &samples, RealMatrix &sample_ranks)
Similar to generate_samples but this function ensures that all discrete samples are unique.
Private Member Functions
void check_error (int err_code, const char *err_source) const
checks the return codes from LHS routines and aborts if an error is returned
Static Private Member Functions
static void abort_if_no_lhs ()
checks whether LHS is enabled in the build and aborts if not
Private Attributes
String sampleType
type of sampling: random, lhs, incremental_lhs, or incremental_random
int randomSeed
the current random number seed
short sampleRanksMode
mode of sample ranks I/O: IGNORE_RANKS, SET_RANKS, GET_RANKS, or SET_GET_RANKS
bool reportFlag
flag for generating LHS report output
short allowSeedAdvance
for honoring advance_seed_sequence() calls
Detailed Description
Driver class for Latin Hypercube Sampling (LHS)
This class provides common code for sampling methods which employ the Latin Hypercube Sampling (LHS) package from Sandia Albuquerque's Risk and Reliability organization.
Member Function Documentation
void advance_seed_sequence () inline
reseed using a deterministic sequence
It would be preferable to call srand() only once and then call rand() for each LHS execution (the intended usage model), but possible interaction with other uses of rand() in other contexts is a concern. E.g., an srand(clock()) executed elsewhere would ruin the repeatability of the LHSDriver seed sequence. The only way to insure isolation is to reseed each time. Any induced correlation should be inconsequential for the intended use.
References LHSDriver::allowSeedAdvance, LHSDriver::generate_samples(), LHSDriver::randomSeed, and LHSDriver::seed().
Referenced by FourierInverseTransformation::compute_sample_grigoriu(), and FourierInverseTransformation::compute_sample_shinozuka_deodatis().
void generate_samples (const RealVector & cd_l_bnds, const RealVector & cd_u_bnds, const IntVector & ddri_l_bnds, const IntVector & ddri_u_bnds, const IntSetArray & ddsi_values, const StringSetArray & ddss_values, const RealSetArray & ddsr_values, const RealVector & cs_l_bnds, const RealVector & cs_u_bnds, const IntVector & dsri_l_bnds, const IntVector & dsri_u_bnds, const IntSetArray & dssi_values, const StringSetArray & dsss_values, const RealSetArray & dssr_values, const AleatoryDistParams & adp, const EpistemicDistParams & edp, int num_samples, RealMatrix & samples, RealMatrix & sample_ranks)
generates the desired set of parameter samples from within general user-specified probabilistic distributions (AleatoryDistParams and EpistemicDistParams instances augmented with design and state variables)
While it would be desirable in some cases to carve this function into smaller parts and allow multiple invocations of LHS_RUN following a single initialization of types and arrays, the LHS code does not currently allow this: it will return an error if LHS_INIT/LHS_INIT_MEM, at least one distribution call (i.e., LHS_DIST, LHS_UDIST or LHS_SDIST), and LHS_PREP are not called prior to each invocation of LHS_RUN. Since LHS_INIT/LHS_INIT_MEM require input of a seed, the approach to computing multiple distinct sample sets must employ advance_seed_sequence() to re-seed multiple generate_samples() calls, rather than continuing an existing random number sequence.
References AleatoryDistParams::beta_alphas(), AleatoryDistParams::beta_betas(), AleatoryDistParams::beta_lower_bounds(), AleatoryDistParams::beta_upper_bounds(), AleatoryDistParams::binomial_num_trials(), AleatoryDistParams::binomial_probability_per_trial(), LHSDriver::check_error(), EpistemicDistParams::continuous_interval_basic_probabilities(), EpistemicDistParams::discrete_interval_basic_probabilities(), EpistemicDistParams::discrete_set_int_values_probabilities(), EpistemicDistParams::discrete_set_real_values_probabilities(), EpistemicDistParams::discrete_set_string_values_probabilities(), AleatoryDistParams::exponential_betas(), AleatoryDistParams::frechet_alphas(), AleatoryDistParams::frechet_betas(), AleatoryDistParams::gamma_alphas(), AleatoryDistParams::gamma_betas(), LHSDriver::generate_unique_samples(), AleatoryDistParams::geometric_probability_per_trial(), AleatoryDistParams::gumbel_alphas(), AleatoryDistParams::gumbel_betas(), AleatoryDistParams::histogram_bin_pairs(), AleatoryDistParams::histogram_point_int_pairs(), AleatoryDistParams::histogram_point_real_pairs(), AleatoryDistParams::histogram_point_string_pairs(), AleatoryDistParams::hypergeometric_num_drawn(), AleatoryDistParams::hypergeometric_selected_population(), AleatoryDistParams::hypergeometric_total_population(), AleatoryDistParams::lognormal_error_factors(), AleatoryDistParams::lognormal_lambdas(), AleatoryDistParams::lognormal_lower_bounds(), AleatoryDistParams::lognormal_means(), AleatoryDistParams::lognormal_std_deviations(), AleatoryDistParams::lognormal_upper_bounds(), AleatoryDistParams::lognormal_zetas(), AleatoryDistParams::loguniform_lower_bounds(), AleatoryDistParams::loguniform_upper_bounds(), AleatoryDistParams::negative_binomial_num_trials(), AleatoryDistParams::negative_binomial_probability_per_trial(), AleatoryDistParams::normal_lower_bounds(), AleatoryDistParams::normal_means(), AleatoryDistParams::normal_std_deviations(), AleatoryDistParams::normal_upper_bounds(), AleatoryDistParams::poisson_lambdas(), LHSDriver::randomSeed, LHSDriver::reportFlag, LHSDriver::sampleRanksMode, LHSDriver::sampleType, AleatoryDistParams::triangular_lower_bounds(), AleatoryDistParams::triangular_modes(), AleatoryDistParams::triangular_upper_bounds(), AleatoryDistParams::uncertain_correlations(), AleatoryDistParams::uniform_lower_bounds(), AleatoryDistParams::uniform_upper_bounds(), AleatoryDistParams::weibull_alphas(), and AleatoryDistParams::weibull_betas().
Referenced by LHSDriver::abort_if_no_lhs(), LHSDriver::advance_seed_sequence(), LHSDriver::generate_normal_samples(), LHSDriver::generate_samples(), LHSDriver::generate_uniform_index_samples(), LHSDriver::generate_uniform_samples(), and LHSDriver::generate_unique_samples().
The documentation for this class was generated from the following files:
LHSDriver.hpp
LHSDriver.cpp