PECOS: HistogramPtRandomVariable Class Reference
HistogramPtRandomVariable Class Reference
Derived random variable class for gumbel random variables.
Public Member Functions
HistogramPtRandomVariable ()
default constructor
HistogramPtRandomVariable (const IntRealMap &i_prs)
alternate constructor
HistogramPtRandomVariable (const StringRealMap &s_prs)
alternate constructor
HistogramPtRandomVariable (const RealRealMap &r_prs)
alternate constructor
~HistogramPtRandomVariable ()
destructor
Real mean () const
return the distribution mean
Real mode () const
return the distribution mode
Real standard_deviation () const
return the distribution variance
Real variance () const
return the distribution variance
RealRealPair moments () const
return the distribution mean and standard deviation as a pair
RealRealPair bounds () const
return the distribution lower and upper bounds as a pair
Real coefficient_of_variation () const
compute the coefficient of variation (used to compute selected correlation warping factors); defined for semi-infinite distributions with nonzero mean (lognormal, exponential, gamma, frechet, weibull)
void update (const IntRealMap &i_prs)
void update (const StringRealMap &s_prs)
void update (const RealRealMap &r_prs)
Public Member Functions inherited from RandomVariable
RandomVariable ()
default constructor
RandomVariable (short ran_var_type)
standard constructor for envelope
RandomVariable (const RandomVariable &ran_var)
copy constructor
virtual ~RandomVariable ()
destructor
RandomVariable operator= (const RandomVariable &ran_var)
assignment operator
virtual Real cdf (Real x) const
return the cumulative distribution function value of the random variable at x
virtual Real inverse_cdf (Real p_cdf) const
return the x value corresponding to a cumulative probability
virtual Real ccdf (Real x) const
return the complementary cumulative distribution function value of the random variable at x
virtual Real inverse_ccdf (Real p_ccdf) const
return the x value corresponding to a complementary cumulative probability
virtual Real pdf (Real x) const
return the value of the random variable's probability density function at x
virtual Real pdf_gradient (Real x) const
return the gradient of the random variable's probability density function at x
virtual Real pdf_hessian (Real x) const
return the hessian of the random variable's probability density function at x
virtual Real log_pdf (Real x) const
return the value of the natural log of the random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_pdf_gradient (Real x) const
return the gradient of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
virtual Real log_pdf_hessian (Real x) const
return the Hessian of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
virtual Real inverse_standard_cdf (Real p_cdf) const
return the x value for a standardized probability distribution corresponding to a cumulative probability
virtual Real standard_pdf (Real z) const
return the value of a standardized random variable's probability density function at x
virtual Real log_standard_pdf (Real z) const
return the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_standard_pdf_gradient (Real z) const
return the gradient of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_standard_pdf_hessian (Real z) const
return the Hessian of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real to_standard (Real x) const
scale variable value x from current to standardized distribution
virtual Real from_standard (Real z) const
scale variable value z from standardized to current distribution
virtual Real parameter (short dist_param) const
return the value of the named distribution parameter
virtual void parameter (short dist_param, Real val)
update the value of the named distribution parameter
virtual Real median () const
return the distribution mode
virtual Real correlation_warping_factor (const RandomVariable &rv, Real corr) const
compute the warping factor for correlation between the current variable and the one passed in (used in NatafTransformation)
virtual Real dx_ds (short dist_param, short u_type, Real x, Real z) const
compute the design Jacobian from differentiating the X->Z mapping with respect to the distibution parameter s
virtual Real dz_ds_factor (short u_type, Real x, Real z) const
compute the mapping-specific factor that is multiplied by dz/ds for contributions to the dx/ds design Jacobian in the case of correlated random variables (dz/ds is evaluated numerically and multiplied by this analytic factor)
template<typename Engine >
Real draw_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
template<typename Engine >
Real draw_standard_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
void type (short ran_var_type)
set ranVarType
short type () const
get ranVarType
RandomVariable * random_variable_rep () const
returns ranVarRep for access to derived class member functions that are not mapped to the base level
Static Public Member Functions
static void moments_from_params (const IntRealMap &i_prs, Real &mean, Real &std_dev)
for integer-valued histogram, return a real-valued mean and std dev
static void moments_from_params (const StringRealMap &s_prs, Real &mean, Real &std_dev)
for string variables, define the mean as the count-weighted mean of a zero-based index
static void moments_from_params (const RealRealMap &r_prs, Real &mean, Real &std_dev)
return the mean and standard deviation of a real-valued point histogram
Protected Attributes
IntRealMap intPtPairs
value-count pairs for int values within a set
StringRealMap stringPtPairs
value-count pairs for string values within a set
RealRealMap realPtPairs
value-count pairs for real values within a set
Protected Attributes inherited from RandomVariable
short ranVarType
enumeration value indicating type of random variable
Additional Inherited Members
Protected Member Functions inherited from RandomVariable
RandomVariable (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Detailed Description
Derived random variable class for gumbel random variables.
Manages int, string, or real PtPairs mappings. At most, one mapping is active at a time.
Member Function Documentation
RealRealPair moments () const inline virtual
return the distribution mean and standard deviation as a pair
default is only overridden when more efficient to compute together
Reimplemented from RandomVariable.
References HistogramPtRandomVariable::intPtPairs, HistogramPtRandomVariable::mean(), HistogramPtRandomVariable::moments_from_params(), RandomVariable::ranVarType, HistogramPtRandomVariable::realPtPairs, and HistogramPtRandomVariable::stringPtPairs.
Referenced by HistogramPtRandomVariable::coefficient_of_variation(), HistogramPtRandomVariable::mean(), HistogramPtRandomVariable::standard_deviation(), and HistogramPtRandomVariable::variance().
Real coefficient_of_variation () const inline virtual
compute the coefficient of variation (used to compute selected correlation warping factors); defined for semi-infinite distributions with nonzero mean (lognormal, exponential, gamma, frechet, weibull)
default is only overridden when more efficient to compute together
Reimplemented from RandomVariable.
References HistogramPtRandomVariable::intPtPairs, HistogramPtRandomVariable::moments(), HistogramPtRandomVariable::moments_from_params(), RandomVariable::ranVarType, HistogramPtRandomVariable::realPtPairs, and HistogramPtRandomVariable::stringPtPairs.
The documentation for this class was generated from the following file:
HistogramPtRandomVariable.hpp