PECOS: IntegrationDriver Class Reference
IntegrationDriver Class Reference
base class for generating N-dimensional grids for numerical evaluation of expectation integrals over independent standard random variables.
Public Member Functions
IntegrationDriver ()
default constructor
IntegrationDriver (short driver_type)
standard constructor for envelope
IntegrationDriver (const IntegrationDriver &driver)
copy constructor
virtual ~IntegrationDriver ()
destructor
IntegrationDriver operator= (const IntegrationDriver &driver)
assignment operator
virtual void initialize_grid (const std::vector< BasisPolynomial > &poly_basis)
initialize all grid settings (distribution params already set within poly_basis)
virtual void initialize_grid (const ShortArray &u_types, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
set int_rules and growth_rules from u_types and mode booleans
virtual void initialize_grid_parameters (const ShortArray &u_types, const AleatoryDistParams &adp)
update polynomialBasis with data from AleatoryDistParams
virtual void compute_grid (RealMatrix &var_sets)
compute scaled variable and weight sets for the TPQ grid
virtual int grid_size ()
compute number of collocation points
virtual void reinterpolated_tensor_grid (const UShortArray &lev_index, const SizetList &reinterp_indices)
computes and stores data for reinterpolation of covariance on a higher-order tensor grid
virtual void store_grid (size_t index=_NPOS)
store configuration settings for the current grid before advancing to the next settings within a prescribed grid sequence (default is push_back)
virtual void restore_grid (size_t index=_NPOS)
restore configuration settings from a previously stored grid
virtual void remove_stored_grid (size_t index=_NPOS)
remove configuration settings for a stored grid (default is pop_back)
virtual void clear_stored ()
clear stored grid settings following their usage/combination
virtual size_t maximal_grid () const
return the index of the maximal stored grid state (_NPOS if the current unstored grid state)
virtual void swap_grid (size_t index)
swap settings between the current grid and the stored grid identified by index
virtual const RealVector & type1_weight_sets () const
return type1WeightSets from Cubature/TensorProduct/CombinedSparseGrid or concatenate type1WeightSets in HierarchSparseGrid
virtual const RealMatrix & type2_weight_sets () const
return type2WeightSets from Cubature/TensorProduct/CombinedSparseGrid or concatenate type2WeightSets in HierarchSparseGrid
void assign_rep (IntegrationDriver *driver_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
void compute_tensor_grid (const UShortArray &quad_order, const UShortArray &lev_index, const SizetList &subset_indices, RealMatrix &variable_sets, UShort2DArray &colloc_key)
compute variable sets for a tensor-product grid
void update_1d_collocation_points_weights (const UShortArray &quad_order, const UShortArray &lev_index)
update collocPts1D and type{1,2}CollocWts1D
const std::vector< BasisPolynomial > & polynomial_basis () const
return polynomialBasis
void mode (short driver_mode)
set driverMode
short mode () const
get driverMode
const Real3DArray & collocation_points_1d () const
return collocPts1D
const Real3DArray & type1_collocation_weights_1d () const
return type1CollocWts1D
const Real3DArray & type2_collocation_weights_1d () const
return type2CollocWts1D
const ShortArray & collocation_rules () const
return collocRules
const UShortArray & reinterpolated_level_index () const
return reinterpLevelIndices[activeReinterpIndex]
const UShortArray & reinterpolated_quadrature_order () const
return reinterpQuadOrders[activeReinterpIndex]
const RealMatrix & reinterpolated_variable_sets () const
return reinterpVarSets[activeReinterpIndex]
const UShort2DArray & reinterpolated_collocation_key () const
return reinterpCollocKeys[activeReinterpIndex]
const UShortArray & genz_keister_order () const
return orderGenzKeister
const UShortArray & genz_keister_precision () const
return precGenzKeister
IntegrationDriver * driver_rep () const
returns driverRep for access to derived class member functions that are not mapped to the base level
Protected Member Functions
IntegrationDriver (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
void compute_tensor_grid (const UShortArray &quad_order, const UShortArray &lev_index, RealMatrix &variable_sets, RealVector &t1_weight_sets, RealMatrix &t2_weight_sets, UShort2DArray &colloc_key)
compute variable and weight sets for a tensor-product grid
void update_1d_collocation_points_weights (const UShortArray &quad_order, const UShortArray &lev_index, const SizetList &subset_indices)
update collocPts1D and type{1,2}CollocWts1D for subset variables
void assign_1d_collocation_points_weights (size_t i, unsigned short quad_order, unsigned short lev_index)
update collocPts1D[lev_index][i] and type{1,2}CollocWts1D[lev_index][i]
Protected Attributes
size_t numVars
number of variables in the tensor-product grid
short driverMode
enumeration value indicating INTEGRATION_MODE or INTERPOLATION_MODE
ShortArray collocRules
enumeration codes for integration rule options. Manages internal mode switches for 1D polynomial types: e.g., GAUSS_LEGENDRE or GAUSS_PATTERSON for Legendre, CLENSHAW_CURTIS or FEJER2 for Chebyshev, GAUSS_HERMITE or GENZ_KEISTER for Hermite.
std::vector< BasisPolynomial > polynomialBasis
array of one-dimensional orthogonal polynomials used in computing Gaussian quadrature points and weights
Real3DArray collocPts1D
num_levels_per_var x numVars sets of 1D collocation points
Real3DArray type1CollocWts1D
num_levels_per_var x numVars sets of 1D type1 collocation weights
Real3DArray type2CollocWts1D
num_levels_per_var x numVars sets of 1D type2 collocation weights
bool computeType2Weights
flag indicating usage of compute1DType2Weights to define type2WeightSets
UShort2DArray reinterpLevelIndices
bookkeeping for reinterpolation of covariance: stored level indices
UShort2DArray reinterpQuadOrders
bookkeeping for reinterpolation of covariance: stored quadrature orders
RealMatrixArray reinterpVarSets
bookkeeping for reinterpolation of covariance: stored variable sets
UShort3DArray reinterpCollocKeys
bookkeeping for reinterpolation of covariance: stored collocation keys
std::map< UShortArray, size_t > reinterpMap
tracks existing reinterpolation grids to avoid unnecessary recomputation
size_t activeReinterpIndex
bookkeeping for reinterpolation of covariance: active index into arrays
Static Protected Attributes
static UShortArray orderGenzKeister
lookup for set of 1-D Genz-Keister quadrature orders
static UShortArray precGenzKeister
lookup for set of 1-D Genz-Keister integrand precisions
Private Member Functions
IntegrationDriver * get_driver (short driver_type)
Used only by the standard envelope constructor to initialize driverRep to the appropriate derived type.
Private Attributes
IntegrationDriver * driverRep
pointer to the letter (initialized only for the envelope)
int referenceCount
number of objects sharing driverRep
Detailed Description
base class for generating N-dimensional grids for numerical evaluation of expectation integrals over independent standard random variables.
This class enables Dakota::NonD{Quadrature,Cubature,SparseGrid}.
Constructor & Destructor Documentation
IntegrationDriver ()
default constructor
The default constructor: driverRep is NULL in this case. This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
IntegrationDriver (short driver_type)
standard constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_driver, since IntegrationDriver(BaseConstructor) builds the actual base class data for the derived basis functions.
References IntegrationDriver::driverRep, and IntegrationDriver::get_driver().
IntegrationDriver (const IntegrationDriver & driver)
copy constructor
Copy constructor manages sharing of driverRep and incrementing of referenceCount.
References IntegrationDriver::driverRep, and IntegrationDriver::referenceCount.
~IntegrationDriver () virtual
destructor
Destructor decrements referenceCount and only deletes driverRep when referenceCount reaches zero.
References IntegrationDriver::assign_rep(), IntegrationDriver::driverRep, and IntegrationDriver::referenceCount.
IntegrationDriver (BaseConstructor) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor is the one which must build the base class data for all derived classes. get_driver() instantiates a derived class letter and the derived constructor selects this base class constructor in its initialization list (to avoid recursion in the base class constructor calling get_driver() again). Since the letter IS the representation, its rep pointer is set to NULL (an uninitialized pointer causes problems in ~IntegrationDriver).
References IntegrationDriver::orderGenzKeister, and IntegrationDriver::precGenzKeister.
Member Function Documentation
IntegrationDriver operator= (const IntegrationDriver & driver)
assignment operator
Assignment operator decrements referenceCount for old driverRep, assigns new driverRep, and increments referenceCount for new driverRep.
References IntegrationDriver::driverRep, and IntegrationDriver::referenceCount.
void initialize_grid (const std::vector< BasisPolynomial > & poly_basis) virtual
initialize all grid settings (distribution params already set within poly_basis)
protected function called only from derived class letters.
Reimplemented in TensorProductDriver, CombinedSparseGridDriver, and CubatureDriver.
References IntegrationDriver::collocRules, IntegrationDriver::computeType2Weights, IntegrationDriver::driverRep, IntegrationDriver::initialize_grid(), IntegrationDriver::numVars, and IntegrationDriver::polynomialBasis.
Referenced by SharedNodalInterpPolyApproxData::allocate_data(), IntegrationDriver::initialize_grid(), CombinedSparseGridDriver::initialize_grid(), SparseGridDriver::initialize_grid(), TensorProductDriver::initialize_grid(), and IntegrationDriver::type2_weight_sets().
void initialize_grid (const ShortArray & u_types, const ExpansionConfigOptions & ec_options, const BasisConfigOptions & bc_options) virtual
set int_rules and growth_rules from u_types and mode booleans
protected function called only from derived class letters.
Reimplemented in TensorProductDriver.
References IntegrationDriver::collocRules, IntegrationDriver::computeType2Weights, IntegrationDriver::driverMode, ExpansionConfigOptions::expBasisType, SharedInterpPolyApproxData::initialize_driver_types_rules(), IntegrationDriver::initialize_grid(), SharedPolyApproxData::initialize_orthogonal_basis_types_rules(), SharedPolyApproxData::initialize_polynomial_basis(), IntegrationDriver::numVars, and IntegrationDriver::polynomialBasis.
IntegrationDriver * get_driver (short driver_type) private
Used only by the standard envelope constructor to initialize driverRep to the appropriate derived type.
Used only by the envelope constructor to initialize driverRep to the appropriate derived type.
Referenced by IntegrationDriver::IntegrationDriver().
The documentation for this class was generated from the following files:
IntegrationDriver.hpp
IntegrationDriver.cpp