PECOS: NatafTransformation Class Reference
NatafTransformation Class Reference
Class for Nataf nonlinear distribution transformation.
Public Member Functions
NatafTransformation ()
constructor
~NatafTransformation ()
destructor
Public Member Functions inherited from ProbabilityTransformation
ProbabilityTransformation ()
default constructor
ProbabilityTransformation (const String &prob_trans_type)
standard constructor for envelope
ProbabilityTransformation (const ProbabilityTransformation &prob_trans)
copy constructor
virtual ~ProbabilityTransformation ()
destructor
ProbabilityTransformation operator= (const ProbabilityTransformation &prob_trans)
assignment operator
void copy (const ProbabilityTransformation &prob_trans)
perform a deep copy of incoming prob_trans
void initialize_random_variable_types (const ShortArray &x_types)
initializes randomVarsX (no transformation: u-space not needed)
void initialize_random_variable_types (const ShortArray &x_types, const ShortArray &u_types)
initializes randomVarsX and ranVarTypesU
void initialize_random_variable_parameters (const RealVector &cd_l_bnds, const RealVector &cd_u_bnds, const AleatoryDistParams &adp, const EpistemicDistParams &edp, const RealVector &cs_l_bnds, const RealVector &cs_u_bnds)
updates parameters within randomVarsX
void initialize_random_variable_correlations (const RealSymMatrix &x_corr)
initializes corrMatrixX and correlationFlagX
void reshape_correlation_matrix (size_t num_leading_vars, size_t num_probabilistic_vars, size_t num_trailing_vars)
reshape corrMatrixX for an all_variables specification
const std::vector< RandomVariable > & x_random_variables () const
return randomVarsX
RealRealPairArray x_moments () const
assemble means and standard deviations in original space from RandomVariable::moments()
RealRealPairArray u_moments () const
assemble means and standard deviations in transformed space combining data from ranVarTypesU with RandomVariable::moments()
RealVector x_means () const
assemble means in original space from RandomVariable::mean()
RealVector x_std_deviations () const
assemble standard deviations in original space from RandomVariable::standard_deviation()
RealRealPairArray x_bounds () const
assemble lower and upper bounds from RandomVariable::bounds()
RealRealPairArray u_bounds () const
assemble lower and upper bounds in transformed space combining data from ranVarTypesU with RandomVariable::bounds()
RealVector x_lower_bounds () const
assemble lower bounds from RandomVariable::bounds()
RealVector x_upper_bounds () const
assemble upper bounds from RandomVariable::bounds()
Real x_pdf (Real x_val, size_t i) const
return the univariate PDF value for an x-space random variable
Real x_log_pdf (Real x_val, size_t i) const
return the univariate log PDF value for an x-space random variable
Real x_log_pdf_gradient (Real x_val, size_t i) const
return the gradient of the univariate log PDF for an x-space random variable
Real x_log_pdf_hessian (Real x_val, size_t i) const
return the Hessian of the univariate log PDF for an x-space random variable
Real u_pdf (Real u_val, size_t i) const
return the univariate PDF value for a u-space random variable
Real u_log_pdf (Real u_val, size_t i) const
return the univariate log PDF value for a u-space random variable
Real u_log_pdf_gradient (Real u_val, size_t i) const
return the gradient of the univariate log PDF for a u-space random variable
Real u_log_pdf_hessian (Real u_val, size_t i) const
return the Hessian of the univariate log PDF for a u-space random variable
Real x_pdf (const RealVector &x_pt) const
return the multivariate PDF value for x-space random variables
Real x_log_pdf (const RealVector &x_pt) const
return the multivariate log PDF value for x-space random variables
Real u_pdf (const RealVector &u_pt) const
return the multivariate PDF value for u-space random variables
Real u_log_pdf (const RealVector &u_pt) const
return the multivariate log PDF value for u-space random variables
template<typename Engine >
Real draw_x_sample (size_t i, Engine &rng) const
draw a sample from an x-space random variable
template<typename Engine >
Real draw_u_sample (size_t i, Engine &rng) const
draw a sample from a u-space random variable
const ShortArray & u_types () const
return ranVarTypesU
void u_types (const ShortArray &types)
set ranVarTypesU
void u_type (short type, size_t i)
set ranVarTypesU[i]
void check_x_type (size_t i, short x_type) const
verify that randomVarsX[i].type() equals x_type
bool x_correlation () const
return correlationFlagX
const RealSymMatrix & x_correlation_matrix () const
return corrMatrixX
const RealMatrix & z_correlation_factor () const
return corrCholeskyFactorZ
bool is_null () const
function to check modelRep (does this envelope contain a letter)
Protected Member Functions
void trans_U_to_X (const RealVector &u_vars, RealVector &x_vars)
Transformation routine from u-space of uncorrelated standard normal variables to x-space of correlated random variables.
void trans_X_to_U (const RealVector &x_vars, RealVector &u_vars)
Transformation routine from x-space of correlated random variables to u-space of uncorrelated standard normal variables.
void transform_correlations ()
As part of the Nataf distribution model (Der Kiureghian & Liu, 1986), this procedure modifies the user-specified correlation matrix (corrMatrixX) to account for correlation warping from the nonlinear X->Z transformation and performs a Cholesky factorization to create corrCholeskyFactorZ.
void trans_grad_X_to_U (const RealVector &fn_grad_x, RealVector &fn_grad_u, const RealVector &x_vars, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from x-space to u-space.
void trans_grad_X_to_U (const RealVector &fn_grad_x, RealVector &fn_grad_u, const RealMatrix &jacobian_xu, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from x-space to u-space.
void trans_grad_X_to_S (const RealVector &fn_grad_x, RealVector &fn_grad_s, const RealVector &x_vars, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Transformation routine from x-space gradient vector to design space.
void trans_grad_X_to_S (const RealVector &fn_grad_x, RealVector &fn_grad_s, const RealMatrix &jacobian_xs, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Transformation routine from x-space gradient vector to design space.
void trans_grad_U_to_X (const RealVector &fn_grad_u, RealVector &fn_grad_x, const RealVector &x_vars, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from u-space to x-space.
void trans_grad_U_to_X (const RealVector &fn_grad_u, RealVector &fn_grad_x, const RealMatrix &jacobian_ux, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from u-space to x-space.
void trans_hess_X_to_U (const RealSymMatrix &fn_hess_x, RealSymMatrix &fn_hess_u, const RealVector &x_vars, const RealVector &fn_grad_x, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for Hessian matrix from x-space to u-space.
void trans_hess_X_to_U (const RealSymMatrix &fn_hess_x, RealSymMatrix &fn_hess_u, const RealMatrix &jacobian_xu, const RealSymMatrixArray &hessian_xu, const RealVector &fn_grad_x, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for Hessian matrix from x-space to u-space.
void jacobian_dX_dU (const RealVector &x_vars, RealMatrix &jacobian_xu)
Jacobian of x(u) mapping obtained from dX/dZ dZ/dU.
void jacobian_dU_dX (const RealVector &x_vars, RealMatrix &jacobian_ux)
Jacobian of u(x) mapping obtained from dU/dZ dZ/dX.
void jacobian_dX_dS (const RealVector &x_vars, RealMatrix &jacobian_xs, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Design Jacobian of x(u,s) mapping obtained from differentiation of trans_U_to_X() with respect to distribution parameters S.
void hessian_d2X_dU2 (const RealVector &x_vars, RealSymMatrixArray &hessian_xu)
Hessian of x(u) mapping obtained from dZ/dU^T d^2X/dZ^2 dZ/dU.
Protected Member Functions inherited from ProbabilityTransformation
ProbabilityTransformation (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
void numerical_design_jacobian (const RealVector &x_vars, bool xs, RealMatrix &num_jacobian_xs, bool zs, RealMatrix &num_jacobian_zs, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Computes numerical dx/ds and dz/ds Jacobians as requested by xs and zs booleans.
void verify_trans_jacobian_hessian (const RealVector &v0)
routine for verification of transformation Jacobian/Hessian terms
void verify_design_jacobian (const RealVector &u0)
routine for verification of design Jacobian terms
Private Member Functions
void trans_U_to_Z (const RealVector &u_vars, RealVector &z_vars)
Transformation routine from u-space of uncorrelated standard normal variables to z-space of correlated standard normal variables.
void trans_Z_to_X (const RealVector &z_vars, RealVector &x_vars)
Transformation routine from z-space of correlated standard normal variables to x-space of correlated random variables.
void trans_Z_to_X (Real z, Real &x, size_t i)
Transformation routine from a single z-space variable to a corresponding x-space variable.
void trans_X_to_Z (const RealVector &x_vars, RealVector &z_vars)
Transformation routine from x-space of correlated random variables to z-space of correlated standard normal variables.
void trans_X_to_Z (Real x, Real &z, size_t i)
Transformation routine from a single x-space random variable to a corresponding z-space variable.
void trans_Z_to_U (RealVector &z_vars, RealVector &u_vars)
Transformation routine from z-space of correlated standard normal variables to u-space of uncorrelated standard normal variables.
void jacobian_dX_dZ (const RealVector &x_vars, RealMatrix &jacobian_xz)
Jacobian of x(z) mapping obtained from differentiation of trans_Z_to_X()
void jacobian_dZ_dX (const RealVector &x_vars, RealMatrix &jacobian_zx)
Jacobian of z(x) mapping obtained from differentiation of trans_X_to_Z()
void hessian_d2X_dZ2 (const RealVector &x_vars, RealSymMatrixArray &hessian_xz)
Hessian of x(z) mapping obtained from differentiation of jacobian_dX_dZ()
Additional Inherited Members
Protected Attributes inherited from ProbabilityTransformation
std::vector< RandomVariable > randomVarsX
vector of random variables encapsulating distribution parameters and statistical functions (pdf, cdf, etc.)
ShortArray ranVarTypesU
vector of types of each u-space standardized uncertain variable to which each x-space variable is transformed
bool correlationFlagX
flag for indicating if correlation exists among the x-space uncertain variables
RealSymMatrix corrMatrixX
matrix of random variable correlation coefficients
RealMatrix corrCholeskyFactorZ
cholesky factor of a modified correlation matrix (corrMatrixX is modified in transform_correlations() for use in z-space)
Detailed Description
Class for Nataf nonlinear distribution transformation.
The Nataf transformation occurs in two steps: (1) transformation from the original correlated distributions (x-space) to correlated standard normals (z-space) using CDF matching and from correlated standard normals to uncorrelated standard normals (u-space) using the inverse Cholesky factor of a modified correlation matrix.
Member Function Documentation
void trans_U_to_X (const RealVector & u_vars, RealVector & x_vars) protected virtual
Transformation routine from u-space of uncorrelated standard normal variables to x-space of correlated random variables.
This procedure performs the transformation from u to x space. u_vars is the vector of random variables in uncorrelated standard normal space (u-space). x_vars is the vector of random variables in the original user-defined x-space.
Reimplemented from ProbabilityTransformation.
References ProbabilityTransformation::correlationFlagX, NatafTransformation::trans_U_to_Z(), and NatafTransformation::trans_Z_to_X().
void trans_X_to_U (const RealVector & x_vars, RealVector & u_vars) protected virtual
Transformation routine from x-space of correlated random variables to u-space of uncorrelated standard normal variables.
This procedure performs the transformation from x to u space u_vars is the vector of random variables in uncorrelated standard normal space (u-space). x_vars is the vector of random variables in the original user-defined x-space.
Reimplemented from ProbabilityTransformation.
References ProbabilityTransformation::correlationFlagX, NatafTransformation::trans_X_to_Z(), and NatafTransformation::trans_Z_to_U().
Referenced by NatafTransformation::trans_Z_to_X().
void transform_correlations () protected virtual
As part of the Nataf distribution model (Der Kiureghian & Liu, 1986), this procedure modifies the user-specified correlation matrix (corrMatrixX) to account for correlation warping from the nonlinear X->Z transformation and performs a Cholesky factorization to create corrCholeskyFactorZ.
This procedure modifies the correlation matrix input by the user for use in the Nataf distribution model (Der Kiureghian and Liu, ASCE JEM 112:1, 1986). It uses empirical expressionss derived from least-squares polynomial fits to numerical integration data.
corrMatrixX: the correlation coefficient matrix of the random variables provided by the user
mod_corr_matrix: modified correlation matrix
corrCholeskyFactorZ: Cholesky factor of the modified correlation matrix for use in Z_to_U and U_to_Z transformations.
cf_var_{i,j}: coefficient of variation of Xi,Xj
Note: The modification is exact for normal-normal, lognormal-lognormal, and normal-lognormal tranformations. All other cases are approximations with some error as noted below.
Reimplemented from ProbabilityTransformation.
References ProbabilityTransformation::corrCholeskyFactorZ, ProbabilityTransformation::correlationFlagX, ProbabilityTransformation::corrMatrixX, ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, and NatafTransformation::trans_grad_X_to_U().
void trans_grad_X_to_U (const RealVector & fn_grad_x, RealVector & fn_grad_u, const RealVector & x_vars, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids) protected virtual
Transformation routine for gradient vector from x-space to u-space.
This procedure tranforms a gradient vector dg/dx from the original user-defined x-space (where evaluations are performed) to uncorrelated standard normal space (u-space) through application of the Jacobian dx/du. x_vars is the vector of random variables in x-space.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::jacobian_dX_dU().
Referenced by NatafTransformation::transform_correlations().
void trans_grad_X_to_U (const RealVector & fn_grad_x, RealVector & fn_grad_u, const RealMatrix & jacobian_xu, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids) protected virtual
Transformation routine for gradient vector from x-space to u-space.
This procedure tranforms a gradient vector dg/dx from the original user-defined x-space (where evaluations are performed) to uncorrelated standard normal space (u-space) through application of the Jacobian dx/du. This overloaded form allows for the separate calculation of jacobian_xu, as this matrix is independent of the response function index and can be pulled outside response function loops.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::trans_grad_U_to_X().
void trans_grad_X_to_S (const RealVector & fn_grad_x, RealVector & fn_grad_s, const RealVector & x_vars, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray & acv_map1_indices, const ShortArray & acv_map2_targets) protected virtual
Transformation routine from x-space gradient vector to design space.
This procedure multiplies a gradient vector dg/dx from the original user-defined x-space (where evaluations are performed) with the design Jacobian dx/ds of the transformation x = x(u,s) to form the design gradient dg/ds. x_vars is the vector of random variables in x-space.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::jacobian_dX_dS().
Referenced by NatafTransformation::trans_grad_U_to_X().
void trans_grad_X_to_S (const RealVector & fn_grad_x, RealVector & fn_grad_s, const RealMatrix & jacobian_xs, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray & acv_map1_indices, const ShortArray & acv_map2_targets) protected virtual
Transformation routine from x-space gradient vector to design space.
This procedure multiplies a gradient vector dg/dx from the original user-defined x-space (where evaluations are performed) with the design Jacobian dx/ds of the transformation x = x(u,s) to form the design gradient dg/ds. This overloaded form allows for the separate calculation of jacobian_xs, as this matrix is independent of the response function index and can be pulled outside response function loops.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::trans_hess_X_to_U().
void trans_grad_U_to_X (const RealVector & fn_grad_u, RealVector & fn_grad_x, const RealVector & x_vars, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids) protected virtual
Transformation routine for gradient vector from u-space to x-space.
This procedure tranforms a gradient vector dg/du from uncorrelated standard space (u-space) to the original user-defined x-space through application of the Jacobian du/dx. x_vars is the vector of random variables in x-space.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::jacobian_dU_dX().
Referenced by NatafTransformation::trans_grad_X_to_U().
void trans_grad_U_to_X (const RealVector & fn_grad_u, RealVector & fn_grad_x, const RealMatrix & jacobian_ux, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids) protected virtual
Transformation routine for gradient vector from u-space to x-space.
This procedure tranforms a gradient vector dg/du from uncorrelated standard space (u-space) to the original user-defined x-space through application of the Jacobian du/dx. This overloaded form allows for the separate calculation of jacobian_ux, as this matrix is independent of the response function index and can be pulled outside response function loops.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::trans_grad_X_to_S().
void trans_hess_X_to_U (const RealSymMatrix & fn_hess_x, RealSymMatrix & fn_hess_u, const RealVector & x_vars, const RealVector & fn_grad_x, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids) protected virtual
Transformation routine for Hessian matrix from x-space to u-space.
This procedure tranforms a Hessian matrix from the original user-defined x-space (where evaluations are performed) to uncorrelated standard normal space (u-space). x_vars is the vector of the random variables in x-space.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::hessian_d2X_dU2(), NatafTransformation::jacobian_dX_dU(), ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, and ProbabilityTransformation::u_type().
Referenced by NatafTransformation::trans_grad_X_to_S().
void trans_hess_X_to_U (const RealSymMatrix & fn_hess_x, RealSymMatrix & fn_hess_u, const RealMatrix & jacobian_xu, const RealSymMatrixArray & hessian_xu, const RealVector & fn_grad_x, const SizetArray & x_dvv, SizetMultiArrayConstView cv_ids) protected virtual
Transformation routine for Hessian matrix from x-space to u-space.
This procedure tranforms a Hessian matrix from the original user-defined x-space (where evaluations are performed) to uncorrelated standard normal space (u-space). This overloaded form allows for the separate calculation of jacobian_xu and hessian_xu, since these are independent of the response function index and can be pulled outside response function loops.
Reimplemented from ProbabilityTransformation.
References NatafTransformation::jacobian_dX_dU().
void jacobian_dX_dU (const RealVector & x_vars, RealMatrix & jacobian_xu) protected virtual
Jacobian of x(u) mapping obtained from dX/dZ dZ/dU.
This procedure computes the Jacobian of the transformation x(u). x_vars is the vector of random variables in the original user-defined x-space.
Reimplemented from ProbabilityTransformation.
References ProbabilityTransformation::corrCholeskyFactorZ, ProbabilityTransformation::correlationFlagX, and NatafTransformation::jacobian_dX_dZ().
Referenced by NatafTransformation::trans_grad_X_to_U(), and NatafTransformation::trans_hess_X_to_U().
void jacobian_dU_dX (const RealVector & x_vars, RealMatrix & jacobian_ux) protected virtual
Jacobian of u(x) mapping obtained from dU/dZ dZ/dX.
This procedure computes the Jacobian of the transformation u(x). x_vars is the vector of random variables in the original user-defined x-space.
Reimplemented from ProbabilityTransformation.
References ProbabilityTransformation::corrCholeskyFactorZ, ProbabilityTransformation::correlationFlagX, and NatafTransformation::jacobian_dZ_dX().
Referenced by NatafTransformation::jacobian_dX_dZ(), and NatafTransformation::trans_grad_U_to_X().
void jacobian_dX_dS (const RealVector & x_vars, RealMatrix & jacobian_xs, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray & acv_map1_indices, const ShortArray & acv_map2_targets) protected virtual
Design Jacobian of x(u,s) mapping obtained from differentiation of trans_U_to_X() with respect to distribution parameters S.
This procedure computes the derivative of the original variables x with respect to the random variable distribution parameters s. This provides the design Jacobian of the transformation for use in computing statistical design sensitivities for OUU.
dX/dS is derived by differentiating trans_Z_to_X with respect to S. For the uncorrelated case, u and z are constants. For the correlated case, u is a constant, but z(s) = L(s) u due to Nataf dependence on s and dz/ds = dL/ds u.
Reimplemented from ProbabilityTransformation.
References ProbabilityTransformation::correlationFlagX, ProbabilityTransformation::corrMatrixX, RandomVariable::dx_ds(), RandomVariable::dz_ds_factor(), NatafTransformation::hessian_d2X_dU2(), ProbabilityTransformation::numerical_design_jacobian(), ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, NatafTransformation::trans_X_to_Z(), RandomVariable::type(), and ProbabilityTransformation::u_type().
Referenced by NatafTransformation::jacobian_dZ_dX(), and NatafTransformation::trans_grad_X_to_S().
void hessian_d2X_dU2 (const RealVector & x_vars, RealSymMatrixArray & hessian_xu) protected virtual
Hessian of x(u) mapping obtained from dZ/dU^T d^2X/dZ^2 dZ/dU.
This procedure computes the Hessian of the transformation x(u). hessian_xu is a 3D tensor modeled as an array of matrices, where the i_th matrix is d^2X_i/dU^2. x_vars is the vector of random variables in the original user-defined x-space.
Reimplemented from ProbabilityTransformation.
References ProbabilityTransformation::corrCholeskyFactorZ, ProbabilityTransformation::correlationFlagX, and NatafTransformation::hessian_d2X_dZ2().
Referenced by NatafTransformation::jacobian_dX_dS(), and NatafTransformation::trans_hess_X_to_U().
void trans_U_to_Z (const RealVector & u_vars, RealVector & z_vars) private
Transformation routine from u-space of uncorrelated standard normal variables to z-space of correlated standard normal variables.
This procedure computes the transformation from u to z space. u_vars is the vector of random variables in uncorrelated standard normal space (u-space). z_vars is the vector of random variables in normal space with proper correlations (z-space).
References ProbabilityTransformation::corrCholeskyFactorZ, and NatafTransformation::trans_Z_to_X().
Referenced by NatafTransformation::trans_U_to_X().
void trans_Z_to_X (const RealVector & z_vars, RealVector & x_vars) private
Transformation routine from z-space of correlated standard normal variables to x-space of correlated random variables.
This procedure computes the transformation from z to x space. z_vars is the vector of random variables in normal space with proper correlations (z-space). x_vars is the vector of random variables in the original user-defined x-space
Referenced by NatafTransformation::trans_U_to_X(), and NatafTransformation::trans_U_to_Z().
void trans_Z_to_X (Real z, Real & x, size_t i) private
Transformation routine from a single z-space variable to a corresponding x-space variable.
This procedure computes the transformation from z to x space. z_var is the random variable in standardized space with proper correlations (z-space). x_var is the random variable in the original user-defined x-space
References RandomVariable::from_standard(), RandomVariable::inverse_ccdf(), RandomVariable::inverse_cdf(), RandomVariable::parameter(), ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, NormalRandomVariable::std_cdf(), NatafTransformation::trans_X_to_U(), RandomVariable::type(), and ProbabilityTransformation::u_type().
void trans_X_to_Z (const RealVector & x_vars, RealVector & z_vars) private
Transformation routine from x-space of correlated random variables to z-space of correlated standard normal variables.
This procedure performs the transformation from x to z space: z_vars is the vector of random variables in normal space with proper correlations (z-space). x_vars is the vector of random variables in the original user-defined x-space.
Referenced by NatafTransformation::hessian_d2X_dZ2(), NatafTransformation::jacobian_dX_dS(), NatafTransformation::jacobian_dX_dZ(), NatafTransformation::jacobian_dZ_dX(), and NatafTransformation::trans_X_to_U().
void trans_X_to_Z (Real x, Real & z, size_t i) private
Transformation routine from a single x-space random variable to a corresponding z-space variable.
This procedure performs the transformation from x to z space: z_var is the random variable in standardized space with proper correlations (z-space). x_var is the random variable in the original user-defined x-space.
References RandomVariable::ccdf(), RandomVariable::cdf(), RandomVariable::parameter(), ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, RandomVariable::to_standard(), RandomVariable::type(), and ProbabilityTransformation::u_type().
void trans_Z_to_U (RealVector & z_vars, RealVector & u_vars) private
Transformation routine from z-space of correlated standard normal variables to u-space of uncorrelated standard normal variables.
This procedure computes the transformation from z to u space. u_vars is the vector of random variables in uncorrelated standard normal space (u-space). z_vars is the vector of random variables in normal space with proper correlations (z-space).
References ProbabilityTransformation::corrCholeskyFactorZ.
Referenced by NatafTransformation::trans_X_to_U().
void jacobian_dX_dZ (const RealVector & x_vars, RealMatrix & jacobian_xz) private
Jacobian of x(z) mapping obtained from differentiation of trans_Z_to_X()
This procedure computes the Jacobian of the transformation x(z). x_vars is the vector of random variables in the original user-defined x-space.
References NatafTransformation::jacobian_dU_dX(), RandomVariable::parameter(), RandomVariable::pdf(), ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, NormalRandomVariable::std_pdf(), NatafTransformation::trans_X_to_Z(), RandomVariable::type(), and ProbabilityTransformation::u_type().
Referenced by NatafTransformation::jacobian_dX_dU().
void jacobian_dZ_dX (const RealVector & x_vars, RealMatrix & jacobian_zx) private
Jacobian of z(x) mapping obtained from differentiation of trans_X_to_Z()
This procedure computes the Jacobian of the transformation z(x). x_vars is the vector of random variables in the original user-defined x-space.
References NatafTransformation::jacobian_dX_dS(), RandomVariable::parameter(), RandomVariable::pdf(), ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, NormalRandomVariable::std_pdf(), NatafTransformation::trans_X_to_Z(), RandomVariable::type(), and ProbabilityTransformation::u_type().
Referenced by NatafTransformation::jacobian_dU_dX().
void hessian_d2X_dZ2 (const RealVector & x_vars, RealSymMatrixArray & hessian_xz) private
Hessian of x(z) mapping obtained from differentiation of jacobian_dX_dZ()
This procedure computes the Hessian of the transformation x(z). hessian_xz is a 3D tensor modeled as an array of matrices, where the i_th matrix is d^2X_i/dZ^2. x_vars is the vector of random variables in the original user-defined x-space.
References RandomVariable::parameter(), RandomVariable::pdf(), RandomVariable::pdf_gradient(), ProbabilityTransformation::randomVarsX, ProbabilityTransformation::ranVarTypesU, NormalRandomVariable::std_pdf(), NatafTransformation::trans_X_to_Z(), RandomVariable::type(), and ProbabilityTransformation::u_type().
Referenced by NatafTransformation::hessian_d2X_dU2().
The documentation for this class was generated from the following files:
NatafTransformation.hpp
NatafTransformation.cpp