PECOS: NumericGenOrthogPolynomial Class Reference
NumericGenOrthogPolynomial Class Reference
Derived orthogonal polynomial class for numerically-generated orthogonal polynomials.
Public Member Functions
NumericGenOrthogPolynomial ()
default constructor
~NumericGenOrthogPolynomial ()
destructor
Real alpha_recursion (unsigned short order)
calculate and return alpha3TR[order]
Real beta_recursion (unsigned short order)
calculate and return beta3TR[order]
void bounded_normal_distribution (Real mean, Real std_dev, Real l_bnd, Real u_bnd)
set distribution type and parameters for a BOUNDED_NORMAL distribution
void lognormal_distribution (Real lambda, Real zeta)
set distribution type and parameters for a LOGNORMAL distribution
void bounded_lognormal_distribution (Real lambda, Real zeta, Real l_bnd, Real u_bnd)
set distribution type and parameters for a BOUNDED_LOGNORMAL distribution
void loguniform_distribution (Real l_bnd, Real u_bnd)
set distribution type and parameters for a LOGUNIFORM distribution
void triangular_distribution (Real l_bnd, Real mode, Real u_bnd)
set distribution type and parameters for a TRIANGULAR distribution
void gumbel_distribution (Real alpha, Real beta)
set distribution type and parameters for a GUMBEL distribution
void frechet_distribution (Real alpha, Real beta)
set distribution type and parameters for a FRECHET distribution
void weibull_distribution (Real alpha, Real beta)
set distribution type and parameters for a WEIBULL distribution
void histogram_bin_distribution (const RealRealMap &bin_pairs)
set distribution type and parameters for a HISTOGRAM_BIN distribution
void histogram_pt_distribution (const IntRealMap &bin_pairs)
set distribution type and parameters for a HISTOGRAM_PT_INT distribution
void histogram_pt_distribution (const StringRealMap &bin_pairs)
set distribution type and parameters for a HISTOGRAM_PT_STRING distribution
void histogram_pt_distribution (const RealRealMap &bin_pairs)
set distribution type and parameters for a HISTOGRAM_PT_REAL distribution
void coefficients_norms_flag (bool flag)
set coeffsNormsFlag
Public Member Functions inherited from OrthogonalPolynomial
~OrthogonalPolynomial ()
default constructor
void reset_gauss ()
destructor
void precompute_triple_products (const UShortMultiSet &max_ijk)
precompute tripleProductMap
bool triple_product (const UShortMultiSet &ijk_key, Real &trip_prod) const
lookup value based on UShortMultiSet key within tripleProductMap; returns false if not stored
bool triple_product (size_t i, size_t j, size_t k, Real &trip_prod) const
lookup value based on three size_t keys within tripleProductMap; returns false if not stored
void gauss_check (unsigned short order)
perform unit testing on Gauss points/weights
Public Member Functions inherited from BasisPolynomial
BasisPolynomial ()
default constructor
BasisPolynomial (short poly_type, short rule=0)
alternate constructor
BasisPolynomial (const BasisPolynomial &polynomial)
copy constructor
virtual ~BasisPolynomial ()
destructor
BasisPolynomial operator= (const BasisPolynomial &polynomial)
assignment operator
virtual Real type1_value (unsigned short n)
retrieve the value of the n_th type 1 polynomial for a given parameter x using barycentric formulation
virtual Real type2_value (Real x, unsigned short n)
retrieve the value of the n_th type 2 polynomial for a given parameter x
virtual Real type1_gradient (unsigned short n)
retrieve the gradient of the n_th type 1 polynomial for a given parameter x using barycentric formulation
virtual Real type2_gradient (Real x, unsigned short n)
retrieve the gradient of the n_th type 2 polynomial for a given parameter x
virtual const RealArray & type2_collocation_weights (unsigned short order)
return the type 2 collocation weights corresponding to a point set of size order
virtual void set_new_point (Real x, short order)
for barycentric interpolation, set the point to be interpolated for purposes of precomputation of nodal value/gradient factors
virtual void set_new_point (Real x, short order, const UShortArray &delta_key)
for barycentric interpolation, set the point to be interpolated for purposes of precomputation of hierarchical value/gradient factors
virtual size_t exact_index () const
returns the index of a collocation point that is an exact match with the point to be interpolated (from set_new_point()) if detected (_NPOS if not)
virtual size_t exact_delta_index () const
returns the index of a hierarchical increment to the interpolation points that is an exact match with the point to be interpolated (from set_new_point()) if detected (_NPOS if not)
virtual const RealVector & barycentric_value_factors () const
return the barycentric value factors
virtual Real barycentric_value_factor (unsigned short i) const
return a particular barycentric value factor
virtual const RealVector & barycentric_gradient_factors () const
return the barycentric gradient factors
virtual Real barycentric_gradient_factor (unsigned short i) const
return a particular barycentric gradient factor
virtual Real barycentric_value_factor_sum () const
return the sum of all barycentric value factors for use in computing the barycentric interpolant denominator
virtual Real barycentric_difference_product () const
return the product of all differences between the interpolation points and a current point
virtual Real point_factor ()
(calculate and) return ptFactor
virtual Real weight_factor ()
(calculate and) return wtFactor
virtual Real alpha_polynomial () const
return {Jacobi,GenLaguerre}OrthogPolynomial::alphaPoly
virtual Real beta_polynomial () const
return JacobiOrthogPolynomial::betaPoly
virtual void alpha_stat (Real alpha)
set JacobiOrthogPolynomial::betaPoly or GenLaguerreOrthogPolynomial::alphaPoly from statistical defn of alpha
virtual void beta_stat (Real beta)
set JacobiOrthogPolynomial::alphaPoly from statistical defn of beta
virtual size_t interpolation_size () const
get size of InterpolationPolynomial::interpPts
virtual void interpolation_points (const RealArray &interpolation_pts)
set InterpolationPolynomial::interpPts
virtual const RealArray & interpolation_points () const
get InterpolationPolynomial::interpPts
short basis_type () const
return basisPolyType
bool parametric_update () const
return parametricUpdate
BasisPolynomial * polynomial_rep () const
returns polyRep for access to derived class member functions that are not mapped to the top BasisPolynomial level
bool is_null () const
function to check polyRep (does this handle contain a body)
Protected Member Functions
Real type1_value (Real x, unsigned short order)
retrieve the value of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
Real type1_gradient (Real x, unsigned short order)
retrieve the gradient of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
Real type1_hessian (Real x, unsigned short order)
retrieve the Hessian of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
Real norm_squared (unsigned short order)
returns the norm-squared of the n_th order polynomial defined by the inner product <Poly_n, Poly_n> = ||Poly_n||^2
const RealArray & collocation_points (unsigned short order)
return collocation points corresponding to orthogonal polynomial order n
const RealArray & type1_collocation_weights (unsigned short order)
return the type 1 collocation weights corresponding to a point set of size order
bool parameterized () const
return whether a derived BasisPolynomial type supports parameterization
Real length_scale () const
void precompute_rules (unsigned short order)
precompute quadrature rules up to specified order
Protected Member Functions inherited from OrthogonalPolynomial
void collocation_rule (short rule)
set collocRule
short collocation_rule () const
get collocRule
Protected Member Functions inherited from BasisPolynomial
BasisPolynomial (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Private Member Functions
void solve_eigenproblem (unsigned short m)
solve a symmetric tridiagonal eigenvalue problem for the Gauss points and weights for an orthogonal polynomial of order m
void polynomial_recursion (RealVector &poly_coeffs_ip1, Real alpha_i, const RealVector &poly_coeffs_i, Real beta_i, const RealVector &poly_coeffs_im1)
compute three point recursion for polyCoeffs[i+1]
void polynomial_recursion (RealVector &poly_coeffs_ip1, Real alpha_i, const RealVector &poly_coeffs_i)
compute truncated three point recursion for polyCoeffs[i+1]
Real inner_product (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2)
compute inner product of specified polynomial orders
Real hermite_unbounded_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2, NGFPType weight_fn)
compute an unbounded integral using Gauss-Hermite integration
Real fejer_unbounded_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2, NGFPType weight_fn, unsigned short quad_order)
compute an unbounded integral using Fejer integration and a change of variables
Real laguerre_semibounded_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2, NGFPType weight_fn)
compute a semibounded integral using Gauss-Laguerre integration
Real fejer_semibounded_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2, NGFPType weight_fn, unsigned short quad_order)
compute a semibounded integral using Fejer integration and a change of variables
Real legendre_bounded_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2, NGFPType weight_fn, Real start, Real end)
compute a bounded integral over the specified range using Gauss-Legendre integration
Real cc_bounded_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2, NGFPType weight_fn, Real start, Real end, unsigned short quad_order)
compute a bounded integral over the specified range using Clenshaw-Curtis integration
Real riemann_bounded_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2, NGFPType weight_fn, Real start, Real end)
compute a bounded integral over the specified range using Riemann sums
Real native_quadrature_integral (const RealVector &poly_coeffs1, const RealVector &poly_coeffs2)
compute an integral using the native Gaussian quadrature rule (up to order 2m-1 based on collocPoints and collocWeights of order m)
Real type1_value (Real x, const RealVector &poly_coeffs)
retrieve the value of the 1-D generated polynomial (of given coefficients) for a given parameter value
Real type1_gradient (Real x, const RealVector &poly_coeffs)
retrieve the gradient of the 1-D generated polynomial (of given coefficients) with respect to its dimension for a given parameter value
Real type1_hessian (Real x, const RealVector &poly_coeffs)
retrieve the Hessian of the 1-D generated polynomial (of given coefficients) with respect to its dimension for a given parameter value
Static Private Member Functions
static Real bounded_normal_pdf (Real x, const RealVector &params)
thin wrapper for bounded_normal_pdf for NGFPType API
static Real lognormal_pdf (Real x, const RealVector &params)
thin wrapper for lognormal_pdf for NGFPType API
static Real bounded_lognormal_pdf (Real x, const RealVector &params)
thin wrapper for bounded_lognormal_pdf for NGFPType API
static Real loguniform_pdf (Real x, const RealVector &params)
thin wrapper for loguniform_pdf for NGFPType API
static Real triangular_pdf (Real x, const RealVector &params)
thin wrapper for triangular_pdf for NGFPType API
static Real gumbel_pdf (Real x, const RealVector &params)
thin wrapper for gumbel_pdf for NGFPType API
static Real frechet_pdf (Real x, const RealVector &params)
thin wrapper for frechet_pdf for NGFPType API
static Real weibull_pdf (Real x, const RealVector &params)
thin wrapper for weibull_pdf for NGFPType API
Private Attributes
short distributionType
the type of non-Askey distribution: BOUNDED_NORMAL, LOGNORMAL, BOUNDED_LOGNORMAL, LOGUNIFORM, TRIANGULAR, GUMBEL, FRECHET, WEIBULL, HISTOGRAM_BIN, or STOCHASTIC_EXPANSION
RealVector distParams
distribution parameters (e.g., mean, std_dev, alpha, beta)
bool coeffsNormsFlag
flag identifying the need to compute polyCoeffs and orthogPolyNormsSq (if false, only collocPoints and collocWeights are computed)
RealVectorArray polyCoeffs
coefficients of the orthogonal polynomials, from order 0 to m
RealVector alpha3TR
alpha three-term recurrence parameters: alpha3TR[i] multiplied by polyCoeffs[i] contributes to polyCoeffs[i+1]
RealVector beta3TR
beta three-term recurrence parameters: beta3TR[i] multiplied by polyCoeffs[i-1] contributes to polyCoeffs[i+1]
RealVector orthogPolyNormsSq
norm-squared of all orthogonal polynomials, from order 0 to m, as defined by the inner product <Poly_i, Poly_i> = ||Poly_i||^2
Additional Inherited Members
Static Public Member Functions inherited from BasisPolynomial
static Real factorial (unsigned short n)
compute n!
static Real factorial_ratio (unsigned short num, unsigned short den)
compute num!/den!
static Real n_choose_k (unsigned short n, unsigned short k)
compute n!/(k!(n-k)!)
static Real pochhammer (Real m, unsigned short n)
compute the Pochhammer symbol (m)_n = m*(m+1)...*(m+n-1)
Protected Attributes inherited from OrthogonalPolynomial
RealArray collocPoints
collocation points for one-dimensional quadrature (x parameter values for which Poly_n(x) = 0)
RealArray collocWeights
collocation weights for one-dimensional quadrature
short collocRule
the type of integration rule associated with the orthogonal polynomial
Protected Attributes inherited from BasisPolynomial
short basisPolyType
basis polynomial type: {HERMITE,LEGENDRE,LAGUERRE,JACOBI,GEN_LAGUERRE,NUM_GEN}_ORTHOG, {LAGRANGE,HERMITE}_INTERP, or PIECEWISE_{LINEAR,QUADRATIC,CUBIC}_INTERP
bool parametricUpdate
flag indicating presence of a parametric update to the basis polynomial, such that previous points/weights may not be reused
Real wtFactor
weight discrepancy factor between Abramowitz-Stegun and PDF orthogonality
Real ptFactor
point discrepancy factor between Abramowitz-Stegun and PDF orthogonality
Detailed Description
Derived orthogonal polynomial class for numerically-generated orthogonal polynomials.
The NumericGenOrthogPolynomial class numerically generates a univariate orthogonal polynomial of a particular order, along with its Gauss points, Gauss weights, and norms. It uses a variety of algorithms due to Chebyshev and Stieltjes as reported by Golub and Welsch (Mathematics of Computation, Vol. 23, No. 106, 1969) and Gautschi (SIAM J. Sci. Stat. Comput., Vol. 3, No. 3, 1982). It enables (mixed) multidimensional orthogonal polynomial basis functions within OrthogPolyApproximation.
Member Function Documentation
Real type1_value (Real x, unsigned short n) protected virtual
retrieve the value of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented from BasisPolynomial.
References NumericGenOrthogPolynomial::polyCoeffs, and NumericGenOrthogPolynomial::solve_eigenproblem().
Referenced by NumericGenOrthogPolynomial::cc_bounded_integral(), NumericGenOrthogPolynomial::fejer_semibounded_integral(), NumericGenOrthogPolynomial::fejer_unbounded_integral(), NumericGenOrthogPolynomial::hermite_unbounded_integral(), NumericGenOrthogPolynomial::inner_product(), NumericGenOrthogPolynomial::laguerre_semibounded_integral(), NumericGenOrthogPolynomial::legendre_bounded_integral(), NumericGenOrthogPolynomial::native_quadrature_integral(), and NumericGenOrthogPolynomial::riemann_bounded_integral().
Real type1_gradient (Real x, unsigned short n) protected virtual
retrieve the gradient of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented from BasisPolynomial.
References NumericGenOrthogPolynomial::polyCoeffs, and NumericGenOrthogPolynomial::solve_eigenproblem().
Real type1_hessian (Real x, unsigned short n) protected virtual
retrieve the Hessian of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented from BasisPolynomial.
References NumericGenOrthogPolynomial::polyCoeffs, and NumericGenOrthogPolynomial::solve_eigenproblem().
Real norm_squared (unsigned short n) protected virtual
returns the norm-squared of the n_th order polynomial defined by the inner product <Poly_n, Poly_n> = ||Poly_n||^2
This is defined only for orthogonal polynomials.
Reimplemented from BasisPolynomial.
References NumericGenOrthogPolynomial::collocation_points(), NumericGenOrthogPolynomial::orthogPolyNormsSq, and NumericGenOrthogPolynomial::solve_eigenproblem().
const RealArray & collocation_points (unsigned short n) protected virtual
return collocation points corresponding to orthogonal polynomial order n
This is defined for orthogonal and piecewise interpolation polynomials.
Reimplemented from BasisPolynomial.
References OrthogonalPolynomial::collocPoints, NumericGenOrthogPolynomial::solve_eigenproblem(), and NumericGenOrthogPolynomial::type1_collocation_weights().
Referenced by NumericGenOrthogPolynomial::norm_squared().
const RealArray & type1_collocation_weights (unsigned short order) protected virtual
return the type 1 collocation weights corresponding to a point set of size order
This is defined for orthogonal and piecewise interpolation polynomials.
Reimplemented from BasisPolynomial.
References OrthogonalPolynomial::collocWeights, and NumericGenOrthogPolynomial::solve_eigenproblem().
Referenced by NumericGenOrthogPolynomial::collocation_points().
Real length_scale () const inline protected virtual
return max(mean,stdev)
Reimplemented from BasisPolynomial.
References NumericGenOrthogPolynomial::distParams, and NumericGenOrthogPolynomial::distributionType.
void solve_eigenproblem (unsigned short m) private
solve a symmetric tridiagonal eigenvalue problem for the Gauss points and weights for an orthogonal polynomial of order m
Numbering conventions follow Gautschi.
References NumericGenOrthogPolynomial::alpha3TR, NumericGenOrthogPolynomial::beta3TR, NumericGenOrthogPolynomial::coeffsNormsFlag, OrthogonalPolynomial::collocPoints, OrthogonalPolynomial::collocWeights, NumericGenOrthogPolynomial::distParams, NumericGenOrthogPolynomial::distributionType, NumericGenOrthogPolynomial::inner_product(), NumericGenOrthogPolynomial::native_quadrature_integral(), NumericGenOrthogPolynomial::orthogPolyNormsSq, NumericGenOrthogPolynomial::polyCoeffs, and NumericGenOrthogPolynomial::polynomial_recursion().
Referenced by NumericGenOrthogPolynomial::alpha_recursion(), NumericGenOrthogPolynomial::beta_recursion(), NumericGenOrthogPolynomial::collocation_points(), NumericGenOrthogPolynomial::norm_squared(), NumericGenOrthogPolynomial::precompute_rules(), NumericGenOrthogPolynomial::type1_collocation_weights(), NumericGenOrthogPolynomial::type1_gradient(), NumericGenOrthogPolynomial::type1_hessian(), and NumericGenOrthogPolynomial::type1_value().
The documentation for this class was generated from the following files:
NumericGenOrthogPolynomial.hpp
NumericGenOrthogPolynomial.cpp