PECOS: DataTransformation Class Reference
DataTransformation Class Reference
Base class for forward/inverse transformations between time and frequency domain data.
Public Member Functions
DataTransformation ()
default constructor
DataTransformation (const String &data_trans_type)
standard constructor for envelope
DataTransformation (const DataTransformation &data_trans)
copy constructor
virtual ~DataTransformation ()
destructor
DataTransformation operator= (const DataTransformation &data_trans)
assignment operator
virtual void initialize (const Real &total_t, const Real &w_bar, size_t seed)
set scalar data
virtual void power_spectral_density (const String &psd_name, const Real &param=0.)
set PSD to standard embedded function
virtual void power_spectral_density (const RealVector &psd)
pass a discretized PSD directly: vector or pairs...
virtual const RealVector & compute_sample ()
compute and return InverseTransformation::inverseSample
virtual const RealMatrix & compute_samples (size_t num_samples)
compute and return InverseTransformation::inverseSamples
Protected Member Functions
DataTransformation (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
ProbabilityTransformation probTransform
nonlinear variable transformation
Private Member Functions
DataTransformation * get_data_trans (const String &data_trans_type)
Used only by the standard envelope constructor to initialize transRep to the appropriate derived type.
Private Attributes
DataTransformation * dataTransRep
pointer to the letter (initialized only for the envelope)
int referenceCount
number of objects sharing dataTransRep
Detailed Description
Base class for forward/inverse transformations between time and frequency domain data.
The base class for data transformations based on forward/inverse mappings between the time and frequency domain based on spectral/FFT, Karhunen-Loeve, and sampling-based approaches.
Constructor & Destructor Documentation
DataTransformation ()
default constructor
The default constructor: dataTransRep is NULL in this case. This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
DataTransformation (const String & data_trans_type)
standard constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_data_trans, since DataTransformation(BaseConstructor) builds the actual base class data for the derived transformations.
References DataTransformation::dataTransRep, and DataTransformation::get_data_trans().
DataTransformation (const DataTransformation & data_trans)
copy constructor
Copy constructor manages sharing of dataTransRep and incrementing of referenceCount.
References DataTransformation::dataTransRep, DataTransformation::operator=(), and DataTransformation::referenceCount.
~DataTransformation () virtual
destructor
Destructor decrements referenceCount and only deletes dataTransRep when referenceCount reaches zero.
References DataTransformation::dataTransRep, DataTransformation::initialize(), and DataTransformation::referenceCount.
DataTransformation (BaseConstructor) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor is the one which must build the base class data for all derived classes. get_data_trans() instantiates a derived class letter and the derived constructor selects this base class constructor in its initialization list (to avoid recursion in the base class constructor calling get_data_trans() again). Since the letter IS the representation, its rep pointer is set to NULL (an uninitialized pointer causes problems in ~DataTransformation).
Member Function Documentation
DataTransformation operator= (const DataTransformation & data_trans)
assignment operator
Assignment operator decrements referenceCount for old dataTransRep, assigns new dataTransRep, and increments referenceCount for new dataTransRep.
References DataTransformation::dataTransRep, and DataTransformation::referenceCount.
Referenced by DataTransformation::DataTransformation().
DataTransformation * get_data_trans (const String & data_trans_type) private
Used only by the standard envelope constructor to initialize transRep to the appropriate derived type.
Used only by the envelope constructor to initialize dataTransRep to the appropriate derived type.
Referenced by DataTransformation::DataTransformation().
The documentation for this class was generated from the following files:
DataTransformation.hpp
DataTransformation.cpp