PECOS: TensorProductDriver Class Reference
TensorProductDriver Class Reference
generates N-dimensional tensor-product quadrature grids for numerical evaluation of expectation integrals over independent standard random variables.
Public Member Functions
TensorProductDriver ()
default constructor
TensorProductDriver (const UShortArray &quad_order)
constructor
~TensorProductDriver ()
destructor
void compute_grid (RealMatrix &variable_sets)
compute scaled variable and weight sets for the TPQ grid
int grid_size ()
compute number of collocation points
void reinterpolated_tensor_grid (const UShortArray &lev_index, const SizetList &reinterp_indices)
computes and stores data for reinterpolation of covariance on a higher-order tensor grid
void store_grid (size_t index=_NPOS)
store configuration settings for the current grid before advancing to the next settings within a prescribed grid sequence (default is push_back)
void restore_grid (size_t index=_NPOS)
restore configuration settings from a previously stored grid
void remove_stored_grid (size_t index=_NPOS)
remove configuration settings for a stored grid (default is pop_back)
void clear_stored ()
clear stored grid settings following their usage/combination
size_t maximal_grid () const
return the index of the maximal stored grid state (_NPOS if the current unstored grid state)
void swap_grid (size_t index)
swap settings between the current grid and the stored grid identified by index
void quadrature_order (const UShortArray &quad_order)
set quadOrder
void quadrature_order (unsigned short order, size_t i)
set ith entry in quadOrder
const UShortArray & quadrature_order () const
return quadOrder
unsigned short quadrature_order (size_t i) const
return ith entry in quadOrder
void integrand_goal_to_nested_quadrature_order (size_t i, unsigned short integrand_goal, unsigned short &nested_quad_order)
determine the lowest quadrature order that provides integrand exactness at least as great as the specified goal, while satisfying any nestedness constraints
void quadrature_goal_to_nested_quadrature_order (size_t i, unsigned short quad_goal, unsigned short &nested_quad_order)
determine the lowest quadrature order that provides at least as many points as the specified goal, while satisfying any nestedness constraints
void nested_quadrature_order (const UShortArray &ref_quad_order)
update quadOrder and levelIndex from ref_quad_order while satisfying nested rule constraints
const RealVector & type1_weight_sets () const
return type1WeightSets
const RealMatrix & type2_weight_sets () const
return type2WeightSets
const UShortArray & level_index () const
return levelIndex
const UShort2DArray & collocation_key () const
return collocKey
const UShortArray & stored_level_index (size_t index) const
return storedLevelIndex[index]
const UShort2DArray & stored_collocation_key (size_t index) const
return storedCollocKey[index]
void initialize_grid (const ShortArray &u_types, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
stand-alone initializer of tensor grid settings (except for distribution params)
void initialize_grid (const std::vector< BasisPolynomial > &poly_basis)
helper initializer of tensor grid settings (except distribution params)
void precompute_rules ()
precompute quadrature rules to the maximum current order for each basis polynomial (efficiency optimization when rules are expensive to compute)
Public Member Functions inherited from IntegrationDriver
IntegrationDriver ()
default constructor
IntegrationDriver (short driver_type)
standard constructor for envelope
IntegrationDriver (const IntegrationDriver &driver)
copy constructor
virtual ~IntegrationDriver ()
destructor
IntegrationDriver operator= (const IntegrationDriver &driver)
assignment operator
virtual void initialize_grid_parameters (const ShortArray &u_types, const AleatoryDistParams &adp)
update polynomialBasis with data from AleatoryDistParams
void assign_rep (IntegrationDriver *driver_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
void compute_tensor_grid (const UShortArray &quad_order, const UShortArray &lev_index, const SizetList &subset_indices, RealMatrix &variable_sets, UShort2DArray &colloc_key)
compute variable sets for a tensor-product grid
void update_1d_collocation_points_weights (const UShortArray &quad_order, const UShortArray &lev_index)
update collocPts1D and type{1,2}CollocWts1D
const std::vector< BasisPolynomial > & polynomial_basis () const
return polynomialBasis
void mode (short driver_mode)
set driverMode
short mode () const
get driverMode
const Real3DArray & collocation_points_1d () const
return collocPts1D
const Real3DArray & type1_collocation_weights_1d () const
return type1CollocWts1D
const Real3DArray & type2_collocation_weights_1d () const
return type2CollocWts1D
const ShortArray & collocation_rules () const
return collocRules
const UShortArray & reinterpolated_level_index () const
return reinterpLevelIndices[activeReinterpIndex]
const UShortArray & reinterpolated_quadrature_order () const
return reinterpQuadOrders[activeReinterpIndex]
const RealMatrix & reinterpolated_variable_sets () const
return reinterpVarSets[activeReinterpIndex]
const UShort2DArray & reinterpolated_collocation_key () const
return reinterpCollocKeys[activeReinterpIndex]
const UShortArray & genz_keister_order () const
return orderGenzKeister
const UShortArray & genz_keister_precision () const
return precGenzKeister
IntegrationDriver * driver_rep () const
returns driverRep for access to derived class member functions that are not mapped to the base level
Private Member Functions
void update_level_index_from_quadrature_order ()
update levelIndex from quadOrder
void update_level_index_from_quadrature_order (size_t i)
update levelIndex[i] from quadOrder[i]
void update_quadrature_order_from_level_index ()
update quadOrder from levelIndex
Private Attributes
UShortArray quadOrder
the isotropic/anisotropic quadrature order
UShortArray levelIndex
quadrature order offset by one for use as 0-based indices
UShort2DArray collocKey
num points-by-numVars array for identifying the 1-D point indices for sets of tensor-product collocation points
UShort2DArray storedLevelIndex
stored driver states: copies of levelIndex
UShort3DArray storedCollocKey
stored driver states: copies of collocKey
RealVector type1WeightSets
the set of type1 weights (for integration of value interpolants) associated with each point in the tensor grid
RealMatrix type2WeightSets
the set of type2 weights (for integration of gradient interpolants) for each derivative component and for each point in the tensor grid
RealVectorArray storedType1WeightSets
stored driver states: copies of type1WeightSets
RealMatrixArray storedType2WeightSets
stored driver states: copies of type2WeightSets
Additional Inherited Members
Protected Member Functions inherited from IntegrationDriver
IntegrationDriver (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
void compute_tensor_grid (const UShortArray &quad_order, const UShortArray &lev_index, RealMatrix &variable_sets, RealVector &t1_weight_sets, RealMatrix &t2_weight_sets, UShort2DArray &colloc_key)
compute variable and weight sets for a tensor-product grid
void update_1d_collocation_points_weights (const UShortArray &quad_order, const UShortArray &lev_index, const SizetList &subset_indices)
update collocPts1D and type{1,2}CollocWts1D for subset variables
void assign_1d_collocation_points_weights (size_t i, unsigned short quad_order, unsigned short lev_index)
update collocPts1D[lev_index][i] and type{1,2}CollocWts1D[lev_index][i]
Protected Attributes inherited from IntegrationDriver
size_t numVars
number of variables in the tensor-product grid
short driverMode
enumeration value indicating INTEGRATION_MODE or INTERPOLATION_MODE
ShortArray collocRules
enumeration codes for integration rule options. Manages internal mode switches for 1D polynomial types: e.g., GAUSS_LEGENDRE or GAUSS_PATTERSON for Legendre, CLENSHAW_CURTIS or FEJER2 for Chebyshev, GAUSS_HERMITE or GENZ_KEISTER for Hermite.
std::vector< BasisPolynomial > polynomialBasis
array of one-dimensional orthogonal polynomials used in computing Gaussian quadrature points and weights
Real3DArray collocPts1D
num_levels_per_var x numVars sets of 1D collocation points
Real3DArray type1CollocWts1D
num_levels_per_var x numVars sets of 1D type1 collocation weights
Real3DArray type2CollocWts1D
num_levels_per_var x numVars sets of 1D type2 collocation weights
bool computeType2Weights
flag indicating usage of compute1DType2Weights to define type2WeightSets
UShort2DArray reinterpLevelIndices
bookkeeping for reinterpolation of covariance: stored level indices
UShort2DArray reinterpQuadOrders
bookkeeping for reinterpolation of covariance: stored quadrature orders
RealMatrixArray reinterpVarSets
bookkeeping for reinterpolation of covariance: stored variable sets
UShort3DArray reinterpCollocKeys
bookkeeping for reinterpolation of covariance: stored collocation keys
std::map< UShortArray, size_t > reinterpMap
tracks existing reinterpolation grids to avoid unnecessary recomputation
size_t activeReinterpIndex
bookkeeping for reinterpolation of covariance: active index into arrays
Static Protected Attributes inherited from IntegrationDriver
static UShortArray orderGenzKeister
lookup for set of 1-D Genz-Keister quadrature orders
static UShortArray precGenzKeister
lookup for set of 1-D Genz-Keister integrand precisions
Detailed Description
generates N-dimensional tensor-product quadrature grids for numerical evaluation of expectation integrals over independent standard random variables.
This class is used by Dakota::NonDQuadrature, but could also be used for general numerical integration of moments.
Member Function Documentation
void integrand_goal_to_nested_quadrature_order (size_t i, unsigned short integrand_goal, unsigned short & nested_quad_order)
determine the lowest quadrature order that provides integrand exactness at least as great as the specified goal, while satisfying any nestedness constraints
This function selects the smallest nested rule order that meets the integrand precision of a corresponding Gauss rule. It is similar to the moderate exponential growth option in sparse grids.
References IntegrationDriver::collocRules, IntegrationDriver::orderGenzKeister, IntegrationDriver::precGenzKeister, and TensorProductDriver::quadrature_goal_to_nested_quadrature_order().
Referenced by TensorProductDriver::nested_quadrature_order(), and TensorProductDriver::swap_grid().
void quadrature_goal_to_nested_quadrature_order (size_t i, unsigned short quad_goal, unsigned short & nested_quad_order)
determine the lowest quadrature order that provides at least as many points as the specified goal, while satisfying any nestedness constraints
This function selects the smallest nested rule order that meets the quadrature order goal.
References IntegrationDriver::collocRules, IntegrationDriver::orderGenzKeister, and TensorProductDriver::reinterpolated_tensor_grid().
Referenced by TensorProductDriver::integrand_goal_to_nested_quadrature_order(), and TensorProductDriver::nested_quadrature_order().
The documentation for this class was generated from the following files:
TensorProductDriver.hpp
TensorProductDriver.cpp