PECOS: LightweightSparseGridDriver Class Reference
LightweightSparseGridDriver Class Reference
Lighweight sparse grid driver class that generates index sets for N-dimensional Smolyak sparse grids.
Public Member Functions
LightweightSparseGridDriver ()
default constructor
LightweightSparseGridDriver (unsigned short ssg_level, const RealVector &dim_pref=RealVector(), short growth_rate=MODERATE_RESTRICTED_GROWTH, short refine_control=NO_CONTROL)
constructor
~LightweightSparseGridDriver ()
destructor
void initialize_sets ()
initializes old/active/evaluation sets for use within the generalized sparse grid procedure
void push_trial_set (const UShortArray &set)
update smolyakMultiIndex with a new trial set for use within the generalized sparse grid procedure
void pop_trial_set ()
remove the previously pushed trial set from smolyakMultiIndex during the course of the generalized sparse grid procedure
const UShortArray & trial_set () const
return the trial index set from push_trial_set()
void print_smolyak_multi_index () const
print smolyakMultiIndex
void initialize_grid (size_t num_v, unsigned short ssg_level)
initialize a lightweight instance that only generates index sets
void prune_sets (const SizetSet &save_tp)
prune sets from oldMultiIndex and redefine activeMultiIndex
const UShort2DArray & smolyak_multi_index () const
return smolyakMultiIndex
Public Member Functions inherited from SparseGridDriver
SparseGridDriver ()
default constructor
SparseGridDriver (unsigned short ssg_level, const RealVector &dim_pref, short growth_rate, short refine_control)
constructor
~SparseGridDriver ()
destructor
virtual void restore_set ()
update collocKey, collocIndices, and uniqueIndexMapping based on restoration of previous trial to smolyakMultiIndex
virtual void compute_trial_grid (RealMatrix &var_sets)
computes the tensor grid for the index set from push_trial_set()
virtual void merge_set ()
merge reference sets with trial set and update reference set
virtual void finalize_sets (bool output_sets, bool converged_within_tol)
accept all remaining trial sets within the generalized sparse grid procedure
virtual void update_reference ()
update derived reference data, if required
virtual int unique_trial_points () const
return the number of unique collocation points in the trial index set
virtual void compute_grid_increment (RealMatrix &var_sets)
computes tensor grids for new index sets due to an isotropic/anisotropic refinement
void initialize_grid (unsigned short ssg_level, const RealVector &dim_pref, const ShortArray &u_types, const ExpansionConfigOptions &ec_options, BasisConfigOptions &bc_options, short growth_rate=MODERATE_RESTRICTED_GROWTH)
initialize all sparse grid settings except for distribution params
void precompute_rules ()
precompute quadrature rules to the maximum current order for each basis polynomial (efficiency optimization when rules are expensive to compute)
void assign_1d_collocation_points_weights ()
initialize collocPts1D and type{1,2}CollocWts1D
void update_axis_lower_bounds ()
update axisLowerBounds
void update_sets (const UShortArray &set_star)
accept the best of several trial sets and update old/active within the generalized sparse grid procedure
void add_active_neighbors (const UShortArray &set, bool frontier)
update activeMultiIndex from the passed trial set for use within the generalized sparse grid procedure
void level_to_order (size_t i, unsigned short level, unsigned short &order)
converts an array of sparse grid levels to an array of quadrature orders based on apiIntegrationRules/apiGrowthRules
void level_to_order (const UShortArray &levels, UShortArray &orders)
converts an array of sparse grid levels to an array of quadrature orders based on apiIntegrationRules/apiGrowthRules
void level (unsigned short ssg_level)
set ssgLevel
unsigned short level () const
return ssgLevel
void dimension_preference (const RealVector &dim_pref)
set anisoLevelWts
void anisotropic_weights (const RealVector &aniso_wts)
set anisoLevelWts
const RealVector & anisotropic_weights () const
return anisoLevelWts
bool isotropic () const
return dimIsotropic
void growth_rate (short growth_rate)
set growthRate
short growth_rate () const
get growthRate
void refinement_control (short cntl)
set refineControl
short refinement_control () const
get refineControl
const UShortArraySet & active_multi_index () const
return activeMultiIndex
const UShortArraySet & computed_trial_sets () const
return computedTrialSets
Public Member Functions inherited from IntegrationDriver
IntegrationDriver ()
default constructor
IntegrationDriver (short driver_type)
standard constructor for envelope
IntegrationDriver (const IntegrationDriver &driver)
copy constructor
virtual ~IntegrationDriver ()
destructor
IntegrationDriver operator= (const IntegrationDriver &driver)
assignment operator
virtual void initialize_grid (const std::vector< BasisPolynomial > &poly_basis)
initialize all grid settings (distribution params already set within poly_basis)
virtual void initialize_grid (const ShortArray &u_types, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
set int_rules and growth_rules from u_types and mode booleans
virtual void initialize_grid_parameters (const ShortArray &u_types, const AleatoryDistParams &adp)
update polynomialBasis with data from AleatoryDistParams
virtual void compute_grid (RealMatrix &var_sets)
compute scaled variable and weight sets for the TPQ grid
virtual int grid_size ()
compute number of collocation points
virtual void reinterpolated_tensor_grid (const UShortArray &lev_index, const SizetList &reinterp_indices)
computes and stores data for reinterpolation of covariance on a higher-order tensor grid
virtual void store_grid (size_t index=_NPOS)
store configuration settings for the current grid before advancing to the next settings within a prescribed grid sequence (default is push_back)
virtual void restore_grid (size_t index=_NPOS)
restore configuration settings from a previously stored grid
virtual void remove_stored_grid (size_t index=_NPOS)
remove configuration settings for a stored grid (default is pop_back)
virtual void clear_stored ()
clear stored grid settings following their usage/combination
virtual size_t maximal_grid () const
return the index of the maximal stored grid state (_NPOS if the current unstored grid state)
virtual void swap_grid (size_t index)
swap settings between the current grid and the stored grid identified by index
virtual const RealVector & type1_weight_sets () const
return type1WeightSets from Cubature/TensorProduct/CombinedSparseGrid or concatenate type1WeightSets in HierarchSparseGrid
virtual const RealMatrix & type2_weight_sets () const
return type2WeightSets from Cubature/TensorProduct/CombinedSparseGrid or concatenate type2WeightSets in HierarchSparseGrid
void assign_rep (IntegrationDriver *driver_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
void compute_tensor_grid (const UShortArray &quad_order, const UShortArray &lev_index, const SizetList &subset_indices, RealMatrix &variable_sets, UShort2DArray &colloc_key)
compute variable sets for a tensor-product grid
void update_1d_collocation_points_weights (const UShortArray &quad_order, const UShortArray &lev_index)
update collocPts1D and type{1,2}CollocWts1D
const std::vector< BasisPolynomial > & polynomial_basis () const
return polynomialBasis
void mode (short driver_mode)
set driverMode
short mode () const
get driverMode
const Real3DArray & collocation_points_1d () const
return collocPts1D
const Real3DArray & type1_collocation_weights_1d () const
return type1CollocWts1D
const Real3DArray & type2_collocation_weights_1d () const
return type2CollocWts1D
const ShortArray & collocation_rules () const
return collocRules
const UShortArray & reinterpolated_level_index () const
return reinterpLevelIndices[activeReinterpIndex]
const UShortArray & reinterpolated_quadrature_order () const
return reinterpQuadOrders[activeReinterpIndex]
const RealMatrix & reinterpolated_variable_sets () const
return reinterpVarSets[activeReinterpIndex]
const UShort2DArray & reinterpolated_collocation_key () const
return reinterpCollocKeys[activeReinterpIndex]
const UShortArray & genz_keister_order () const
return orderGenzKeister
const UShortArray & genz_keister_precision () const
return precGenzKeister
IntegrationDriver * driver_rep () const
returns driverRep for access to derived class member functions that are not mapped to the base level
Private Attributes
UShort2DArray smolyakMultiIndex
numSmolyakIndices-by-numVars array for identifying the index to use within the polynomialBasis for a particular variable
Additional Inherited Members
Protected Member Functions inherited from SparseGridDriver
void print_index_set (std::ostream &s, const UShortArray &mi) const
print an index set
Protected Member Functions inherited from IntegrationDriver
IntegrationDriver (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
void compute_tensor_grid (const UShortArray &quad_order, const UShortArray &lev_index, RealMatrix &variable_sets, RealVector &t1_weight_sets, RealMatrix &t2_weight_sets, UShort2DArray &colloc_key)
compute variable and weight sets for a tensor-product grid
void update_1d_collocation_points_weights (const UShortArray &quad_order, const UShortArray &lev_index, const SizetList &subset_indices)
update collocPts1D and type{1,2}CollocWts1D for subset variables
void assign_1d_collocation_points_weights (size_t i, unsigned short quad_order, unsigned short lev_index)
update collocPts1D[lev_index][i] and type{1,2}CollocWts1D[lev_index][i]
Static Protected Member Functions inherited from SparseGridDriver
static int level_to_order_exp_hgk_interp (int level, int growth)
level to order mapping for interpolation with nested Genz-Keister rules
static int level_to_order_exp_closed_interp (int level, int growth)
level to order mapping for interpolation with nested closed rules
static int level_to_order_exp_open_interp (int level, int growth)
level to order mapping for interpolation with nested open rules
Protected Attributes inherited from SparseGridDriver
unsigned short ssgLevel
the Smolyak sparse grid level
bool dimIsotropic
flag indicating a dimension isotropic grid
RealVector anisoLevelWts
weighting vector for dimension anisotropic grids
short growthRate
enumeration for rate of exponential growth in nested rules
short refineControl
algorithm control governing expansion refinement
int numCollocPts
the current number of unique points in the grid
bool updateGridSize
flag indicating when numCollocPts needs to be recomputed due to an update to the sparse grid settings
UShortArraySet oldMultiIndex
old reference index sets for generalized sparse grids
UShortArraySet activeMultiIndex
active index sets under current consideration for inclusion in a generalized sparse grid
UShortArraySet computedTrialSets
subset of active set that have been evaluated as trial sets (incremented in compute_trial_grid() and decremented in update_sets())
Protected Attributes inherited from IntegrationDriver
size_t numVars
number of variables in the tensor-product grid
short driverMode
enumeration value indicating INTEGRATION_MODE or INTERPOLATION_MODE
ShortArray collocRules
enumeration codes for integration rule options. Manages internal mode switches for 1D polynomial types: e.g., GAUSS_LEGENDRE or GAUSS_PATTERSON for Legendre, CLENSHAW_CURTIS or FEJER2 for Chebyshev, GAUSS_HERMITE or GENZ_KEISTER for Hermite.
std::vector< BasisPolynomial > polynomialBasis
array of one-dimensional orthogonal polynomials used in computing Gaussian quadrature points and weights
Real3DArray collocPts1D
num_levels_per_var x numVars sets of 1D collocation points
Real3DArray type1CollocWts1D
num_levels_per_var x numVars sets of 1D type1 collocation weights
Real3DArray type2CollocWts1D
num_levels_per_var x numVars sets of 1D type2 collocation weights
bool computeType2Weights
flag indicating usage of compute1DType2Weights to define type2WeightSets
UShort2DArray reinterpLevelIndices
bookkeeping for reinterpolation of covariance: stored level indices
UShort2DArray reinterpQuadOrders
bookkeeping for reinterpolation of covariance: stored quadrature orders
RealMatrixArray reinterpVarSets
bookkeeping for reinterpolation of covariance: stored variable sets
UShort3DArray reinterpCollocKeys
bookkeeping for reinterpolation of covariance: stored collocation keys
std::map< UShortArray, size_t > reinterpMap
tracks existing reinterpolation grids to avoid unnecessary recomputation
size_t activeReinterpIndex
bookkeeping for reinterpolation of covariance: active index into arrays
Static Protected Attributes inherited from IntegrationDriver
static UShortArray orderGenzKeister
lookup for set of 1-D Genz-Keister quadrature orders
static UShortArray precGenzKeister
lookup for set of 1-D Genz-Keister integrand precisions
Detailed Description
Lighweight sparse grid driver class that generates index sets for N-dimensional Smolyak sparse grids.
This class is used for basis adaptation using sparse grid index sets and omits many of the details needed for computing expectation integrals.
Member Function Documentation
void initialize_sets () virtual
initializes old/active/evaluation sets for use within the generalized sparse grid procedure
dimIsotropic ||
Implements SparseGridDriver.
References SparseGridDriver::activeMultiIndex, SparseGridDriver::add_active_neighbors(), SparseGridDriver::oldMultiIndex, LightweightSparseGridDriver::smolyakMultiIndex, and SparseGridDriver::ssgLevel.
Referenced by RegressOrthogPolyApproximation::adapt_regression().
void initialize_grid (size_t num_v, unsigned short ssg_level)
initialize a lightweight instance that only generates index sets
this lightweight sparse grid mode only generates index sets without points, weights, or collocation bookkeeping.
References IntegrationDriver::numVars, LightweightSparseGridDriver::smolyakMultiIndex, SparseGridDriver::ssgLevel, and SharedPolyApproxData::total_order_multi_index().
Referenced by SharedRegressOrthogPolyApproxData::allocate_data().
Member Data Documentation
UShort2DArray smolyakMultiIndex private
numSmolyakIndices-by-numVars array for identifying the index to use within the polynomialBasis for a particular variable
The index sets correspond to j (0-based) for use as indices, which are offset from the i indices (1-based) normally used in the Smolyak expressions. The indices correspond to levels, one for each anisotropic tensor-product grid within a Smolyak recursion.
Referenced by LightweightSparseGridDriver::initialize_grid(), LightweightSparseGridDriver::initialize_sets(), LightweightSparseGridDriver::pop_trial_set(), LightweightSparseGridDriver::print_smolyak_multi_index(), LightweightSparseGridDriver::prune_sets(), LightweightSparseGridDriver::push_trial_set(), LightweightSparseGridDriver::smolyak_multi_index(), and LightweightSparseGridDriver::trial_set().
The documentation for this class was generated from the following files:
LightweightSparseGridDriver.hpp
LightweightSparseGridDriver.cpp