PECOS: BasisPolynomial Class Reference
BasisPolynomial Class Reference
Base class for the basis polynomial class hierarchy.
Public Member Functions
BasisPolynomial ()
default constructor
BasisPolynomial (short poly_type, short rule=0)
alternate constructor
BasisPolynomial (const BasisPolynomial &polynomial)
copy constructor
virtual ~BasisPolynomial ()
destructor
BasisPolynomial operator= (const BasisPolynomial &polynomial)
assignment operator
virtual Real type1_value (unsigned short n)
retrieve the value of the n_th type 1 polynomial for a given parameter x using barycentric formulation
virtual Real type1_value (Real x, unsigned short n)
retrieve the value of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
virtual Real type2_value (Real x, unsigned short n)
retrieve the value of the n_th type 2 polynomial for a given parameter x
virtual Real type1_gradient (unsigned short n)
retrieve the gradient of the n_th type 1 polynomial for a given parameter x using barycentric formulation
virtual Real type1_gradient (Real x, unsigned short n)
retrieve the gradient of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
virtual Real type2_gradient (Real x, unsigned short n)
retrieve the gradient of the n_th type 2 polynomial for a given parameter x
virtual Real type1_hessian (Real x, unsigned short n)
retrieve the Hessian of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
virtual Real norm_squared (unsigned short n)
returns the norm-squared of the n_th order polynomial defined by the inner product <Poly_n, Poly_n> = ||Poly_n||^2
virtual const RealArray & collocation_points (unsigned short n)
return collocation points corresponding to orthogonal polynomial order n
virtual const RealArray & type1_collocation_weights (unsigned short order)
return the type 1 collocation weights corresponding to a point set of size order
virtual const RealArray & type2_collocation_weights (unsigned short order)
return the type 2 collocation weights corresponding to a point set of size order
virtual void set_new_point (Real x, short order)
for barycentric interpolation, set the point to be interpolated for purposes of precomputation of nodal value/gradient factors
virtual void set_new_point (Real x, short order, const UShortArray &delta_key)
for barycentric interpolation, set the point to be interpolated for purposes of precomputation of hierarchical value/gradient factors
virtual size_t exact_index () const
returns the index of a collocation point that is an exact match with the point to be interpolated (from set_new_point()) if detected (_NPOS if not)
virtual size_t exact_delta_index () const
returns the index of a hierarchical increment to the interpolation points that is an exact match with the point to be interpolated (from set_new_point()) if detected (_NPOS if not)
virtual const RealVector & barycentric_value_factors () const
return the barycentric value factors
virtual Real barycentric_value_factor (unsigned short i) const
return a particular barycentric value factor
virtual const RealVector & barycentric_gradient_factors () const
return the barycentric gradient factors
virtual Real barycentric_gradient_factor (unsigned short i) const
return a particular barycentric gradient factor
virtual Real barycentric_value_factor_sum () const
return the sum of all barycentric value factors for use in computing the barycentric interpolant denominator
virtual Real barycentric_difference_product () const
return the product of all differences between the interpolation points and a current point
virtual void reset_gauss ()
destroy history of Gauss pts/wts (due to distribution parameter changes)
virtual Real point_factor ()
(calculate and) return ptFactor
virtual Real weight_factor ()
(calculate and) return wtFactor
virtual Real alpha_polynomial () const
return {Jacobi,GenLaguerre}OrthogPolynomial::alphaPoly
virtual Real beta_polynomial () const
return JacobiOrthogPolynomial::betaPoly
virtual void alpha_stat (Real alpha)
set JacobiOrthogPolynomial::betaPoly or GenLaguerreOrthogPolynomial::alphaPoly from statistical defn of alpha
virtual void beta_stat (Real beta)
set JacobiOrthogPolynomial::alphaPoly from statistical defn of beta
virtual void collocation_rule (short rule)
set OrthogonalPolynomial::collocRule
virtual short collocation_rule () const
get OrthogonalPolynomial::collocRule
virtual size_t interpolation_size () const
get size of InterpolationPolynomial::interpPts
virtual void interpolation_points (const RealArray &interpolation_pts)
set InterpolationPolynomial::interpPts
virtual const RealArray & interpolation_points () const
get InterpolationPolynomial::interpPts
virtual bool parameterized () const
return whether a derived BasisPolynomial type supports parameterization
virtual Real length_scale () const
return a characteristic length scale for the probability distribution associated with an orthogonal polynomial basis
virtual void precompute_rules (unsigned short order)
precompute quadrature rules up to specified order
short basis_type () const
return basisPolyType
bool parametric_update () const
return parametricUpdate
BasisPolynomial * polynomial_rep () const
returns polyRep for access to derived class member functions that are not mapped to the top BasisPolynomial level
bool is_null () const
function to check polyRep (does this handle contain a body)
Static Public Member Functions
static Real factorial (unsigned short n)
compute n!
static Real factorial_ratio (unsigned short num, unsigned short den)
compute num!/den!
static Real n_choose_k (unsigned short n, unsigned short k)
compute n!/(k!(n-k)!)
static Real pochhammer (Real m, unsigned short n)
compute the Pochhammer symbol (m)_n = m*(m+1)...*(m+n-1)
Protected Member Functions
BasisPolynomial (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
short basisPolyType
basis polynomial type: {HERMITE,LEGENDRE,LAGUERRE,JACOBI,GEN_LAGUERRE,NUM_GEN}_ORTHOG, {LAGRANGE,HERMITE}_INTERP, or PIECEWISE_{LINEAR,QUADRATIC,CUBIC}_INTERP
bool parametricUpdate
flag indicating presence of a parametric update to the basis polynomial, such that previous points/weights may not be reused
Real wtFactor
weight discrepancy factor between Abramowitz-Stegun and PDF orthogonality
Real ptFactor
point discrepancy factor between Abramowitz-Stegun and PDF orthogonality
Private Member Functions
BasisPolynomial * get_polynomial (short poly_type, short rule)
Used by the envelope constructor to initialize polyRep to the appropriate derived type.
Private Attributes
BasisPolynomial * polyRep
pointer to the letter (initialized only for the envelope)
int referenceCount
number of objects sharing polyRep
Detailed Description
Base class for the basis polynomial class hierarchy.
The BasisPolynomial class is the base class for the univariate basis polynomial class hierarchy in PECOS. One instance of an BasisPolynomial is created for each variable within a multidimensional polynomial basis function (a vector of BasisPolynomials is contained in BasisPolyApproximation, which may be mixed and matched in, e.g., the Wiener-Askey scheme for polynomial chaos). For memory efficiency and enhanced polymorphism, the basis polynomial hierarchy employs the "letter/envelope idiom" (see Coplien "Advanced C++", p. 133), for which the base class (BasisPolynomial) serves as the envelope and one of the derived classes (selected in BasisPolynomial::get_polynomial()) serves as the letter.
Constructor & Destructor Documentation
BasisPolynomial ()
default constructor
The default constructor is used in Array<BasisPolynomial> instantiations and by the alternate envelope constructor. polyRep is NULL in this case (problem_db is needed to build a meaningful instance). This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
BasisPolynomial (short poly_type, short rule = 0)
alternate constructor
Envelope constructor which does not require access to problem_db. This constructor executes get_polynomial(type), which invokes the default constructor of the derived letter class, which in turn invokes the BaseConstructor of the base class.
References BasisPolynomial::get_polynomial(), and BasisPolynomial::polyRep.
BasisPolynomial (const BasisPolynomial & polynomial)
copy constructor
Copy constructor manages sharing of polyRep and incrementing of referenceCount.
References BasisPolynomial::polyRep, and BasisPolynomial::referenceCount.
~BasisPolynomial () virtual
destructor
Destructor decrements referenceCount and only deletes polyRep when referenceCount reaches zero.
References BasisPolynomial::polyRep, and BasisPolynomial::referenceCount.
BasisPolynomial (BaseConstructor) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor is the one which must build the base class data for all derived classes. get_polynomial() instantiates a derived class letter and the derived constructor selects this base class constructor in its initialization list (to avoid recursion in the base class constructor calling get_polynomial() again). Since the letter IS the representation, its rep pointer is set to NULL (an uninitialized pointer causes problems in ~BasisPolynomial).
Member Function Documentation
BasisPolynomial operator= (const BasisPolynomial & polynomial)
assignment operator
Assignment operator decrements referenceCount for old polyRep, assigns new polyRep, and increments referenceCount for new polyRep.
References BasisPolynomial::polyRep, and BasisPolynomial::referenceCount.
Real type1_value (unsigned short n) virtual
retrieve the value of the n_th type 1 polynomial for a given parameter x using barycentric formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented in LagrangeInterpPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type1_value().
Referenced by SharedNodalInterpPolyApproxData::accumulate_horners(), SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), SharedNodalInterpPolyApproxData::basis_product_1d(), OrthogonalPolynomial::gauss_check(), OrthogonalPolynomial::precompute_triple_products(), NodalInterpPolyApproximation::tensor_product_covariance(), NodalInterpPolyApproximation::tensor_product_mean(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), SharedProjectOrthogPolyApproxData::tensor_product_value(), SharedInterpPolyApproxData::tensor_product_value(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), and BasisPolynomial::type1_value().
Real type1_value (Real x, unsigned short n) virtual
retrieve the value of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented in NumericGenOrthogPolynomial, JacobiOrthogPolynomial, HahnOrthogPolynomial, GenLaguerreOrthogPolynomial, MeixnerOrthogPolynomial, LagrangeInterpPolynomial, KrawtchoukOrthogPolynomial, PiecewiseInterpPolynomial, HermiteInterpPolynomial, LegendreOrthogPolynomial, LaguerreOrthogPolynomial, ChebyshevOrthogPolynomial, HermiteOrthogPolynomial, and CharlierOrthogPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type1_value().
Real type2_value (Real x, unsigned short n) virtual
retrieve the value of the n_th type 2 polynomial for a given parameter x
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented in PiecewiseInterpPolynomial, and HermiteInterpPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type2_value().
Referenced by SharedNodalInterpPolyApproxData::accumulate_horners(), SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), NodalInterpPolyApproximation::tensor_product_covariance(), NodalInterpPolyApproximation::tensor_product_mean(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), SharedInterpPolyApproxData::tensor_product_value(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), and BasisPolynomial::type2_value().
Real type1_gradient (unsigned short n) virtual
retrieve the gradient of the n_th type 1 polynomial for a given parameter x using barycentric formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented in LagrangeInterpPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type1_gradient().
Referenced by SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), SharedOrthogPolyApproxData::gradient_check(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), and BasisPolynomial::type1_gradient().
Real type1_gradient (Real x, unsigned short n) virtual
retrieve the gradient of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented in NumericGenOrthogPolynomial, JacobiOrthogPolynomial, GenLaguerreOrthogPolynomial, LagrangeInterpPolynomial, PiecewiseInterpPolynomial, HermiteInterpPolynomial, LegendreOrthogPolynomial, LaguerreOrthogPolynomial, ChebyshevOrthogPolynomial, HermiteOrthogPolynomial, and CharlierOrthogPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type1_gradient().
Real type2_gradient (Real x, unsigned short n) virtual
retrieve the gradient of the n_th type 2 polynomial for a given parameter x
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented in PiecewiseInterpPolynomial, and HermiteInterpPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type2_gradient().
Referenced by SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), and BasisPolynomial::type2_gradient().
Real type1_hessian (Real x, unsigned short n) virtual
retrieve the Hessian of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
For orthogonal polynomials, n specifies the order of the polynomial, whereas for interpolation polynomials, it identifies the interpolant for the n-th point.
Reimplemented in NumericGenOrthogPolynomial, JacobiOrthogPolynomial, GenLaguerreOrthogPolynomial, LegendreOrthogPolynomial, LaguerreOrthogPolynomial, ChebyshevOrthogPolynomial, HermiteOrthogPolynomial, and CharlierOrthogPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type1_hessian().
Referenced by BasisPolynomial::type1_hessian().
Real norm_squared (unsigned short n) virtual
returns the norm-squared of the n_th order polynomial defined by the inner product <Poly_n, Poly_n> = ||Poly_n||^2
This is defined only for orthogonal polynomials.
Reimplemented in NumericGenOrthogPolynomial, JacobiOrthogPolynomial, GenLaguerreOrthogPolynomial, LegendreOrthogPolynomial, LaguerreOrthogPolynomial, ChebyshevOrthogPolynomial, HermiteOrthogPolynomial, and CharlierOrthogPolynomial.
References BasisPolynomial::norm_squared(), and BasisPolynomial::polyRep.
Referenced by RegressOrthogPolyApproximation::dimension_decay_rates(), BasisPolynomial::norm_squared(), and OrthogonalPolynomial::precompute_triple_products().
const RealArray & collocation_points (unsigned short n) virtual
return collocation points corresponding to orthogonal polynomial order n
This is defined for orthogonal and piecewise interpolation polynomials.
Reimplemented in NumericGenOrthogPolynomial, JacobiOrthogPolynomial, GenLaguerreOrthogPolynomial, PiecewiseInterpPolynomial, HermiteInterpPolynomial, LegendreOrthogPolynomial, LaguerreOrthogPolynomial, ChebyshevOrthogPolynomial, and HermiteOrthogPolynomial.
References BasisPolynomial::collocation_points(), and BasisPolynomial::polyRep.
Referenced by IntegrationDriver::assign_1d_collocation_points_weights(), BasisPolynomial::collocation_points(), OrthogonalPolynomial::gauss_check(), NumericGenOrthogPolynomial::hermite_unbounded_integral(), NumericGenOrthogPolynomial::laguerre_semibounded_integral(), NumericGenOrthogPolynomial::legendre_bounded_integral(), and OrthogonalPolynomial::precompute_triple_products().
const RealArray & type1_collocation_weights (unsigned short order) virtual
return the type 1 collocation weights corresponding to a point set of size order
This is defined for orthogonal and piecewise interpolation polynomials.
Reimplemented in NumericGenOrthogPolynomial, JacobiOrthogPolynomial, GenLaguerreOrthogPolynomial, PiecewiseInterpPolynomial, HermiteInterpPolynomial, LegendreOrthogPolynomial, LaguerreOrthogPolynomial, ChebyshevOrthogPolynomial, and HermiteOrthogPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type1_collocation_weights().
Referenced by IntegrationDriver::assign_1d_collocation_points_weights(), OrthogonalPolynomial::gauss_check(), NumericGenOrthogPolynomial::hermite_unbounded_integral(), NumericGenOrthogPolynomial::laguerre_semibounded_integral(), NumericGenOrthogPolynomial::legendre_bounded_integral(), OrthogonalPolynomial::precompute_triple_products(), and BasisPolynomial::type1_collocation_weights().
const RealArray & type2_collocation_weights (unsigned short order) virtual
return the type 2 collocation weights corresponding to a point set of size order
This is defined for piecewise interpolation polynomials.
Reimplemented in PiecewiseInterpPolynomial, and HermiteInterpPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::type2_collocation_weights().
Referenced by IntegrationDriver::assign_1d_collocation_points_weights(), and BasisPolynomial::type2_collocation_weights().
void reset_gauss () virtual
destroy history of Gauss pts/wts (due to distribution parameter changes)
This is defined only for orthogonal polynomials.
Reimplemented in OrthogonalPolynomial.
References BasisPolynomial::polyRep, and BasisPolynomial::reset_gauss().
Referenced by BasisPolynomial::reset_gauss().
Real alpha_polynomial () const virtual
return {Jacobi,GenLaguerre}OrthogPolynomial::alphaPoly
This is defined only for parameterized orthogonal polynomials.
Reimplemented in JacobiOrthogPolynomial, GenLaguerreOrthogPolynomial, HahnOrthogPolynomial, MeixnerOrthogPolynomial, KrawtchoukOrthogPolynomial, and CharlierOrthogPolynomial.
References BasisPolynomial::alpha_polynomial(), and BasisPolynomial::polyRep.
Referenced by BasisPolynomial::alpha_polynomial(), CubatureDriver::compute_grid(), and CubatureDriver::grid_size().
Real beta_polynomial () const virtual
return JacobiOrthogPolynomial::betaPoly
This is defined only for parameterized orthogonal polynomials.
Reimplemented in JacobiOrthogPolynomial, HahnOrthogPolynomial, MeixnerOrthogPolynomial, and KrawtchoukOrthogPolynomial.
References BasisPolynomial::beta_polynomial(), and BasisPolynomial::polyRep.
Referenced by BasisPolynomial::beta_polynomial(), CubatureDriver::compute_grid(), and CubatureDriver::grid_size().
void alpha_stat (Real alpha) virtual
set JacobiOrthogPolynomial::betaPoly or GenLaguerreOrthogPolynomial::alphaPoly from statistical defn of alpha
This is defined only for parameterized orthogonal polynomials.
Reimplemented in JacobiOrthogPolynomial, GenLaguerreOrthogPolynomial, HahnOrthogPolynomial, MeixnerOrthogPolynomial, KrawtchoukOrthogPolynomial, and CharlierOrthogPolynomial.
References BasisPolynomial::alpha_stat(), and BasisPolynomial::polyRep.
Referenced by BasisPolynomial::alpha_stat().
void beta_stat (Real beta) virtual
set JacobiOrthogPolynomial::alphaPoly from statistical defn of beta
This is defined only for parameterized orthogonal polynomials.
Reimplemented in JacobiOrthogPolynomial, HahnOrthogPolynomial, MeixnerOrthogPolynomial, and KrawtchoukOrthogPolynomial.
References BasisPolynomial::beta_stat(), and BasisPolynomial::polyRep.
Referenced by BasisPolynomial::beta_stat().
size_t interpolation_size () const virtual
get size of InterpolationPolynomial::interpPts
This is defined only for interpolation polynomials.
Reimplemented in InterpolationPolynomial.
References BasisPolynomial::interpolation_size(), and BasisPolynomial::polyRep.
Referenced by SharedNodalInterpPolyApproxData::accumulate_barycentric(), SharedNodalInterpPolyApproxData::accumulate_barycentric_gradient(), SharedNodalInterpPolyApproxData::accumulate_horners(), SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), SharedNodalInterpPolyApproxData::barycentric_exact_index(), BasisPolynomial::interpolation_size(), NodalInterpPolyApproximation::tensor_product_covariance(), NodalInterpPolyApproximation::tensor_product_mean(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), and NodalInterpPolyApproximation::tensor_product_variance_gradient().
void interpolation_points (const RealArray & interpolation_pts) virtual
set InterpolationPolynomial::interpPts
This is defined only for interpolation polynomials.
Reimplemented in InterpolationPolynomial.
References BasisPolynomial::interpolation_points(), and BasisPolynomial::polyRep.
Referenced by BasisPolynomial::interpolation_points(), and SharedInterpPolyApproxData::update_interpolation_basis().
const RealArray & interpolation_points () const virtual
get InterpolationPolynomial::interpPts
This is defined only for interpolation polynomials.
Reimplemented in InterpolationPolynomial.
References BasisPolynomial::interpolation_points(), and BasisPolynomial::polyRep.
Real factorial (unsigned short n) inline static
compute n!
This implementation is unprotected from overflow, but this should be fine for the polynomial orders that we would expect to encounter. Whenever possible, orthogonal polynomial implementations should use factorial_ratio() or n_choose_k() instead of factorial() to avoid overflow.
References BasisPolynomial::factorial_ratio().
Referenced by HermiteOrthogPolynomial::norm_squared(), GenLaguerreOrthogPolynomial::norm_squared(), JacobiOrthogPolynomial::norm_squared(), HermiteOrthogPolynomial::type1_collocation_weights(), and GenLaguerreOrthogPolynomial::type1_collocation_weights().
Real factorial_ratio (unsigned short num, unsigned short den) inline static
compute num!/den!
This implementation sequences products in order to minimize the chances of overflow, and its use should be preferred to factorial() whenever possible.
Referenced by BasisPolynomial::factorial().
Real n_choose_k (unsigned short n, unsigned short k) inline static
compute n!/(k!(n-k)!)
Note: n+p choose n or p = (n+p)!/n!/p!
This implementation sequences products in order to minimize the chances of overflow, and its use should be preferred to factorial() whenever possible.
Referenced by CombinedSparseGridDriver::assign_smolyak_arrays(), and SharedPolyApproxData::total_order_terms().
Real pochhammer (Real m, unsigned short n) inline static
compute the Pochhammer symbol (m)_n = m*(m+1)...*(m+n-1)
This is the rising/upper factorial formulation of the Pochhammer symbol (m)_n.
Referenced by GenLaguerreOrthogPolynomial::norm_squared(), JacobiOrthogPolynomial::norm_squared(), GenLaguerreOrthogPolynomial::type1_collocation_weights(), JacobiOrthogPolynomial::type1_gradient(), JacobiOrthogPolynomial::type1_hessian(), and JacobiOrthogPolynomial::type1_value().
BasisPolynomial * get_polynomial (short poly_type, short rule) private
Used by the envelope constructor to initialize polyRep to the appropriate derived type.
Used only by the envelope constructor to initialize polyRep to the appropriate derived type.
References BasisPolynomial::basisPolyType.
Referenced by BasisPolynomial::BasisPolynomial().
The documentation for this class was generated from the following files:
BasisPolynomial.hpp
BasisPolynomial.cpp