PECOS: ProbabilityTransformation Class Reference
ProbabilityTransformation Class Reference
Base class for all nonlinear distribution transformations.
Public Member Functions
ProbabilityTransformation ()
default constructor
ProbabilityTransformation (const String &prob_trans_type)
standard constructor for envelope
ProbabilityTransformation (const ProbabilityTransformation &prob_trans)
copy constructor
virtual ~ProbabilityTransformation ()
destructor
ProbabilityTransformation operator= (const ProbabilityTransformation &prob_trans)
assignment operator
virtual void trans_U_to_X (const RealVector &u_vars, RealVector &x_vars)
Transformation routine from u-space of uncorrelated standard normal variables to x-space of correlated random variables.
virtual void trans_X_to_U (const RealVector &x_vars, RealVector &u_vars)
Transformation routine from x-space of correlated random variables to u-space of uncorrelated standard normal variables.
virtual void transform_correlations ()
As part of the Nataf distribution model (Der Kiureghian & Liu, 1986), this procedure modifies the user-specified correlation matrix (corrMatrixX) to account for correlation warping from the nonlinear X->Z transformation and performs a Cholesky factorization to create corrCholeskyFactorZ.
virtual void trans_grad_X_to_U (const RealVector &fn_grad_x, RealVector &fn_grad_u, const RealVector &x_vars, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from x-space to u-space.
virtual void trans_grad_X_to_U (const RealVector &fn_grad_x, RealVector &fn_grad_u, const RealMatrix &jacobian_xu, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from x-space to u-space.
virtual void trans_grad_X_to_S (const RealVector &fn_grad_x, RealVector &fn_grad_s, const RealVector &x_vars, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Transformation routine from x-space gradient vector to design space.
virtual void trans_grad_X_to_S (const RealVector &fn_grad_x, RealVector &fn_grad_s, const RealMatrix &jacobian_xs, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Transformation routine from x-space gradient vector to design space.
virtual void trans_grad_U_to_X (const RealVector &fn_grad_u, RealVector &fn_grad_x, const RealVector &x_vars, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from u-space to x-space.
virtual void trans_grad_U_to_X (const RealVector &fn_grad_u, RealVector &fn_grad_x, const RealMatrix &jacobian_ux, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for gradient vector from u-space to x-space.
virtual void trans_hess_X_to_U (const RealSymMatrix &fn_hess_x, RealSymMatrix &fn_hess_u, const RealVector &x_vars, const RealVector &fn_grad_x, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for Hessian matrix from x-space to u-space.
virtual void trans_hess_X_to_U (const RealSymMatrix &fn_hess_x, RealSymMatrix &fn_hess_u, const RealMatrix &jacobian_xu, const RealSymMatrixArray &hessian_xu, const RealVector &fn_grad_x, const SizetArray &x_dvv, SizetMultiArrayConstView cv_ids)
Transformation routine for Hessian matrix from x-space to u-space.
virtual void jacobian_dX_dU (const RealVector &x_vars, RealMatrix &jacobian_xu)
Jacobian of x(u) mapping obtained from dX/dZ dZ/dU.
virtual void jacobian_dU_dX (const RealVector &x_vars, RealMatrix &jacobian_ux)
Jacobian of u(x) mapping obtained from dU/dZ dZ/dX.
virtual void jacobian_dX_dS (const RealVector &x_vars, RealMatrix &jacobian_xs, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Design Jacobian of x(u,s) mapping obtained from differentiation of trans_U_to_X() with respect to distribution parameters S.
virtual void hessian_d2X_dU2 (const RealVector &x_vars, RealSymMatrixArray &hessian_xu)
Hessian of x(u) mapping obtained from dZ/dU^T d^2X/dZ^2 dZ/dU.
void copy (const ProbabilityTransformation &prob_trans)
perform a deep copy of incoming prob_trans
void initialize_random_variable_types (const ShortArray &x_types)
initializes randomVarsX (no transformation: u-space not needed)
void initialize_random_variable_types (const ShortArray &x_types, const ShortArray &u_types)
initializes randomVarsX and ranVarTypesU
void initialize_random_variable_parameters (const RealVector &cd_l_bnds, const RealVector &cd_u_bnds, const AleatoryDistParams &adp, const EpistemicDistParams &edp, const RealVector &cs_l_bnds, const RealVector &cs_u_bnds)
updates parameters within randomVarsX
void initialize_random_variable_correlations (const RealSymMatrix &x_corr)
initializes corrMatrixX and correlationFlagX
void reshape_correlation_matrix (size_t num_leading_vars, size_t num_probabilistic_vars, size_t num_trailing_vars)
reshape corrMatrixX for an all_variables specification
const std::vector< RandomVariable > & x_random_variables () const
return randomVarsX
RealRealPairArray x_moments () const
assemble means and standard deviations in original space from RandomVariable::moments()
RealRealPairArray u_moments () const
assemble means and standard deviations in transformed space combining data from ranVarTypesU with RandomVariable::moments()
RealVector x_means () const
assemble means in original space from RandomVariable::mean()
RealVector x_std_deviations () const
assemble standard deviations in original space from RandomVariable::standard_deviation()
RealRealPairArray x_bounds () const
assemble lower and upper bounds from RandomVariable::bounds()
RealRealPairArray u_bounds () const
assemble lower and upper bounds in transformed space combining data from ranVarTypesU with RandomVariable::bounds()
RealVector x_lower_bounds () const
assemble lower bounds from RandomVariable::bounds()
RealVector x_upper_bounds () const
assemble upper bounds from RandomVariable::bounds()
Real x_pdf (Real x_val, size_t i) const
return the univariate PDF value for an x-space random variable
Real x_log_pdf (Real x_val, size_t i) const
return the univariate log PDF value for an x-space random variable
Real x_log_pdf_gradient (Real x_val, size_t i) const
return the gradient of the univariate log PDF for an x-space random variable
Real x_log_pdf_hessian (Real x_val, size_t i) const
return the Hessian of the univariate log PDF for an x-space random variable
Real u_pdf (Real u_val, size_t i) const
return the univariate PDF value for a u-space random variable
Real u_log_pdf (Real u_val, size_t i) const
return the univariate log PDF value for a u-space random variable
Real u_log_pdf_gradient (Real u_val, size_t i) const
return the gradient of the univariate log PDF for a u-space random variable
Real u_log_pdf_hessian (Real u_val, size_t i) const
return the Hessian of the univariate log PDF for a u-space random variable
Real x_pdf (const RealVector &x_pt) const
return the multivariate PDF value for x-space random variables
Real x_log_pdf (const RealVector &x_pt) const
return the multivariate log PDF value for x-space random variables
Real u_pdf (const RealVector &u_pt) const
return the multivariate PDF value for u-space random variables
Real u_log_pdf (const RealVector &u_pt) const
return the multivariate log PDF value for u-space random variables
template<typename Engine >
Real draw_x_sample (size_t i, Engine &rng) const
draw a sample from an x-space random variable
template<typename Engine >
Real draw_u_sample (size_t i, Engine &rng) const
draw a sample from a u-space random variable
const ShortArray & u_types () const
return ranVarTypesU
void u_types (const ShortArray &types)
set ranVarTypesU
void u_type (short type, size_t i)
set ranVarTypesU[i]
void check_x_type (size_t i, short x_type) const
verify that randomVarsX[i].type() equals x_type
bool x_correlation () const
return correlationFlagX
const RealSymMatrix & x_correlation_matrix () const
return corrMatrixX
const RealMatrix & z_correlation_factor () const
return corrCholeskyFactorZ
bool is_null () const
function to check modelRep (does this envelope contain a letter)
Protected Member Functions
ProbabilityTransformation (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
void numerical_design_jacobian (const RealVector &x_vars, bool xs, RealMatrix &num_jacobian_xs, bool zs, RealMatrix &num_jacobian_zs, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray &acv_map1_indices, const ShortArray &acv_map2_targets)
Computes numerical dx/ds and dz/ds Jacobians as requested by xs and zs booleans.
void verify_trans_jacobian_hessian (const RealVector &v0)
routine for verification of transformation Jacobian/Hessian terms
void verify_design_jacobian (const RealVector &u0)
routine for verification of design Jacobian terms
Protected Attributes
std::vector< RandomVariable > randomVarsX
vector of random variables encapsulating distribution parameters and statistical functions (pdf, cdf, etc.)
ShortArray ranVarTypesU
vector of types of each u-space standardized uncertain variable to which each x-space variable is transformed
bool correlationFlagX
flag for indicating if correlation exists among the x-space uncertain variables
RealSymMatrix corrMatrixX
matrix of random variable correlation coefficients
RealMatrix corrCholeskyFactorZ
cholesky factor of a modified correlation matrix (corrMatrixX is modified in transform_correlations() for use in z-space)
Static Private Member Functions
static ProbabilityTransformation * get_prob_trans (const String &prob_trans_type)
Used only by the standard envelope constructor to initialize probTransRep to the appropriate derived type.
Private Attributes
ProbabilityTransformation * probTransRep
pointer to the letter (initialized only for the envelope)
int referenceCount
number of objects sharing probTransRep
Detailed Description
Base class for all nonlinear distribution transformations.
The base class for nonlinear distribution transformations, including Nataf, Rosenblatt, et al.
Constructor & Destructor Documentation
ProbabilityTransformation ()
default constructor
The default constructor: probTransRep is NULL in this case. This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
Referenced by ProbabilityTransformation::get_prob_trans().
ProbabilityTransformation (const String & prob_trans_type)
standard constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_prob_trans, since ProbabilityTransformation(BaseConstructor) builds the actual base class data for the derived transformations.
References ProbabilityTransformation::get_prob_trans(), and ProbabilityTransformation::probTransRep.
ProbabilityTransformation (const ProbabilityTransformation & prob_trans)
copy constructor
Copy constructor manages sharing of probTransRep and incrementing of referenceCount.
References ProbabilityTransformation::operator=(), ProbabilityTransformation::probTransRep, and ProbabilityTransformation::referenceCount.
~ProbabilityTransformation () virtual
destructor
Destructor decrements referenceCount and only deletes probTransRep when referenceCount reaches zero.
References ProbabilityTransformation::copy(), ProbabilityTransformation::probTransRep, and ProbabilityTransformation::referenceCount.
ProbabilityTransformation (BaseConstructor) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor is the one which must build the base class data for all derived classes. get_prob_trans() instantiates a derived class letter and the derived constructor selects this base class constructor in its initialization list (to avoid recursion in the base class constructor calling get_prob_trans() again). Since the letter IS the representation, its rep pointer is set to NULL (an uninitialized pointer causes problems in ~ProbabilityTransformation).
Member Function Documentation
ProbabilityTransformation operator= (const ProbabilityTransformation & prob_trans)
assignment operator
Assignment operator decrements referenceCount for old probTransRep, assigns new probTransRep, and increments referenceCount for new probTransRep.
References ProbabilityTransformation::probTransRep, and ProbabilityTransformation::referenceCount.
Referenced by ProbabilityTransformation::ProbabilityTransformation().
void copy (const ProbabilityTransformation & prob_trans)
perform a deep copy of incoming prob_trans
This function provides a deep copy (the copy constructor supports shallow copies with shared reps) and is commonly used to publish tranformation data when the Model variables are in a transformed space (e.g., u-space) and x-space data may not be generated directly. This allows for the use of inverse transformations to return the transformed space variables to their original states.
References ProbabilityTransformation::copy(), ProbabilityTransformation::corrCholeskyFactorZ, ProbabilityTransformation::correlationFlagX, ProbabilityTransformation::corrMatrixX, ProbabilityTransformation::initialize_random_variable_types(), ProbabilityTransformation::probTransRep, ProbabilityTransformation::randomVarsX, and ProbabilityTransformation::ranVarTypesU.
Referenced by ProbabilityTransformation::copy(), and ProbabilityTransformation::~ProbabilityTransformation().
void numerical_design_jacobian (const RealVector & x_vars, bool xs, RealMatrix & num_jacobian_xs, bool zs, RealMatrix & num_jacobian_zs, SizetMultiArrayConstView cv_ids, SizetMultiArrayConstView acv_ids, const SizetArray & acv_map1_indices, const ShortArray & acv_map2_targets) protected
Computes numerical dx/ds and dz/ds Jacobians as requested by xs and zs booleans.
This procedure computes numerical derivatives of x and/or z with respect to distribution parameters s, and is used by jacobian_dX_dS() to provide data that is not available analytically. Numerical dz/ds involves dL/ds (z(s) = L(s) u and dz/ds = dL/ds u) and is needed to evaluate dx/ds semi-analytically for correlated variables. Numerical dx/ds is needed for distributions lacking simple closed-form CDF expressions (beta and gamma distributions).
References ProbabilityTransformation::corrCholeskyFactorZ, ProbabilityTransformation::randomVarsX, ProbabilityTransformation::trans_U_to_X(), ProbabilityTransformation::trans_X_to_U(), ProbabilityTransformation::transform_correlations(), and ProbabilityTransformation::verify_trans_jacobian_hessian().
Referenced by ProbabilityTransformation::hessian_d2X_dU2(), NatafTransformation::jacobian_dX_dS(), and ProbabilityTransformation::verify_design_jacobian().
ProbabilityTransformation * get_prob_trans (const String & prob_trans_type) static private
Used only by the standard envelope constructor to initialize probTransRep to the appropriate derived type.
Used only by the envelope constructor to initialize probTransRep to the appropriate derived type.
References ProbabilityTransformation::ProbabilityTransformation().
Referenced by ProbabilityTransformation::ProbabilityTransformation().
The documentation for this class was generated from the following files:
ProbabilityTransformation.hpp
ProbabilityTransformation.cpp