PECOS: RandomVariable Class Reference
RandomVariable Class Reference
base class for random variable hierarchy
Public Member Functions
RandomVariable ()
default constructor
RandomVariable (short ran_var_type)
standard constructor for envelope
RandomVariable (const RandomVariable &ran_var)
copy constructor
virtual ~RandomVariable ()
destructor
RandomVariable operator= (const RandomVariable &ran_var)
assignment operator
virtual Real cdf (Real x) const
return the cumulative distribution function value of the random variable at x
virtual Real inverse_cdf (Real p_cdf) const
return the x value corresponding to a cumulative probability
virtual Real ccdf (Real x) const
return the complementary cumulative distribution function value of the random variable at x
virtual Real inverse_ccdf (Real p_ccdf) const
return the x value corresponding to a complementary cumulative probability
virtual Real pdf (Real x) const
return the value of the random variable's probability density function at x
virtual Real pdf_gradient (Real x) const
return the gradient of the random variable's probability density function at x
virtual Real pdf_hessian (Real x) const
return the hessian of the random variable's probability density function at x
virtual Real log_pdf (Real x) const
return the value of the natural log of the random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_pdf_gradient (Real x) const
return the gradient of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
virtual Real log_pdf_hessian (Real x) const
return the Hessian of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
virtual Real inverse_standard_cdf (Real p_cdf) const
return the x value for a standardized probability distribution corresponding to a cumulative probability
virtual Real standard_pdf (Real z) const
return the value of a standardized random variable's probability density function at x
virtual Real log_standard_pdf (Real z) const
return the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_standard_pdf_gradient (Real z) const
return the gradient of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_standard_pdf_hessian (Real z) const
return the Hessian of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real to_standard (Real x) const
scale variable value x from current to standardized distribution
virtual Real from_standard (Real z) const
scale variable value z from standardized to current distribution
virtual Real parameter (short dist_param) const
return the value of the named distribution parameter
virtual void parameter (short dist_param, Real val)
update the value of the named distribution parameter
virtual Real mean () const
return the distribution mean
virtual Real median () const
return the distribution mode
virtual Real mode () const
return the distribution mode
virtual Real standard_deviation () const
return the distribution variance
virtual Real variance () const
return the distribution variance
virtual RealRealPair moments () const
return the distribution mean and standard deviation as a pair
virtual RealRealPair bounds () const
return the distribution lower and upper bounds as a pair
virtual Real coefficient_of_variation () const
compute the coefficient of variation (used to compute selected correlation warping factors); defined for semi-infinite distributions with nonzero mean (lognormal, exponential, gamma, frechet, weibull)
virtual Real correlation_warping_factor (const RandomVariable &rv, Real corr) const
compute the warping factor for correlation between the current variable and the one passed in (used in NatafTransformation)
virtual Real dx_ds (short dist_param, short u_type, Real x, Real z) const
compute the design Jacobian from differentiating the X->Z mapping with respect to the distibution parameter s
virtual Real dz_ds_factor (short u_type, Real x, Real z) const
compute the mapping-specific factor that is multiplied by dz/ds for contributions to the dx/ds design Jacobian in the case of correlated random variables (dz/ds is evaluated numerically and multiplied by this analytic factor)
template<typename Engine >
Real draw_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
template<typename Engine >
Real draw_standard_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
void type (short ran_var_type)
set ranVarType
short type () const
get ranVarType
RandomVariable * random_variable_rep () const
returns ranVarRep for access to derived class member functions that are not mapped to the base level
Protected Member Functions
RandomVariable (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
short ranVarType
enumeration value indicating type of random variable
Private Member Functions
RandomVariable * get_random_variable (short ran_var_type)
Used only by the standard envelope constructor to initialize ranVarRep to the appropriate derived type.
Private Attributes
boost::uniform_real< Real > uniformSampler
draws real samples on [0,1]
RandomVariable * ranVarRep
pointer to the letter (initialized only for the envelope)
int referenceCount
number of objects sharing ranVarRep
Detailed Description
base class for random variable hierarchy
This class enables cdf(), ccdf(), inverse_cdf(), inverse_ccdf(), pdf(), pdf_gradient(), pdf_hessian(), and related random variable utilities from contained distribution parameters.
Constructor & Destructor Documentation
RandomVariable ()
default constructor
The default constructor: ranVarRep is NULL in this case. This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
RandomVariable (short ran_var_type)
standard constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_random_variable, since RandomVariable(BaseConstructor) builds the actual base class data for the derived basis functions.
References RandomVariable::get_random_variable(), and RandomVariable::ranVarRep.
RandomVariable (const RandomVariable & ran_var)
copy constructor
Copy constructor manages sharing of ranVarRep and incrementing of referenceCount.
References RandomVariable::ranVarRep, and RandomVariable::referenceCount.
~RandomVariable () virtual
destructor
Destructor decrements referenceCount and only deletes ranVarRep when referenceCount reaches zero.
References RandomVariable::ranVarRep, and RandomVariable::referenceCount.
RandomVariable (BaseConstructor) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor is the one which must build the base class data for all derived classes. get_random_variable() instantiates a derived class letter and the derived constructor selects this base class constructor in its initialization list (to avoid recursion in the base class constructor calling get_random_variable() again). Since the letter IS the representation, its rep pointer is set to NULL (an uninitialized pointer causes problems in ~RandomVariable).
Member Function Documentation
RandomVariable operator= (const RandomVariable & ran_var)
assignment operator
Assignment operator decrements referenceCount for old ranVarRep, assigns new ranVarRep, and increments referenceCount for new ranVarRep.
References RandomVariable::ranVarRep, and RandomVariable::referenceCount.
RealRealPair moments () const virtual
return the distribution mean and standard deviation as a pair
default is only overridden when more efficient to compute together
Reimplemented in BoundedLognormalRandomVariable, BoundedNormalRandomVariable, HistogramBinRandomVariable, and HistogramPtRandomVariable.
References RandomVariable::mean(), RandomVariable::moments(), RandomVariable::ranVarRep, and RandomVariable::standard_deviation().
Referenced by RandomVariable::moments().
Real coefficient_of_variation () const virtual
compute the coefficient of variation (used to compute selected correlation warping factors); defined for semi-infinite distributions with nonzero mean (lognormal, exponential, gamma, frechet, weibull)
default is only overridden when more efficient to compute together
Reimplemented in ExponentialRandomVariable, BoundedLognormalRandomVariable, BoundedNormalRandomVariable, LognormalRandomVariable, HistogramBinRandomVariable, and HistogramPtRandomVariable.
References RandomVariable::coefficient_of_variation(), RandomVariable::correlation_warping_factor(), RandomVariable::mean(), RandomVariable::ranVarRep, and RandomVariable::standard_deviation().
Referenced by RandomVariable::coefficient_of_variation(), WeibullRandomVariable::correlation_warping_factor(), FrechetRandomVariable::correlation_warping_factor(), GumbelRandomVariable::correlation_warping_factor(), LognormalRandomVariable::correlation_warping_factor(), UniformRandomVariable::correlation_warping_factor(), NormalRandomVariable::correlation_warping_factor(), GammaRandomVariable::correlation_warping_factor(), and ExponentialRandomVariable::correlation_warping_factor().
RandomVariable * get_random_variable (short ran_var_type) private
Used only by the standard envelope constructor to initialize ranVarRep to the appropriate derived type.
Used only by the envelope constructor to initialize ranVarRep to the appropriate derived type.
References RandomVariable::ranVarType.
Referenced by RandomVariable::RandomVariable().
The documentation for this class was generated from the following files:
RandomVariable.hpp
RandomVariable.cpp