PECOS: NodalInterpPolyApproximation Class Reference
NodalInterpPolyApproximation Class Reference
Derived approximation class for nodal interpolation polynomials (global approximation interpolating function values and potentially gradients at collocation points).
Public Member Functions
NodalInterpPolyApproximation (const SharedBasisApproxData &shared_data)
default constructor
~NodalInterpPolyApproximation ()
destructor
Public Member Functions inherited from InterpPolyApproximation
InterpPolyApproximation (const SharedBasisApproxData &shared_data)
default constructor
~InterpPolyApproximation ()
destructor
Public Member Functions inherited from PolynomialApproximation
PolynomialApproximation (const SharedBasisApproxData &shared_data)
standard constructor
~PolynomialApproximation ()
destructorboth
virtual void allocate_component_sobol ()
size component Sobol arrays
virtual ULongULongMap sparse_sobol_index_map () const
return RegressOrthogPolyApproximation::sparseSobolIndexMap
virtual Real delta_covariance (PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions, treating all variables as random
virtual Real delta_covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions for a given parameter vector, treating a subset of the variables as random
virtual Real delta_mean ()
return the change in mean between two response expansions, treating all variables as random
virtual Real delta_mean (const RealVector &x)
return the change in mean between two response expansions, treating a subset of the variables as random
virtual Real delta_std_deviation ()
return the change in standard deviation between two response expansions, treating all variables as random
virtual Real delta_std_deviation (const RealVector &x)
return the change in standard deviation between two response expansions, treating a subset of the variables as random
virtual Real delta_beta (bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating all variables as random
virtual Real delta_beta (const RealVector &x, bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating a subset of the variables as random
virtual Real delta_z (bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating all variables as random
virtual Real delta_z (const RealVector &x, bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating a subset of the variables as random
bool deep_copied_surrogate_data () const
returns true if surrData is a deep copy of origSurrData
const RealVector & expansion_moments () const
return expansionMoments
const RealVector & numerical_integration_moments () const
return numericalMoments
const RealVector & moments () const
return preferred response moments (either expansion or numerical integration, depending on approximation type)
void standardize_moments (const RealVector &central_moments, RealVector &std_moments)
standardize central moments 2-n and eliminate excess kurtosis
void expansion_coefficient_flag (bool coeff_flag)
set ExpansionConfigOptions::expansionCoeffFlag
bool expansion_coefficient_flag () const
get ExpansionConfigOptions::expansionCoeffFlag
void expansion_coefficient_gradient_flag (bool grad_flag)
set ExpansionConfigOptions::expansionCoeffGradFlag
bool expansion_coefficient_gradient_flag () const
get ExpansionConfigOptions::expansionCoeffGradFlag
const RealVector & sobol_indices () const
return sobolIndices
const RealVector & total_sobol_indices () const
return totalSobolIndices
Public Member Functions inherited from BasisApproximation
BasisApproximation ()
default constructor
BasisApproximation (const SharedBasisApproxData &shared_data)
standard constructor for envelope
BasisApproximation (const BasisApproximation &basis_approx)
copy constructor
virtual ~BasisApproximation ()
destructor
BasisApproximation operator= (const BasisApproximation &basis_approx)
assignment operator
virtual void print_coefficients (std::ostream &s, bool normalized)
print the coefficient array computed in compute_coefficients()
virtual void coefficient_labels (std::vector< std::string > &coeff_labels) const
retrieve a vector of coefficient label strings, one per expansion term
void assign_rep (BasisApproximation *approx_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
BasisApproximation * approx_rep () const
returns approxRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
void allocate_arrays ()
size expansionType{1,2}Coeffs and expansionType1CoeffGrads
void compute_coefficients (size_t index=_NPOS)
calculate the approximation coefficients using a set of surrogate data
void increment_coefficients (size_t index=_NPOS)
update the coefficients for the expansion of interpolation polynomials: increment expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void decrement_coefficients (bool save_data)
restore the coefficients to their previous state prior to last increment: decrement expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void push_coefficients ()
restore the coefficients to a previously incremented state as identified by the current increment to the Smolyak multi index: push expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void finalize_coefficients ()
finalize the coefficients by applying all previously evaluated increments: finalize expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void store_coefficients (size_t index=_NPOS)
store current state within storedExpType{1Coeffs,2Coeffs,1CoeffGrads}
void restore_coefficients (size_t index=_NPOS)
restore previous state from storedExpType{1Coeffs,2Coeffs,1CoeffGrads}
void swap_coefficients (size_t index)
swap storedExpType{1Coeffs,2Coeffs,1CoeffGrads}[index] with active current data
void remove_stored_coefficients (size_t index=_NPOS)
remove a redundant entry from storedExpType{1Coeffs,2Coeffs,1CoeffGrads} prior to combine_coefficients (default is pop_back)
void clear_stored ()
clear storedExpType{1Coeffs,2Coeffs,1CoeffGrads}
void combine_coefficients (size_t swap_index)
augment current interpolant using storedExpType{1Coeffs,2Coeffs,1CoeffGrads}[index]
void integrate_response_moments (size_t num_moments)
compute moments of response using numerical integration
void integrate_expansion_moments (size_t num_moments)
compute moments of expansion using numerical integration
Real value (const RealVector &x)
retrieve the approximate function value for a given parameter vector
const RealVector & gradient_basis_variables (const RealVector &x)
retrieve the gradient for a response expansion with respect to all variables included in the polynomial bases using the given parameter vector and default DVV
const RealVector & gradient_basis_variables (const RealVector &x, const SizetArray &dvv)
const RealVector & gradient_nonbasis_variables (const RealVector &x)
retrieve the gradient for a response expansion with respect to all variables not included in the polynomial bases (nonprobabilistic variables such as design or epistemic when not in "all" mode) using the given parameter vector and default DVV
const RealSymMatrix & hessian_basis_variables (const RealVector &x)
retrieve the Hessian of the response expansion with respect to all variables included in the polynomial basis (e.g., probabilistic variables) for a given parameter vector
Real stored_value (const RealVector &x, size_t index)
retrieve the response value for a stored expansion using the given parameter vector
const RealVector & stored_gradient_basis_variables (const RealVector &x, size_t index)
retrieve the response gradient for a stored expansion with respect to all variables included in the polynomial bases; evaluate for the given parameter vector.
const RealVector & stored_gradient_nonbasis_variables (const RealVector &x, size_t index)
retrieve the response gradient for a stored expansion with respect to all variables not included in the polynomial bases; evaluate for the given parameter vector.
Real mean ()
Real mean (const RealVector &x)
const RealVector & mean_gradient ()
const RealVector & mean_gradient (const RealVector &x, const SizetArray &dvv)
Real variance ()
Real variance (const RealVector &x)
const RealVector & variance_gradient ()
const RealVector & variance_gradient (const RealVector &x, const SizetArray &dvv)
Real covariance (PolynomialApproximation *poly_approx_2)
Real covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)
void compute_total_sobol_indices ()
void compute_partial_variance (const BitArray &set_value)
RealVector approximation_coefficients (bool normalized) const
return the coefficient array computed by compute_coefficients()
void approximation_coefficients (const RealVector &approx_coeffs, bool normalized)
set the coefficient array from external sources, rather than computing with compute_coefficients()
Protected Member Functions inherited from InterpPolyApproximation
int min_coefficients () const
return the minimum number of samples (unknowns) required to build the derived class approximation type in numVars dimensions
void compute_component_sobol ()
computes component (main and interaction) Sobol' indices
void compute_total_sobol ()
computes total Sobol' indices
void compute_moments (bool full_stats=true)
compute numerical moments to order 4
void compute_moments (const RealVector &x, bool full_stats=true)
compute numerical moments in all-variables mode to order 2
void test_interpolation ()
test accuracy of the interpolants
Protected Member Functions inherited from PolynomialApproximation
void surrogate_data (const SurrogateData &data)
set PolynomialApproximation::origSurrData
const SurrogateData & surrogate_data () const
get PolynomialApproximation::surrData (const)
SurrogateData & surrogate_data ()
get PolynomialApproximation::surrData (non-const)
void compute_coefficients (size_t index=_NPOS)
calculate the approximation coefficients using a set of surrogate data
const RealVector & gradient (const RealVector &x)
generic base class function mapped to gradient_basis_variables(x)
const RealSymMatrix & hessian (const RealVector &x)
generic base class function mapped to hessian_basis_variables(x)
void synchronize_surrogate_data (size_t index)
update surrData from origSurrData based on deep or shallow copy
void response_data_to_surplus_data (size_t index)
modify origSurrData to create hierarchical surplus response data within surrData
void integrate_moments (const RealVector &coeffs, const RealVector &t1_wts, RealVector &moments)
compute central moments of response using type1 numerical integration
void integrate_moments (const RealVector &t1_coeffs, const RealMatrix &t2_coeffs, const RealVector &t1_wts, const RealMatrix &t2_wts, RealVector &moments)
compute central moments of response using type1/2 numerical integration
void allocate_total_sobol ()
size total Sobol arrays
Protected Member Functions inherited from BasisApproximation
BasisApproximation (BaseConstructor, const SharedBasisApproxData &shared_data)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Private Member Functions
void update_expansion_coefficients ()
update expansionType{1Coeffs,2Coeffs,1CoeffGrads} following changes to surrData
Real tensor_product_mean (const RealVector &x, const UShortArray &lev_index, const UShort2DArray &key, const SizetArray &colloc_index)
compute the mean of a tensor interpolant on a tensor grid; contributes to mean(x)
const RealVector & tensor_product_mean_gradient (const RealVector &x, const UShortArray &lev_index, const UShort2DArray &key, const SizetArray &colloc_index, const SizetArray &dvv)
compute the gradient of the mean of a tensor interpolant on a tensor grid; contributes to mean_gradient(x)
Real tensor_product_covariance (const RealVector &x, const UShortArray &lev_index, const UShort2DArray &key, const SizetArray &colloc_index, NodalInterpPolyApproximation *nip_approx_2)
compute the covariance of two tensor interpolants on the same tensor grid using an interpolation of products or product of interpolants approach; contributes to covariance(x, poly_approx_2)
Real tensor_product_covariance (const RealVector &x, const UShortArray &lev_index_1, const UShort2DArray &key_1, const SizetArray &colloc_index_1, const UShortArray &lev_index_2, const UShort2DArray &key_2, const SizetArray &colloc_index_2, NodalInterpPolyApproximation *nip_approx_2)
compute the covariance of two tensor interpolants on different tensor grids using a product of interpolants approach; contributes to covariance(x, poly_approx_2)
const RealVector & tensor_product_variance_gradient (const RealVector &x, const UShortArray &lev_index, const UShort2DArray &key, const SizetArray &colloc_index, const SizetArray &dvv)
compute the gradient of the variance of a tensor interpolant on a tensor grid using an interpolation of products or product of interpolants approach; contributes to variance_gradient(x)
Real value (const RealVector &x, const RealVectorArray &t1_coeffs, const RealMatrixArray &t2_coeffs, const UShort3DArray &colloc_key, const SizetList &subset_indices)
compute value of reduced-dimension interpolant
const RealVector & gradient_basis_variables (const RealVector &x, const RealVectorArray &t1_coeffs, const RealMatrixArray &t2_coeffs, const UShort3DArray &colloc_key, const SizetList &subset_indices)
compute gradient of reduced-dimension interpolant with respect to basis variables
Real expectation (const RealVector &t1_coeffs, const RealMatrix &t2_coeffs)
compute the expected value of the interpolant given by t{1,2}_coeffs using weights from the CombinedSparseGridDriver
Real expectation (const RealVector &t1_coeffs, const RealVector &t1_wts, const RealMatrix &t2_coeffs, const RealMatrix &t2_wts)
compute the expected value of the interpolant given by t{1,2}_coeffs using t{1,2}_wts
void reinterpolated_level (const UShortArray &lev_index)
computes higher-order grid for tensor reinterpolation of the covariance fn for non-integrated dimensions in all_variables mode
Real member_integral (const BitArray &member_bits, Real mean)
compute integral for total Sobol' index for variables in a set
void member_coefficients_weights (const BitArray &member_bits, const UShortArray &quad_order, const UShortArray &lev_index, const UShort2DArray &colloc_key, const SizetArray &colloc_index, RealVector &member_t1_coeffs, RealVector &member_t1_wts, RealMatrix &member_t2_coeffs, RealMatrix &member_t2_wts, UShort2DArray &member_colloc_key, SizetArray &member_colloc_index)
defines member_coeffs and member_wts for a particular membership set
void update_member_key (const UShortArray &data, const SizetList &member_indices, UShortArray &member_map_key, size_t cntr)
create a unique map key for value() and gradient() calculation reuse
Private Attributes
RealVector expansionType1Coeffs
the type1 coefficients of the expansion for interpolating values
RealMatrix expansionType2Coeffs
the type2 coefficients of the expansion for interpolating gradients
RealMatrix expansionType1CoeffGrads
the gradients of the type1 expansion coefficients
RealVectorArray storedExpType1Coeffs
copies of expansionType1Coeffs state for subsequent restoration
RealMatrixArray storedExpType2Coeffs
copies of expansionType2Coeffs state for subsequent restoration
RealMatrixArray storedExpType1CoeffGrads
copies of expansionType1CoeffGrads state for subsequent restoration
RealVector tpMeanGrad
the gradient of the mean of a tensor-product interpolant; a contributor to meanGradient
RealVector tpVarianceGrad
the gradient of the variance of a tensor-product interpolant; a contributor to varianceGradient
Additional Inherited Members
Protected Attributes inherited from InterpPolyApproximation
RealVector partialVariance
the partialVariances of subset functions f_alpha
Protected Attributes inherited from PolynomialApproximation
SurrogateData origSurrData
SurrogateData instance containing the variables (shared) and response (unique) data arrays for constructing a surrogate of a single response function; this is the original unmodified data set, prior to any potential manipulations by the approximation classes.
SurrogateData surrData
SurrogateData instance used in current approximation builds, potentially reflecting data modifications relative to origSurrData.
bool expansionCoeffFlag
flag for calculation of expansion coefficients from response values
bool expansionCoeffGradFlag
flag for calculation of gradients of expansion coefficients from response gradients
RealVector expansionMoments
mean and central moments 2/3/4 computed from the stochastic expansion form. For OrthogPolyApproximation, these are primary, and for InterpPolyApproximation, they are secondary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector numericalMoments
mean and central moments 2/3/4 computed via numerical integration of the response. For OrthogPolyApproximation, these are secondary, and for InterpPolyApproximation, they are primary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector approxGradient
gradient of the polynomial approximation returned by gradient()
RealSymMatrix approxHessian
Hessian of the polynomial approximation returned by hessian()
RealVector meanGradient
gradient of the primary mean (expansion mean for OrthogPoly, numerical integration mean for InterpPoly)
RealVector varianceGradient
gradient of the primary variance (expansion variance for OrthogPoly, numerical integration variance for InterpPoly)
short computedMean
track computation of mean and mean gradient to avoid unnecessary recomputation
short computedVariance
track computation of variance and variance gradient to avoid unnecessary recomputation
RealVector xPrevMean
track previous evaluation point for all_variables mean to avoid unnecessary recomputation
RealVector xPrevMeanGrad
track previous evaluation point for all_variables mean gradient to avoid unnecessary recomputation
RealVector xPrevVar
track previous evaluation point for all_variables variance to avoid unnecessary recomputation
RealVector xPrevVarGrad
track previous evaluation point for all_variables variance gradient to avoid unnecessary recomputation
RealVector sobolIndices
global sensitivities as given by Sobol'
RealVector totalSobolIndices
total global sensitivities as given by Sobol'
Protected Attributes inherited from BasisApproximation
SharedBasisApproxData * sharedDataRep
contains the approximation data that is shared among the response set
Detailed Description
Derived approximation class for nodal interpolation polynomials (global approximation interpolating function values and potentially gradients at collocation points).
The NodalInterpPolyApproximation class provides a global polynomial approximation based on either Lagrange or Hermite interpolation polynomials using a nodal basis approach. It is used primarily for stochastic collocation approaches to uncertainty quantification.
Member Function Documentation
const RealVector & gradient_basis_variables (const RealVector & x, const SizetArray & dvv) protected virtual
Special case used for sparse grid interpolation on variable sub-sets defined from partial integration.
Implements PolynomialApproximation.
References PolynomialApproximation::approxGradient, CombinedSparseGridDriver::collocation_indices(), TensorProductDriver::collocation_key(), CombinedSparseGridDriver::collocation_key(), SharedNodalInterpPolyApproxData::csg_driver(), PolynomialApproximation::expansionCoeffFlag, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, NodalInterpPolyApproximation::gradient_nonbasis_variables(), TensorProductDriver::level_index(), BasisApproximation::sharedDataRep, CombinedSparseGridDriver::smolyak_coefficients(), CombinedSparseGridDriver::smolyak_multi_index(), and SharedNodalInterpPolyApproxData::tpq_driver().
Real mean () protected virtual
In this case, all expansion variables are random variables and the mean of the expansion is simply the sum over i of r_i w_i.
Implements PolynomialApproximation.
References PolynomialApproximation::computedMean, PolynomialApproximation::expansionCoeffFlag, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, NodalInterpPolyApproximation::expectation(), SharedPolyApproxData::nonRandomIndices, PolynomialApproximation::numericalMoments, and BasisApproximation::sharedDataRep.
Referenced by NodalInterpPolyApproximation::compute_partial_variance(), NodalInterpPolyApproximation::covariance(), NodalInterpPolyApproximation::mean(), NodalInterpPolyApproximation::member_integral(), NodalInterpPolyApproximation::tensor_product_covariance(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), and NodalInterpPolyApproximation::variance_gradient().
Real mean (const RealVector & x) protected virtual
In this case, a subset of the expansion variables are random variables and the mean of the expansion involves integration over this subset and evaluation over the subset's complement. For the linear sums of tensor interpolants within a sparse interpolant, the expectation can be taken inside the sum and we can simply add up the tensor mean contributions.
Implements PolynomialApproximation.
References CombinedSparseGridDriver::collocation_indices(), TensorProductDriver::collocation_key(), CombinedSparseGridDriver::collocation_key(), PolynomialApproximation::computedMean, SharedNodalInterpPolyApproxData::csg_driver(), ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, TensorProductDriver::level_index(), SharedPolyApproxData::match_nonrandom_vars(), NodalInterpPolyApproximation::mean(), SharedPolyApproxData::nonRandomIndices, PolynomialApproximation::numericalMoments, BasisApproximation::sharedDataRep, CombinedSparseGridDriver::smolyak_coefficients(), CombinedSparseGridDriver::smolyak_multi_index(), NodalInterpPolyApproximation::tensor_product_mean(), SharedNodalInterpPolyApproxData::tpq_driver(), and PolynomialApproximation::xPrevMean.
const RealVector & mean_gradient () protected virtual
In this function, all expansion variables are random variables and any design/state variables are omitted from the expansion. In this case, the derivative of the expectation is the expectation of the derivative. The mixed derivative case (some design variables are inserted and some are augmented) requires no special treatment.
Implements PolynomialApproximation.
References PolynomialApproximation::computedMean, SharedPolyApproxData::driverRep, PolynomialApproximation::expansionCoeffGradFlag, NodalInterpPolyApproximation::expansionType1CoeffGrads, PolynomialApproximation::meanGradient, SharedPolyApproxData::nonRandomIndices, BasisApproximation::sharedDataRep, and IntegrationDriver::type1_weight_sets().
Referenced by NodalInterpPolyApproximation::tensor_product_variance_gradient().
const RealVector & mean_gradient (const RealVector & x, const SizetArray & dvv) protected virtual
In this function, a subset of the expansion variables are random variables and any augmented design/state variables (i.e., not inserted as random variable distribution parameters) are included in the expansion. In this case, the mean of the expansion is the expectation over the random subset and the derivative of the mean is the derivative of the remaining expansion over the non-random subset. This function must handle the mixed case, where some design/state variables are augmented (and are part of the expansion: derivatives are evaluated as described above) and some are inserted (derivatives are obtained from expansionType1CoeffGrads). For the linear sums of tensor interpolants within a sparse interpolant, the expectation can be taken inside the sum and we can simply add up the tensor mean gradient contributions.
Implements PolynomialApproximation.
References CombinedSparseGridDriver::collocation_indices(), TensorProductDriver::collocation_key(), CombinedSparseGridDriver::collocation_key(), PolynomialApproximation::computedMean, NodalInterpPolyApproximation::covariance(), SharedNodalInterpPolyApproxData::csg_driver(), ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, TensorProductDriver::level_index(), SharedPolyApproxData::match_nonrandom_vars(), PolynomialApproximation::meanGradient, SharedPolyApproxData::nonRandomIndices, BasisApproximation::sharedDataRep, CombinedSparseGridDriver::smolyak_coefficients(), CombinedSparseGridDriver::smolyak_multi_index(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), NodalInterpPolyApproximation::tpMeanGrad, SharedNodalInterpPolyApproxData::tpq_driver(), and PolynomialApproximation::xPrevMeanGrad.
Real variance () inline protected virtual
In this case, all expansion variables are random variables and the variance of the expansion uses an interpolation of response products.
Implements PolynomialApproximation.
References NodalInterpPolyApproximation::covariance().
Referenced by NodalInterpPolyApproximation::compute_partial_variance().
Real variance (const RealVector & x) inline protected virtual
In this case, a subset of the expansion variables are random variables and the variance of the expansion involves integration over this subset and evaluation over the subset's complement.
Implements PolynomialApproximation.
References NodalInterpPolyApproximation::covariance(), and NodalInterpPolyApproximation::expectation().
const RealVector & variance_gradient () protected virtual
In this function, all expansion variables are random variables and any design/state variables are omitted from the expansion. The mixed derivative case (some design/epistemic variables are inserted and some are augmented) requires no special treatment. Since we reinterpolate the central products (INTERPOLATION_OF_PRODUCTS is the only option for the standard expansion mode) such that we retain the linear sums of tensor interpolants within a sparse interpolant, the expectation gradient simply involves a summation over the sparse integration weights.
Implements PolynomialApproximation.
References PolynomialApproximation::computedVariance, SharedPolyApproxData::driverRep, PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, NodalInterpPolyApproximation::expansionType1CoeffGrads, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::mean(), SharedPolyApproxData::nonRandomIndices, BasisApproximation::sharedDataRep, IntegrationDriver::type1_weight_sets(), and PolynomialApproximation::varianceGradient.
const RealVector & variance_gradient (const RealVector & x, const SizetArray & dvv) protected virtual
In this function, a subset of the expansion variables are random variables and any augmented design/state variables (i.e., not inserted as random variable distribution parameters) are included in the expansion. This function must handle the mixed case, where some design/state variables are augmented (and are part of the expansion) and some are inserted (derivatives are obtained from expansionType1CoeffGrads).
Implements PolynomialApproximation.
References CombinedSparseGridDriver::collocation_indices(), TensorProductDriver::collocation_key(), CombinedSparseGridDriver::collocation_key(), PolynomialApproximation::computedVariance, SharedNodalInterpPolyApproxData::csg_driver(), ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, NodalInterpPolyApproximation::expectation(), TensorProductDriver::level_index(), SharedPolyApproxData::match_nonrandom_vars(), SharedNodalInterpPolyApproxData::momentInterpType, SharedPolyApproxData::nonRandomIndices, NodalInterpPolyApproximation::reinterpolated_level(), BasisApproximation::sharedDataRep, CombinedSparseGridDriver::smolyak_coefficients(), CombinedSparseGridDriver::smolyak_multi_index(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), SharedNodalInterpPolyApproxData::tpq_driver(), NodalInterpPolyApproximation::tpVarianceGrad, PolynomialApproximation::varianceGradient, and PolynomialApproximation::xPrevVarGrad.
Real covariance (PolynomialApproximation * poly_approx_2) protected virtual
In this case, all expansion variables are random variables and the variance of the expansion uses an interpolation of central products (INTERPOLATION_OF_PRODUCTS is the only option for the standard expansion mode). Since we reinterpolate the central products such that we retain the linear sums of tensor interpolants within a sparse interpolant, the expectation simply involves a summation over the sparse integration weights.
Implements PolynomialApproximation.
References SharedPolyApproxData::basisConfigOptions, PolynomialApproximation::computedVariance, SharedPolyApproxData::driverRep, PolynomialApproximation::expansionCoeffFlag, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, NodalInterpPolyApproximation::mean(), SharedPolyApproxData::nonRandomIndices, PolynomialApproximation::numericalMoments, SharedBasisApproxData::numVars, BasisApproximation::sharedDataRep, IntegrationDriver::type1_weight_sets(), IntegrationDriver::type2_weight_sets(), and BasisConfigOptions::useDerivs.
Referenced by NodalInterpPolyApproximation::mean_gradient(), and NodalInterpPolyApproximation::variance().
Real covariance (const RealVector & x, PolynomialApproximation * poly_approx_2) protected virtual
In this case, a subset of the expansion variables are random variables and the variance of the expansion involves integration over this subset. Three cases are at least partially implemented (type 2 covariance contributions are not currently implemented for PRODUCT_OF_INTERPOLANTS approaches, and variance_gradient() is not implemented for PRODUCT_OF_INTERPOLANTS_FULL): (1) REINTERPOLATION_OF_PRODUCTS: (R-)^2 is (re)interpolated, allowing sparse grid covariance to use a linear sum of tensor contributions. This is most consistent with covariance for the standard variables mode. The penalty is that the reinterpolated function is higher order. (1) INTERPOLATION_OF_PRODUCTS: (R-)^2 is interpolated, allowing sparse grid covariance to use a linear sum of tensor contributions. This is most consistent with covariance for the standard variables mode. (2) PRODUCT_OF_INTERPOLANTS_FAST: the covariance of the existing sparse interpolant is computed without reinterpolation, but only the individual covariances from matching tensor grids are included. Covariance from mismatched tensor grids is neglected, and the mean reference values are individual tensor means, not the "total" mean. Due to some fortuitous cancellations in the Smolyak construction that have not been fully analyzed, this shortcut/fast approach is often quite accurate. (3) PRODUCT_OF_INTERPOLANTS_FULL: the covariance of the existing sparse interpolant is computed without reinterpolation, the sparse covariance among all tensor grid combinations is included, and the total mean is used as the reference value for all products. The covariance among mismatched tensor grids requires the evaluation of expectations of mismatched interpolation polynomials (matched order basis polynomials admit a Kronecker delta simplification). This option has been the most accurate in testing but, despite attempts at pre-computation and fast lookup of these products, has been too expensive for large grids.
Implements PolynomialApproximation.
References CombinedSparseGridDriver::collocation_indices(), TensorProductDriver::collocation_key(), CombinedSparseGridDriver::collocation_key(), PolynomialApproximation::computedVariance, SharedNodalInterpPolyApproxData::csg_driver(), PolynomialApproximation::expansionCoeffFlag, ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, TensorProductDriver::level_index(), SharedPolyApproxData::match_nonrandom_vars(), SharedNodalInterpPolyApproxData::momentInterpType, SharedPolyApproxData::nonRandomIndices, PolynomialApproximation::numericalMoments, NodalInterpPolyApproximation::reinterpolated_level(), BasisApproximation::sharedDataRep, CombinedSparseGridDriver::smolyak_coefficients(), CombinedSparseGridDriver::smolyak_multi_index(), NodalInterpPolyApproximation::tensor_product_covariance(), SharedNodalInterpPolyApproxData::tpq_driver(), SharedNodalInterpPolyApproxData::update_nonzero_basis_products(), and PolynomialApproximation::xPrevVar.
void compute_partial_variance (const BitArray & set_value) protected virtual
Computes the variance of component functions. Assumes that all subsets of set_value have been computed in advance which will be true so long as the partial_variance is called following appropriate enumeration of set value
Reimplemented from InterpPolyApproximation.
References InterpPolyApproximation::compute_partial_variance(), NodalInterpPolyApproximation::mean(), NodalInterpPolyApproximation::member_integral(), SharedBasisApproxData::numVars, InterpPolyApproximation::partialVariance, BasisApproximation::sharedDataRep, SharedPolyApproxData::sobolIndexMap, PolynomialApproximation::totalSobolIndices, and NodalInterpPolyApproximation::variance().
Referenced by NodalInterpPolyApproximation::integrate_expansion_moments().
Real tensor_product_mean (const RealVector & x, const UShortArray & lev_index, const UShort2DArray & key, const SizetArray & colloc_index) private
compute the mean of a tensor interpolant on a tensor grid; contributes to mean(x)
Overloaded all_variables version supporting Smolyak sparse grids.
References SharedNodalInterpPolyApproxData::accumulate_barycentric(), SharedNodalInterpPolyApproxData::accumulate_horners(), BasisPolynomial::barycentric_value_factors(), SharedInterpPolyApproxData::barycentric_value_scaling(), SharedInterpPolyApproxData::barycentricFlag, SharedPolyApproxData::basisConfigOptions, SharedPolyApproxData::driverRep, BasisPolynomial::exact_index(), PolynomialApproximation::expansionCoeffFlag, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, BasisPolynomial::interpolation_size(), SharedPolyApproxData::nonRandomIndices, SharedBasisApproxData::numVars, SharedInterpPolyApproxData::polynomialBasis, SharedPolyApproxData::randomVarsKey, SharedNodalInterpPolyApproxData::set_new_point(), BasisApproximation::sharedDataRep, NodalInterpPolyApproximation::tensor_product_mean_gradient(), IntegrationDriver::type1_collocation_weights_1d(), BasisPolynomial::type1_value(), IntegrationDriver::type2_collocation_weights_1d(), BasisPolynomial::type2_value(), and BasisConfigOptions::useDerivs.
Referenced by NodalInterpPolyApproximation::mean(), NodalInterpPolyApproximation::tensor_product_covariance(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), and NodalInterpPolyApproximation::update_expansion_coefficients().
const RealVector & tensor_product_mean_gradient (const RealVector & x, const UShortArray & lev_index, const UShort2DArray & key, const SizetArray & colloc_index, const SizetArray & dvv) private
compute the gradient of the mean of a tensor interpolant on a tensor grid; contributes to mean_gradient(x)
Overloaded all_variables version supporting Smolyak sparse grids.
References SharedNodalInterpPolyApproxData::accumulate_barycentric_gradient(), SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), BasisPolynomial::barycentric_gradient_factors(), BasisPolynomial::barycentric_value_factors(), SharedInterpPolyApproxData::barycentricFlag, SharedPolyApproxData::basisConfigOptions, SharedPolyApproxData::driverRep, BasisPolynomial::exact_index(), PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, NodalInterpPolyApproximation::expansionType1CoeffGrads, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, BasisPolynomial::interpolation_size(), SharedPolyApproxData::nonRandomIndices, SharedBasisApproxData::numVars, SharedInterpPolyApproxData::polynomialBasis, SharedPolyApproxData::randomVarsKey, SharedNodalInterpPolyApproxData::set_new_point(), BasisApproximation::sharedDataRep, NodalInterpPolyApproximation::tensor_product_covariance(), NodalInterpPolyApproximation::tpMeanGrad, IntegrationDriver::type1_collocation_weights_1d(), BasisPolynomial::type1_gradient(), BasisPolynomial::type1_value(), IntegrationDriver::type2_collocation_weights_1d(), BasisPolynomial::type2_gradient(), BasisPolynomial::type2_value(), and BasisConfigOptions::useDerivs.
Referenced by NodalInterpPolyApproximation::mean_gradient(), NodalInterpPolyApproximation::tensor_product_mean(), and NodalInterpPolyApproximation::tensor_product_variance_gradient().
Real tensor_product_covariance (const RealVector & x, const UShortArray & lev_index, const UShort2DArray & key, const SizetArray & colloc_index, NodalInterpPolyApproximation * nip_approx_2) private
compute the covariance of two tensor interpolants on the same tensor grid using an interpolation of products or product of interpolants approach; contributes to covariance(x, poly_approx_2)
Covariance of response functions for a matched tensor product grid. Supports all_variables mode and either interpolation of products or product of interpolants formulations. For the latter, recursive usage only provides the "diagonal" contributions from matched tensor products (PRODUCT_OF_INTERPOLANTS_FAST); an exact estimation (PRODUCT_OF_INTERPOLANTS_FULL) requires augmentation with mixed tensor product contributions using the overloaded form of this function.
References SharedNodalInterpPolyApproxData::accumulate_barycentric(), SharedNodalInterpPolyApproxData::accumulate_horners(), BasisPolynomial::barycentric_value_factors(), SharedInterpPolyApproxData::barycentricFlag, SharedPolyApproxData::basisConfigOptions, SharedPolyApproxData::driverRep, BasisPolynomial::exact_index(), PolynomialApproximation::expansionCoeffFlag, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, NodalInterpPolyApproximation::gradient_basis_variables(), BasisPolynomial::interpolation_size(), SharedPolyApproxData::match_random_key(), NodalInterpPolyApproximation::mean(), SharedNodalInterpPolyApproxData::momentInterpType, SharedPolyApproxData::nonRandomIndices, SharedBasisApproxData::numVars, SharedInterpPolyApproxData::polynomialBasis, SharedPolyApproxData::randomIndices, SharedPolyApproxData::randomVarsKey, IntegrationDriver::reinterpolated_collocation_key(), IntegrationDriver::reinterpolated_level_index(), IntegrationDriver::reinterpolated_variable_sets(), SharedNodalInterpPolyApproxData::set_new_point(), BasisApproximation::sharedDataRep, NodalInterpPolyApproximation::tensor_product_mean(), IntegrationDriver::type1_collocation_weights_1d(), SharedInterpPolyApproxData::type1_interpolant_value(), BasisPolynomial::type1_value(), SharedInterpPolyApproxData::type1_weight(), IntegrationDriver::type2_collocation_weights_1d(), BasisPolynomial::type2_value(), BasisConfigOptions::useDerivs, and NodalInterpPolyApproximation::value().
Referenced by NodalInterpPolyApproximation::covariance(), and NodalInterpPolyApproximation::tensor_product_mean_gradient().
Real tensor_product_covariance (const RealVector & x, const UShortArray & lev_index_1, const UShort2DArray & key_1, const SizetArray & colloc_index_1, const UShortArray & lev_index_2, const UShort2DArray & key_2, const SizetArray & colloc_index_2, NodalInterpPolyApproximation * nip_approx_2) private
compute the covariance of two tensor interpolants on different tensor grids using a product of interpolants approach; contributes to covariance(x, poly_approx_2)
Covariance of response functions for differing tensor products using a PRODUCT_OF_INTERPOLANTS_FULL approach. Needed for sparse interpolants in all_variables mode.
References SharedNodalInterpPolyApproxData::basis_product(), PolynomialApproximation::expansionCoeffFlag, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, NodalInterpPolyApproximation::mean(), SharedNodalInterpPolyApproxData::momentInterpType, SharedPolyApproxData::nonRandomIndices, BasisApproximation::sharedDataRep, NodalInterpPolyApproximation::tensor_product_variance_gradient(), and SharedInterpPolyApproxData::type1_interpolant_value().
const RealVector & tensor_product_variance_gradient (const RealVector & x, const UShortArray & lev_index, const UShort2DArray & key, const SizetArray & colloc_index, const SizetArray & dvv) private
compute the gradient of the variance of a tensor interpolant on a tensor grid using an interpolation of products or product of interpolants approach; contributes to variance_gradient(x)
Overloaded all_variables version supporting interpolation of products or product of interpolants approaches.
References SharedNodalInterpPolyApproxData::accumulate_barycentric_gradient(), SharedNodalInterpPolyApproxData::accumulate_horners_gradient(), BasisPolynomial::barycentric_gradient_factors(), BasisPolynomial::barycentric_value_factors(), SharedInterpPolyApproxData::barycentricFlag, SharedPolyApproxData::basisConfigOptions, SharedPolyApproxData::driverRep, BasisPolynomial::exact_index(), PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, NodalInterpPolyApproximation::expansionType1CoeffGrads, NodalInterpPolyApproximation::expansionType1Coeffs, NodalInterpPolyApproximation::expansionType2Coeffs, NodalInterpPolyApproximation::gradient_basis_variables(), NodalInterpPolyApproximation::gradient_nonbasis_variables(), BasisPolynomial::interpolation_size(), SharedPolyApproxData::match_random_key(), NodalInterpPolyApproximation::mean(), NodalInterpPolyApproximation::mean_gradient(), SharedNodalInterpPolyApproxData::momentInterpType, SharedPolyApproxData::nonRandomIndices, SharedBasisApproxData::numVars, SharedInterpPolyApproxData::polynomialBasis, SharedPolyApproxData::randomIndices, SharedPolyApproxData::randomVarsKey, IntegrationDriver::reinterpolated_collocation_key(), IntegrationDriver::reinterpolated_level_index(), IntegrationDriver::reinterpolated_variable_sets(), SharedNodalInterpPolyApproxData::set_new_point(), BasisApproximation::sharedDataRep, NodalInterpPolyApproximation::tensor_product_mean(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), NodalInterpPolyApproximation::tpVarianceGrad, IntegrationDriver::type1_collocation_weights_1d(), BasisPolynomial::type1_gradient(), SharedInterpPolyApproxData::type1_interpolant_gradient(), SharedInterpPolyApproxData::type1_interpolant_value(), BasisPolynomial::type1_value(), SharedInterpPolyApproxData::type1_weight(), IntegrationDriver::type2_collocation_weights_1d(), BasisPolynomial::type2_gradient(), BasisPolynomial::type2_value(), BasisConfigOptions::useDerivs, and NodalInterpPolyApproximation::value().
Referenced by NodalInterpPolyApproximation::tensor_product_covariance(), and NodalInterpPolyApproximation::variance_gradient().
Real value (const RealVector & x, const RealVectorArray & t1_coeffs, const RealMatrixArray & t2_coeffs, const UShort3DArray & colloc_key, const SizetList & subset_indices) private
compute value of reduced-dimension interpolant
Special case used for sparse grid interpolation on variable sub-sets defined from partial integration.
References SharedNodalInterpPolyApproxData::csg_driver(), PolynomialApproximation::expansionCoeffFlag, NodalInterpPolyApproximation::gradient_basis_variables(), BasisApproximation::sharedDataRep, CombinedSparseGridDriver::smolyak_coefficients(), and CombinedSparseGridDriver::smolyak_multi_index().
void reinterpolated_level (const UShortArray & lev_index) private
computes higher-order grid for tensor reinterpolation of the covariance fn for non-integrated dimensions in all_variables mode
Computes the specifics of a higher order grid for reinterpolating covariance over dimensions that will not be integrated.
References SharedPolyApproxData::driverRep, NodalInterpPolyApproximation::integrate_response_moments(), SharedPolyApproxData::nonRandomIndices, IntegrationDriver::reinterpolated_level_index(), IntegrationDriver::reinterpolated_tensor_grid(), and BasisApproximation::sharedDataRep.
Referenced by NodalInterpPolyApproximation::covariance(), NodalInterpPolyApproximation::expectation(), and NodalInterpPolyApproximation::variance_gradient().
Real member_integral (const BitArray & member_bits, Real mean) private
compute integral for total Sobol' index for variables in a set
Forms a new interpolant h over member variables after integrating out the non-member variables. Then finds the variance by integrating (h-mean)^2 over the member variables, where the mean can be zero for non-central/raw moment cases.
References SharedPolyApproxData::basisConfigOptions, CombinedSparseGridDriver::collocation_indices(), TensorProductDriver::collocation_key(), CombinedSparseGridDriver::collocation_key(), SharedNodalInterpPolyApproxData::csg_driver(), ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, NodalInterpPolyApproximation::gradient_basis_variables(), TensorProductDriver::level_index(), SparseGridDriver::level_to_order(), NodalInterpPolyApproximation::mean(), NodalInterpPolyApproximation::member_coefficients_weights(), SharedBasisApproxData::numVars, TensorProductDriver::quadrature_order(), BasisApproximation::sharedDataRep, CombinedSparseGridDriver::smolyak_coefficients(), CombinedSparseGridDriver::smolyak_multi_index(), PolynomialApproximation::surrData, SharedNodalInterpPolyApproxData::tpq_driver(), NodalInterpPolyApproximation::update_member_key(), BasisConfigOptions::useDerivs, and NodalInterpPolyApproximation::value().
Referenced by NodalInterpPolyApproximation::compute_partial_variance().
Member Data Documentation
RealMatrix expansionType1CoeffGrads private
the gradients of the type1 expansion coefficients
may be interpreted as either the gradients of the expansion coefficients or the coefficients of expansions for the response gradients. This array is used when sensitivities of moments are needed with respect to variables that do not appear in the expansion (e.g., with respect to design variables for an expansion only over the random variables).
Referenced by NodalInterpPolyApproximation::allocate_arrays(), NodalInterpPolyApproximation::combine_coefficients(), NodalInterpPolyApproximation::compute_coefficients(), NodalInterpPolyApproximation::decrement_coefficients(), NodalInterpPolyApproximation::gradient_nonbasis_variables(), NodalInterpPolyApproximation::mean_gradient(), NodalInterpPolyApproximation::restore_coefficients(), NodalInterpPolyApproximation::store_coefficients(), NodalInterpPolyApproximation::swap_coefficients(), NodalInterpPolyApproximation::tensor_product_mean_gradient(), NodalInterpPolyApproximation::tensor_product_variance_gradient(), NodalInterpPolyApproximation::update_expansion_coefficients(), and NodalInterpPolyApproximation::variance_gradient().
The documentation for this class was generated from the following files:
NodalInterpPolyApproximation.hpp
NodalInterpPolyApproximation.cpp