PECOS: HierarchInterpPolyApproximation Class Reference
HierarchInterpPolyApproximation Class Reference
Derived approximation class for hierarchical interpolation polynomials (interpolating values and potentially gradients at collocation points).
Public Member Functions
HierarchInterpPolyApproximation (const SharedBasisApproxData &shared_data)
Default constructor.
~HierarchInterpPolyApproximation ()
destructor
Public Member Functions inherited from InterpPolyApproximation
InterpPolyApproximation (const SharedBasisApproxData &shared_data)
default constructor
~InterpPolyApproximation ()
destructor
Public Member Functions inherited from PolynomialApproximation
PolynomialApproximation (const SharedBasisApproxData &shared_data)
standard constructor
~PolynomialApproximation ()
destructorboth
virtual void allocate_component_sobol ()
size component Sobol arrays
virtual ULongULongMap sparse_sobol_index_map () const
return RegressOrthogPolyApproximation::sparseSobolIndexMap
bool deep_copied_surrogate_data () const
returns true if surrData is a deep copy of origSurrData
const RealVector & expansion_moments () const
return expansionMoments
const RealVector & numerical_integration_moments () const
return numericalMoments
const RealVector & moments () const
return preferred response moments (either expansion or numerical integration, depending on approximation type)
void standardize_moments (const RealVector &central_moments, RealVector &std_moments)
standardize central moments 2-n and eliminate excess kurtosis
void expansion_coefficient_flag (bool coeff_flag)
set ExpansionConfigOptions::expansionCoeffFlag
bool expansion_coefficient_flag () const
get ExpansionConfigOptions::expansionCoeffFlag
void expansion_coefficient_gradient_flag (bool grad_flag)
set ExpansionConfigOptions::expansionCoeffGradFlag
bool expansion_coefficient_gradient_flag () const
get ExpansionConfigOptions::expansionCoeffGradFlag
const RealVector & sobol_indices () const
return sobolIndices
const RealVector & total_sobol_indices () const
return totalSobolIndices
Public Member Functions inherited from BasisApproximation
BasisApproximation ()
default constructor
BasisApproximation (const SharedBasisApproxData &shared_data)
standard constructor for envelope
BasisApproximation (const BasisApproximation &basis_approx)
copy constructor
virtual ~BasisApproximation ()
destructor
BasisApproximation operator= (const BasisApproximation &basis_approx)
assignment operator
virtual void print_coefficients (std::ostream &s, bool normalized)
print the coefficient array computed in compute_coefficients()
virtual RealVector approximation_coefficients (bool normalized) const
return the coefficient array computed by compute_coefficients()
virtual void approximation_coefficients (const RealVector &approx_coeffs, bool normalized)
set the coefficient array from external sources, rather than computing with compute_coefficients()
virtual void coefficient_labels (std::vector< std::string > &coeff_labels) const
retrieve a vector of coefficient label strings, one per expansion term
void assign_rep (BasisApproximation *approx_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
BasisApproximation * approx_rep () const
returns approxRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
void allocate_arrays ()
size expansionType{1,2}Coeffs and expansionType1CoeffGrads
void compute_coefficients (size_t index=_NPOS)
calculate the approximation coefficients using a set of surrogate data
void increment_coefficients (size_t index=_NPOS)
update the coefficients for the expansion of interpolation polynomials: increment expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void decrement_coefficients (bool save_data)
restore the coefficients to their previous state prior to last increment: decrement expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void push_coefficients ()
restore the coefficients to a previously incremented state as identified by the current increment to the Smolyak multi index: push expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void finalize_coefficients ()
finalize the coefficients by applying all previously evaluated increments: finalize expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void store_coefficients (size_t index=_NPOS)
store current state within storedExpType{1Coeffs,2Coeffs,1CoeffGrads}
void restore_coefficients (size_t index=_NPOS)
restore previous state from storedExpType{1Coeffs,2Coeffs,1CoeffGrads}
void swap_coefficients (size_t index)
swap storedExpType{1Coeffs,2Coeffs,1CoeffGrads}[index] with active current data
void remove_stored_coefficients (size_t index=_NPOS)
remove a redundant entry from storedExpType{1Coeffs,2Coeffs,1CoeffGrads} prior to combine_coefficients (default is pop_back)
void clear_stored ()
clear storedExpType{1Coeffs,2Coeffs,1CoeffGrads}
void combine_coefficients (size_t swap_index)
augment current interpolant using storedExpType{1Coeffs,2Coeffs,1CoeffGrads}
void integrate_response_moments (size_t num_moments)
compute moments of response using numerical integration
void integrate_expansion_moments (size_t num_moments)
compute moments of expansion using numerical integration
Real value (const RealVector &x)
retrieve the approximate function value for a given parameter vector
const RealVector & gradient_basis_variables (const RealVector &x)
retrieve the gradient for a response expansion with respect to all variables included in the polynomial bases using the given parameter vector and default DVV
const RealVector & gradient_basis_variables (const RealVector &x, const SizetArray &dvv)
retrieve the gradient for a response expansion with respect to variables included in the polynomial basis for a given parameter vector and a given DVV subset
const RealVector & gradient_nonbasis_variables (const RealVector &x)
retrieve the gradient for a response expansion with respect to all variables not included in the polynomial bases (nonprobabilistic variables such as design or epistemic when not in "all" mode) using the given parameter vector and default DVV
const RealSymMatrix & hessian_basis_variables (const RealVector &x)
retrieve the Hessian of the response expansion with respect to all variables included in the polynomial basis (e.g., probabilistic variables) for a given parameter vector
Real stored_value (const RealVector &x, size_t index)
retrieve the response value for a stored expansion using the given parameter vector
const RealVector & stored_gradient_basis_variables (const RealVector &x, size_t index)
retrieve the response gradient for a stored expansion with respect to all variables included in the polynomial bases; evaluate for the given parameter vector.
const RealVector & stored_gradient_nonbasis_variables (const RealVector &x, size_t index)
retrieve the response gradient for a stored expansion with respect to all variables not included in the polynomial bases; evaluate for the given parameter vector.
Real mean ()
return the mean of the expansion, treating all variables as random
Real mean (const RealVector &x)
return the mean of the expansion for a given parameter vector, treating a subset of the variables as random
const RealVector & mean_gradient ()
const RealVector & mean_gradient (const RealVector &x, const SizetArray &dvv)
Real variance ()
return the variance of the expansion, treating all variables as random
Real variance (const RealVector &x)
return the variance of the expansion for a given parameter vector, treating a subset of the variables as random
const RealVector & variance_gradient ()
const RealVector & variance_gradient (const RealVector &x, const SizetArray &dvv)
Real covariance (PolynomialApproximation *poly_approx_2)
return the covariance between two response expansions, treating all variables as random
Real covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)
return the covariance between two response expansions for a given parameter vector, treating a subset of the variables as random
Real delta_covariance (PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions, treating all variables as random
Real delta_covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions for a given parameter vector, treating a subset of the variables as random
Real delta_mean ()
return the change in mean between two response expansions, treating all variables as random
Real delta_mean (const RealVector &x)
return the change in mean between two response expansions, treating a subset of the variables as random
Real delta_std_deviation ()
return the change in standard deviation between two response expansions, treating all variables as random
Real delta_std_deviation (const RealVector &x)
return the change in standard deviation between two response expansions, treating a subset of the variables as random
Real delta_beta (bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating all variables as random
Real delta_beta (const RealVector &x, bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating a subset of the variables as random
Real delta_z (bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating all variables as random
Real delta_z (const RealVector &x, bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating a subset of the variables as random
void compute_total_sobol_indices ()
void compute_partial_variance (const BitArray &set_value)
Protected Member Functions inherited from InterpPolyApproximation
int min_coefficients () const
return the minimum number of samples (unknowns) required to build the derived class approximation type in numVars dimensions
void allocate_arrays ()
size derived class data attributes
void compute_component_sobol ()
computes component (main and interaction) Sobol' indices
void compute_total_sobol ()
computes total Sobol' indices
void compute_moments (bool full_stats=true)
compute numerical moments to order 4
void compute_moments (const RealVector &x, bool full_stats=true)
compute numerical moments in all-variables mode to order 2
void test_interpolation ()
test accuracy of the interpolants
Protected Member Functions inherited from PolynomialApproximation
void surrogate_data (const SurrogateData &data)
set PolynomialApproximation::origSurrData
const SurrogateData & surrogate_data () const
get PolynomialApproximation::surrData (const)
SurrogateData & surrogate_data ()
get PolynomialApproximation::surrData (non-const)
void compute_coefficients (size_t index=_NPOS)
calculate the approximation coefficients using a set of surrogate data
const RealVector & gradient (const RealVector &x)
generic base class function mapped to gradient_basis_variables(x)
const RealSymMatrix & hessian (const RealVector &x)
generic base class function mapped to hessian_basis_variables(x)
void synchronize_surrogate_data (size_t index)
update surrData from origSurrData based on deep or shallow copy
void response_data_to_surplus_data (size_t index)
modify origSurrData to create hierarchical surplus response data within surrData
void integrate_moments (const RealVector &coeffs, const RealVector &t1_wts, RealVector &moments)
compute central moments of response using type1 numerical integration
void integrate_moments (const RealVector &t1_coeffs, const RealMatrix &t2_coeffs, const RealVector &t1_wts, const RealMatrix &t2_wts, RealVector &moments)
compute central moments of response using type1/2 numerical integration
void allocate_total_sobol ()
size total Sobol arrays
Protected Member Functions inherited from BasisApproximation
BasisApproximation (BaseConstructor, const SharedBasisApproxData &shared_data)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Private Member Functions
Real value (const RealVector &x, const UShort3DArray &sm_mi, const UShort4DArray &key, const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, unsigned short level)
compute the value at a point for a particular interpolation level
Real value (const RealVector &x, const UShort3DArray &sm_mi, const UShort4DArray &key, const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, unsigned short level, const SizetList &subset_indices)
compute the value at a point for a particular interpolation level and for a specified subset of the variables
const RealVector & gradient_basis_variables (const RealVector &x, const UShort3DArray &sm_mi, const UShort4DArray &key, const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, unsigned short level)
compute the approximate gradient with respect to the basis variables at a particular point for a particular interpolation level
const RealVector & gradient_basis_variables (const RealVector &x, const UShort3DArray &sm_mi, const UShort4DArray &key, const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, unsigned short level, const SizetList &subset_indices)
compute the approximate gradient with respect to the basis variables at a particular point for a particular interpolation level
const RealVector & gradient_basis_variables (const RealVector &x, const UShort3DArray &sm_mi, const UShort4DArray &key, const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, const SizetArray &dvv, unsigned short level)
compute the approximate gradient with respect to the basis variables for a particular point, interpolation level, and DVV
const RealVector & gradient_nonbasis_variables (const RealVector &x, const UShort3DArray &sm_mi, const UShort4DArray &key, const RealMatrix2DArray &t1_coeff_grads, unsigned short level)
compute the approximate gradient with respect to the nonbasis variables at a particular point for a particular interpolation level
void increment_current_from_reference ()
update bookkeeping when adding a grid increment relative to the grid reference
void decrement_current_to_reference ()
update bookkeeping when removing a grid increment and returning to the grid reference
Real reference_mean (const UShort2DArray &ref_key)
compute the reference mean, excluding the current grid increment, using ref_key
Real reference_mean (const RealVector &x, const UShort2DArray &ref_key)
compute the reference mean, excluding the current grid increment, using ref_key
Real reference_variance (const UShort2DArray &ref_key)
compute the reference variance, excluding the current grid increment, using ref_key
Real reference_variance (const RealVector &x, const UShort2DArray &ref_key)
compute the reference variance, excluding the current grid increment, using ref_key
Real delta_covariance (PolynomialApproximation *poly_approx_2, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the covariance increment due to the current grid increment
Real delta_covariance (const RealVector &x, PolynomialApproximation *poly_approx_2, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the covariance increment due to the current grid increment
Real delta_mean (const UShort2DArray &incr_key)
compute the mean increment due to the current grid increment
Real delta_mean (const RealVector &x, const UShort2DArray &incr_key)
compute the mean increment due to the current grid increment
Real delta_variance (const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the variance increment due to the current grid increment
Real delta_variance (const RealVector &x, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the variance increment due to the current grid increment
Real delta_std_deviation (const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the standard deviation increment due to the current grid increment
Real delta_std_deviation (const RealVector &x, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the standard deviation increment due to the current grid increment
Real delta_beta (bool cdf_flag, Real z_bar, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the reliability index increment due to the current grid increment
Real delta_beta (const RealVector &x, bool cdf_flag, Real z_bar, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the reliability index increment due to the current grid increment
Real delta_beta_map (Real mu0, Real delta_mu, Real var0, Real delta_sigma, bool cdf_flag, Real z_bar)
shared logic for handling exceptional cases
Real delta_z (bool cdf_flag, Real beta_bar, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the response level increment due to the current grid increment
Real delta_z (const RealVector &x, bool cdf_flag, Real beta_bar, const UShort2DArray &ref_key, const UShort2DArray &incr_key)
compute the response level increment due to the current grid increment
void product_interpolant (HierarchInterpPolyApproximation *hip_approx_2, RealVector2DArray &r1r2_t1_coeffs, RealMatrix2DArray &r1r2_t2_coeffs, const UShort2DArray &reference_key=UShort2DArray())
form type 1/2 coefficients for interpolation of R_1 R_2
void central_product_interpolant (HierarchInterpPolyApproximation *hip_approx_2, Real mean_1, Real mean_2, RealVector2DArray &cov_t1_coeffs, RealMatrix2DArray &cov_t2_coeffs, const UShort2DArray &reference_key=UShort2DArray())
form type 1/2 coefficients for interpolation of (R_1 - mu_1)(R_2 - mu_2)
void central_product_gradient_interpolant (HierarchInterpPolyApproximation *hip_approx_2, Real mean_1, Real mean_2, const RealVector &mean1_grad, const RealVector &mean2_grad, RealMatrix2DArray &cov_t1_coeff_grads, const UShort2DArray &reference_key=UShort2DArray())
form type1 coefficient gradients for interpolation of d/ds [(R_1 - mu_1)(R_2 - mu_2)]
Real expectation (const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, const UShort2DArray &set_partition=UShort2DArray())
compute the expected value of the interpolant given by t{1,2}_coeffs using weights from the HierarchSparseGridDriver
Real expectation (const RealVector2DArray &t1_coeffs, const RealVector2DArray &t1_wts, const RealMatrix2DArray &t2_coeffs, const RealMatrix2DArray &t2_wts, const UShort2DArray &set_partition=UShort2DArray())
compute the expected value of the interpolant given by t{1,2}_coeffs using t{1,2}_wts
Real expectation (const RealVector &x, const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, const UShort2DArray &set_partition=UShort2DArray())
compute the expected value of the interpolant given by t{1,2}_coeffs using weights from the HierarchSparseGridDriver
const RealVector & expectation_gradient (const RealMatrix2DArray &t1_coeff_grads)
compute the expected value of the gradient interpolant given by t1_coeff_grads using weights from the HierarchSparseGridDriver
const RealVector & expectation_gradient (const RealMatrix2DArray &t1_coeff_grads, const RealVector2DArray &t1_wts)
compute the expected value of the gradient interpolant given by t1_coeff_grads using t1_wts
Real expectation_gradient (const RealVector &x, const RealMatrix2DArray &t1_coeff_grads, size_t t1cg_index)
compute the expectation of t1_coeff_grads for index t1cg_index
Real expectation_gradient (const RealVector &x, const RealVector2DArray &t1_coeffs, const RealMatrix2DArray &t2_coeffs, size_t deriv_index)
compute the expectation of the gradient of {t1,t2}_coeffs for index deriv_index
void increment_coefficients (const UShortArray &index_set)
increment expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads} for a single index_set
void push_coefficients (const UShortArray &push_set)
move the expansion coefficients for push_set from poppedExp{T1Coeffs,T2Coeffs,T1CoeffGrads} to expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
void member_coefficients_weights (const BitArray &member_bits, RealVector2DArray &member_t1_coeffs, RealVector2DArray &member_t1_wts, RealMatrix2DArray &member_t2_coeffs, RealMatrix2DArray &member_t2_wts, UShort4DArray &member_colloc_key, Sizet3DArray &member_colloc_index)
compute member expansion for Sobol' index integration
void central_product_member_coefficients (const BitArray &m_bits, const RealVector2DArray &m_t1_coeffs, const RealMatrix2DArray &m_t2_coeffs, const UShort4DArray &m_colloc_key, const Sizet3DArray &m_colloc_index, Real mean, RealVector2DArray &cprod_m_t1_coeffs, RealMatrix2DArray &cprod_m_t2_coeffs)
form hierarchical interpolant of (h-mean)^2 from member-variable expansion of h
Private Attributes
short computedRefMean
bookkeeping to track computation of reference mean to avoid unnecessary recomputation
short computedDeltaMean
bookkeeping to track computation of mean increment to avoid unnecessary recomputation
short computedRefVariance
bookkeeping to track computation of reference variance to avoid unnecessary recomputation
short computedDeltaVariance
bookkeeping to track computation of variance increment to avoid unnecessary recomputation
RealVector xPrevRefMean
track previous evaluation point for all_variables reference mean to avoid unnecessary recomputation
RealVector xPrevDeltaMean
track previous evaluation point for all_variables mean increment to avoid unnecessary recomputation
RealVector xPrevRefVar
track previous evaluation point for all_variables reference variance to avoid unnecessary recomputation
RealVector xPrevDeltaVar
track previous evaluation point for all_variables variance increment to avoid unnecessary recomputation
RealVector referenceMoments
storage for reference mean and variance
RealVector deltaMoments
storage for mean and variance increments
RealVector meanRefGradient
storage for reference mean gradient
RealVector varianceRefGradient
storage for reference variance gradient
RealVector2DArray expansionType1Coeffs
the type1 coefficients of the expansion for interpolating values
RealMatrix2DArray expansionType2Coeffs
the type2 coefficients of the expansion for interpolating gradients
RealMatrix2DArray expansionType1CoeffGrads
the gradients of the type1 expansion coefficients
std::map< UShortArray, RealVector > poppedExpT1Coeffs
type 1 expansion coefficients popped during decrement for later restoration to expansionType1Coeffs
std::map< UShortArray, RealMatrix > poppedExpT2Coeffs
type 2 expansion coefficients popped during decrement for later restoration to expansionType2Coeffs
std::map< UShortArray, RealMatrix > poppedExpT1CoeffGrads
type 1 expansion coefficient gradients popped during decrement for later restoration to expansionType1CoeffGrads
RealVector3DArray storedExpType1Coeffs
storage of expansionType1Coeffs state for subsequent restoration/combination
RealMatrix3DArray storedExpType2Coeffs
storage of expansionType2Coeffs state for subsequent restoration/combination
RealMatrix3DArray storedExpType1CoeffGrads
storage of expansionType1CoeffGrads state for subsequent restoration/combination
Additional Inherited Members
Protected Attributes inherited from InterpPolyApproximation
RealVector partialVariance
the partialVariances of subset functions f_alpha
Protected Attributes inherited from PolynomialApproximation
SurrogateData origSurrData
SurrogateData instance containing the variables (shared) and response (unique) data arrays for constructing a surrogate of a single response function; this is the original unmodified data set, prior to any potential manipulations by the approximation classes.
SurrogateData surrData
SurrogateData instance used in current approximation builds, potentially reflecting data modifications relative to origSurrData.
bool expansionCoeffFlag
flag for calculation of expansion coefficients from response values
bool expansionCoeffGradFlag
flag for calculation of gradients of expansion coefficients from response gradients
RealVector expansionMoments
mean and central moments 2/3/4 computed from the stochastic expansion form. For OrthogPolyApproximation, these are primary, and for InterpPolyApproximation, they are secondary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector numericalMoments
mean and central moments 2/3/4 computed via numerical integration of the response. For OrthogPolyApproximation, these are secondary, and for InterpPolyApproximation, they are primary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector approxGradient
gradient of the polynomial approximation returned by gradient()
RealSymMatrix approxHessian
Hessian of the polynomial approximation returned by hessian()
RealVector meanGradient
gradient of the primary mean (expansion mean for OrthogPoly, numerical integration mean for InterpPoly)
RealVector varianceGradient
gradient of the primary variance (expansion variance for OrthogPoly, numerical integration variance for InterpPoly)
short computedMean
track computation of mean and mean gradient to avoid unnecessary recomputation
short computedVariance
track computation of variance and variance gradient to avoid unnecessary recomputation
RealVector xPrevMean
track previous evaluation point for all_variables mean to avoid unnecessary recomputation
RealVector xPrevMeanGrad
track previous evaluation point for all_variables mean gradient to avoid unnecessary recomputation
RealVector xPrevVar
track previous evaluation point for all_variables variance to avoid unnecessary recomputation
RealVector xPrevVarGrad
track previous evaluation point for all_variables variance gradient to avoid unnecessary recomputation
RealVector sobolIndices
global sensitivities as given by Sobol'
RealVector totalSobolIndices
total global sensitivities as given by Sobol'
Protected Attributes inherited from BasisApproximation
SharedBasisApproxData * sharedDataRep
contains the approximation data that is shared among the response set
Detailed Description
Derived approximation class for hierarchical interpolation polynomials (interpolating values and potentially gradients at collocation points).
The HierarchInterpPolyApproximation class provides a polynomial approximation based on hierarchical interpolation. Both local and global hierarchical basis functions are available. It is used primarily for stochastic collocation approaches to uncertainty quantification.
Member Function Documentation
const RealVector & mean_gradient () protected virtual
In this function, all expansion variables are random variables and any design/state variables are omitted from the expansion. In this case, the derivative of the expectation is the expectation of the derivative. The mixed derivative case (some design variables are inserted and some are augmented) requires no special treatment.
Implements PolynomialApproximation.
References PolynomialApproximation::computedMean, PolynomialApproximation::expansionCoeffGradFlag, HierarchInterpPolyApproximation::expansionType1CoeffGrads, HierarchInterpPolyApproximation::expectation_gradient(), PolynomialApproximation::meanGradient, SharedPolyApproxData::nonRandomIndices, and BasisApproximation::sharedDataRep.
Referenced by HierarchInterpPolyApproximation::variance_gradient().
const RealVector & mean_gradient (const RealVector & x, const SizetArray & dvv) protected virtual
In this function, a subset of the expansion variables are random variables and any augmented design/state variables (i.e., not inserted as random variable distribution parameters) are included in the expansion. In this case, the mean of the expansion is the expectation over the random subset and the derivative of the mean is the derivative of the remaining expansion over the non-random subset. This function must handle the mixed case, where some design/state variables are augmented (and are part of the expansion: derivatives are evaluated as described above) and some are inserted (derivatives are obtained from expansionType1CoeffGrads).
Implements PolynomialApproximation.
References SharedPolyApproxData::basisConfigOptions, PolynomialApproximation::computedMean, HierarchInterpPolyApproximation::covariance(), PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, HierarchInterpPolyApproximation::expansionType1CoeffGrads, HierarchInterpPolyApproximation::expansionType1Coeffs, HierarchInterpPolyApproximation::expansionType2Coeffs, HierarchInterpPolyApproximation::expectation_gradient(), SharedPolyApproxData::match_nonrandom_vars(), PolynomialApproximation::meanGradient, SharedPolyApproxData::nonRandomIndices, SharedPolyApproxData::randomVarsKey, BasisApproximation::sharedDataRep, BasisConfigOptions::useDerivs, and PolynomialApproximation::xPrevMeanGrad.
const RealVector & variance_gradient () protected virtual
In this function, all expansion variables are random variables and any design/state variables are omitted from the expansion. The mixed derivative case (some design variables are inserted and some are augmented) requires no special treatment.
Implements PolynomialApproximation.
References HierarchInterpPolyApproximation::central_product_gradient_interpolant(), PolynomialApproximation::computedVariance, PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, HierarchInterpPolyApproximation::expectation_gradient(), HierarchInterpPolyApproximation::mean(), HierarchInterpPolyApproximation::mean_gradient(), SharedPolyApproxData::nonRandomIndices, BasisApproximation::sharedDataRep, and PolynomialApproximation::varianceGradient.
const RealVector & variance_gradient (const RealVector & x, const SizetArray & dvv) protected virtual
In this function, a subset of the expansion variables are random variables and any augmented design/state variables (i.e., not inserted as random variable distribution parameters) are included in the expansion. This function must handle the mixed case, where some design/state variables are augmented (and are part of the expansion) and some are inserted (derivatives are obtained from expansionType1CoeffGrads).
Implements PolynomialApproximation.
References SharedPolyApproxData::basisConfigOptions, HierarchInterpPolyApproximation::central_product_gradient_interpolant(), HierarchInterpPolyApproximation::central_product_interpolant(), PolynomialApproximation::computedVariance, PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, HierarchInterpPolyApproximation::expectation_gradient(), SharedPolyApproxData::match_nonrandom_vars(), HierarchInterpPolyApproximation::mean(), HierarchInterpPolyApproximation::mean_gradient(), SharedPolyApproxData::nonRandomIndices, SharedPolyApproxData::randomVarsKey, HierarchInterpPolyApproximation::reference_mean(), BasisApproximation::sharedDataRep, BasisConfigOptions::useDerivs, PolynomialApproximation::varianceGradient, and PolynomialApproximation::xPrevVarGrad.
void compute_partial_variance (const BitArray & set_value) protected virtual
Computes the variance of component functions. Assumes that all subsets of set_value have been computed in advance which will be true so long as the partial_variance is called following appropriate enumeration of set value.
Reimplemented from InterpPolyApproximation.
References HierarchInterpPolyApproximation::central_product_member_coefficients(), InterpPolyApproximation::compute_partial_variance(), HierarchInterpPolyApproximation::expectation(), HierarchInterpPolyApproximation::mean(), HierarchInterpPolyApproximation::member_coefficients_weights(), SharedBasisApproxData::numVars, InterpPolyApproximation::partialVariance, BasisApproximation::sharedDataRep, SharedPolyApproxData::sobolIndexMap, PolynomialApproximation::totalSobolIndices, and HierarchInterpPolyApproximation::variance().
Referenced by HierarchInterpPolyApproximation::integrate_expansion_moments().
Real value (const RealVector & x, const UShort3DArray & sm_mi, const UShort4DArray & key, const RealVector2DArray & t1_coeffs, const RealMatrix2DArray & t2_coeffs, unsigned short level, const SizetList & subset_indices) private
compute the value at a point for a particular interpolation level and for a specified subset of the variables
All variables version.
References PolynomialApproximation::expansionCoeffFlag, HierarchInterpPolyApproximation::gradient_basis_variables(), BasisApproximation::sharedDataRep, and SharedInterpPolyApproxData::tensor_product_value().
void product_interpolant (HierarchInterpPolyApproximation * hip_approx_2, RealVector2DArray & r1r2_t1_coeffs, RealMatrix2DArray & r1r2_t2_coeffs, const UShort2DArray & reference_key = UShort2DArray()) private
form type 1/2 coefficients for interpolation of R_1 R_2
Whereas expectation() supports either a reference or increment key (passed as generic set_partition), functions forming hierarchical interpolant coefficients support only a reference key (starting point must be set 0; end point can be controlled).
References SharedPolyApproxData::basisConfigOptions, HierarchInterpPolyApproximation::central_product_interpolant(), HierarchSparseGridDriver::collocation_indices(), HierarchSparseGridDriver::collocation_key(), HierarchInterpPolyApproximation::expansionType1Coeffs, HierarchInterpPolyApproximation::gradient_basis_variables(), SharedHierarchInterpPolyApproxData::hsg_driver(), SharedBasisApproxData::numVars, BasisApproximation::sharedDataRep, HierarchSparseGridDriver::smolyak_multi_index(), PolynomialApproximation::surrData, BasisConfigOptions::useDerivs, and HierarchInterpPolyApproximation::value().
Referenced by HierarchInterpPolyApproximation::delta_covariance(), and HierarchInterpPolyApproximation::expectation_gradient().
void central_product_interpolant (HierarchInterpPolyApproximation * hip_approx_2, Real mean_1, Real mean_2, RealVector2DArray & cov_t1_coeffs, RealMatrix2DArray & cov_t2_coeffs, const UShort2DArray & reference_key = UShort2DArray()) private
form type 1/2 coefficients for interpolation of (R_1 - mu_1)(R_2 - mu_2)
Whereas expectation() supports either a reference or increment key (passed as generic set_partition), functions forming hierarchical interpolant coefficients support only a reference key (starting point must be set 0; end point can be controlled).
References SharedPolyApproxData::basisConfigOptions, HierarchInterpPolyApproximation::central_product_gradient_interpolant(), HierarchSparseGridDriver::collocation_indices(), HierarchSparseGridDriver::collocation_key(), HierarchInterpPolyApproximation::expansionType1Coeffs, HierarchInterpPolyApproximation::gradient_basis_variables(), SharedHierarchInterpPolyApproxData::hsg_driver(), SharedBasisApproxData::numVars, BasisApproximation::sharedDataRep, HierarchSparseGridDriver::smolyak_multi_index(), PolynomialApproximation::surrData, BasisConfigOptions::useDerivs, and HierarchInterpPolyApproximation::value().
Referenced by HierarchInterpPolyApproximation::covariance(), HierarchInterpPolyApproximation::product_interpolant(), HierarchInterpPolyApproximation::reference_variance(), and HierarchInterpPolyApproximation::variance_gradient().
const RealVector & expectation_gradient (const RealMatrix2DArray & t1_coeff_grads, const RealVector2DArray & t1_wts) private
compute the expected value of the gradient interpolant given by t1_coeff_grads using t1_wts
For inserted/augmented design/epistemic variables in standard mode.
References PolynomialApproximation::approxGradient, and HierarchInterpPolyApproximation::expectation_gradient().
Real expectation_gradient (const RealVector & x, const RealMatrix2DArray & t1_coeff_grads, size_t t1cg_index) private
compute the expectation of t1_coeff_grads for index t1cg_index
For inserted design/epistemic variables in all_variables mode.
References HierarchSparseGridDriver::collocation_key(), HierarchInterpPolyApproximation::expectation_gradient(), SharedHierarchInterpPolyApproxData::hsg_driver(), SharedPolyApproxData::nonRandomIndices, SharedPolyApproxData::randomIndices, BasisApproximation::sharedDataRep, HierarchSparseGridDriver::smolyak_multi_index(), SharedInterpPolyApproxData::type1_interpolant_value(), and SharedInterpPolyApproxData::type1_weight().
Real expectation_gradient (const RealVector & x, const RealVector2DArray & t1_coeffs, const RealMatrix2DArray & t2_coeffs, size_t deriv_index) private
compute the expectation of the gradient of {t1,t2}_coeffs for index deriv_index
For augmented design/epistemic variables in all_variables mode.
References SharedPolyApproxData::basisConfigOptions, HierarchSparseGridDriver::collocation_key(), SharedHierarchInterpPolyApproxData::hsg_driver(), SharedPolyApproxData::nonRandomIndices, SharedBasisApproxData::numVars, HierarchInterpPolyApproximation::product_interpolant(), SharedPolyApproxData::randomIndices, BasisApproximation::sharedDataRep, HierarchSparseGridDriver::smolyak_multi_index(), SharedInterpPolyApproxData::type1_interpolant_gradient(), SharedInterpPolyApproxData::type1_weight(), SharedInterpPolyApproxData::type2_interpolant_gradient(), SharedInterpPolyApproxData::type2_weight(), and BasisConfigOptions::useDerivs.
void increment_coefficients (const UShortArray & index_set) private
increment expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads} for a single index_set
Lower level helper function to process a single index set.
References SharedPolyApproxData::basisConfigOptions, HierarchSparseGridDriver::collocation_key(), PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, HierarchInterpPolyApproximation::expansionType1CoeffGrads, HierarchInterpPolyApproximation::expansionType1Coeffs, HierarchInterpPolyApproximation::expansionType2Coeffs, HierarchInterpPolyApproximation::gradient_basis_variables(), HierarchInterpPolyApproximation::gradient_nonbasis_variables(), SharedHierarchInterpPolyApproxData::hsg_driver(), HierarchInterpPolyApproximation::push_coefficients(), BasisApproximation::sharedDataRep, HierarchSparseGridDriver::smolyak_multi_index(), PolynomialApproximation::surrData, BasisConfigOptions::useDerivs, and HierarchInterpPolyApproximation::value().
void push_coefficients (const UShortArray & push_set) private
move the expansion coefficients for push_set from poppedExp{T1Coeffs,T2Coeffs,T1CoeffGrads} to expansion{Type1Coeffs,Type2Coeffs,Type1CoeffGrads}
Lower level helper function to process a single index set.
References SharedPolyApproxData::basisConfigOptions, PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, HierarchInterpPolyApproximation::expansionType1CoeffGrads, HierarchInterpPolyApproximation::expansionType1Coeffs, HierarchInterpPolyApproximation::expansionType2Coeffs, HierarchInterpPolyApproximation::poppedExpT1CoeffGrads, HierarchInterpPolyApproximation::poppedExpT1Coeffs, HierarchInterpPolyApproximation::poppedExpT2Coeffs, BasisApproximation::sharedDataRep, and BasisConfigOptions::useDerivs.
void member_coefficients_weights (const BitArray & member_bits, RealVector2DArray & member_t1_coeffs, RealVector2DArray & member_t1_wts, RealMatrix2DArray & member_t2_coeffs, RealMatrix2DArray & member_t2_wts, UShort4DArray & member_colloc_key, Sizet3DArray & member_colloc_index) private
compute member expansion for Sobol' index integration
Forms a lower dimensional interpolant over variables that are members of the given set.
References SharedPolyApproxData::basisConfigOptions, HierarchInterpPolyApproximation::central_product_member_coefficients(), HierarchSparseGridDriver::collocation_indices(), HierarchSparseGridDriver::collocation_key(), HierarchInterpPolyApproximation::expansionType1Coeffs, HierarchInterpPolyApproximation::expansionType2Coeffs, SharedHierarchInterpPolyApproxData::hsg_driver(), HierarchSparseGridDriver::levels_to_delta_keys(), HierarchSparseGridDriver::levels_to_delta_sizes(), SharedBasisApproxData::numVars, BasisApproximation::sharedDataRep, HierarchSparseGridDriver::smolyak_multi_index(), SharedInterpPolyApproxData::type1_weight(), SharedInterpPolyApproxData::type2_weight(), and BasisConfigOptions::useDerivs.
Referenced by HierarchInterpPolyApproximation::compute_partial_variance().
Member Data Documentation
RealMatrix2DArray expansionType1CoeffGrads private
the gradients of the type1 expansion coefficients
may be interpreted as either the gradients of the expansion coefficients or the coefficients of expansions for the response gradients. This array is used when sensitivities of moments are needed with respect to variables that do not appear in the expansion (e.g., with respect to design variables for an expansion only over the random variables).
Referenced by HierarchInterpPolyApproximation::allocate_arrays(), HierarchInterpPolyApproximation::central_product_gradient_interpolant(), HierarchInterpPolyApproximation::compute_coefficients(), HierarchInterpPolyApproximation::decrement_coefficients(), HierarchInterpPolyApproximation::finalize_coefficients(), HierarchInterpPolyApproximation::gradient_nonbasis_variables(), HierarchInterpPolyApproximation::increment_coefficients(), HierarchInterpPolyApproximation::mean_gradient(), HierarchInterpPolyApproximation::push_coefficients(), HierarchInterpPolyApproximation::restore_coefficients(), HierarchInterpPolyApproximation::store_coefficients(), and HierarchInterpPolyApproximation::swap_coefficients().
The documentation for this class was generated from the following files:
HierarchInterpPolyApproximation.hpp
HierarchInterpPolyApproximation.cpp