PECOS: SharedOrthogPolyApproxData Class Reference
SharedOrthogPolyApproxData Class Reference
Derived approximation class for orthogonal polynomials (global approximation).
Public Member Functions
SharedOrthogPolyApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars)
standard constructor
SharedOrthogPolyApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
alternate constructor
~SharedOrthogPolyApproxData ()
destructor
void allocate_data (const UShort2DArray &mi)
alternative form for setting multiIndex (expansion import) and allocating related arrays
const UShort2DArray & multi_index () const
get multiIndex
size_t expansion_terms () const
retrieve size of multiIndex
const UShortArray & expansion_order () const
get approxOrder
void expansion_order (const UShortArray &order)
set approxOrder
void increment_order ()
uniformly increment approxOrder
void construct_basis (const ShortArray &u_types, const AleatoryDistParams &adp)
invoke initialize_orthogonal_basis_types_rules(), initialize_polynomial_basis(), and, if needed, update_basis_distribution_parameters() using class member data
void orthogonal_basis_types (const ShortArray &opb_types)
set orthogPolyTypes
const ShortArray & orthogonal_basis_types () const
get orthogPolyTypes
const std::vector< BasisPolynomial > & polynomial_basis () const
get polynomialBasis
std::vector< BasisPolynomial > & polynomial_basis ()
void polynomial_basis (const std::vector< BasisPolynomial > &poly_basis)
set polynomialBasis
void coefficients_norms_flag (bool flag)
set NumericGenOrthogPolynomial::coeffsNormsFlag
Public Member Functions inherited from SharedPolyApproxData
SharedPolyApproxData ()
default constructor
SharedPolyApproxData (short basis_type, size_t num_vars)
standard constructor
SharedPolyApproxData (short basis_type, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
alternate constructor with full configuration options
~SharedPolyApproxData ()
destructorboth
virtual void increment_data (size_t index=_NPOS)
update the shared data prior to rebuilding the set of approximations
virtual void decrement_data ()
decrement the previous increment and store its shared data for later retrieval
virtual void pre_push_data ()
restores previously popped approximation data
virtual void post_push_data ()
restores previously popped approximation data
virtual void pre_finalize_data ()
finalizes the shared approximation data following a set of increments
virtual void post_finalize_data ()
finalizes the shared approximation data following a set of increments
bool push_available ()
test for whether current trial set requires a new approximation increment or can be restored from a previous trial
size_t retrieval_index ()
returns index of the data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex)
size_t finalization_index (size_t i)
returns index of the i-th data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex) during finalization
void configuration_options (const ExpansionConfigOptions &ec_options)
set expConfigOptions as a group (instead of per option below)
void configuration_options (const BasisConfigOptions &bc_options)
set basisConfigOptions (instead of per option below)
const BitArrayULongMap & sobol_index_map () const
return sobolIndexMap
void integration_driver_rep (IntegrationDriver *driver_rep)
set driverRep
void random_variables_key (const BitArray &random_vars_key)
set randomVarsKey
Public Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData ()
default constructor
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars)
standard constructor for envelope
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options, const RegressionConfigOptions &rc_options)
alternate constructor for envelope
SharedBasisApproxData (const SharedBasisApproxData &shared_data)
copy constructor
virtual ~SharedBasisApproxData ()
destructor
SharedBasisApproxData operator= (const SharedBasisApproxData &shared_data)
assignment operator
void assign_rep (SharedBasisApproxData *data_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
SharedBasisApproxData * data_rep () const
returns dataRep for access to derived class member functions that are not mapped to the top Approximation level
Static Public Member Functions
static void construct_basis (const ShortArray &u_types, const AleatoryDistParams &adp, const BasisConfigOptions &bc_options, std::vector< BasisPolynomial > &poly_basis)
invoke initialize_orthogonal_basis_types_rules(), initialize_polynomial_basis(), and, if needed, update_basis_distribution_parameters() using passed data
static void construct_basis (const ShortArray &u_types, const AleatoryDistParams &adp, const BasisConfigOptions &bc_options, std::vector< BasisPolynomial > &poly_basis, ShortArray &basis_types, ShortArray &colloc_rules)
invoke initialize_orthogonal_basis_types_rules(), initialize_polynomial_basis(), and, if needed, update_basis_distribution_parameters() using passed data
static void coefficients_norms_flag (bool flag, ShortArray &poly_types, std::vector< BasisPolynomial > &poly_basis)
set NumericGenOrthogPolynomial::coeffsNormsFlag
Static Public Member Functions inherited from SharedPolyApproxData
static bool initialize_orthogonal_basis_types_rules (const ShortArray &u_types, const BasisConfigOptions &bc_options, ShortArray &basis_types, ShortArray &colloc_rules)
allocate orthogonal polynomial basis types and integration rules based on u_types and rule options
static bool initialize_orthogonal_basis_type_rule (short u_type, const BasisConfigOptions &bc_options, short &basis_type, short &colloc_rule)
assign orthogonal polynomial basis type and integration rule based on u_type and basis configuration options
static void initialize_polynomial_basis (const ShortArray &basis_types, const ShortArray &colloc_rules, std::vector< BasisPolynomial > &poly_basis)
allocate poly_basis based on basis_types and colloc_rules
static void update_basis_distribution_parameters (const ShortArray &u_types, const AleatoryDistParams &dp, std::vector< BasisPolynomial > &poly_basis)
pass distribution parameters from dp to poly_basis
static size_t total_order_terms (const UShortArray &upper_bound, short lower_bound_offset=-1)
return the number of expansion terms for a total order expansion with the provided (anisotropic) upper_bound array specification
static size_t tensor_product_terms (const UShortArray &order, bool include_upper_bound=true)
return the number of expansion terms for a tensor-product expansion with the provided (anisotropic) quadrature orders (include_upper_bound = false) or expansion orders (default)
static void tensor_product_multi_index (const UShortArray &order, UShort2DArray &multi_index, bool include_upper_bound=true)
initialize expansion multi_index using a tensor-product expansion
static void hierarchical_tensor_product_multi_index (const UShort2DArray &delta_quad, UShort2DArray &multi_index)
initialize multi_index using a hierarchical tensor-product expansion
static void total_order_multi_index (unsigned short level, size_t num_vars, UShort2DArray &multi_index)
initialize multi_index using a total-order expansion from a scalar level
static void total_order_multi_index (const UShortArray &upper_bound, UShort2DArray &multi_index, short lower_bound_offset=-1, size_t max_terms=_NPOS)
initialize expansion multi_index using a total-order expansion from an upper_bound array specification
static void increment_indices (UShortArray &indices, const UShortArray &limits, bool include_upper_bound)
utility function for incrementing a set of multidimensional indices
static void increment_terms (UShortArray &terms, size_t &last_index, size_t &prev_index, size_t term_limit, bool &order_complete)
utility function for incrementing a set of multidimensional terms
Protected Member Functions
void allocate_data (size_t index=_NPOS)
allocate the shared data prior to building the set of approximations
size_t pre_combine_data ()
combines current and stored approximation data
void post_combine_data ()
combines current and stored approximation data
void store_data (size_t index=_NPOS)
void restore_data (size_t index=_NPOS)
restores previously stored approximation data
void remove_stored_data (size_t index=_NPOS)
removes a redundant stored approximation data prior to combination
void clear_stored_data ()
clear stored approximation data
size_t maximal_expansion ()
detect whether current expansion settings are the most refined
void swap_shared_data (size_t index)
swap current shared data with a stored shared data set, as identified by stored index
void sparse_grid_level_to_expansion_order (CombinedSparseGridDriver *csg_driver, const UShortArray &levels, UShortArray &exp_order)
convert a sparse grid index set and a growth setting to an integrand_order
void quadrature_order_to_integrand_order (IntegrationDriver *int_driver, const UShortArray &quad_order, UShortArray &int_order)
convert quadrature orders to integrand orders using rigorous mappings
void integrand_order_to_expansion_order (const UShortArray &int_order, UShortArray &exp_order)
convert integrand orders to expansion orders using rigorous mappings
void increment_trial_set (CombinedSparseGridDriver *csg_driver, UShort2DArray &aggregated_mi)
helper function for incrementing that is modular on sparse grid driver and multi-index
void decrement_trial_set (const UShortArray &trial_set, UShort2DArray &aggregated_mi, bool save_map=true)
helper function for decrementing that is modular on trial set and multi-index
void pre_push_trial_set (const UShortArray &trial_set, UShort2DArray &aggregated_mi, bool monotonic=true)
helper function for restoring that is modular on trial set and multi-index
void post_push_trial_set (const UShortArray &trial_set, UShort2DArray &aggregated_mi, bool save_map=true)
helper function for restoring that is modular on trial set and multi-index
void push_trial_set (const UShortArray &trial_set, UShort2DArray &aggregated_mi, bool monotonic=true, bool save_map=true)
helper function for restoring that is modular on trial set and multi-index
void precompute_maximal_rules (const UShort2DArray &multi_index)
Precompute a maximal order of quadrature rules (based on a multiIndex) when too expensive to compute on demand.
void precompute_maximal_rules (const UShortArray &approx_order)
Precompute a maximal order of quadrature rules (based on an approxOrder) when too expensive to compute on demand.
void allocate_component_sobol (const UShort2DArray &multi_index)
allocate sobolIndexMap from multi_index
void update_component_sobol (const UShort2DArray &multi_index)
update sobolIndexMap using new multi_index terms (from multifidelity overlay or a new QoI in orthogonal least interpolation)
void append_multi_index (const UShort2DArray &append_mi, UShort2DArray &combined_mi)
append multi-indices from append_mi that do not already appear in combined_mi
void append_multi_index (const UShortArraySet &append_mi, UShort2DArray &combined_mi)
append multi-indices from append_mi that do not already appear in combined_mi
void append_multi_index (const UShort2DArray &append_mi, UShort2DArray &combined_mi, SizetArray &append_mi_map, size_t &append_mi_map_ref)
append multi-indices from append_mi that do not already appear in combined_mi; define append_mi_map and append_mi_map_ref
void append_multi_index (const UShort2DArray &append_mi, UShort2DArray &combined_mi, SizetSet &append_mi_map, size_t &append_mi_map_ref)
append multi-indices from append_mi that do not already appear in combined_mi; define append_mi_map and append_mi_map_ref
void append_leading_multi_index (const UShort2DArray &append_mi, UShort2DArray &combined_mi, SizetSet &append_mi_map, size_t &append_mi_map_ref)
append multi-indices from append_mi that do not already appear in combined_mi (consistent ordering assumed); define append_mi_map and append_mi_map_ref
void append_multi_index (const UShort2DArray &append_mi, SizetArray &append_mi_map, size_t &append_mi_map_ref, UShort2DArray &combined_mi)
append multi-indices from append_mi that do not already appear in combined_mi, using previously defined append_mi_map and append_mi_map_ref for mapping
void append_multi_index (SizetSet &sparse_indices, const UShort2DArray &append_mi, UShort2DArray &combined_mi, RealVector &exp_coeffs, RealMatrix &exp_coeff_grads)
append multi-indices from append_mi that do not already appear in combined_mi, updating sparse_indices, exp_coeffs, and exp_coeff_grads
Real norm_squared (const UShortArray &indices)
returns the norm-squared of a particular multivariate polynomial, treating all variables as probabilistic
Real norm_squared (const UShortArray &indices, const SizetList &rand_indices)
returns the norm-squared of a particular multivariate polynomial, treating a subset of the variables as probabilistic
Real multivariate_polynomial (const RealVector &x, const UShortArray &indices)
calculate a particular multivariate orthogonal polynomial value evaluated at a particular parameter set
Real multivariate_polynomial (const RealVector &x, const UShortArray &indices, const SizetList &non_rand_indices)
calculate a particular multivariate orthogonal polynomial value over the nonrandom variable subset evaluated at a particular parameter set
Real multivariate_polynomial_gradient (const RealVector &x, size_t deriv_index, const UShortArray &indices)
compute multivariate orthogonal polynomial gradient evaluated at x for term corresponding to indices and derivative variable deriv_index
Real multivariate_polynomial_gradient (const RealVector &x, size_t deriv_index, const UShortArray &indices, const SizetList &non_rand_indices)
compute multivariate orthogonal polynomial gradient evaluated at x for term corresponding to indices, for derivative variable deriv_index, and for a nonrandom variable subset
Real multivariate_polynomial_hessian (const RealVector &x, size_t deriv_index_i, size_t deriv_index_j, const UShortArray &indices)
compute multivariate orthogonal polynomial Hessian for term corresponding to deriv_index, evaluated at x
const RealVector & multivariate_polynomial_gradient_vector (const RealVector &x, const UShortArray &indices)
calculate multivariate orthogonal polynomial gradient vector evaluated at a particular parameter set
const RealVector & multivariate_polynomial_gradient_vector (const RealVector &x, const UShortArray &indices, const SizetArray &dvv)
calculate multivariate orthogonal polynomial gradient vector with respect to specified dvv and evaluated at a particular parameter set
const RealSymMatrix & multivariate_polynomial_hessian_matrix (const RealVector &x, const UShortArray &indices)
calculate multivariate orthogonal polynomial gradient vector evaluated at a particular parameter set
void update_pareto_set (const UShort2DArray &multi_index, UShort2DArray &combined_pareto)
define/update a combined Pareto set with a new multi_index by omitting terms that are weakly Pareto dominated (more omissions = smaller resulting set)
void update_pareto_set (const UShortArray &mi_i, UShort2DArray &combined_pareto)
define/update a combined Pareto set for a new multi_index term
void update_frontier (const UShortArraySet &multi_index, UShortArraySet &mi_frontier)
define/update a leading multi_index frontier omitting points that are strongly Pareto dominated (fewer omissions = larger resulting set)
void update_frontier (const UShort2DArray &multi_index, UShortArraySet &mi_frontier)
define/update a leading multi_index frontier omitting points that are strongly Pareto dominated (fewer omissions = larger resulting set)
void update_frontier (const UShortArray &mi_i, UShortArraySet &mi_frontier)
update/update a leading multi_index frontier for a new multi_index term
void assess_dominance (const UShortArray &new_order, const UShortArray &existing_order, bool &new_dominated, bool &existing_dominated)
assess bi-directional weak dominance for a "challenger" polynomial index set against an "incumbent" polynomial index set
void assess_strong_dominance (const UShortArray &order_a, const UShortArray &order_b, bool &a_dominated, bool &b_dominated)
assess bi-directional strong dominance between two polynomial index sets
bool zero_random (const UShortArray &indices) const
test for nonzero indices in random variable subset
void get_tag (char *tag, size_t j, unsigned short order) const
Generate the coefficient tag for variable j of given expansion term order.
void gradient_check ()
tests 1D gradient computations (active in DEBUG compile mode)
Protected Member Functions inherited from SharedPolyApproxData
bool match_random_key (const UShortArray &key_1, const UShortArray &key_2) const
return true if matching key values within random variable subset
bool match_nonrandom_vars (const RealVector &vars_1, const RealVector &vars_2) const
return true if matching variable values within nonrandom variable subset
void allocate_main_sobol ()
allocate sobolIndices and sobolIndexMap for main effects only
void multi_index_to_sobol_index_map (const UShort2DArray &mi)
Define the sobolIndexMap (which defines the set of Sobol' indices) from the incoming multi-index. sobolIndexMap values are initialized to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void reset_sobol_index_map_values ()
return the sobolIndexMap values to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void assign_sobol_index_map_values ()
Define the mapping from sobolIndexMap into sobolIndices.
bool push_available (const UShortArray &trial_set)
check for the presence of trial_set within poppedLevMultiIndex
Protected Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData (BaseConstructor, short basis_type, size_t num_vars)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Static Protected Member Functions
static Real multivariate_polynomial (const RealVector &x, const UShortArray &indices, std::vector< BasisPolynomial > &polynomial_basis)
calculate a particular multivariate orthogonal polynomial value evaluated at a particular parameter set
static Real multivariate_polynomial (const RealVector &x, const UShortArray &indices, const SizetList &non_rand_indices, std::vector< BasisPolynomial > &polynomial_basis)
calculate a particular multivariate orthogonal polynomial value over the nonrandom variable subset evaluated at a particular parameter set
Protected Attributes
ShortArray orthogPolyTypes
array of basis types for each one-dimensional orthogonal polynomial: HERMITE_ORTHOG, LEGENDRE_ORTHOG, LAGUERRE_ORTHOG, JACOBI_ORTHOG, GEN_LAGUERRE_ORTHOG, CHEBYSHEV_ORTHOG, or NUM_GEN_ORTHOG
std::vector< BasisPolynomial > polynomialBasis
array of one-dimensional basis polynomial objects which are used in constructing the multivariate orthogonal/interpolation polynomials
UShortArray approxOrder
order of orthogonal polynomial expansion
UShortArray approxOrderPrev
previous value of approxOrder; used for detecting when a multiIndex update is needed
UShort2DArray multiIndex
number of exp terms-by-number of vars array for identifying the orders of the one-dimensional orthogonal polynomials contributing to each of the multivariate orthogonal polynomials
UShort2DArray combinedMultiIndex
multi-index that is the result of expansion combination
UShort2DArray storedApproxOrder
array of stored approxOrder's cached in store_coefficients() for use in combine_coefficients()
UShort3DArray storedMultiIndex
array of stored multiIndex's cached in store_coefficients() for use in combine_coefficients()
Sizet2DArray storedMultiIndexMap
mapping of terms when aggregating storedMultiIndex with multiIndex in pre_combine_data()
UShort3DArray tpMultiIndex
numSmolyakIndices-by-numTensorProductPts-by-numVars array for identifying the orders of the one-dimensional orthogonal polynomials contributing to each of the multivariate orthogonal polynomials.
Sizet2DArray tpMultiIndexMap
sparse grid bookkeeping: mapping from num tensor-products by tensor-product multi-indices into aggregated multiIndex
SizetArray tpMultiIndexMapRef
sparse grid bookkeeping: reference points for tpMultiIndexMap
std::deque< UShort2DArray > poppedTPMultiIndex
popped instances of tpMultiIndex that were computed but not selected
std::deque< SizetArray > poppedTPMultiIndexMap
popped instances of tpMultiIndexMap that were computed but not selected
std::deque< size_t > poppedTPMultiIndexMapRef
popped instances of tpMultiIndexMapRef that were computed but not selected
size_t pushIndex
index into popped sets of data to be restored (stored in this class for used by each ProjectOrthogPolyApproximation)
RealVector mvpGradient
Data vector for storing the gradients of individual expansion term polynomials (see multivariate_polynomial_gradient_vector())
RealSymMatrix mvpHessian
Data matrix for storing the Hessians of individual expansion term polynomials (see multivariate_polynomial_hessian_matrix())
Protected Attributes inherited from SharedPolyApproxData
IntegrationDriver * driverRep
pointer to integration driver instance
ExpansionConfigOptions expConfigOptions
an encapsulation of expansion configuration options
BasisConfigOptions basisConfigOptions
an encapsulation of basis configuration options
UShortArray quadOrderPrev
previous quadrature order; used for tracking need for expansion form updates
unsigned short ssgLevelPrev
previous Smolyak sparse grid level; used for tracking need for expansion form updates
RealVector ssgAnisoWtsPrev
previous Smolyak sparse grid anisotropic weighting; used for tracking need for expansion form updates
BitArray randomVarsKey
array of bits identifying the random variable subset within the active variables (used in all_variables mode)
SizetList randomIndices
list of indices identifying the random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
SizetList nonRandomIndices
list of indices identifying the non-random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
std::deque< UShortArray > poppedLevMultiIndex
popped trial sets that were computed but not selected
BitArrayULongMap sobolIndexMap
mapping to manage different global sensitivity index options (e.g. univariate/main effects only vs all effects)
Protected Attributes inherited from SharedBasisApproxData
short basisType
type of derived instance as well as sub-type for interpolation
size_t numVars
number of variables used in the approximation
Friends
class OrthogPolyApproximation
Detailed Description
Derived approximation class for orthogonal polynomials (global approximation).
The SharedOrthogPolyApproxData class provides a global approximation based on orthogonal polynomials. It is used primarily for polynomial chaos expansions (for stochastic finite element approaches to uncertainty quantification).
Member Function Documentation
void construct_basis (const ShortArray & u_types, const AleatoryDistParams & adp) inline
invoke initialize_orthogonal_basis_types_rules(), initialize_polynomial_basis(), and, if needed, update_basis_distribution_parameters() using class member data
This function is invoked to create orthogPolyTypes and polynomialBasis for cases where they have not already been created by an IntegrationDriver (i.e., expansion_samples or regression).
References SharedPolyApproxData::basisConfigOptions, SharedOrthogPolyApproxData::orthogPolyTypes, and SharedOrthogPolyApproxData::polynomialBasis.
Referenced by SharedOrthogPolyApproxData::construct_basis(), and SharedOrthogPolyApproxData::increment_order().
void construct_basis (const ShortArray & u_types, const AleatoryDistParams & adp, const BasisConfigOptions & bc_options, std::vector< BasisPolynomial > & poly_basis) inline static
invoke initialize_orthogonal_basis_types_rules(), initialize_polynomial_basis(), and, if needed, update_basis_distribution_parameters() using passed data
This function is invoked to create orthogPolyTypes and polynomialBasis for cases where they have not already been created by an IntegrationDriver (i.e., expansion_samples or regression).
References SharedOrthogPolyApproxData::construct_basis().
void construct_basis (const ShortArray & u_types, const AleatoryDistParams & adp, const BasisConfigOptions & bc_options, std::vector< BasisPolynomial > & poly_basis, ShortArray & basis_types, ShortArray & colloc_rules) inline static
invoke initialize_orthogonal_basis_types_rules(), initialize_polynomial_basis(), and, if needed, update_basis_distribution_parameters() using passed data
This function is invoked to create orthogPolyTypes and polynomialBasis for cases where they have not already been created by an IntegrationDriver (i.e., expansion_samples or regression).
References SharedPolyApproxData::initialize_orthogonal_basis_types_rules(), SharedPolyApproxData::initialize_polynomial_basis(), SharedOrthogPolyApproxData::orthogonal_basis_types(), and SharedPolyApproxData::update_basis_distribution_parameters().
void store_data (size_t index = _NPOS) protected virtual
Default storage, specialized in derived classes.
Implements SharedPolyApproxData.
References SharedOrthogPolyApproxData::approxOrder, SharedPolyApproxData::driverRep, ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, SharedOrthogPolyApproxData::multiIndex, IntegrationDriver::store_grid(), SharedOrthogPolyApproxData::storedApproxOrder, and SharedOrthogPolyApproxData::storedMultiIndex.
void sparse_grid_level_to_expansion_order (CombinedSparseGridDriver * csg_driver, const UShortArray & level, UShortArray & exp_order) protected
convert a sparse grid index set and a growth setting to an integrand_order
The optional growth_rate supports the option of forcing the computed integrand order to be conservative in the presence of exponential growth due to nested quadrature rules. This avoids aggressive formulation of PCE expansion orders when an exponential rule takes a large jump that is not balanced by the other index set component mappings. Note that restricting the expansion growth directly from the level (*_RESTRICTED_GROWTH cases below used by SPARSE_INT_RESTR_TENSOR_SUM_EXP) is similar but not identical to restricting the quadrature order growth from the level and then computing the integrand and expansion orders from the restricted quadrature order (default UNRESTRICTED_GROWTH case below used by SPARSE_INT_TENSOR_SUM_EXP and TENSOR_INT_TENSOR_SUM_EXP, where quadrature rule restriction happens elsewhere). In particular, these approaches differ in granularity of control, since the former approach grows linearly and the latter approach selects the minimal quadrature order (from nonlinear growth or lookup) that meets a linear target.
References SharedOrthogPolyApproxData::integrand_order_to_expansion_order(), SparseGridDriver::level_to_order(), and SharedOrthogPolyApproxData::quadrature_order_to_integrand_order().
Referenced by SharedOrthogPolyApproxData::clear_stored_data(), SharedOrthogPolyApproxData::increment_trial_set(), SharedProjectOrthogPolyApproxData::pre_combine_data(), and SharedProjectOrthogPolyApproxData::sparse_grid_multi_index().
void append_multi_index (const UShort2DArray & append_mi, UShort2DArray & combined_mi) protected
append multi-indices from append_mi that do not already appear in combined_mi
Append to combined_mi based on append_mi.
Referenced by RegressOrthogPolyApproximation::adapt_regression(), RegressOrthogPolyApproximation::advance_multi_index(), SharedOrthogPolyApproxData::append_leading_multi_index(), SharedOrthogPolyApproxData::append_multi_index(), SharedOrthogPolyApproxData::increment_trial_set(), SharedRegressOrthogPolyApproxData::increment_trial_set(), SharedOrthogPolyApproxData::integrand_order_to_expansion_order(), SharedProjectOrthogPolyApproxData::pre_combine_data(), SharedOrthogPolyApproxData::pre_combine_data(), SharedProjectOrthogPolyApproxData::pre_finalize_data(), SharedOrthogPolyApproxData::pre_push_trial_set(), SharedRegressOrthogPolyApproxData::set_restriction(), and SharedProjectOrthogPolyApproxData::sparse_grid_multi_index().
void append_multi_index (const UShortArraySet & append_mi, UShort2DArray & combined_mi) protected
append multi-indices from append_mi that do not already appear in combined_mi
Append to combined_mi based on append_mi.
References SharedOrthogPolyApproxData::append_multi_index().
void append_multi_index (const UShort2DArray & append_mi, UShort2DArray & combined_mi, SizetArray & append_mi_map, size_t & append_mi_map_ref) protected
append multi-indices from append_mi that do not already appear in combined_mi; define append_mi_map and append_mi_map_ref
Append append_mi to combined_mi, and update append_mi_map (SizetArray) and append_mi_map_ref to facilitate related aggregations without repeated searching.
References SharedOrthogPolyApproxData::append_multi_index().
void append_multi_index (const UShort2DArray & append_mi, UShort2DArray & combined_mi, SizetSet & append_mi_map, size_t & append_mi_map_ref) protected
append multi-indices from append_mi that do not already appear in combined_mi; define append_mi_map and append_mi_map_ref
Append append_mi to combined_mi, and update append_mi_map (SizetSet) and append_mi_map_ref to facilitate related aggregations without repeated searching.
References SharedOrthogPolyApproxData::append_leading_multi_index().
void append_leading_multi_index (const UShort2DArray & append_mi, UShort2DArray & combined_mi, SizetSet & append_mi_map, size_t & append_mi_map_ref) protected
append multi-indices from append_mi that do not already appear in combined_mi (consistent ordering assumed); define append_mi_map and append_mi_map_ref
Append append_mi to combined_mi, and update append_mi_map (SizetSet) and append_mi_map_ref to facilitate related aggregations without repeated searching. This case is used when append_mi and combined_mi follow a consistent order without gaps.
References SharedOrthogPolyApproxData::append_multi_index().
Referenced by SharedOrthogPolyApproxData::append_multi_index(), and RegressOrthogPolyApproximation::compressed_sensing().
void append_multi_index (const UShort2DArray & append_mi, SizetArray & append_mi_map, size_t & append_mi_map_ref, UShort2DArray & combined_mi) protected
append multi-indices from append_mi that do not already appear in combined_mi, using previously defined append_mi_map and append_mi_map_ref for mapping
Append to combined_mi based on append_mi and previously defined append_mi_map and append_mi_map_ref. If necessary, update append_mi_map and append_mi_map_ref.
References SharedOrthogPolyApproxData::append_multi_index().
void append_multi_index (SizetSet & sparse_indices, const UShort2DArray & append_mi, UShort2DArray & combined_mi, RealVector & exp_coeffs, RealMatrix & exp_coeff_grads) protected
append multi-indices from append_mi that do not already appear in combined_mi, updating sparse_indices, exp_coeffs, and exp_coeff_grads
Append to combined_mi based on append_mi and previously defined append_mi_map and append_mi_map_ref. If necessary, update append_mi_map and append_mi_map_ref.
References SharedBasisApproxData::numVars, and SharedOrthogPolyApproxData::update_pareto_set().
Real norm_squared (const UShortArray & indices, const SizetList & rand_indices) inline protected
returns the norm-squared of a particular multivariate polynomial, treating a subset of the variables as probabilistic
All variables version.
References SharedOrthogPolyApproxData::polynomialBasis.
Real multivariate_polynomial (const RealVector & x, const UShortArray & indices, const SizetList & non_rand_indices) inline protected
calculate a particular multivariate orthogonal polynomial value over the nonrandom variable subset evaluated at a particular parameter set
All variables version.
References SharedOrthogPolyApproxData::multivariate_polynomial(), and SharedOrthogPolyApproxData::polynomialBasis.
Real multivariate_polynomial (const RealVector & x, const UShortArray & indices, const SizetList & non_rand_indices, std::vector< BasisPolynomial > & polynomial_basis) inline static protected
calculate a particular multivariate orthogonal polynomial value over the nonrandom variable subset evaluated at a particular parameter set
All variables version.
References SharedOrthogPolyApproxData::multivariate_polynomial_gradient().
Real multivariate_polynomial_gradient (const RealVector & x, size_t deriv_index, const UShortArray & indices, const SizetList & non_rand_indices) inline protected
compute multivariate orthogonal polynomial gradient evaluated at x for term corresponding to indices, for derivative variable deriv_index, and for a nonrandom variable subset
All variables version.
References SharedOrthogPolyApproxData::multivariate_polynomial_gradient_vector(), and SharedOrthogPolyApproxData::polynomialBasis.
void assess_dominance (const UShortArray & new_order, const UShortArray & existing_order, bool & new_dominated, bool & existing_dominated) protected
assess bi-directional weak dominance for a "challenger" polynomial index set against an "incumbent" polynomial index set
Weak Pareto dominance: multi_index a weakly dominates multi_index b iff a_i >= b_i for all i and a_i > b_i for at least one dimension. Here we add the additional distinction of a challenger versus an incumbent: tie goes to the incumbent (the challenger is dominated and is not added redundantly to the Pareto set).
References SharedOrthogPolyApproxData::assess_strong_dominance().
Referenced by RegressOrthogPolyApproximation::frontier_restriction(), SharedOrthogPolyApproxData::update_frontier(), and SharedOrthogPolyApproxData::update_pareto_set().
void assess_strong_dominance (const UShortArray & order_a, const UShortArray & order_b, bool & a_dominated, bool & b_dominated) protected
assess bi-directional strong dominance between two polynomial index sets
Strong Pareto dominance: multi_index a strongly dominates multi_index b iff a_i > b_i for all i. This case needs no notion of challenger versus incumbent.
Referenced by SharedOrthogPolyApproxData::assess_dominance(), and SharedOrthogPolyApproxData::update_frontier().
void gradient_check () protected
tests 1D gradient computations (active in DEBUG compile mode)
This test works in combination with DEBUG settings in (Legendre,Laguerre,Jacobi,GenLaguerre)OrthogPolynomial::type1_gradient().
References SharedOrthogPolyApproxData::get_tag(), and BasisPolynomial::type1_gradient().
Referenced by ProjectOrthogPolyApproximation::compute_coefficients(), and RegressOrthogPolyApproximation::compute_coefficients().
Member Data Documentation
UShort3DArray tpMultiIndex protected
numSmolyakIndices-by-numTensorProductPts-by-numVars array for identifying the orders of the one-dimensional orthogonal polynomials contributing to each of the multivariate orthogonal polynomials.
For nested rules (GP, CC, or GK), the integration driver's collocKey is insufficient and we must track expansion orders separately.
Referenced by SharedRegressOrthogPolyApproxData::allocate_data(), SharedRegressOrthogPolyApproxData::clear_adapted(), ProjectOrthogPolyApproximation::compute_coefficients(), SharedOrthogPolyApproxData::decrement_trial_set(), ProjectOrthogPolyApproximation::increment_coefficients(), SharedProjectOrthogPolyApproxData::increment_data(), SharedOrthogPolyApproxData::increment_trial_set(), SharedRegressOrthogPolyApproxData::increment_trial_set(), SharedProjectOrthogPolyApproxData::pre_finalize_data(), SharedOrthogPolyApproxData::pre_push_trial_set(), SharedRegressOrthogPolyApproxData::set_restriction(), and SharedProjectOrthogPolyApproxData::sparse_grid_multi_index().
The documentation for this class was generated from the following files:
SharedOrthogPolyApproxData.hpp
SharedOrthogPolyApproxData.cpp