PECOS: LognormalRandomVariable Class Reference
LognormalRandomVariable Class Reference
Derived random variable class for lognormal random variables.
Public Member Functions
LognormalRandomVariable ()
constructor
LognormalRandomVariable (Real lambda, Real zeta)
alternate constructor
~LognormalRandomVariable ()
destructor
Real cdf (Real x) const
return the cumulative distribution function value of the random variable at x
Real ccdf (Real x) const
return the complementary cumulative distribution function value of the random variable at x
Real inverse_cdf (Real p_cdf) const
return the x value corresponding to a cumulative probability
Real inverse_ccdf (Real p_ccdf) const
return the x value corresponding to a complementary cumulative probability
Real pdf (Real x) const
return the value of the random variable's probability density function at x
Real pdf_gradient (Real x) const
return the gradient of the random variable's probability density function at x
Real pdf_hessian (Real x) const
return the hessian of the random variable's probability density function at x
Real log_pdf (Real x) const
return the value of the natural log of the random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
Real log_pdf_gradient (Real x) const
return the gradient of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
Real log_pdf_hessian (Real x) const
return the Hessian of the natural log of the random variable's probability density function at x (useful for defining MCMC proposal distributions in Bayesian methods)
Real parameter (short dist_param) const
return the value of the named distribution parameter
void parameter (short dist_param, Real val)
update the value of the named distribution parameter
Real mean () const
return the distribution mean
Real median () const
return the distribution mode
Real mode () const
return the distribution mode
Real standard_deviation () const
return the distribution variance
Real variance () const
return the distribution variance
RealRealPair bounds () const
return the distribution lower and upper bounds as a pair
Real coefficient_of_variation () const
compute the coefficient of variation (used to compute selected correlation warping factors); defined for semi-infinite distributions with nonzero mean (lognormal, exponential, gamma, frechet, weibull)
Real correlation_warping_factor (const RandomVariable &rv, Real corr) const
compute the warping factor for correlation between the current variable and the one passed in (used in NatafTransformation)
Real dx_ds (short dist_param, short u_type, Real x, Real z) const
Real dz_ds_factor (short u_type, Real x, Real z) const
void update (Real lambda, Real zeta)
Public Member Functions inherited from RandomVariable
RandomVariable ()
default constructor
RandomVariable (short ran_var_type)
standard constructor for envelope
RandomVariable (const RandomVariable &ran_var)
copy constructor
virtual ~RandomVariable ()
destructor
RandomVariable operator= (const RandomVariable &ran_var)
assignment operator
virtual Real inverse_standard_cdf (Real p_cdf) const
return the x value for a standardized probability distribution corresponding to a cumulative probability
virtual Real standard_pdf (Real z) const
return the value of a standardized random variable's probability density function at x
virtual Real log_standard_pdf (Real z) const
return the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_standard_pdf_gradient (Real z) const
return the gradient of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real log_standard_pdf_hessian (Real z) const
return the Hessian of the natural log of a standardized random variable's probability density function at x (useful for calculations of log density in Bayesian methods)
virtual Real to_standard (Real x) const
scale variable value x from current to standardized distribution
virtual Real from_standard (Real z) const
scale variable value z from standardized to current distribution
virtual RealRealPair moments () const
return the distribution mean and standard deviation as a pair
template<typename Engine >
Real draw_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
template<typename Engine >
Real draw_standard_sample (Engine &rng) const
Draw a sample from the distribution using inverse_cdf on uniform[0,1].
void type (short ran_var_type)
set ranVarType
short type () const
get ranVarType
RandomVariable * random_variable_rep () const
returns ranVarRep for access to derived class member functions that are not mapped to the base level
Static Public Member Functions
static Real pdf (Real x, Real lambda, Real zeta)
static Real cdf (Real x, Real lambda, Real zeta)
static void zeta_from_error_factor (Real err_fact, Real &zeta)
static void error_factor_from_zeta (Real zeta, Real &err_fact)
static void std_deviation_from_error_factor (Real mean, Real err_fact, Real &std_dev)
static void error_factor_from_std_deviation (Real mean, Real std_dev, Real &err_fact)
static void moments_from_params (Real lambda, Real zeta, Real &mean, Real &std_dev)
static void zeta_sq_from_moments (Real mean, Real std_dev, Real &zeta_sq)
static void params_from_moments (Real mean, Real std_dev, Real &lambda, Real &zeta)
Protected Attributes
Real lnLambda
lambda parameter for lognormal random variable
Real lnZeta
zeta parameter for lognormal random variable
Protected Attributes inherited from RandomVariable
short ranVarType
enumeration value indicating type of random variable
Additional Inherited Members
Protected Member Functions inherited from RandomVariable
RandomVariable (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Detailed Description
Derived random variable class for lognormal random variables.
Manages lambda and zeta (mean and std deviation of underlying normal distribution).
Member Function Documentation
Real coefficient_of_variation () const inline virtual
compute the coefficient of variation (used to compute selected correlation warping factors); defined for semi-infinite distributions with nonzero mean (lognormal, exponential, gamma, frechet, weibull)
default is only overridden when more efficient to compute together
Reimplemented from RandomVariable.
References LognormalRandomVariable::correlation_warping_factor(), and LognormalRandomVariable::lnZeta.
Referenced by LognormalRandomVariable::correlation_warping_factor().
Real dx_ds (short dist_param, short u_type, Real x, Real z) const inline virtual
dx/ds is derived by differentiating NatafTransformation::trans_Z_to_X() with respect to distribution parameter s. dz/ds is zero if uncorrelated, while dz_ds_factor() manages contributions in the correlated case.
Reimplemented from RandomVariable.
References LognormalRandomVariable::dz_ds_factor(), LognormalRandomVariable::lnLambda, LognormalRandomVariable::lnZeta, and LognormalRandomVariable::mean().
Referenced by LognormalRandomVariable::correlation_warping_factor().
Real dz_ds_factor (short u_type, Real x, Real z) const inline virtual
dx/ds is derived by differentiating NatafTransformation::trans_Z_to_X() with respect to distribution parameter s. For the uncorrelated case, u and z are constants. For the correlated case, u is a constant, but z(s) = L(s) u due to Nataf dependence on s and dz/ds = dL/ds u.
Reimplemented from RandomVariable.
References LognormalRandomVariable::cdf(), LognormalRandomVariable::lnLambda, LognormalRandomVariable::lnZeta, LognormalRandomVariable::mean(), and LognormalRandomVariable::pdf().
Referenced by LognormalRandomVariable::dx_ds().
The documentation for this class was generated from the following file:
LognormalRandomVariable.hpp