PECOS: LagrangeInterpPolynomial Class Reference
LagrangeInterpPolynomial Class Reference
Derived basis polynomial class for 1-D Lagrange interpolation polynomials.
Public Member Functions
LagrangeInterpPolynomial ()
default constructor
LagrangeInterpPolynomial (const RealArray &interp_pts)
standard constructor
~LagrangeInterpPolynomial ()
destructor
Real type1_value (unsigned short i)
retrieve the value of the i_th Lagrange polynomial for a given parameter x using barycentric formulation
Real type1_value (Real x, unsigned short i)
retrieve the value of the i_th Lagrange polynomial for a given parameter x using traditional characteristic polynomial formulation
Real type1_gradient (unsigned short i)
retrieve the gradient of the i_th Lagrange polynomial for a given parameter x using barycentric formulation
Real type1_gradient (Real x, unsigned short i)
retrieve the gradient of the i_th Lagrange polynomial for a given parameter x using traditional characteristic polynomial formulation
void set_new_point (Real x, short request_order)
void set_new_point (Real x, short request_order, const UShortArray &delta_key)
size_t exact_index () const
returns the index of a collocation point that is an exact match with the point to be interpolated (from set_new_point()) if detected (_NPOS if not)
size_t exact_delta_index () const
returns the index of a hierarchical increment to the interpolation points that is an exact match with the point to be interpolated (from set_new_point()) if detected (_NPOS if not)
const RealVector & barycentric_value_factors () const
return the barycentric value factors
const RealVector & barycentric_gradient_factors () const
return the barycentric gradient factors
Real barycentric_value_factor (unsigned short i) const
return a particular barycentric value factor
Real barycentric_gradient_factor (unsigned short i) const
return a particular barycentric gradient factor
Real barycentric_value_factor_sum () const
return the sum of all barycentric value factors for use in computing the barycentric interpolant denominator
Real barycentric_difference_product () const
return the product of all differences between the interpolation points and a current point
Public Member Functions inherited from InterpolationPolynomial
InterpolationPolynomial ()
default constructor
InterpolationPolynomial (const RealArray &interp_pts)
standard constructor
virtual ~InterpolationPolynomial ()
destructor
size_t interpolation_size () const
get size of interpPts
void interpolation_points (const RealArray &interp_pts)
set interpPts
const RealArray & interpolation_points () const
get interpPts
Public Member Functions inherited from BasisPolynomial
BasisPolynomial ()
default constructor
BasisPolynomial (short poly_type, short rule=0)
alternate constructor
BasisPolynomial (const BasisPolynomial &polynomial)
copy constructor
virtual ~BasisPolynomial ()
destructor
BasisPolynomial operator= (const BasisPolynomial &polynomial)
assignment operator
virtual Real type2_value (Real x, unsigned short n)
retrieve the value of the n_th type 2 polynomial for a given parameter x
virtual Real type2_gradient (Real x, unsigned short n)
retrieve the gradient of the n_th type 2 polynomial for a given parameter x
virtual Real type1_hessian (Real x, unsigned short n)
retrieve the Hessian of the n_th type 1 polynomial for a given parameter x using traditional characteristic polynomial formulation
virtual Real norm_squared (unsigned short n)
returns the norm-squared of the n_th order polynomial defined by the inner product <Poly_n, Poly_n> = ||Poly_n||^2
virtual const RealArray & collocation_points (unsigned short n)
return collocation points corresponding to orthogonal polynomial order n
virtual const RealArray & type1_collocation_weights (unsigned short order)
return the type 1 collocation weights corresponding to a point set of size order
virtual const RealArray & type2_collocation_weights (unsigned short order)
return the type 2 collocation weights corresponding to a point set of size order
virtual void reset_gauss ()
destroy history of Gauss pts/wts (due to distribution parameter changes)
virtual Real point_factor ()
(calculate and) return ptFactor
virtual Real weight_factor ()
(calculate and) return wtFactor
virtual Real alpha_polynomial () const
return {Jacobi,GenLaguerre}OrthogPolynomial::alphaPoly
virtual Real beta_polynomial () const
return JacobiOrthogPolynomial::betaPoly
virtual void alpha_stat (Real alpha)
set JacobiOrthogPolynomial::betaPoly or GenLaguerreOrthogPolynomial::alphaPoly from statistical defn of alpha
virtual void beta_stat (Real beta)
set JacobiOrthogPolynomial::alphaPoly from statistical defn of beta
virtual void collocation_rule (short rule)
set OrthogonalPolynomial::collocRule
virtual short collocation_rule () const
get OrthogonalPolynomial::collocRule
virtual bool parameterized () const
return whether a derived BasisPolynomial type supports parameterization
virtual Real length_scale () const
return a characteristic length scale for the probability distribution associated with an orthogonal polynomial basis
virtual void precompute_rules (unsigned short order)
precompute quadrature rules up to specified order
short basis_type () const
return basisPolyType
bool parametric_update () const
return parametricUpdate
BasisPolynomial * polynomial_rep () const
returns polyRep for access to derived class member functions that are not mapped to the top BasisPolynomial level
bool is_null () const
function to check polyRep (does this handle contain a body)
Protected Member Functions
void precompute_data ()
Protected Member Functions inherited from BasisPolynomial
BasisPolynomial (BaseConstructor)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Private Member Functions
void init_new_point (Real x, short request_order, short &compute_order)
define compute order from request order and newPoint match
void allocate_factors (short compute_order)
based on compute order, size barycentric value/gradient factors
Private Attributes
RealVector bcWeights
set of denominator products calculated from interpPts in precompute_data(); in barycentric formulations, these are the weights
Real newPoint
the parameter value for evaluation of the interpolant
short newPtOrder
order of data that has been precomputed at newPoint
size_t exactIndex
index of interpolation point that exactly matches the interpolated value x
size_t exactDeltaIndex
index within a hierarchical increment to the interpolation points that exactly matches the interpolated value x
Real diffProduct
product of point differences (x-x_j) for a particular newPoint x and interpPts x_j
RealVector bcValueFactors
terms bcWeights[j]/(x-x[j]) from barycentric formulation
Real bcValueFactorSum
sum of bcValueFactors used for evaluating barycentric interpolant denominator term
RealVector bcGradFactors
terms for gradients of barycentric interpolants
Additional Inherited Members
Static Public Member Functions inherited from BasisPolynomial
static Real factorial (unsigned short n)
compute n!
static Real factorial_ratio (unsigned short num, unsigned short den)
compute num!/den!
static Real n_choose_k (unsigned short n, unsigned short k)
compute n!/(k!(n-k)!)
static Real pochhammer (Real m, unsigned short n)
compute the Pochhammer symbol (m)_n = m*(m+1)...*(m+n-1)
Protected Attributes inherited from InterpolationPolynomial
RealArray interpPts
set of 1-D interpolation points: the i_th interpolation polynomial evaluated at the j_th interpolation point produces Kronecker delta_ij
Protected Attributes inherited from BasisPolynomial
short basisPolyType
basis polynomial type: {HERMITE,LEGENDRE,LAGUERRE,JACOBI,GEN_LAGUERRE,NUM_GEN}_ORTHOG, {LAGRANGE,HERMITE}_INTERP, or PIECEWISE_{LINEAR,QUADRATIC,CUBIC}_INTERP
bool parametricUpdate
flag indicating presence of a parametric update to the basis polynomial, such that previous points/weights may not be reused
Real wtFactor
weight discrepancy factor between Abramowitz-Stegun and PDF orthogonality
Real ptFactor
point discrepancy factor between Abramowitz-Stegun and PDF orthogonality
Detailed Description
Derived basis polynomial class for 1-D Lagrange interpolation polynomials.
The LagrangeInterpPolynomial class evaluates a univariate Lagrange interpolation polynomial. The order of the polynomial is dictated by the number of interpolation points (order = N_p - 1). It enables multidimensional interpolants within InterpPolyApproximation. This class supports both the traditional characteristic polynomial form of Lagrange interpolation as well as barycentric Lagrange interpolation (the second form from Berrut and Trefethen, 2004). The former is used for actual evaluation of 1D polynomial values (when needed), whereas the latter allows alternative interpolant evaluations with additional precomputation that improve efficiency from O(n^2) evaluations to O(n).
Member Function Documentation
Real type1_value (unsigned short i) virtual
retrieve the value of the i_th Lagrange polynomial for a given parameter x using barycentric formulation
Compute value of the Lagrange polynomial (1st barycentric form) corresponding to interpolation point i using data from previous call to set_new_point().
Reimplemented from BasisPolynomial.
References LagrangeInterpPolynomial::bcValueFactors, LagrangeInterpPolynomial::diffProduct, and LagrangeInterpPolynomial::exactIndex.
Real type1_value (Real x, unsigned short i) virtual
retrieve the value of the i_th Lagrange polynomial for a given parameter x using traditional characteristic polynomial formulation
Compute value of the Lagrange polynomial (traditional characteristic polynomial form) corresponding to interpolation point i.
Reimplemented from BasisPolynomial.
References LagrangeInterpPolynomial::bcWeights, and InterpolationPolynomial::interpPts.
Real type1_gradient (unsigned short i) virtual
retrieve the gradient of the i_th Lagrange polynomial for a given parameter x using barycentric formulation
Compute derivative with respect to x of the Lagrange polynomial (1st barycentric form) corresponding to interpolation point i using data from previous call to set_new_point().
Reimplemented from BasisPolynomial.
References LagrangeInterpPolynomial::bcGradFactors, LagrangeInterpPolynomial::diffProduct, and LagrangeInterpPolynomial::exactIndex.
Real type1_gradient (Real x, unsigned short i) virtual
retrieve the gradient of the i_th Lagrange polynomial for a given parameter x using traditional characteristic polynomial formulation
Compute derivative with respect to x of the Lagrange polynomial (traditional characteristic polynomial form) corresponding to interpolation point i.
Reimplemented from BasisPolynomial.
References LagrangeInterpPolynomial::bcWeights, InterpolationPolynomial::interpPts, and Pecos::sum().
void set_new_point (Real x, short request_order) virtual
Define the bcValueFactors (and exactIndex if needed) corresponding to x.
Reimplemented from BasisPolynomial.
References LagrangeInterpPolynomial::allocate_factors(), LagrangeInterpPolynomial::bcGradFactors, LagrangeInterpPolynomial::bcValueFactors, LagrangeInterpPolynomial::bcValueFactorSum, LagrangeInterpPolynomial::bcWeights, LagrangeInterpPolynomial::diffProduct, LagrangeInterpPolynomial::exactDeltaIndex, LagrangeInterpPolynomial::exactIndex, LagrangeInterpPolynomial::init_new_point(), InterpolationPolynomial::interpPts, and LagrangeInterpPolynomial::newPoint.
void set_new_point (Real x, short request_order, const UShortArray & delta_key) virtual
Define the bcValueFactors (and exactIndex if needed) corresponding to x.
Reimplemented from BasisPolynomial.
References LagrangeInterpPolynomial::allocate_factors(), LagrangeInterpPolynomial::bcGradFactors, LagrangeInterpPolynomial::bcValueFactors, LagrangeInterpPolynomial::bcValueFactorSum, LagrangeInterpPolynomial::bcWeights, LagrangeInterpPolynomial::diffProduct, LagrangeInterpPolynomial::exactDeltaIndex, LagrangeInterpPolynomial::exactIndex, LagrangeInterpPolynomial::init_new_point(), InterpolationPolynomial::interpPts, and LagrangeInterpPolynomial::newPoint.
void precompute_data () protected virtual
Pre-compute denominator products that are only a function of the interpolation points.
Reimplemented from InterpolationPolynomial.
References LagrangeInterpPolynomial::bcWeights, LagrangeInterpPolynomial::init_new_point(), and InterpolationPolynomial::interpPts.
void init_new_point (Real x, short request_order, short & compute_order) private
define compute order from request order and newPoint match
Shared initialization code.
References LagrangeInterpPolynomial::exactDeltaIndex, LagrangeInterpPolynomial::exactIndex, LagrangeInterpPolynomial::newPoint, and LagrangeInterpPolynomial::newPtOrder.
Referenced by LagrangeInterpPolynomial::precompute_data(), and LagrangeInterpPolynomial::set_new_point().
void allocate_factors (short compute_order) inline private
based on compute order, size barycentric value/gradient factors
Shared initialization code.
References LagrangeInterpPolynomial::bcGradFactors, LagrangeInterpPolynomial::bcValueFactors, LagrangeInterpPolynomial::bcWeights, and InterpolationPolynomial::interpPts.
Referenced by LagrangeInterpPolynomial::set_new_point().
The documentation for this class was generated from the following files:
LagrangeInterpPolynomial.hpp
LagrangeInterpPolynomial.cpp