PECOS: InterpPolyApproximation Class Reference
InterpPolyApproximation Class Reference abstract
Derived approximation class for interpolation polynomials (global approximation).
Public Member Functions
InterpPolyApproximation (const SharedBasisApproxData &shared_data)
default constructor
~InterpPolyApproximation ()
destructor
Public Member Functions inherited from PolynomialApproximation
PolynomialApproximation (const SharedBasisApproxData &shared_data)
standard constructor
~PolynomialApproximation ()
destructorboth
virtual void allocate_component_sobol ()
size component Sobol arrays
virtual ULongULongMap sparse_sobol_index_map () const
return RegressOrthogPolyApproximation::sparseSobolIndexMap
virtual const RealVector & gradient_basis_variables (const RealVector &x)=0
retrieve the gradient for a response expansion with respect to all variables included in the polynomial bases using the given parameter vector and default DVV
virtual const RealVector & gradient_basis_variables (const RealVector &x, const SizetArray &dvv)=0
retrieve the gradient for a response expansion with respect to variables included in the polynomial basis for a given parameter vector and a given DVV subset
virtual const RealVector & gradient_nonbasis_variables (const RealVector &x)=0
retrieve the gradient for a response expansion with respect to all variables not included in the polynomial bases (nonprobabilistic variables such as design or epistemic when not in "all" mode) using the given parameter vector and default DVV
virtual const RealSymMatrix & hessian_basis_variables (const RealVector &x)=0
retrieve the Hessian of the response expansion with respect to all variables included in the polynomial basis (e.g., probabilistic variables) for a given parameter vector
virtual Real stored_value (const RealVector &x, size_t index)=0
retrieve the response value for a stored expansion using the given parameter vector
virtual const RealVector & stored_gradient_basis_variables (const RealVector &x, size_t index)=0
retrieve the response gradient for a stored expansion with respect to all variables included in the polynomial bases; evaluate for the given parameter vector.
virtual const RealVector & stored_gradient_nonbasis_variables (const RealVector &x, size_t index)=0
retrieve the response gradient for a stored expansion with respect to all variables not included in the polynomial bases; evaluate for the given parameter vector.
virtual Real mean ()=0
return the mean of the expansion, treating all variables as random
virtual Real mean (const RealVector &x)=0
return the mean of the expansion for a given parameter vector, treating a subset of the variables as random
virtual const RealVector & mean_gradient ()=0
return the gradient of the expansion mean for a given parameter vector, treating all variables as random
virtual const RealVector & mean_gradient (const RealVector &x, const SizetArray &dvv)=0
return the gradient of the expansion mean for a given parameter vector and given DVV, treating a subset of the variables as random
virtual Real variance ()=0
return the variance of the expansion, treating all variables as random
virtual Real variance (const RealVector &x)=0
return the variance of the expansion for a given parameter vector, treating a subset of the variables as random
virtual const RealVector & variance_gradient ()=0
return the gradient of the expansion variance for a given parameter vector, treating all variables as random
virtual const RealVector & variance_gradient (const RealVector &x, const SizetArray &dvv)=0
return the gradient of the expansion variance for a given parameter vector and given DVV, treating a subset of the variables as random
virtual Real covariance (PolynomialApproximation *poly_approx_2)=0
return the covariance between two response expansions, treating all variables as random
virtual Real covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)=0
return the covariance between two response expansions for a given parameter vector, treating a subset of the variables as random
virtual Real delta_covariance (PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions, treating all variables as random
virtual Real delta_covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions for a given parameter vector, treating a subset of the variables as random
virtual Real delta_mean ()
return the change in mean between two response expansions, treating all variables as random
virtual Real delta_mean (const RealVector &x)
return the change in mean between two response expansions, treating a subset of the variables as random
virtual Real delta_std_deviation ()
return the change in standard deviation between two response expansions, treating all variables as random
virtual Real delta_std_deviation (const RealVector &x)
return the change in standard deviation between two response expansions, treating a subset of the variables as random
virtual Real delta_beta (bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating all variables as random
virtual Real delta_beta (const RealVector &x, bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating a subset of the variables as random
virtual Real delta_z (bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating all variables as random
virtual Real delta_z (const RealVector &x, bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating a subset of the variables as random
bool deep_copied_surrogate_data () const
returns true if surrData is a deep copy of origSurrData
const RealVector & expansion_moments () const
return expansionMoments
const RealVector & numerical_integration_moments () const
return numericalMoments
const RealVector & moments () const
return preferred response moments (either expansion or numerical integration, depending on approximation type)
void standardize_moments (const RealVector &central_moments, RealVector &std_moments)
standardize central moments 2-n and eliminate excess kurtosis
void expansion_coefficient_flag (bool coeff_flag)
set ExpansionConfigOptions::expansionCoeffFlag
bool expansion_coefficient_flag () const
get ExpansionConfigOptions::expansionCoeffFlag
void expansion_coefficient_gradient_flag (bool grad_flag)
set ExpansionConfigOptions::expansionCoeffGradFlag
bool expansion_coefficient_gradient_flag () const
get ExpansionConfigOptions::expansionCoeffGradFlag
const RealVector & sobol_indices () const
return sobolIndices
const RealVector & total_sobol_indices () const
return totalSobolIndices
Public Member Functions inherited from BasisApproximation
BasisApproximation ()
default constructor
BasisApproximation (const SharedBasisApproxData &shared_data)
standard constructor for envelope
BasisApproximation (const BasisApproximation &basis_approx)
copy constructor
virtual ~BasisApproximation ()
destructor
BasisApproximation operator= (const BasisApproximation &basis_approx)
assignment operator
virtual Real value (const RealVector &x)
retrieve the approximate function value for a given parameter vector
virtual void increment_coefficients (size_t index=_NPOS)
recalculate approximation coefficients following a surrogate data update
virtual void decrement_coefficients (bool save_data)
restore the approximation coefficients to the state preceding the last increment
virtual void push_coefficients ()
restore the approximation coefficients to a previously incremented state as identified by the current data increment
virtual void finalize_coefficients ()
finalize the coefficients by applying all previously evaluated increments
virtual void store_coefficients (size_t index=_NPOS)
store the current coefficients for later combination
virtual void restore_coefficients (size_t index=_NPOS)
restore a previously stored coefficient state
virtual void swap_coefficients (size_t index)
swap the current coefficients with a previously stored set
virtual void remove_stored_coefficients (size_t index=_NPOS)
remove a redundant stored entry prior to combine_coefficients (default is pop_back)
virtual void clear_stored ()
clear stored approximation data
virtual void combine_coefficients (size_t swap_index)
combine the current coefficients with a previously stored set
virtual void print_coefficients (std::ostream &s, bool normalized)
print the coefficient array computed in compute_coefficients()
virtual RealVector approximation_coefficients (bool normalized) const
return the coefficient array computed by compute_coefficients()
virtual void approximation_coefficients (const RealVector &approx_coeffs, bool normalized)
set the coefficient array from external sources, rather than computing with compute_coefficients()
virtual void coefficient_labels (std::vector< std::string > &coeff_labels) const
retrieve a vector of coefficient label strings, one per expansion term
void assign_rep (BasisApproximation *approx_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
BasisApproximation * approx_rep () const
returns approxRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
int min_coefficients () const
return the minimum number of samples (unknowns) required to build the derived class approximation type in numVars dimensions
void allocate_arrays ()
size derived class data attributes
void compute_component_sobol ()
computes component (main and interaction) Sobol' indices
void compute_total_sobol ()
computes total Sobol' indices
void compute_moments (bool full_stats=true)
compute numerical moments to order 4
void compute_moments (const RealVector &x, bool full_stats=true)
compute numerical moments in all-variables mode to order 2
virtual void integrate_response_moments (size_t num_moments)=0
compute moments of response using numerical integration
virtual void integrate_expansion_moments (size_t num_moments)=0
compute moments of expansion using numerical integration
virtual void compute_total_sobol_indices ()=0
virtual void compute_partial_variance (const BitArray &set_value)
void test_interpolation ()
test accuracy of the interpolants
Protected Member Functions inherited from PolynomialApproximation
void surrogate_data (const SurrogateData &data)
set PolynomialApproximation::origSurrData
const SurrogateData & surrogate_data () const
get PolynomialApproximation::surrData (const)
SurrogateData & surrogate_data ()
get PolynomialApproximation::surrData (non-const)
void compute_coefficients (size_t index=_NPOS)
calculate the approximation coefficients using a set of surrogate data
const RealVector & gradient (const RealVector &x)
generic base class function mapped to gradient_basis_variables(x)
const RealSymMatrix & hessian (const RealVector &x)
generic base class function mapped to hessian_basis_variables(x)
void synchronize_surrogate_data (size_t index)
update surrData from origSurrData based on deep or shallow copy
void response_data_to_surplus_data (size_t index)
modify origSurrData to create hierarchical surplus response data within surrData
void integrate_moments (const RealVector &coeffs, const RealVector &t1_wts, RealVector &moments)
compute central moments of response using type1 numerical integration
void integrate_moments (const RealVector &t1_coeffs, const RealMatrix &t2_coeffs, const RealVector &t1_wts, const RealMatrix &t2_wts, RealVector &moments)
compute central moments of response using type1/2 numerical integration
void allocate_total_sobol ()
size total Sobol arrays
Protected Member Functions inherited from BasisApproximation
BasisApproximation (BaseConstructor, const SharedBasisApproxData &shared_data)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
RealVector partialVariance
the partialVariances of subset functions f_alpha
Protected Attributes inherited from PolynomialApproximation
SurrogateData origSurrData
SurrogateData instance containing the variables (shared) and response (unique) data arrays for constructing a surrogate of a single response function; this is the original unmodified data set, prior to any potential manipulations by the approximation classes.
SurrogateData surrData
SurrogateData instance used in current approximation builds, potentially reflecting data modifications relative to origSurrData.
bool expansionCoeffFlag
flag for calculation of expansion coefficients from response values
bool expansionCoeffGradFlag
flag for calculation of gradients of expansion coefficients from response gradients
RealVector expansionMoments
mean and central moments 2/3/4 computed from the stochastic expansion form. For OrthogPolyApproximation, these are primary, and for InterpPolyApproximation, they are secondary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector numericalMoments
mean and central moments 2/3/4 computed via numerical integration of the response. For OrthogPolyApproximation, these are secondary, and for InterpPolyApproximation, they are primary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector approxGradient
gradient of the polynomial approximation returned by gradient()
RealSymMatrix approxHessian
Hessian of the polynomial approximation returned by hessian()
RealVector meanGradient
gradient of the primary mean (expansion mean for OrthogPoly, numerical integration mean for InterpPoly)
RealVector varianceGradient
gradient of the primary variance (expansion variance for OrthogPoly, numerical integration variance for InterpPoly)
short computedMean
track computation of mean and mean gradient to avoid unnecessary recomputation
short computedVariance
track computation of variance and variance gradient to avoid unnecessary recomputation
RealVector xPrevMean
track previous evaluation point for all_variables mean to avoid unnecessary recomputation
RealVector xPrevMeanGrad
track previous evaluation point for all_variables mean gradient to avoid unnecessary recomputation
RealVector xPrevVar
track previous evaluation point for all_variables variance to avoid unnecessary recomputation
RealVector xPrevVarGrad
track previous evaluation point for all_variables variance gradient to avoid unnecessary recomputation
RealVector sobolIndices
global sensitivities as given by Sobol'
RealVector totalSobolIndices
total global sensitivities as given by Sobol'
Protected Attributes inherited from BasisApproximation
SharedBasisApproxData * sharedDataRep
contains the approximation data that is shared among the response set
Private Member Functions
void proper_subsets (const BitArray &parent_set, BitArraySet &children)
recursively identifies constituent subsets that are children of a parent set
Detailed Description
Derived approximation class for interpolation polynomials (global approximation).
The InterpPolyApproximation class provides a global approximation based on interpolation polynomials. It is used primarily for stochastic collocation approaches to uncertainty quantification.
Member Function Documentation
void compute_partial_variance (const BitArray & set_value) protected virtual
Computes the variance of component functions. Assumes that partial variances of all subsets of set_value have been computed in advance: compute_component_sobol() calls compute_partial_variance() using the ordered set_value's in sobolIndexMap.
Reimplemented in HierarchInterpPolyApproximation, and NodalInterpPolyApproximation.
References InterpPolyApproximation::partialVariance, InterpPolyApproximation::proper_subsets(), BasisApproximation::sharedDataRep, and SharedPolyApproxData::sobolIndexMap.
Referenced by InterpPolyApproximation::compute_component_sobol(), NodalInterpPolyApproximation::compute_partial_variance(), HierarchInterpPolyApproximation::compute_partial_variance(), and InterpPolyApproximation::compute_total_sobol().
void proper_subsets (const BitArray & parent_set, BitArraySet & children) private
recursively identifies constituent subsets that are children of a parent set
For input parent set, recursively finds constituent child subsets with one fewer element
References SharedBasisApproxData::numVars, and BasisApproximation::sharedDataRep.
Referenced by InterpPolyApproximation::compute_partial_variance().
The documentation for this class was generated from the following files:
InterpPolyApproximation.hpp
InterpPolyApproximation.cpp