PECOS: SharedPolyApproxData Class Reference
SharedPolyApproxData Class Reference abstract
Derived approximation class for global basis polynomials.
Public Member Functions
SharedPolyApproxData ()
default constructor
SharedPolyApproxData (short basis_type, size_t num_vars)
standard constructor
SharedPolyApproxData (short basis_type, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
alternate constructor with full configuration options
~SharedPolyApproxData ()
destructorboth
virtual void allocate_data (size_t index=_NPOS)=0
allocate the shared data prior to building the set of approximations
virtual void increment_data (size_t index=_NPOS)
update the shared data prior to rebuilding the set of approximations
virtual void decrement_data ()
decrement the previous increment and store its shared data for later retrieval
virtual void pre_push_data ()
restores previously popped approximation data
virtual void post_push_data ()
restores previously popped approximation data
virtual void pre_finalize_data ()
finalizes the shared approximation data following a set of increments
virtual void post_finalize_data ()
finalizes the shared approximation data following a set of increments
virtual void store_data (size_t index=_NPOS)=0
stores current approximation data for later combination
virtual void restore_data (size_t index=_NPOS)=0
restores previously stored approximation data
virtual void remove_stored_data (size_t index=_NPOS)=0
removes a redundant stored approximation data prior to combination
virtual size_t pre_combine_data ()
combines current and stored approximation data
virtual void post_combine_data ()
combines current and stored approximation data
virtual void clear_stored_data ()
clear stored approximation data
bool push_available ()
test for whether current trial set requires a new approximation increment or can be restored from a previous trial
size_t retrieval_index ()
returns index of the data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex)
size_t finalization_index (size_t i)
returns index of the i-th data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex) during finalization
void configuration_options (const ExpansionConfigOptions &ec_options)
set expConfigOptions as a group (instead of per option below)
void configuration_options (const BasisConfigOptions &bc_options)
set basisConfigOptions (instead of per option below)
const BitArrayULongMap & sobol_index_map () const
return sobolIndexMap
void integration_driver_rep (IntegrationDriver *driver_rep)
set driverRep
void random_variables_key (const BitArray &random_vars_key)
set randomVarsKey
Public Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData ()
default constructor
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars)
standard constructor for envelope
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options, const RegressionConfigOptions &rc_options)
alternate constructor for envelope
SharedBasisApproxData (const SharedBasisApproxData &shared_data)
copy constructor
virtual ~SharedBasisApproxData ()
destructor
SharedBasisApproxData operator= (const SharedBasisApproxData &shared_data)
assignment operator
void assign_rep (SharedBasisApproxData *data_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
SharedBasisApproxData * data_rep () const
returns dataRep for access to derived class member functions that are not mapped to the top Approximation level
Static Public Member Functions
static bool initialize_orthogonal_basis_types_rules (const ShortArray &u_types, const BasisConfigOptions &bc_options, ShortArray &basis_types, ShortArray &colloc_rules)
allocate orthogonal polynomial basis types and integration rules based on u_types and rule options
static bool initialize_orthogonal_basis_type_rule (short u_type, const BasisConfigOptions &bc_options, short &basis_type, short &colloc_rule)
assign orthogonal polynomial basis type and integration rule based on u_type and basis configuration options
static void initialize_polynomial_basis (const ShortArray &basis_types, const ShortArray &colloc_rules, std::vector< BasisPolynomial > &poly_basis)
allocate poly_basis based on basis_types and colloc_rules
static void update_basis_distribution_parameters (const ShortArray &u_types, const AleatoryDistParams &dp, std::vector< BasisPolynomial > &poly_basis)
pass distribution parameters from dp to poly_basis
static size_t total_order_terms (const UShortArray &upper_bound, short lower_bound_offset=-1)
return the number of expansion terms for a total order expansion with the provided (anisotropic) upper_bound array specification
static size_t tensor_product_terms (const UShortArray &order, bool include_upper_bound=true)
return the number of expansion terms for a tensor-product expansion with the provided (anisotropic) quadrature orders (include_upper_bound = false) or expansion orders (default)
static void tensor_product_multi_index (const UShortArray &order, UShort2DArray &multi_index, bool include_upper_bound=true)
initialize expansion multi_index using a tensor-product expansion
static void hierarchical_tensor_product_multi_index (const UShort2DArray &delta_quad, UShort2DArray &multi_index)
initialize multi_index using a hierarchical tensor-product expansion
static void total_order_multi_index (unsigned short level, size_t num_vars, UShort2DArray &multi_index)
initialize multi_index using a total-order expansion from a scalar level
static void total_order_multi_index (const UShortArray &upper_bound, UShort2DArray &multi_index, short lower_bound_offset=-1, size_t max_terms=_NPOS)
initialize expansion multi_index using a total-order expansion from an upper_bound array specification
static void increment_indices (UShortArray &indices, const UShortArray &limits, bool include_upper_bound)
utility function for incrementing a set of multidimensional indices
static void increment_terms (UShortArray &terms, size_t &last_index, size_t &prev_index, size_t term_limit, bool &order_complete)
utility function for incrementing a set of multidimensional terms
Protected Member Functions
bool match_random_key (const UShortArray &key_1, const UShortArray &key_2) const
return true if matching key values within random variable subset
bool match_nonrandom_vars (const RealVector &vars_1, const RealVector &vars_2) const
return true if matching variable values within nonrandom variable subset
void allocate_main_sobol ()
allocate sobolIndices and sobolIndexMap for main effects only
void multi_index_to_sobol_index_map (const UShort2DArray &mi)
Define the sobolIndexMap (which defines the set of Sobol' indices) from the incoming multi-index. sobolIndexMap values are initialized to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void reset_sobol_index_map_values ()
return the sobolIndexMap values to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void assign_sobol_index_map_values ()
Define the mapping from sobolIndexMap into sobolIndices.
bool push_available (const UShortArray &trial_set)
check for the presence of trial_set within poppedLevMultiIndex
Protected Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData (BaseConstructor, short basis_type, size_t num_vars)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
IntegrationDriver * driverRep
pointer to integration driver instance
ExpansionConfigOptions expConfigOptions
an encapsulation of expansion configuration options
BasisConfigOptions basisConfigOptions
an encapsulation of basis configuration options
UShortArray quadOrderPrev
previous quadrature order; used for tracking need for expansion form updates
unsigned short ssgLevelPrev
previous Smolyak sparse grid level; used for tracking need for expansion form updates
RealVector ssgAnisoWtsPrev
previous Smolyak sparse grid anisotropic weighting; used for tracking need for expansion form updates
BitArray randomVarsKey
array of bits identifying the random variable subset within the active variables (used in all_variables mode)
SizetList randomIndices
list of indices identifying the random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
SizetList nonRandomIndices
list of indices identifying the non-random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
std::deque< UShortArray > poppedLevMultiIndex
popped trial sets that were computed but not selected
BitArrayULongMap sobolIndexMap
mapping to manage different global sensitivity index options (e.g. univariate/main effects only vs all effects)
Protected Attributes inherited from SharedBasisApproxData
short basisType
type of derived instance as well as sub-type for interpolation
size_t numVars
number of variables used in the approximation
Friends
class PolynomialApproximation
class InterpPolyApproximation
class NodalInterpPolyApproximation
class HierarchInterpPolyApproximation
class OrthogPolyApproximation
class ProjectOrthogPolyApproximation
class RegressOrthogPolyApproximation
Detailed Description
Derived approximation class for global basis polynomials.
The SharedPolyApproxData class provides a global approximation based on basis polynomials. This includes orthogonal polynomials used for polynomial chaos expansions and interpolation polynomials used for stochastic collocation.
Member Function Documentation
bool initialize_orthogonal_basis_types_rules (const ShortArray & u_types, const BasisConfigOptions & bc_options, ShortArray & basis_types, ShortArray & colloc_rules) static
allocate orthogonal polynomial basis types and integration rules based on u_types and rule options
This version supports only orthogonal polynomial types. In this case, the polynomial types needed for an orthogonal basis and for computing collocation points and weights in an integration driver are the same.
References SharedPolyApproxData::initialize_orthogonal_basis_type_rule().
Referenced by SharedOrthogPolyApproxData::construct_basis(), and IntegrationDriver::initialize_grid().
size_t total_order_terms (const UShortArray & upper_bound, short lower_bound_offset = -1) static
return the number of expansion terms for a total order expansion with the provided (anisotropic) upper_bound array specification
Return the number of terms in a total-order expansion. For anisotropic expansion order, no simple expression is currently available and the number of expansion terms is computed using the multiIndex recursion.
References SharedPolyApproxData::increment_terms(), BasisPolynomial::n_choose_k(), and SharedPolyApproxData::total_order_multi_index().
Referenced by SharedPolyApproxData::hierarchical_tensor_product_multi_index(), and SharedOrthogPolyApproxData::maximal_expansion().
size_t tensor_product_terms (const UShortArray & order, bool include_upper_bound = true) static
return the number of expansion terms for a tensor-product expansion with the provided (anisotropic) quadrature orders (include_upper_bound = false) or expansion orders (default)
Return the number of terms in a tensor-product expansion. For isotropic and anisotropic expansion orders, calculation of the number of expansion terms is straightforward: Prod(p_i + 1).
References SharedPolyApproxData::tensor_product_multi_index().
Referenced by SharedPolyApproxData::assign_sobol_index_map_values(), HierarchSparseGridDriver::grid_size(), and SharedPolyApproxData::tensor_product_multi_index().
void total_order_multi_index (unsigned short level, size_t num_vars, UShort2DArray & multi_index) static
initialize multi_index using a total-order expansion from a scalar level
Overloaded version for defining the multi-indices for a single scalar level. Anisotropy is not supported, so this version is not usable as a kernel within other overloaded versions.
References SharedPolyApproxData::increment_terms().
Referenced by SharedProjectOrthogPolyApproxData::allocate_data(), SharedOrthogPolyApproxData::allocate_data(), SharedRegressOrthogPolyApproxData::allocate_data(), CombinedSparseGridDriver::assign_smolyak_arrays(), RegressOrthogPolyApproximation::compressed_sensing(), HierarchSparseGridDriver::grid_size(), SharedRegressOrthogPolyApproxData::increment_data(), LightweightSparseGridDriver::initialize_grid(), SharedOrthogPolyApproxData::pre_combine_data(), and SharedPolyApproxData::total_order_terms().
The documentation for this class was generated from the following files:
SharedPolyApproxData.hpp
SharedPolyApproxData.cpp