PECOS: SharedNodalInterpPolyApproxData Class Reference
SharedNodalInterpPolyApproxData Class Reference
Derived approximation class for nodal interpolation polynomials (global approximation interpolating function values and potentially gradients at collocation points).
Public Member Functions
SharedNodalInterpPolyApproxData (short basis_type, size_t num_vars)
lightweight constructor
SharedNodalInterpPolyApproxData (short basis_type, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
full constructor
~SharedNodalInterpPolyApproxData ()
destructor
Public Member Functions inherited from SharedInterpPolyApproxData
SharedInterpPolyApproxData (short basis_type, size_t num_vars)
standard constructor
SharedInterpPolyApproxData (short basis_type, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
alternate constructor
~SharedInterpPolyApproxData ()
destructor
Public Member Functions inherited from SharedPolyApproxData
SharedPolyApproxData ()
default constructor
SharedPolyApproxData (short basis_type, size_t num_vars)
standard constructor
SharedPolyApproxData (short basis_type, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options)
alternate constructor with full configuration options
~SharedPolyApproxData ()
destructorboth
virtual void pre_push_data ()
restores previously popped approximation data
virtual void pre_finalize_data ()
finalizes the shared approximation data following a set of increments
virtual void post_combine_data ()
combines current and stored approximation data
bool push_available ()
test for whether current trial set requires a new approximation increment or can be restored from a previous trial
size_t retrieval_index ()
returns index of the data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex)
size_t finalization_index (size_t i)
returns index of the i-th data set to be restored from within popped bookkeeping (e.g., PolynomialApproximation::poppedLevMultiIndex) during finalization
void configuration_options (const ExpansionConfigOptions &ec_options)
set expConfigOptions as a group (instead of per option below)
void configuration_options (const BasisConfigOptions &bc_options)
set basisConfigOptions (instead of per option below)
const BitArrayULongMap & sobol_index_map () const
return sobolIndexMap
void integration_driver_rep (IntegrationDriver *driver_rep)
set driverRep
void random_variables_key (const BitArray &random_vars_key)
set randomVarsKey
Public Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData ()
default constructor
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars)
standard constructor for envelope
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options, const RegressionConfigOptions &rc_options)
alternate constructor for envelope
SharedBasisApproxData (const SharedBasisApproxData &shared_data)
copy constructor
virtual ~SharedBasisApproxData ()
destructor
SharedBasisApproxData operator= (const SharedBasisApproxData &shared_data)
assignment operator
void assign_rep (SharedBasisApproxData *data_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
SharedBasisApproxData * data_rep () const
returns dataRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
void allocate_data (size_t index=_NPOS)
allocate the shared data prior to building the set of approximations
void allocate_component_sobol ()
allocate sobolIndexMap based on collocation keys
void increment_component_sobol ()
update sobolIndexMap based on a refinement increment
void set_new_point (const RealVector &x, const UShortArray &basis_index, short order)
set point values within 1D basis polynomials for purposes of barycentric precomputation
void set_new_point (const RealVector &x, const UShortArray &basis_index, const SizetList &subset_indices, short order)
set point values within subset of 1D basis polynomials for purposes of barycentric precomputation
size_t barycentric_exact_index (const UShortArray &basis_index)
for an exact point match in all dimensions, return the tensor-product index of the matching point
size_t barycentric_exact_index (const UShortArray &basis_index, const SizetList &subset_indices)
for an exact point match in all dimensions within subset_indices, return the tensor-product index of the matching point
TensorProductDriver * tpq_driver ()
return driverRep cast to requested derived type
CombinedSparseGridDriver * csg_driver ()
return driverRep cast to requested derived type
Protected Member Functions inherited from SharedInterpPolyApproxData
void increment_data (size_t index=_NPOS)
update the shared data prior to rebuilding the set of approximations
void decrement_data ()
decrement the previous increment and store its shared data for later retrieval
void post_push_data ()
restores previously popped approximation data
void post_finalize_data ()
finalizes the shared approximation data following a set of increments
size_t pre_combine_data ()
combines current and stored approximation data
void store_data (size_t index=_NPOS)
stores current approximation data for later combination
void restore_data (size_t index=_NPOS)
restores previously stored approximation data
void remove_stored_data (size_t index=_NPOS)
removes a redundant stored approximation data prior to combination
void clear_stored_data ()
clear stored approximation data
virtual void precompute_keys (const UShortArray &basis_index)
if needed for efficiency, precompute the count and max values for the collocation keys
virtual void precompute_keys (const UShortArray &basis_index, const SizetList &subset_indices)
if needed for efficiency, precompute the count and max values for the collocation keys within the subset
virtual void precompute_max_keys (const UShortArray &basis_index)
if needed for efficiency, precompute the max values for the collocation keys
virtual void precompute_max_keys (const UShortArray &basis_index, const SizetList &subset_indices)
if needed for efficiency, precompute the max values for the collocation keys within the subset
virtual unsigned short tensor_product_num_key (size_t i, unsigned short level_i)
return the number of collocation keys for i^{th} variable and level_i index set
virtual unsigned short tensor_product_max_key (size_t i, unsigned short level_i)
return the maximum collocation key value for i^{th} variable and level_i index set
Real type1_interpolant_value (const RealVector &x, const UShortArray &key, const UShortArray &basis_index)
return value of type 1 interpolation polynomial using all dimensions
Real type1_interpolant_value (const RealVector &x, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return value of type 1 interpolation polynomial using interpolated (non-integrated) dimension subset
Real type1_interpolant_gradient (const RealVector &x, size_t deriv_index, const UShortArray &key, const UShortArray &basis_index)
return gradient of type 1 interpolation polynomial using all dimensions
Real type1_interpolant_gradient (const RealVector &x, size_t deriv_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return gradient of type 1 interpolation polynomial using interpolated (non-integrated) dimension subset
Real type2_interpolant_value (const RealVector &x, size_t interp_index, const UShortArray &key, const UShortArray &basis_index)
return value of type 2 interpolation polynomial using all dimensions
Real type2_interpolant_value (const RealVector &x, size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return value of type 2 interpolation polynomial using interpolated (non-integrated) dimension subset
Real type2_interpolant_gradient (const RealVector &x, size_t deriv_index, size_t interp_index, const UShortArray &key, const UShortArray &basis_index)
return gradient of type 2 interpolation polynomial using all dimensions
Real type2_interpolant_gradient (const RealVector &x, size_t deriv_index, size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return gradient of type 2 interpolation polynomial using interpolated (non-integrated) dimension subset
size_t barycentric_active_variables (const UShortArray &basis_index)
compute the number of variables that are active for barycentric interpolation
size_t barycentric_active_variables (const UShortArray &basis_index, const SizetList &subset_indices)
compute the number of variables within subset_indices that are active for barycentric interpolation
Real barycentric_value_factor (const UShortArray &key, const UShortArray &basis_index)
compute the product of 1D barycentric value factors
Real barycentric_value_factor (const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric value factors
Real barycentric_value_scaling (const UShortArray &basis_index)
compute the product of 1D barycentric weight factor sums for use in the denominator of the barycentric interpolation formula (second form)
Real barycentric_value_scaling (const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric weight factor sums for use in the denominator of the barycentric interpolation formula (second form)
Real barycentric_gradient_factor (size_t deriv_index, const UShortArray &key, const UShortArray &basis_index)
compute the product of 1D barycentric gradient factors
Real barycentric_gradient_factor (size_t deriv_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric gradient factors
Real barycentric_gradient_scaling (const UShortArray &basis_index)
compute the product of 1D barycentric gradient scalings
Real barycentric_gradient_scaling (const UShortArray &basis_index, const SizetList &subset_indices)
compute the product of a subset of 1D barycentric gradient scalings
Real type1_weight (const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return type 1 product weight from integration of type 1 interpolation polynomials using integrated dimension subset
void type1_weight (const UShortArray &key, const UShortArray &basis_index, const BitArray &member_bits, Real &member_t1_wt_prod, Real &nonmember_t1_wt_prod)
return type 1 product weights from integration of type 1 interpolation polynomials for both member and nonmember sets
Real type2_weight (size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const SizetList &subset_indices)
return type 2 product weight from integration of type 1/2 interpolation polynomials using integrated dimension subset
void type2_weight (size_t interp_index, const UShortArray &key, const UShortArray &basis_index, const BitArray &member_bits, Real &member_t2_wt_prod, Real &nonmember_t2_wt_prod)
return type 2 product weight from integration of type 1/2 interpolation polynomials for both member and nonmember sets
Real tensor_product_value (const RealVector &x, const RealVector &exp_t1_coeffs, const RealMatrix &exp_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index)
compute the value of a tensor interpolant on a tensor grid; contributes to value(x)
Real tensor_product_value (const RealVector &x, const RealVector &subset_t1_coeffs, const RealMatrix &subset_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &subset_key, const SizetArray &subset_colloc_index, const SizetList &subset_indices)
compute the value of a tensor interpolant on a tensor grid over a subset of the variables; contributes to value(x)
const RealVector & tensor_product_gradient_basis_variables (const RealVector &x, const RealVector &exp_t1_coeffs, const RealMatrix &exp_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are included in the polynomial basis; contributes to gradient_basis_variables(x)
const RealVector & tensor_product_gradient_basis_variables (const RealVector &x, const RealVector &subset_t1_coeffs, const RealMatrix &subset_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &subset_key, const SizetArray &subset_colloc_index, const SizetList &subset_indices)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are included in the polynomial basis; contributes to gradient_basis_variables(x)
const RealVector & tensor_product_gradient_basis_variables (const RealVector &x, const RealVector &exp_t1_coeffs, const RealMatrix &exp_t2_coeffs, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index, const SizetArray &dvv)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are included in the polynomial basis for given DVV; contributes to gradient_basis_variables(x, dvv)
const RealVector & tensor_product_gradient_nonbasis_variables (const RealVector &x, const RealMatrix &exp_t1_coeff_grads, const UShortArray &basis_index, const UShort2DArray &key, const SizetArray &colloc_index)
compute the gradient of a tensor interpolant on a tensor grid with respect to variables that are not included in the polynomial basis; contributes to gradient_nonbasis_variables(x)
void resize_polynomial_basis (unsigned short max_level)
resize polynomialBasis to accomodate an update in max interpolation level
void resize_polynomial_basis (const UShortArray &lev_index)
resize polynomialBasis to accomodate an update in interpolation levels
void update_tensor_interpolation_basis (const UShortArray &lev_index, const SizetList &subset_indices)
update polynomialBasis for a subset of variables after a change in quadrature order
bool same_basis (unsigned short level, size_t v1, size_t v2)
for a particular level, test for equality between basis v2 and basis v1
Protected Member Functions inherited from SharedPolyApproxData
bool match_random_key (const UShortArray &key_1, const UShortArray &key_2) const
return true if matching key values within random variable subset
bool match_nonrandom_vars (const RealVector &vars_1, const RealVector &vars_2) const
return true if matching variable values within nonrandom variable subset
void allocate_main_sobol ()
allocate sobolIndices and sobolIndexMap for main effects only
void multi_index_to_sobol_index_map (const UShort2DArray &mi)
Define the sobolIndexMap (which defines the set of Sobol' indices) from the incoming multi-index. sobolIndexMap values are initialized to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void reset_sobol_index_map_values ()
return the sobolIndexMap values to interaction orders, prior to updating with multi-index increments in assign_sobol_index_map_values().
void assign_sobol_index_map_values ()
Define the mapping from sobolIndexMap into sobolIndices.
bool push_available (const UShortArray &trial_set)
check for the presence of trial_set within poppedLevMultiIndex
Protected Member Functions inherited from SharedBasisApproxData
SharedBasisApproxData (BaseConstructor, short basis_type, size_t num_vars)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Private Member Functions
void accumulate_barycentric (RealVector &t1_accumulator, const UShortArray &lev_index, const UShortArray &key_p)
update accumulators for barycentric type1 contributions to moment value
void accumulate_horners (RealVector &t1_accumulator, const UShortArray &lev_index, const UShortArray &key_p, const RealVector &x)
update accumulators for type1 contributions to moment value
void accumulate_horners (RealVector &t1_accumulator, RealMatrix &t2_accumulator, const UShortArray &lev_index, const UShortArray &key_p, const RealVector &x)
update accumulators for type1 + type2 contributions to moment value
void accumulate_barycentric_gradient (RealMatrix &t1_accumulator, const UShortArray &lev_index, const UShortArray &key_p, const SizetArray &dvv)
update accumulators for barycentric type1 contributions to moment gradient
void accumulate_horners_gradient (RealMatrix &t1_accumulator, const UShortArray &lev_index, const UShortArray &key_p, const SizetArray &dvv, const RealVector &x)
update accumulators for type1 contributions to moment gradient
void accumulate_horners_gradient (RealMatrix &t1_accumulator, RealMatrixArray &t2_accumulators, const UShortArray &lev_index, const UShortArray &key_p, const SizetArray &dvv, const RealVector &x)
update accumulators for type1 + type2 contributions to moment gradient
void update_nonzero_basis_products (const UShort2DArray &sm_multi_index)
update precomputation of nonzero multidimensional integrals of products of interpolation polynomials
bool basis_product_1d (InterpolationPolynomial *poly_rep_1, InterpolationPolynomial *poly_rep_2, unsigned short key_1, unsigned short key_2, const RealArray &pts, const RealArray &wts, Real &prod)
evaluate 1D integral of product of interpolation polynomials
bool basis_product (const UShortArray &lev_index_1, const UShortArray &key_1, const UShortArray &lev_index_2, const UShortArray &key_2, Real &prod)
lookup multidimensional integral of products of interpolation polynomials
void reinterpolated_level (const UShortArray &lev_index)
computes higher-order grid for tensor reinterpolation of the covariance fn for non-integrated dimensions in all_variables mode
void update_member_key (const UShortArray &data, const SizetList &member_indices, UShortArray &member_map_key, size_t cntr)
create a unique map key for value() and gradient() calculation reuse
Private Attributes
short momentInterpType
type of interpolation for all-variables covariance and variance gradient
IntegrationDriver expMomentIntDriver
special tensor/sparse integration driver for (exactly) computing expansion moments using sufficiently high-order Gaussian quadrature rules on the interpolant
SizetArray nonZerosMapIndices
map from random index to unique nonZerosMapArray
UShortArray nonZerosMapMaxLevels
tracks level maxima already populated within nonZerosMap
std::vector< UShort2DMultiSetRealMap > nonZerosMapArray
expectations of products of interpolation polynomials, precomputed in update_nonzero_basis_products() for efficiency
Friends
class NodalInterpPolyApproximation
Additional Inherited Members
Static Public Member Functions inherited from SharedInterpPolyApproxData
static bool initialize_driver_types_rules (const ShortArray &u_types, const BasisConfigOptions &bc_options, ShortArray &basis_types, ShortArray &colloc_rules)
define n-D basis types and collocation rules based on u_types and basis configuration options for use in configuring integration drivers
static void construct_basis (const ShortArray &u_types, const AleatoryDistParams &adp, const BasisConfigOptions &bc_options, std::vector< BasisPolynomial > &poly_basis)
initialize basis types and collocation rules, construct a vector of basis polynomials for driver usage (not the vector<vector<BasisPolynomial> > used herein), and initialize distribution parameters within this basis
Static Public Member Functions inherited from SharedPolyApproxData
static bool initialize_orthogonal_basis_types_rules (const ShortArray &u_types, const BasisConfigOptions &bc_options, ShortArray &basis_types, ShortArray &colloc_rules)
allocate orthogonal polynomial basis types and integration rules based on u_types and rule options
static bool initialize_orthogonal_basis_type_rule (short u_type, const BasisConfigOptions &bc_options, short &basis_type, short &colloc_rule)
assign orthogonal polynomial basis type and integration rule based on u_type and basis configuration options
static void initialize_polynomial_basis (const ShortArray &basis_types, const ShortArray &colloc_rules, std::vector< BasisPolynomial > &poly_basis)
allocate poly_basis based on basis_types and colloc_rules
static void update_basis_distribution_parameters (const ShortArray &u_types, const AleatoryDistParams &dp, std::vector< BasisPolynomial > &poly_basis)
pass distribution parameters from dp to poly_basis
static size_t total_order_terms (const UShortArray &upper_bound, short lower_bound_offset=-1)
return the number of expansion terms for a total order expansion with the provided (anisotropic) upper_bound array specification
static size_t tensor_product_terms (const UShortArray &order, bool include_upper_bound=true)
return the number of expansion terms for a tensor-product expansion with the provided (anisotropic) quadrature orders (include_upper_bound = false) or expansion orders (default)
static void tensor_product_multi_index (const UShortArray &order, UShort2DArray &multi_index, bool include_upper_bound=true)
initialize expansion multi_index using a tensor-product expansion
static void hierarchical_tensor_product_multi_index (const UShort2DArray &delta_quad, UShort2DArray &multi_index)
initialize multi_index using a hierarchical tensor-product expansion
static void total_order_multi_index (unsigned short level, size_t num_vars, UShort2DArray &multi_index)
initialize multi_index using a total-order expansion from a scalar level
static void total_order_multi_index (const UShortArray &upper_bound, UShort2DArray &multi_index, short lower_bound_offset=-1, size_t max_terms=_NPOS)
initialize expansion multi_index using a total-order expansion from an upper_bound array specification
static void increment_indices (UShortArray &indices, const UShortArray &limits, bool include_upper_bound)
utility function for incrementing a set of multidimensional indices
static void increment_terms (UShortArray &terms, size_t &last_index, size_t &prev_index, size_t term_limit, bool &order_complete)
utility function for incrementing a set of multidimensional terms
Protected Attributes inherited from SharedInterpPolyApproxData
std::vector< std::vector< BasisPolynomial > > polynomialBasis
2D array of one-dimensional basis polynomial objects used in constructing the multivariate orthogonal/interpolation polynomials.
bool barycentricFlag
flag indicating use of barycentric interpolation for global value-based Lagrange interpolation
Protected Attributes inherited from SharedPolyApproxData
IntegrationDriver * driverRep
pointer to integration driver instance
ExpansionConfigOptions expConfigOptions
an encapsulation of expansion configuration options
BasisConfigOptions basisConfigOptions
an encapsulation of basis configuration options
UShortArray quadOrderPrev
previous quadrature order; used for tracking need for expansion form updates
unsigned short ssgLevelPrev
previous Smolyak sparse grid level; used for tracking need for expansion form updates
RealVector ssgAnisoWtsPrev
previous Smolyak sparse grid anisotropic weighting; used for tracking need for expansion form updates
BitArray randomVarsKey
array of bits identifying the random variable subset within the active variables (used in all_variables mode)
SizetList randomIndices
list of indices identifying the random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
SizetList nonRandomIndices
list of indices identifying the non-random variable subset within the active variables (used in all_variables mode; defined from randomVarsKey)
std::deque< UShortArray > poppedLevMultiIndex
popped trial sets that were computed but not selected
BitArrayULongMap sobolIndexMap
mapping to manage different global sensitivity index options (e.g. univariate/main effects only vs all effects)
Protected Attributes inherited from SharedBasisApproxData
short basisType
type of derived instance as well as sub-type for interpolation
size_t numVars
number of variables used in the approximation
Detailed Description
Derived approximation class for nodal interpolation polynomials (global approximation interpolating function values and potentially gradients at collocation points).
The SharedNodalInterpPolyApproxData class provides a global polynomial approximation based on either Lagrange or Hermite interpolation polynomials using a nodal basis approach. It is used primarily for stochastic collocation approaches to uncertainty quantification.
Member Function Documentation
void update_nonzero_basis_products (const UShort2DArray & sm_multi_index) private
update precomputation of nonzero multidimensional integrals of products of interpolation polynomials
Used for pre-computing the expected values of basis polynomial products within the PRODUCT_OF_INTERPOLANTS_FULL option for all_variables covariance.
References SharedNodalInterpPolyApproxData::basis_product(), SharedNodalInterpPolyApproxData::basis_product_1d(), IntegrationDriver::collocation_points_1d(), SharedPolyApproxData::driverRep, InterpolationPolynomial::interpolation_size(), SharedNodalInterpPolyApproxData::nonZerosMapArray, SharedNodalInterpPolyApproxData::nonZerosMapIndices, SharedNodalInterpPolyApproxData::nonZerosMapMaxLevels, SharedBasisApproxData::numVars, SharedInterpPolyApproxData::polynomialBasis, SharedPolyApproxData::randomIndices, SharedInterpPolyApproxData::same_basis(), and IntegrationDriver::type1_collocation_weights_1d().
Referenced by NodalInterpPolyApproximation::covariance(), and SharedNodalInterpPolyApproxData::reinterpolated_level().
void reinterpolated_level (const UShortArray & lev_index) private
computes higher-order grid for tensor reinterpolation of the covariance fn for non-integrated dimensions in all_variables mode
Computes the specifics of a higher order grid for reinterpolating covariance over dimensions that will not be integrated.
References SharedPolyApproxData::driverRep, SharedPolyApproxData::nonRandomIndices, IntegrationDriver::reinterpolated_level_index(), IntegrationDriver::reinterpolated_tensor_grid(), SharedNodalInterpPolyApproxData::update_nonzero_basis_products(), and SharedInterpPolyApproxData::update_tensor_interpolation_basis().
Referenced by SharedNodalInterpPolyApproxData::accumulate_horners_gradient().
The documentation for this class was generated from the following files:
SharedNodalInterpPolyApproxData.hpp
SharedNodalInterpPolyApproxData.cpp