PECOS: SharedBasisApproxData Class Reference
SharedBasisApproxData Class Reference
Base class for multivariate basis approximations used for projection of random variables through time or space.
Public Member Functions
SharedBasisApproxData ()
default constructor
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars)
standard constructor for envelope
SharedBasisApproxData (short basis_type, const UShortArray &approx_order, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options, const RegressionConfigOptions &rc_options)
alternate constructor for envelope
SharedBasisApproxData (const SharedBasisApproxData &shared_data)
copy constructor
virtual ~SharedBasisApproxData ()
destructor
SharedBasisApproxData operator= (const SharedBasisApproxData &shared_data)
assignment operator
void assign_rep (SharedBasisApproxData *data_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
SharedBasisApproxData * data_rep () const
returns dataRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
SharedBasisApproxData (BaseConstructor, short basis_type, size_t num_vars)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
short basisType
type of derived instance as well as sub-type for interpolation
size_t numVars
number of variables used in the approximation
Private Member Functions
SharedBasisApproxData * get_shared_data (short basis_type, const UShortArray &approx_order, size_t num_vars)
used by the standard envelope constructor to initialize dataRep to the appropriate derived type
SharedBasisApproxData * get_shared_data (short basis_type, const UShortArray &approx_order, size_t num_vars, const ExpansionConfigOptions &ec_options, const BasisConfigOptions &bc_options, const RegressionConfigOptions &rc_options)
used by the alternate envelope constructor to initialize dataRep to the appropriate derived type
Private Attributes
SharedBasisApproxData * dataRep
pointer to the letter (initialized only for the envelope)
int referenceCount
number of objects sharing dataRep
Friends
class BasisApproximation
class PolynomialApproximation
class InterpPolyApproximation
class NodalInterpPolyApproximation
class HierarchInterpPolyApproximation
class OrthogPolyApproximation
class ProjectOrthogPolyApproximation
class RegressOrthogPolyApproximation
Detailed Description
Base class for multivariate basis approximations used for projection of random variables through time or space.
The base class for basis approximations defined from Fourier functions, eigenfunctions, or polynomial functions.
Constructor & Destructor Documentation
SharedBasisApproxData ()
default constructor
The default constructor: dataRep is NULL in this case. This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
Referenced by SharedBasisApproxData::get_shared_data().
SharedBasisApproxData (short basis_type, const UShortArray & approx_order, size_t num_vars)
standard constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_shared_data, since SharedBasisApproxData(BaseConstructor) builds the actual base class data for the derived basis functions.
References SharedBasisApproxData::dataRep, and SharedBasisApproxData::get_shared_data().
SharedBasisApproxData (short basis_type, const UShortArray & approx_order, size_t num_vars, const ExpansionConfigOptions & ec_options, const BasisConfigOptions & bc_options, const RegressionConfigOptions & rc_options)
alternate constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_shared_data, since SharedBasisApproxData(BaseConstructor) builds the actual base class data for the derived basis functions.
References SharedBasisApproxData::dataRep, and SharedBasisApproxData::get_shared_data().
SharedBasisApproxData (const SharedBasisApproxData & shared_data)
copy constructor
Copy constructor manages sharing of dataRep and incrementing of referenceCount.
References SharedBasisApproxData::dataRep, SharedBasisApproxData::operator=(), and SharedBasisApproxData::referenceCount.
~SharedBasisApproxData () virtual
destructor
Destructor decrements referenceCount and only deletes dataRep when referenceCount reaches zero.
References SharedBasisApproxData::assign_rep(), SharedBasisApproxData::dataRep, and SharedBasisApproxData::referenceCount.
SharedBasisApproxData (BaseConstructor , short basis_type, size_t num_vars) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor is the one which must build the base class data for all derived classes. get_shared_data() instantiates a derived class letter and the derived constructor selects this base class constructor in its initialization list (to avoid recursion in the base class constructor calling get_shared_data() again). Since the letter IS the representation, its rep pointer is set to NULL (an uninitialized pointer causes problems in ~SharedBasisApproxData).
Member Function Documentation
SharedBasisApproxData operator= (const SharedBasisApproxData & shared_data)
assignment operator
Assignment operator decrements referenceCount for old dataRep, assigns new dataRep, and increments referenceCount for new dataRep.
References SharedBasisApproxData::dataRep, and SharedBasisApproxData::referenceCount.
Referenced by SharedBasisApproxData::SharedBasisApproxData().
SharedBasisApproxData * get_shared_data (short basis_type, const UShortArray & approx_order, size_t num_vars) private
used by the standard envelope constructor to initialize dataRep to the appropriate derived type
Used only by the envelope constructor to initialize dataRep to the appropriate derived type.
References SharedBasisApproxData::SharedBasisApproxData().
Referenced by SharedBasisApproxData::SharedBasisApproxData().
SharedBasisApproxData * get_shared_data (short basis_type, const UShortArray & approx_order, size_t num_vars, const ExpansionConfigOptions & ec_options, const BasisConfigOptions & bc_options, const RegressionConfigOptions & rc_options) private
used by the alternate envelope constructor to initialize dataRep to the appropriate derived type
Used only by the envelope constructor to initialize dataRep to the appropriate derived type.
References SharedBasisApproxData::SharedBasisApproxData().
The documentation for this class was generated from the following files:
SharedBasisApproxData.hpp
SharedBasisApproxData.cpp