PECOS: BasisApproximation Class Reference
BasisApproximation Class Reference
Base class for multivariate basis approximations used for projection of random variables through time or space.
Public Member Functions
BasisApproximation ()
default constructor
BasisApproximation (const SharedBasisApproxData &shared_data)
standard constructor for envelope
BasisApproximation (const BasisApproximation &basis_approx)
copy constructor
virtual ~BasisApproximation ()
destructor
BasisApproximation operator= (const BasisApproximation &basis_approx)
assignment operator
virtual Real value (const RealVector &x)
retrieve the approximate function value for a given parameter vector
virtual const RealVector & gradient (const RealVector &x)
retrieve the approximate function gradient for a given parameter vector
virtual const RealSymMatrix & hessian (const RealVector &x)
retrieve the approximate function Hessian for a given parameter vector
virtual void surrogate_data (const SurrogateData &data)
set PolynomialApproximation::origSurrData
virtual const SurrogateData & surrogate_data () const
get PolynomialApproximation::surrData (const)
virtual SurrogateData & surrogate_data ()
get PolynomialApproximation::surrData (non-const)
virtual int min_coefficients () const
return the minimum number of samples (unknowns) required to build the derived class approximation type in numVars dimensions
virtual void compute_coefficients (size_t index=_NPOS)
calculate the approximation coefficients using a set of surrogate data
virtual void increment_coefficients (size_t index=_NPOS)
recalculate approximation coefficients following a surrogate data update
virtual void decrement_coefficients (bool save_data)
restore the approximation coefficients to the state preceding the last increment
virtual void push_coefficients ()
restore the approximation coefficients to a previously incremented state as identified by the current data increment
virtual void finalize_coefficients ()
finalize the coefficients by applying all previously evaluated increments
virtual void store_coefficients (size_t index=_NPOS)
store the current coefficients for later combination
virtual void restore_coefficients (size_t index=_NPOS)
restore a previously stored coefficient state
virtual void swap_coefficients (size_t index)
swap the current coefficients with a previously stored set
virtual void remove_stored_coefficients (size_t index=_NPOS)
remove a redundant stored entry prior to combine_coefficients (default is pop_back)
virtual void clear_stored ()
clear stored approximation data
virtual void combine_coefficients (size_t swap_index)
combine the current coefficients with a previously stored set
virtual void print_coefficients (std::ostream &s, bool normalized)
print the coefficient array computed in compute_coefficients()
virtual RealVector approximation_coefficients (bool normalized) const
return the coefficient array computed by compute_coefficients()
virtual void approximation_coefficients (const RealVector &approx_coeffs, bool normalized)
set the coefficient array from external sources, rather than computing with compute_coefficients()
virtual void coefficient_labels (std::vector< std::string > &coeff_labels) const
retrieve a vector of coefficient label strings, one per expansion term
void assign_rep (BasisApproximation *approx_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
BasisApproximation * approx_rep () const
returns approxRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
BasisApproximation (BaseConstructor, const SharedBasisApproxData &shared_data)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Protected Attributes
SharedBasisApproxData * sharedDataRep
contains the approximation data that is shared among the response set
Private Member Functions
BasisApproximation * get_basis_approx (const SharedBasisApproxData &shared_data)
Used only by the standard envelope constructor to initialize basisApproxRep to the appropriate derived type.
Private Attributes
BasisApproximation * basisApproxRep
pointer to the letter (initialized only for the envelope)
int referenceCount
number of objects sharing basisApproxRep
Detailed Description
Base class for multivariate basis approximations used for projection of random variables through time or space.
The base class for basis approximations defined from Fourier functions, eigenfunctions, or polynomial functions.
Constructor & Destructor Documentation
BasisApproximation ()
default constructor
The default constructor: basisApproxRep is NULL in this case. This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
BasisApproximation (const SharedBasisApproxData & shared_data)
standard constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_basis_approx, since BasisApproximation(BaseConstructor) builds the actual base class data for the derived basis functions.
References BasisApproximation::basisApproxRep, and BasisApproximation::get_basis_approx().
BasisApproximation (const BasisApproximation & basis_approx)
copy constructor
Copy constructor manages sharing of basisApproxRep and incrementing of referenceCount.
References BasisApproximation::basisApproxRep, BasisApproximation::operator=(), and BasisApproximation::referenceCount.
~BasisApproximation () virtual
destructor
Destructor decrements referenceCount and only deletes basisApproxRep when referenceCount reaches zero.
References BasisApproximation::assign_rep(), BasisApproximation::basisApproxRep, and BasisApproximation::referenceCount.
BasisApproximation (BaseConstructor , const SharedBasisApproxData & shared_data) protected
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
This constructor is the one which must build the base class data for all derived classes. get_basis_approx() instantiates a derived class letter and the derived constructor selects this base class constructor in its initialization list (to avoid recursion in the base class constructor calling get_basis_approx() again). Since the letter IS the representation, its rep pointer is set to NULL (an uninitialized pointer causes problems in ~BasisApproximation).
Member Function Documentation
BasisApproximation operator= (const BasisApproximation & basis_approx)
assignment operator
Assignment operator decrements referenceCount for old basisApproxRep, assigns new basisApproxRep, and increments referenceCount for new basisApproxRep.
References BasisApproximation::basisApproxRep, and BasisApproximation::referenceCount.
Referenced by BasisApproximation::BasisApproximation().
BasisApproximation * get_basis_approx (const SharedBasisApproxData & shared_data) private
Used only by the standard envelope constructor to initialize basisApproxRep to the appropriate derived type.
Used only by the envelope constructor to initialize basisApproxRep to the appropriate derived type.
References SharedBasisApproxData::basisType, and SharedBasisApproxData::data_rep().
Referenced by BasisApproximation::BasisApproximation().
The documentation for this class was generated from the following files:
BasisApproximation.hpp
BasisApproximation.cpp