PECOS: RegressOrthogPolyApproximation Class Reference
RegressOrthogPolyApproximation Class Reference
Derived approximation class for multivariate orthogonal polynomial approximation with coefficient estimation via regression.
Public Member Functions
RegressOrthogPolyApproximation (const SharedBasisApproxData &shared_data)
default constructor
~RegressOrthogPolyApproximation ()
destructor
void build_linear_system (RealMatrix &A, RealMatrix &B, RealMatrix &points)
Build the pce vandermonde matrix A and extract the function (and gradient) data b so that we can solve (possible approximately) Ax=b; also populate the matrix of points corresponding to the random variable sample set.
void build_linear_system (RealMatrix &A, RealMatrix &B, RealMatrix &points, const UShort2DArray &multi_index)
Build the pce vandermonde matrix A and extract the function (and gradient) data b so that we can solve (possible approximately) Ax=b using the provided multi-index; also populate the matrix of points corresponding to the random variable sample set.
void build_linear_system (RealMatrix &A, RealMatrix &B)
Build the pce vandermonde matrix A and extract the function (and gradient) data b so that we can solve (possible approximately) Ax=b.
void build_linear_system (RealMatrix &A, RealMatrix &B, const UShort2DArray &multi_index)
Build the pce vandermonde matrix A and extract the function (and gradient) data b so that we can solve (possible approximately) Ax=b using the provided multi-index.
void build_linear_system (RealMatrix &A)
Build the pce vandermonde matrix A used in solving the system Ax=b.
void build_linear_system (RealMatrix &A, const UShort2DArray &multi_index)
Build the pce vandermonde matrix A used in solving the system Ax=b using the provided multi-index.
void augment_linear_system (const RealVectorArray &samples, RealMatrix &A, const UShort2DArray &multi_index)
augment a Vandermonde matrix with additional sample points for a fixed multi-index
Public Member Functions inherited from OrthogPolyApproximation
OrthogPolyApproximation (const SharedBasisApproxData &shared_data)
default constructor
~OrthogPolyApproximation ()
destructor
void basis_matrix (const RealMatrix &x, RealMatrix &basis_values)
Public Member Functions inherited from PolynomialApproximation
PolynomialApproximation (const SharedBasisApproxData &shared_data)
standard constructor
~PolynomialApproximation ()
destructorboth
virtual void allocate_component_sobol ()
size component Sobol arrays
virtual Real delta_covariance (PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions, treating all variables as random
virtual Real delta_covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)
return the change in covariance between two response expansions for a given parameter vector, treating a subset of the variables as random
virtual Real delta_mean ()
return the change in mean between two response expansions, treating all variables as random
virtual Real delta_mean (const RealVector &x)
return the change in mean between two response expansions, treating a subset of the variables as random
virtual Real delta_std_deviation ()
return the change in standard deviation between two response expansions, treating all variables as random
virtual Real delta_std_deviation (const RealVector &x)
return the change in standard deviation between two response expansions, treating a subset of the variables as random
virtual Real delta_beta (bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating all variables as random
virtual Real delta_beta (const RealVector &x, bool cdf_flag, Real z_bar)
return the change in reliability index (mapped from z_bar) between two response expansions, treating a subset of the variables as random
virtual Real delta_z (bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating all variables as random
virtual Real delta_z (const RealVector &x, bool cdf_flag, Real beta_bar)
return the change in response level (mapped from beta_bar) between two response expansions, treating a subset of the variables as random
bool deep_copied_surrogate_data () const
returns true if surrData is a deep copy of origSurrData
const RealVector & expansion_moments () const
return expansionMoments
const RealVector & numerical_integration_moments () const
return numericalMoments
const RealVector & moments () const
return preferred response moments (either expansion or numerical integration, depending on approximation type)
void standardize_moments (const RealVector &central_moments, RealVector &std_moments)
standardize central moments 2-n and eliminate excess kurtosis
void expansion_coefficient_flag (bool coeff_flag)
set ExpansionConfigOptions::expansionCoeffFlag
bool expansion_coefficient_flag () const
get ExpansionConfigOptions::expansionCoeffFlag
void expansion_coefficient_gradient_flag (bool grad_flag)
set ExpansionConfigOptions::expansionCoeffGradFlag
bool expansion_coefficient_gradient_flag () const
get ExpansionConfigOptions::expansionCoeffGradFlag
const RealVector & sobol_indices () const
return sobolIndices
const RealVector & total_sobol_indices () const
return totalSobolIndices
Public Member Functions inherited from BasisApproximation
BasisApproximation ()
default constructor
BasisApproximation (const SharedBasisApproxData &shared_data)
standard constructor for envelope
BasisApproximation (const BasisApproximation &basis_approx)
copy constructor
virtual ~BasisApproximation ()
destructor
BasisApproximation operator= (const BasisApproximation &basis_approx)
assignment operator
virtual void decrement_coefficients (bool save_data)
restore the approximation coefficients to the state preceding the last increment
virtual void push_coefficients ()
restore the approximation coefficients to a previously incremented state as identified by the current data increment
virtual void finalize_coefficients ()
finalize the coefficients by applying all previously evaluated increments
void assign_rep (BasisApproximation *approx_rep, bool ref_count_incr)
assign letter or replace existing letter with a new one
BasisApproximation * approx_rep () const
returns approxRep for access to derived class member functions that are not mapped to the top Approximation level
Protected Member Functions
int min_coefficients () const
return the minimum number of samples (unknowns) required to build the derived class approximation type in numVars dimensions
void compute_coefficients (size_t index=_NPOS)
calculate the approximation coefficients using a set of surrogate data
void increment_coefficients (size_t index=_NPOS)
recalculate approximation coefficients following a surrogate data update
void store_coefficients (size_t index=_NPOS)
store the current coefficients for later combination
void restore_coefficients (size_t index=_NPOS)
restore a previously stored coefficient state
void swap_coefficients (size_t index)
swap the current coefficients with a previously stored set
void remove_stored_coefficients (size_t index=_NPOS)
remove a redundant stored entry prior to combine_coefficients (default is pop_back)
void combine_coefficients (size_t swap_index)
combine the current coefficients with a previously stored set
void allocate_arrays ()
initialize multiIndex, expansionCoeffs, et al.
size_t expansion_terms () const
retrieve number of terms in the orthogonal polynomial expansion
const RealVector & dimension_decay_rates ()
estimate chaos expansion coefficient decay rates for each random variable dimension using linear least squares in semilog space
Real value (const RealVector &x)
retrieve the approximate function value for a given parameter vector
const RealVector & gradient_basis_variables (const RealVector &x)
retrieve the gradient for a response expansion with respect to all variables included in the polynomial bases using the given parameter vector and default DVV
const RealVector & gradient_basis_variables (const RealVector &x, const SizetArray &dvv)
retrieve the gradient for a response expansion with respect to variables included in the polynomial basis for a given parameter vector and a given DVV subset
const RealVector & gradient_nonbasis_variables (const RealVector &x)
retrieve the gradient for a response expansion with respect to all variables not included in the polynomial bases (nonprobabilistic variables such as design or epistemic when not in "all" mode) using the given parameter vector and default DVV
const RealSymMatrix & hessian_basis_variables (const RealVector &x)
retrieve the Hessian of the response expansion with respect to all variables included in the polynomial basis (e.g., probabilistic variables) for a given parameter vector
Real stored_value (const RealVector &x, size_t index)
retrieve the response value for a stored expansion using the given parameter vector
const RealVector & stored_gradient_basis_variables (const RealVector &x, size_t index)
retrieve the response gradient for a stored expansion with respect to all variables included in the polynomial bases; evaluate for the given parameter vector.
const RealVector & stored_gradient_nonbasis_variables (const RealVector &x, size_t index)
retrieve the response gradient for a stored expansion with respect to all variables not included in the polynomial bases; evaluate for the given parameter vector.
Real mean (const RealVector &x)
const RealVector & mean_gradient (const RealVector &x, const SizetArray &dvv)
Real covariance (PolynomialApproximation *poly_approx_2)
return the covariance between two response expansions, treating all variables as random
Real covariance (const RealVector &x, PolynomialApproximation *poly_approx_2)
return the covariance between two response expansions for a given parameter vector, treating a subset of the variables as random
const RealVector & variance_gradient ()
const RealVector & variance_gradient (const RealVector &x, const SizetArray &dvv)
void compute_component_sobol ()
Performs global sensitivity analysis via variance-based decomposition; computes component (main and interaction) Sobol' indices.
void compute_total_sobol ()
Performs global sensitivity analysis via variance-based decomposition; computes total Sobol' indices.
ULongULongMap sparse_sobol_index_map () const
return RegressOrthogPolyApproximation::sparseSobolIndexMap
RealVector approximation_coefficients (bool normalized) const
retrieve or form a set of dense coefficients that correspond to SharedOrthogPolyApproxData::multiIndex
void approximation_coefficients (const RealVector &approx_coeffs, bool normalized)
set an array of dense coefficients corresponding to SharedOrthogPolyApproxData::multiIndex
void print_coefficients (std::ostream &s, bool normalized)
print the coefficient array computed in compute_coefficients()
void coefficient_labels (std::vector< std::string > &all_coeff_tags) const
retrieve a vector of coefficient label strings, one per expansion term
Protected Member Functions inherited from OrthogPolyApproximation
void clear_stored ()
clear stored approximation data
Real mean ()
const RealVector & mean_gradient ()
Real variance ()
Real variance (const RealVector &x)
void compute_moments (bool full_stats=true)
compute expansion moments to order 2
void compute_moments (const RealVector &x, bool full_stats=true)
compute expansion moments in all-variables mode to order 2
void size_expansion ()
size expansion{Coeffs,CoeffGrads} based on multiIndex
void size_expansion (size_t num_exp_terms)
size expansion{Coeffs,CoeffGrads} based on multiIndex
void resize_expansion ()
synchronize expansion{Coeffs,CoeffGrads} with an updated multiIndex
void resize_expansion (size_t num_exp_terms)
synchronize expansion{Coeffs,CoeffGrads} with an updated multiIndex
void overlay_expansion (const SizetArray &multi_index_map, const RealVector &exp_coeffs, const RealMatrix &exp_grads, int coeff)
overlay the passed expansion with the aggregate expansion{Coeffs,CoeffGrads} as managed by the multi_index_map
void multiply_expansion (const UShort2DArray &multi_index_b, const RealVector &exp_coeffs_b, const RealMatrix &exp_grads_b, const UShort2DArray &multi_index_c)
multiply current expansion ("a") with incoming expansion ("b") and store in product expansion ("c")
void fail_booleans (SizetShortMap::const_iterator &fit, size_t j, bool &add_val, bool &add_grad)
update add_val and add_gradient based on surrData's failure map
void integration_checks ()
perform sanity checks prior to numerical integration
void solve_decay_rates (RealVectorArray &A_vectors, RealVectorArray &b_vectors, UShortArray &max_orders)
utility function for solving the least squares estimation of decay rates
Protected Member Functions inherited from PolynomialApproximation
void surrogate_data (const SurrogateData &data)
set PolynomialApproximation::origSurrData
const SurrogateData & surrogate_data () const
get PolynomialApproximation::surrData (const)
SurrogateData & surrogate_data ()
get PolynomialApproximation::surrData (non-const)
const RealVector & gradient (const RealVector &x)
generic base class function mapped to gradient_basis_variables(x)
const RealSymMatrix & hessian (const RealVector &x)
generic base class function mapped to hessian_basis_variables(x)
void synchronize_surrogate_data (size_t index)
update surrData from origSurrData based on deep or shallow copy
void response_data_to_surplus_data (size_t index)
modify origSurrData to create hierarchical surplus response data within surrData
void integrate_moments (const RealVector &coeffs, const RealVector &t1_wts, RealVector &moments)
compute central moments of response using type1 numerical integration
void integrate_moments (const RealVector &t1_coeffs, const RealMatrix &t2_coeffs, const RealVector &t1_wts, const RealMatrix &t2_wts, RealVector &moments)
compute central moments of response using type1/2 numerical integration
void allocate_total_sobol ()
size total Sobol arrays
Protected Member Functions inherited from BasisApproximation
BasisApproximation (BaseConstructor, const SharedBasisApproxData &shared_data)
constructor initializes the base class part of letter classes (BaseConstructor overloading avoids infinite recursion in the derived class constructors - Coplien, p. 139)
Private Member Functions
void set_fault_info ()
set the information needed to ensure fault tolerance
void select_solver (bool cv_active)
selects the solver for L1 or L2 minimization based on user input
void run_regression ()
Run the regression method set in select_solver() to compute the expansion coefficients using L1 or L2 minimization.
void adapt_regression ()
perform an adaptive selection of candidate basis for fixed data, employing a generalized sparse grid to define the candidate basis index sets
Real select_best_active_multi_index ()
from among the active index sets, select the candidate refinement that provides the greatest reduction in cross-validation error
Real select_best_basis_expansion ()
from among the candidate basis expansions, select the option that provides the greatest reduction in cross-validation error
Real run_cross_validation_solver (const UShort2DArray &multi_index, RealVector &exp_coeffs, SizetSet &sparse_indices)
Use cross validation to choose solver hyper-parameters when solving the linear system Ax=b. e.g. if the linear solver has an epsilon tolerance internally select the best epsilon and return the corresponding solution.
Real run_cross_validation_expansion ()
Use cross validation to find the hyper-parameters of the polynomial chaos expansion. e.g. find the 'best' total degree basis.
void compressed_sensing (RealMatrix &A, RealMatrix &B)
encapsulate usage of CSTool.solve() and bookkeeping of its sparse solution
void estimate_compressed_sensing_options_via_cross_validation (RealMatrix &vandermonde_matrix, RealMatrix &rhs, std::vector< CompressedSensingOptions > &best_cs_opts, RealVector &best_predictor_indicators, RealMatrixArray &predictor_options_history, RealMatrixArray &predictor_indicators_history, RealMatrixArray &predictor_partition_indicators_history, size_t num_data_pts_fn)
For a specific vandermonde matrix find the compressed sennsing.
void update_sparse (Real *dense_coeffs, size_t num_dense_terms)
define multiIndex and expansionCoeffs from nonzero dense_coeffs
void update_sparse_indices (Real *dense_coeffs, size_t num_dense_terms, SizetSet &sparse_indices)
augment sparse_indices based on nonzero dense_coeffs
void update_sparse_coeffs (Real *dense_coeffs, RealVector &exp_coeffs, const SizetSet &sparse_indices)
define sparse expansionCoeffs from dense_coeffs and sparse_indices
void update_sparse_coeff_grads (Real *dense_coeffs, int row, RealMatrix &exp_coeff_grads, const SizetSet &sparse_indices)
define a row of sparse expansionCoeffGrads from dense_coeffs and sparse_indices
void update_sparse_sobol (const SizetSet &sparse_indices, const UShort2DArray &shared_multi_index, const BitArrayULongMap &shared_sobol_map)
define sparseSobolIndexMap from sparseIndices, shared multi_index, and shared sobolIndexMap
void sparse_restriction (UShort2DArray &multi_index, SizetSet &sparse_indices)
Perform restriction from dense arrays + sparse_indices key into packed arrays without key.
void frontier_restriction (UShort2DArray &multi_index, SizetSet &sparse_indices)
Perform restriction from original multi_index by defining a Pareto frontier of recovered terms and then pruning multi_index back to a complete set (no gaps) within this Pareto frontier.
void advance_multi_index (const UShort2DArray &multi_index, UShortArraySetArray &mi_advancements)
perform SharedOrthogPolyApproxData::numAdvancements expansions of multi_index to create the candidates array
void advance_multi_index_front (const UShort2DArray &multi_index, UShortArraySetArray &mi_advancements)
perform SharedOrthogPolyApproxData::numAdvancements expansions of multi_index to create the candidates array
void add_admissible_forward_neighbors (const UShort2DArray &reference_mi, UShortArraySet &fwd_neighbors)
generate a set of admissible forward neighbors from a reference multi-index (non-frontier version)
void add_admissible_forward_neighbors (const UShortArraySet &reference_mi, UShortArraySet &fwd_neighbors)
generate a set of admissible forward neighbors from a reference multi-index (frontier version)
void define_frontier (const UShort2DArray &multi_index, UShortArraySet &combined_pareto)
define a multi-index frontier from the incoming multi_index. This differs from a Pareto frontier in that the definition of dominated is relaxed (must not be < another term in all dimensions, but can be equal).
void define_frontier (const UShortArray &mi_i, UShortArraySet &combined_pareto)
update a multi-index frontier from an incoming multi_index term. This differs from a Pareto frontier in that the definition of dominated is relaxed (must not be < another term in all dimensions, but can be equal).
void inflate (SizetSet &sparse_ind, size_t num_terms)
define a default definition for sparse_ind: 0 to num_terms-1
void overlay_expansion (const SizetSet &sparse_ind_2, const SizetArray &append_mi_map, const RealVector &exp_coeffs_2, const RealMatrix &exp_grads_2, int coeff_2)
overlay the passed expansion with the aggregate expansion{Coeffs,CoeffGrads} as managed by the multi_index_map
void multiply_expansion (const SizetSet &sparse_ind_b, const UShort2DArray &multi_index_b, const RealVector &exp_coeffs_b, const RealMatrix &exp_grads_b, const UShort2DArray &multi_index_c)
multiply current expansion ("a") with incoming expansion ("b") and store in product expansion ("c")
void gridSearchFunction (RealMatrix &opts, int M, int N, int num_function_samples)
Define the set of options used in the cross validation grid search.
void least_interpolation (RealMatrix &pts, RealMatrix &vals)
void transform_least_interpolant (RealMatrix &L, RealMatrix &U, RealMatrix &H, IntVector &p, RealMatrix &vals)
void least_factorization (RealMatrix &x, UShort2DArray &basis_indices, RealMatrix &l, RealMatrix &u, RealMatrix &H, IntVector &p, IntVector &k)
void get_least_polynomial_coefficients (RealVector &v, IntVector &k, UShort2DArray &basis_indices, int num_dims, int num_pts, RealMatrix &H)
Private Attributes
IntVector bestApproxOrder
order of orthogonal best polynomial expansion found using cross validation
CompressedSensingOptions CSOpts
Stuct use to define the options of a compressed sensing solve.
FaultInfo faultInfo
store the fault info about the response data
bool sparseSoln
tracks use of sparse solvers, indicated the need to employ sparseIndices and sparseSobolIndexMap
SizetSet sparseIndices
tracks sparse terms within multiIndex and expansion{Coeffs,CoeffGrads} that are retained from an original candidate set
SizetSetArray storedSparseIndices
copy of sparseIndices stored in store_coefficients() for use in combine_coefficients()
ULongULongMap sparseSobolIndexMap
maps shared index from sobolIndexMap values to sparse index into sparse sobolIndices
UShort2DArray adaptedMultiIndex
PCE multi-index during the basis adaptation process. Once complete, the shared multiIndex and sparseIndices are updated.
SizetSet adaptedSparseIndices
sparse indices identifying recovered expansion coefficients within adaptedMultiIndex during the basis adaptation process. Once complete, the shared multiIndex and sparseIndices are updated.
UShort2DArray bestAdaptedMultiIndex
the adapted multi-index that corresponds to the best solution identified Due to frontier/sparse restriction operations, bestAdaptedMultiIndex cannot be assumed to be a subset of adaptedMultiIndex.
Real cvErrorRef
the cross validation error reference point for adapting a CS candidate basis; it's state is reset for each response QoI
Additional Inherited Members
Static Public Member Functions inherited from OrthogPolyApproximation
static void basis_value (const RealVector &x, std::vector< BasisPolynomial > &polynomial_basis, const UShort2DArray &multi_index, RealVector &basis_values)
evaluate all pce basis functions at a single point
static void basis_matrix (const RealMatrix &x, std::vector< BasisPolynomial > &polynomial_basis, const UShort2DArray &multi_index, RealMatrix &basis_values)
evaluate all pce basis functions at a set of points
Protected Attributes inherited from OrthogPolyApproximation
RealVector expansionCoeffs
the coefficients of the expansion
RealMatrix expansionCoeffGrads
the gradients of the expansion coefficients
RealVectorArray storedExpCoeffs
copies of expansionCoeffs stored in store_coefficients() for use in combine_coefficients()
RealMatrixArray storedExpCoeffGrads
copies of expansionCoeffGrads stored in store_coefficients() for use in combine_coefficients()
RealVector decayRates
spectral coefficient decay rates estimated by LLS on log of univariate expansion coefficients
Protected Attributes inherited from PolynomialApproximation
SurrogateData origSurrData
SurrogateData instance containing the variables (shared) and response (unique) data arrays for constructing a surrogate of a single response function; this is the original unmodified data set, prior to any potential manipulations by the approximation classes.
SurrogateData surrData
SurrogateData instance used in current approximation builds, potentially reflecting data modifications relative to origSurrData.
bool expansionCoeffFlag
flag for calculation of expansion coefficients from response values
bool expansionCoeffGradFlag
flag for calculation of gradients of expansion coefficients from response gradients
RealVector expansionMoments
mean and central moments 2/3/4 computed from the stochastic expansion form. For OrthogPolyApproximation, these are primary, and for InterpPolyApproximation, they are secondary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector numericalMoments
mean and central moments 2/3/4 computed via numerical integration of the response. For OrthogPolyApproximation, these are secondary, and for InterpPolyApproximation, they are primary. Conversions to standardized moments (std deviation, skewness, kurtosis) are performed elsewhere.
RealVector approxGradient
gradient of the polynomial approximation returned by gradient()
RealSymMatrix approxHessian
Hessian of the polynomial approximation returned by hessian()
RealVector meanGradient
gradient of the primary mean (expansion mean for OrthogPoly, numerical integration mean for InterpPoly)
RealVector varianceGradient
gradient of the primary variance (expansion variance for OrthogPoly, numerical integration variance for InterpPoly)
short computedMean
track computation of mean and mean gradient to avoid unnecessary recomputation
short computedVariance
track computation of variance and variance gradient to avoid unnecessary recomputation
RealVector xPrevMean
track previous evaluation point for all_variables mean to avoid unnecessary recomputation
RealVector xPrevMeanGrad
track previous evaluation point for all_variables mean gradient to avoid unnecessary recomputation
RealVector xPrevVar
track previous evaluation point for all_variables variance to avoid unnecessary recomputation
RealVector xPrevVarGrad
track previous evaluation point for all_variables variance gradient to avoid unnecessary recomputation
RealVector sobolIndices
global sensitivities as given by Sobol'
RealVector totalSobolIndices
total global sensitivities as given by Sobol'
Protected Attributes inherited from BasisApproximation
SharedBasisApproxData * sharedDataRep
contains the approximation data that is shared among the response set
Detailed Description
Derived approximation class for multivariate orthogonal polynomial approximation with coefficient estimation via regression.
The RegressOrthogPolyApproximation class provides a global approximation based on multivariate orthogonal polynomials, where the coefficients are computed using regression approaches such as least squares (L2) or compressed sensing (L1). It is used primarily for polynomial chaos expansion aproaches to UQ.
Member Function Documentation
size_t expansion_terms () const inline protected virtual
retrieve number of terms in the orthogonal polynomial expansion
default implementation if no sparsity (overridden in RegressOrthogPolyApproximation for CS)
Reimplemented from OrthogPolyApproximation.
References OrthogPolyApproximation::expansion_terms(), and RegressOrthogPolyApproximation::sparseIndices.
Real mean (const RealVector & x) protected virtual
In this case, a subset of the expansion variables are random variables and the mean of the expansion involves evaluating the expectation over this subset.
Reimplemented from OrthogPolyApproximation.
References PolynomialApproximation::computedMean, PolynomialApproximation::expansionCoeffFlag, OrthogPolyApproximation::expansionCoeffs, PolynomialApproximation::expansionMoments, SharedPolyApproxData::match_nonrandom_vars(), OrthogPolyApproximation::mean(), OrthogPolyApproximation::mean_gradient(), SharedOrthogPolyApproxData::multiIndex, SharedOrthogPolyApproxData::multivariate_polynomial(), SharedPolyApproxData::nonRandomIndices, BasisApproximation::sharedDataRep, RegressOrthogPolyApproximation::sparseIndices, PolynomialApproximation::xPrevMean, and SharedOrthogPolyApproxData::zero_random().
const RealVector & mean_gradient (const RealVector & x, const SizetArray & dvv) protected virtual
In this function, a subset of the expansion variables are random variables and any augmented design/state variables (i.e., not inserted as random variable distribution parameters) are included in the expansion. In this case, the mean of the expansion is the expectation over the random subset and the derivative of the mean is the derivative of the remaining expansion over the non-random subset. This function must handle the mixed case, where some design/state variables are augmented (and are part of the expansion: derivatives are evaluated as described above) and some are inserted (derivatives are obtained from expansionCoeffGrads).
Reimplemented from OrthogPolyApproximation.
References PolynomialApproximation::computedMean, RegressOrthogPolyApproximation::covariance(), PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, OrthogPolyApproximation::expansionCoeffGrads, OrthogPolyApproximation::expansionCoeffs, SharedPolyApproxData::match_nonrandom_vars(), OrthogPolyApproximation::mean_gradient(), PolynomialApproximation::meanGradient, SharedOrthogPolyApproxData::multiIndex, SharedPolyApproxData::nonRandomIndices, SharedPolyApproxData::randomVarsKey, BasisApproximation::sharedDataRep, RegressOrthogPolyApproximation::sparseIndices, PolynomialApproximation::xPrevMeanGrad, and SharedOrthogPolyApproxData::zero_random().
const RealVector & variance_gradient () protected virtual
In this function, all expansion variables are random variables and any design/state variables are omitted from the expansion. The mixed derivative case (some design variables are inserted and some are augmented) requires no special treatment.
Reimplemented from OrthogPolyApproximation.
References PolynomialApproximation::computedVariance, PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, OrthogPolyApproximation::expansionCoeffGrads, OrthogPolyApproximation::expansionCoeffs, SharedOrthogPolyApproxData::multiIndex, SharedPolyApproxData::nonRandomIndices, SharedOrthogPolyApproxData::norm_squared(), BasisApproximation::sharedDataRep, RegressOrthogPolyApproximation::sparseIndices, OrthogPolyApproximation::variance_gradient(), and PolynomialApproximation::varianceGradient.
const RealVector & variance_gradient (const RealVector & x, const SizetArray & dvv) protected virtual
In this function, a subset of the expansion variables are random variables and any augmented design/state variables (i.e., not inserted as random variable distribution parameters) are included in the expansion. This function must handle the mixed case, where some design/state variables are augmented (and are part of the expansion) and some are inserted (derivatives are obtained from expansionCoeffGrads).
Reimplemented from OrthogPolyApproximation.
References PolynomialApproximation::computedVariance, PolynomialApproximation::expansionCoeffFlag, PolynomialApproximation::expansionCoeffGradFlag, OrthogPolyApproximation::expansionCoeffGrads, OrthogPolyApproximation::expansionCoeffs, SharedPolyApproxData::match_nonrandom_vars(), SharedPolyApproxData::match_random_key(), SharedOrthogPolyApproxData::multiIndex, SharedOrthogPolyApproxData::multivariate_polynomial(), SharedOrthogPolyApproxData::multivariate_polynomial_gradient(), SharedPolyApproxData::nonRandomIndices, SharedOrthogPolyApproxData::norm_squared(), SharedPolyApproxData::randomIndices, SharedPolyApproxData::randomVarsKey, BasisApproximation::sharedDataRep, RegressOrthogPolyApproximation::sparseIndices, OrthogPolyApproximation::variance_gradient(), PolynomialApproximation::varianceGradient, PolynomialApproximation::xPrevVarGrad, and SharedOrthogPolyApproxData::zero_random().
void select_solver (bool cv_active) private
selects the solver for L1 or L2 minimization based on user input
In this case, regression is used in place of spectral projection. That is, instead of calculating the PCE coefficients using inner products, linear least squares is used to estimate the PCE coefficients which best match a set of response samples. The least squares estimation is performed using DGELSS (SVD) or DGGLSE (equality-constrained) from LAPACK, based on anchor point and derivative data availability.
References SharedPolyApproxData::basisConfigOptions, ExpansionConfigOptions::convergenceTol, RegressOrthogPolyApproximation::CSOpts, CompressedSensingOptions::delta, CompressedSensingOptions::epsilon, ExpansionConfigOptions::expCoeffsSolnApproach, SharedPolyApproxData::expConfigOptions, RegressOrthogPolyApproximation::faultInfo, RegressionConfigOptions::l2Penalty, CompressedSensingOptions::maxNumIterations, ExpansionConfigOptions::maxSolverIterations, SharedOrthogPolyApproxData::multiIndex, RegressionConfigOptions::noiseTols, CompressedSensingOptions::numFunctionSamples, ExpansionConfigOptions::outputLevel, SharedRegressOrthogPolyApproxData::regressConfigOptions, BasisApproximation::sharedDataRep, CompressedSensingOptions::solver, CompressedSensingOptions::solverTolerance, RegressOrthogPolyApproximation::sparseSoln, PolynomialApproximation::surrData, BasisConfigOptions::useDerivs, and CompressedSensingOptions::verbosity.
Referenced by RegressOrthogPolyApproximation::compute_coefficients(), RegressOrthogPolyApproximation::run_cross_validation_expansion(), and RegressOrthogPolyApproximation::run_cross_validation_solver().
void sparse_restriction (UShort2DArray & multi_index, SizetSet & sparse_indices) private
Perform restriction from dense arrays + sparse_indices key into packed arrays without key.
This version clears out all terms not recovered in CS and may leave multi-index gaps.
References RegressOrthogPolyApproximation::frontier_restriction().
Referenced by RegressOrthogPolyApproximation::select_best_basis_expansion(), and RegressOrthogPolyApproximation::update_sparse_sobol().
void frontier_restriction (UShort2DArray & multi_index, SizetSet & sparse_indices) private
Perform restriction from original multi_index by defining a Pareto frontier of recovered terms and then pruning multi_index back to a complete set (no gaps) within this Pareto frontier.
This version clears out only the dominated multi-index terms not recovered in CS to avoid multi-index gaps; it provides a frontier with all supporting terms.
References RegressOrthogPolyApproximation::advance_multi_index(), SharedOrthogPolyApproxData::assess_dominance(), BasisApproximation::sharedDataRep, and SharedOrthogPolyApproxData::update_pareto_set().
Referenced by RegressOrthogPolyApproximation::select_best_basis_expansion(), and RegressOrthogPolyApproximation::sparse_restriction().
void gridSearchFunction (RealMatrix & opts, int M, int N, int num_function_samples) private
Define the set of options used in the cross validation grid search.
Parameters
opts (output) the options to be used in the grid search
M The number of rows of the vandermonde matrix
N The number of columns of the vandermonde matrix
References Pecos::cartesian_product(), RegressOrthogPolyApproximation::CSOpts, CompressedSensingOptions::delta, RegressOrthogPolyApproximation::estimate_compressed_sensing_options_via_cross_validation(), SharedPolyApproxData::expConfigOptions, CompressedSensingOptions::maxNumIterations, RegressionConfigOptions::noiseTols, ExpansionConfigOptions::outputLevel, SharedRegressOrthogPolyApproxData::regressConfigOptions, BasisApproximation::sharedDataRep, CompressedSensingOptions::solver, and CompressedSensingOptions::solverTolerance.
Member Data Documentation
SizetSet sparseIndices private
tracks sparse terms within multiIndex and expansion{Coeffs,CoeffGrads} that are retained from an original candidate set
a set is used to manage unique indices among expansionCoeff{s,Grads}. Sorting also simplifies covariance calculations, but care must be exercised to retain synchronization with expansionCoeff{s,Grads} ordering when merging sparse multi-indices.
Referenced by RegressOrthogPolyApproximation::adapt_regression(), RegressOrthogPolyApproximation::approximation_coefficients(), RegressOrthogPolyApproximation::coefficient_labels(), RegressOrthogPolyApproximation::combine_coefficients(), RegressOrthogPolyApproximation::compressed_sensing(), RegressOrthogPolyApproximation::compute_component_sobol(), RegressOrthogPolyApproximation::compute_total_sobol(), RegressOrthogPolyApproximation::covariance(), RegressOrthogPolyApproximation::dimension_decay_rates(), RegressOrthogPolyApproximation::expansion_terms(), RegressOrthogPolyApproximation::gradient_basis_variables(), RegressOrthogPolyApproximation::gradient_nonbasis_variables(), RegressOrthogPolyApproximation::hessian_basis_variables(), RegressOrthogPolyApproximation::mean(), RegressOrthogPolyApproximation::mean_gradient(), RegressOrthogPolyApproximation::multiply_expansion(), RegressOrthogPolyApproximation::overlay_expansion(), RegressOrthogPolyApproximation::print_coefficients(), RegressOrthogPolyApproximation::restore_coefficients(), RegressOrthogPolyApproximation::run_cross_validation_expansion(), RegressOrthogPolyApproximation::select_best_active_multi_index(), RegressOrthogPolyApproximation::select_best_basis_expansion(), RegressOrthogPolyApproximation::store_coefficients(), RegressOrthogPolyApproximation::swap_coefficients(), RegressOrthogPolyApproximation::update_sparse(), RegressOrthogPolyApproximation::value(), and RegressOrthogPolyApproximation::variance_gradient().
The documentation for this class was generated from the following files:
RegressOrthogPolyApproximation.hpp
RegressOrthogPolyApproximation.cpp