PECOS: DensityEstimator Class Reference
DensityEstimator Class Reference
Base class for density estimation strategies.
Public Member Functions
DensityEstimator ()
default constructor
DensityEstimator (const String &density_estimator_type)
standard constructor for envelope
DensityEstimator (const DensityEstimator &density_estimator)
copy constructor
virtual ~DensityEstimator ()
destructor
DensityEstimator operator= (const DensityEstimator &density_estimator)
assignment operator
virtual void initialize (RealMatrix &samples, Teuchos::ETransp trans=Teuchos::NO_TRANS)
initialize the densities
virtual void initialize (RealVectorArray &samples)
virtual size_t getDim ()
get the dimensionality
virtual Real mean ()
mean
virtual Real variance ()
variance
virtual Real std_deviation ()
standard deviation
virtual void cov (RealMatrix &cov)
computes the covariance matrix
virtual void corrcoeff (RealMatrix &corr)
computes the correlation matrix
virtual Real pdf (const RealVector &x) const
operations for one sample
virtual void pdf (const RealMatrix &data, RealVector &res, Teuchos::ETransp trans=Teuchos::NO_TRANS) const
operations for a set of samples
virtual void marginalize (size_t dim, DensityEstimator &estimator)
marginalization operations
virtual void margToDimXs (const IntVector &dims, DensityEstimator &estimator)
creates a maginalized density with remaining dims
virtual void margToDimX (size_t dim, DensityEstimator &estimator)
creates a maginalized density with one remaining dimension
virtual void conditionalize (const RealVector &x, const IntVector &dims, DensityEstimator &estimator)
conditionalization operations
virtual void condToDimX (const RealVector &x, size_t dim, DensityEstimator &estimator)
String getType ()
DensityEstimator * getEnvelope ()
bool is_null ()
Protected Attributes
String density_estimator_type
Static Private Member Functions
static DensityEstimator * get_density_estimator (const String &density_estimator_type)
Private Attributes
DensityEstimator * densityEstimator
int referenceCount
number of objects sharing samples
Detailed Description
Base class for density estimation strategies.
Constructor & Destructor Documentation
DensityEstimator ()
default constructor
The default constructor: samples is NULL in this case. This makes it necessary to check for NULL in the copy constructor, assignment operator, and destructor.
DensityEstimator (const String & density_estimator)
standard constructor for envelope
Envelope constructor only needs to extract enough data to properly execute get_density_estimator, since DensityEstimator(BaseConstructor) builds the actual base class data for the derived transformations.
References DensityEstimator::get_density_estimator().
DensityEstimator (const DensityEstimator & density_estimator)
copy constructor
Copy constructor manages sharing of densityEstimatorand incrementing of referenceCount.
References DensityEstimator::referenceCount.
~DensityEstimator () virtual
destructor
Destructor decrements referenceCount and only deletes dataTransRep when referenceCount reaches zero.
References DensityEstimator::referenceCount.
Member Function Documentation
DensityEstimator operator= (const DensityEstimator & density_estimator)
assignment operator
Assignment operator decrements referenceCount for old dataTransRep, assigns new dataTransRep, and increments referenceCount for new dataTransRep.
References DensityEstimator::referenceCount.
void marginalize (size_t dim, DensityEstimator & estimator) virtual
marginalization operations
marginalizes over dim
Reimplemented in GaussianKDE.
References DensityEstimator::marginalize().
Referenced by DensityEstimator::marginalize().
DensityEstimator * get_density_estimator (const String & density_estimator_type) static private
Used only by the envelope constructor to initialize densityEstimator to the appropriate derived type.
Referenced by DensityEstimator::DensityEstimator().
The documentation for this class was generated from the following files:
DensityEstimator.hpp
DensityEstimator.cpp