PECOS: LinearAlgebra.hpp File Reference
LinearAlgebra.hpp File Reference
Functions used to solve systems of linear equations.
Functions
template<typename O , typename T >
void reshape (Teuchos::SerialDenseMatrix< O, T > &matrix, O M, O N)
Reshape a matrix only if the sizes of the matrices differ.
template<typename O , typename T >
void resize (Teuchos::SerialDenseVector< O, T > &v, O n)
Reshape a vector only if the sizes of the vectors differ.
template<typename O , typename T >
void fill_column (int col_number, const Teuchos::SerialDenseMatrix< O, T > &source, Teuchos::SerialDenseMatrix< O, T > &target)
Fill a column of a matrix with the contents of a flattened matrix. The matrix is flattened so that one column proceeds the next.
template<typename O , typename T >
void append_column (const Teuchos::SerialDenseVector< O, T > &vector, Teuchos::SerialDenseMatrix< O, T > &matrix)
Append a column vector to a matrix.
template<typename O , typename T >
void delete_column (O col_num, Teuchos::SerialDenseMatrix< O, T > &matrix, bool resize=true)
Delete a column from a matrix.
template<typename O , typename T >
void append_row (const Teuchos::SerialDenseVector< O, T > &vector, Teuchos::SerialDenseMatrix< O, T > &matrix)
Append a row vector to a matrix.
template<typename O , typename T >
void deleteRow (O row_num, Teuchos::SerialDenseMatrix< O, T > &matrix, bool resize=true)
template<typename O , typename T >
void row_append (const Teuchos::SerialDenseMatrix< O, T > &source, Teuchos::SerialDenseMatrix< O, T > &target)
Append a matrix to the bottom of another matrix.
template<typename O , typename T >
void column_append (const Teuchos::SerialDenseMatrix< O, T > &source, Teuchos::SerialDenseMatrix< O, T > &target)
Append a matrix to the right hand side of another matrix.
template<typename O , typename T >
void fill_row (int row_number, const Teuchos::SerialDenseMatrix< O, T > &source, Teuchos::SerialDenseMatrix< O, T > &target)
Fill a row of a matrix with the contents of a flattened matrix. The matrix is flattened so that one column proceeds the next.
template<typename O , typename T >
void fill_column (int col_number, const T *source, Teuchos::SerialDenseMatrix< O, T > &target)
Fill a column of a matrix with the contents of an array.
template<typename O , typename T >
void transpose (Teuchos::SerialDenseMatrix< O, T > &matrix, Teuchos::SerialDenseMatrix< O, T > &matrix_transpose)
Return the transpose of a matrix.
template<typename O , typename T >
bool weakScalarVectorLessThan (const Teuchos::SerialDenseVector< O, T > &v1, const Teuchos::SerialDenseVector< O, T > &v2)
template<typename O , typename T >
void permute_matrix_rows (Teuchos::SerialDenseMatrix< O, T > &A, IntVector &P)
template<typename O , typename T >
void permute_matrix_columns (Teuchos::SerialDenseMatrix< O, T > &A, IntVector &P)
template<typename O , typename T >
T trace (Teuchos::SerialDenseMatrix< O, T > &A)
int cholesky (RealMatrix &A, RealMatrix &result, Teuchos::EUplo uplo, bool for_lapack)
computes the Cholesky factorization of a real symmetric positive definite matrix A.
int solve_using_cholesky_factor (RealMatrix &L, RealMatrix &B, RealMatrix &result, Teuchos::EUplo uplo)
Solves a system of linear equations A*X = B with a symmetric positive definite matrix A using a precomputed Cholesky factorization.
int cholesky_solve (RealMatrix &A, RealMatrix &B, RealMatrix &result, Real &rcond)
Solves a system of linear equations A*X = B with a symmetric positive definite matrix A using the Cholesky factorization. The cholesky factorization is computed internally.
void qr_solve (RealMatrix &A, RealMatrix &B, RealMatrix &result, Teuchos::ETransp trans=Teuchos::NO_TRANS)
Solves overdetermined or underdetermined real linear systems involving an M-by-N matrix A, or its transpose, using a QR or LQ factorization of A. It is assumed that A has full rank.
void svd_solve (RealMatrix &A, RealMatrix &B, RealMatrix &result_0, RealVector &result_1, int &rank, Real rcond=-1)
Compute the minimum-norm solution to a real linear least squares problem: minimize 2-norm(| b - A*x |) using the singular value decomposition (SVD) of A. A is an M-by-N matrix which may be rank-deficient.
void substitution_solve (RealMatrix &A, RealMatrix &B, RealMatrix &result, Teuchos::ETransp trans=Teuchos::NO_TRANS, Teuchos::EUplo uplo=Teuchos::UPPER_TRI, Teuchos::EDiag diag=Teuchos::NON_UNIT_DIAG)
Solves a triangular system.
int qr_factorization_update_insert_column (RealMatrix &Q, RealMatrix &R, RealMatrix &col, int iter)
Returns the QR factorization of [A a] given a qr factorization of A.
int cholesky_factorization_update_insert_column (RealMatrix &A, RealMatrix &U, RealMatrix &col, int iter, Real delta=0)
Return the cholesky factorization of a positive definite grammian matrix [A a]'*[A a] given a cholesky factorization of A'*A.
void givens_rotation (RealVector &x, RealVector &x_rot, RealMatrix &givensMatrix)
Compute the givens rotation of a (2x1) vector x and also returned the rotated vector.
void cholesky_factorization_update_delete_column (RealMatrix &U, int col_index, int N)
Update the cholesky factorization of a positive definite grammian matrix A'A when a column is deleted from A.
int conjugate_gradients_solve (RealMatrix &A, RealVector &b, RealVector &x, Real &relative_residual_norm, Real cg_tol, int max_iter, int verbosity)
void equality_constrained_least_squares_solve (RealMatrix &A, RealVector &b, RealMatrix &C, RealVector &d, RealMatrix &x, int verbosity=0)
Solve the linear equality-constrained least squares (LSE) problem:
void cholesky_inverse (RealMatrix &L, RealMatrix &result, Teuchos::EUplo uplo)
Computes the inverse of a real symmetric positive definite matrix A using the Cholesky factorization A = L*L**T or A = U**T*U.
void pivoted_qr_factorization (RealMatrix &A, RealMatrix &Q, RealMatrix &R, IntVector &p)
void truncated_pivoted_lu_factorization (RealMatrix &A, RealMatrix &result_0, RealMatrix &result_1, IntVector &values_0, int max_iters, int num_initial_rows)
Compute an LU factorization with parital row pivoting of the m-by-n matrix A. The factorization has the form A = P * L * U where P is the permutation matrix, L is lower triangular with unit diagonal elements and U is upper triangular.
template<typename O , typename T >
void eye (int N, Teuchos::SerialDenseMatrix< O, T > &result)
template<typename O , typename T >
void unit_vector (int n, int k, Teuchos::SerialDenseVector< O, T > &result)
void lu_inverse (RealMatrix &L, RealMatrix &U, IntVector &p, RealMatrix &LU_inv)
void lu_solve (RealMatrix &A, RealMatrix &B, RealMatrix &result, bool copy, Teuchos::ETransp trans)
Detailed Description
Functions used to solve systems of linear equations.
Author
John D. Jakeman
Date
2 January 2012
Function Documentation
void Pecos::fill_column (int col_number, const T * source, Teuchos::SerialDenseMatrix< O, T > & target)
Fill a column of a matrix with the contents of an array.
The user must ensure that the length of source is consistent with the target. This cannot be used to store a flattened matrix using source.values() if source is a sub view.
References Pecos::fill_column().
void Pecos::transpose (Teuchos::SerialDenseMatrix< O, T > & matrix, Teuchos::SerialDenseMatrix< O, T > & matrix_transpose)
Return the transpose of a matrix.
Parameters
matrix (input) the original matrix
matrix_transpose (output) the transpose of the original matrix
References Pecos::transpose().
Referenced by Pecos::transpose().
int cholesky (RealMatrix & A, RealMatrix & result, Teuchos::EUplo uplo, bool for_lapack)
computes the Cholesky factorization of a real symmetric positive definite matrix A.
The factorization has the form A = U**T * U, if UPLO = 'U', or A = L * L**T, if UPLO = 'L', where U is an upper triangular matrix and L is lower triangular.
Parameters
A (input) DOUBLE PRECISION positive-definite matrix, dimension (N,N)
for_lapack flag specifying whether the cholesky factor is to be used for a lapack function. If true then if A = L * L**T the upper part is not referenced. If false the upper part is filled in with zeros. Similarly for A = U**T * U
int solve_using_cholesky_factor (RealMatrix & L, RealMatrix & B, RealMatrix & result, Teuchos::EUplo uplo)
Solves a system of linear equations A*X = B with a symmetric positive definite matrix A using a precomputed Cholesky factorization.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
int cholesky_solve (RealMatrix & A, RealMatrix & B, RealMatrix & result, Real & rcond)
Solves a system of linear equations A*X = B with a symmetric positive definite matrix A using the Cholesky factorization. The cholesky factorization is computed internally.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
Parameters
rcond (INPUT/OUTPUT) if rcond < 0 compute the reciprocal of the condition number of A and store the result in rcond on output. if rcond > 0 rcond is not computed.
void qr_solve (RealMatrix & A, RealMatrix & B, RealMatrix & result, Teuchos::ETransp trans = Teuchos::NO_TRANS)
Solves overdetermined or underdetermined real linear systems involving an M-by-N matrix A, or its transpose, using a QR or LQ factorization of A. It is assumed that A has full rank.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
Todo:
at the moment A cannot be rank-defficient. implement using dgelsy.
void svd_solve (RealMatrix & A, RealMatrix & B, RealMatrix & result_0, RealVector & result_1, int & rank, Real rcond = -1)
Compute the minimum-norm solution to a real linear least squares problem: minimize 2-norm(| b - A*x |) using the singular value decomposition (SVD) of A. A is an M-by-N matrix which may be rank-deficient.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
The effective rank of A is determined by treating as zero those singular values which are less than RCOND times the largest singular value.
Parameters
A (input) DOUBLE PRECISION matrix, dimension (M,N) On entry, the M-by-N matrix A.
B (input) DOUBLE PRECISION matrix, dimension (M,NRHS) On entry, the M-by-NRHS right hand side matrix B.
result_1 (output) DOUBLE PRECISION matrix, dimension (min(M,N)) The singular values of A in decreasing order. The condition number of A in the 2-norm = S(1)/S(min(m,n)).
RCOND (input) DOUBLE PRECISION RCOND is used to determine the effective rank of A. Singular values S(i) <= RCOND*S(1) are treated as zero. If RCOND < 0, machine precision is used instead.
RANK (output) INTEGER The effective rank of A, i.e., the number of singular values which are greater than RCOND*S(1).
result_0 (output) DOUBLE PRECISION matrix, dimension (M,NRHS) On exit, X is the N-by-NRHS solution matrix. If m >= n and RANK = n, the residual sum-of-squares for the solution in the i-th column is given by the sum of squares of elements n+1:m in that column.
Todo:
implement dgelsd which is faster than dgelss
void substitution_solve (RealMatrix & A, RealMatrix & B, RealMatrix & result, Teuchos::ETransp trans = Teuchos::NO_TRANS, Teuchos::EUplo uplo = Teuchos::UPPER_TRI, Teuchos::EDiag diag = Teuchos::NON_UNIT_DIAG)
Solves a triangular system.
Solves a triangular system of the form A * X = B or A**T * X = B,
where A is a triangular matrix of order N, and B is an N-by-NRHS matrix. A check is made to verify that A is nonsingular.
Arguments
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,N) The triangular matrix A. If uplo = Teuchos::UPPER_TRI, the leading N-by-N upper triangular part of the array A contains the upper triangular matrix, and the strictly lower triangular part of A is not referenced. If UPLO = LOWER_TRU, the leading N-by-N lower triangular part of the array A contains the lower triangular matrix, and the strictly upper triangular part of A is not referenced. If DIAG = UNIT_DIAG, the diagonal elements of A are also not referenced and are assumed to be 1.
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the right hand side matrix B. On exit, if INFO = 0, the solution matrix X.
result (output) DOUBLE PRECISION matrix, dimension (N,NRHS) On exit, X is the N-by-NRHS solution matrix.
uplo Specifies whether A is upper or lower traingular
trans Specifies the form of the system of equations: = Teuchos::NO_TRANS: A * X = B (No transpose) = TRANS : A**T * X = B (Transpose)
diag Specifies if the matrix is unit diagonal
int qr_factorization_update_insert_column (RealMatrix & Q, RealMatrix & R, RealMatrix & col, int iter)
Returns the QR factorization of [A a] given a qr factorization of A.
QR facorization is but this update is only
Parameters
Q (input/output) The (M x iter) orthogonal matrix. On entry contains the original (M x tier-1) orthogonal matrix Q with an additional (M x 1) possibly unitialized column allocated to allow the storage of the larger updated matrix Q. On exit Q is the updated orthogonal matrix factor appended to it . Must have all excess memory initialized to zero.
R (input/output) The (iter x iter) upper triangular matrix. On entry contains the (iter-1 x iter-1) original matrix R with memory allocated to allow the storage of the larger updated matrix R Must have all excess memory initialized to zero.
col (intput) the new column being added to A.
iter specifies the size of the original Q and R matricies.
Returns
info = 0 update sucessful. If info = 1, the new column was colinear with the active set.
int cholesky_factorization_update_insert_column (RealMatrix & A, RealMatrix & U, RealMatrix & col, int iter, Real delta = 0)
Return the cholesky factorization of a positive definite grammian matrix [A a]'*[A a] given a cholesky factorization of A'*A.
Cholesky facorization is but this update is only
Parameters
A (output) The (M x iter) Matrix used to compute the gramian A'A
U (input/output) The (iter x iter) upper triangular matrix. On entry contains the (iter-1 x iter-1) original matrix U with memory allocated to allow the storage of the larger updated matrix U. Must have all excess memory initialized to zero.
col (intput) the new column being added to A.
iter specifies the size of the original U matrix.
delta Regularization parameter. If delta > 0 the function will return chol([A a]'*[A A] + delta*I)
Returns
info = 0 update sucessful. If info = 1, the new column was colinear with the active set.
void givens_rotation (RealVector & x, RealVector & x_rot, RealMatrix & givensMatrix)
Compute the givens rotation of a (2x1) vector x and also returned the rotated vector.
Parameters
x (intput) (2x1) vector to be rotated
x_rot (ouput) (2x1) rotated vector
givensMatrix (ouput) (2x2) Givens rotation matrix
void cholesky_factorization_update_delete_column (RealMatrix & U, int col_index, int N)
Update the cholesky factorization of a positive definite grammian matrix A'A when a column is deleted from A.
Parameters
U (input/output) The (N x N) upper triangular matrix. On entry contains the (N x N) original matrix U On exit containt the (N-1 x N-1) new matrix U with all entries in the Nth row and column set to zero.
col_index The index of the column to be deleted from A
N the number of rows and columns of U
int conjugate_gradients_solve (RealMatrix & A, RealVector & b, RealVector & x, Real & r_norm, Real cg_tol = 1e-8, int max_iter = 50, int verbosity = 1)
Calculate an approximate solution to Ax=b using the conjugate gradient method
Returns
info = 0 update sucessful. If info = 1, the matrix is not positive definite. info = 2. the matrix contains inf or nan.
void equality_constrained_least_squares_solve (RealMatrix & A, RealVector & b, RealMatrix & C, RealVector & d, RealMatrix & x, int verbosity = 0)
Solve the linear equality-constrained least squares (LSE) problem:
minimize || b - A*x ||_2 subject to C*x = d
where A is an M-by-N matrix, C is a P-by-N matrix, b is a given M-vector, and d is a given P-vector. It is assumed that P <= N <= M+P, and
     rank(C) = P and  rank( (A) ) = N.
                          ( (C) )
These conditions ensure that the LSE problem has a unique solution, which is obtained using a generalized RQ factorization of the matrices (C, A) given by
C = (0 R)*Q, A = Z*T*Q.
Parameters
A (input) DOUBLE PRECISION M-by-N matrix A.
C (input) DOUBLE PRECISION P-by-N matrix B.
b (input) DOUBLE PRECISION M vector On entry, b contains the right hand side vector for the least squares part of the LSE problem.
d (input) DOUBLE PRECISION P vector On entry, d contains the right hand side vector for the constrained equation.
x (output) DOUBLE PRECISION N -vector On exit, X is the solution of the LSE problem.
void cholesky_inverse (RealMatrix & L, RealMatrix & result, Teuchos::EUplo uplo)
Computes the inverse of a real symmetric positive definite matrix A using the Cholesky factorization A = L*L**T or A = U**T*U.
Parameters
U (input) DOUBLE PRECISION NxN matrix U. U is the lower or upper traingular factor L or U from the Cholesky factorization A = L*L**T or A = U**T*U
result (output) DOUBLE PRECISION NxN matrix. On exit result is the inverse of A
void truncated_pivoted_lu_factorization (RealMatrix & A, RealMatrix & result_0, RealMatrix & result_1, IntVector & values_0, int max_iters, int num_initial_rows)
Compute an LU factorization with parital row pivoting of the m-by-n matrix A. The factorization has the form A = P * L * U where P is the permutation matrix, L is lower triangular with unit diagonal elements and U is upper triangular.
/param max_iters the maximum number of pivots to perform. This is distinguishing feature from pivoted_lu_factorization() /param num_initial_rows The first n rows of A which must be included in the factorization before any other row can be included