PECOS: MathTools.hpp File Reference
MathTools.hpp File Reference
Miscelaneous math functions.
Enumerations
enum lp_norm { mt_l1_norm, mt_l2_norm, mt_linf_norm }
Functions
void ind2sub (const IntVector &sizes, int index, int num_elems, IntVector &result)
Map a scalar index of a flat 1D array to the equivalent d-dimensional index.
int sub2ind (const IntVector &sizes, const IntVector &multi_index)
Map a d-dimensional index to the scalar index of the equivalent flat 1D array.
template<typename O , typename T >
void cartesian_product (const std::vector< Teuchos::SerialDenseVector< O, T > > &input_sets, Teuchos::SerialDenseMatrix< O, T > &result, int elem_size)
Compute the cartesian product of an arbitray number of sets.
template<typename O , typename T >
void outer_product (const std::vector< Teuchos::SerialDenseVector< O, T > > &input_sets, Teuchos::SerialDenseVector< O, T > &result)
Construct the outer product of an arbitray number of sets.
template<typename O , typename T >
void range (Teuchos::SerialDenseVector< O, T > &result, T m, T n, T incr=1)
Build a vector containing all integers in [m,n) seperated by incr.
void linspace (RealVector &result, Real a, Real b, int n)
Generate a vector whose n elements are equidistantly spaced in the interval [a,b].
Real round (Real r)
Round a Real to the nearest integer.
bool abs_compare (Real a, Real b)
int nearest_integer (Real x)
Return the nearest integer to x.
Real factorial (int n)
Calulate n!
int nchoosek (int n, int k)
Return the number of possible combinations of k elements that can be chosen from n elements.
Real rescale (Real x, Real a, Real b, int dir)
Transform a point x in the interval [a,b] onto the interval [0,1] and vice versa.
void rescale (RealMatrix &x, const RealVector &domain, int dir)
Transform a point x in the interval onto the hypercube interval and vice versa.
void hypercube_map (RealMatrix &x, const RealVector &domain_in, const RealVector &domain_out, RealMatrix &result)
transform points in domain_in to points in domain_out
void mesh_grid (const IntVector &num_pts_1d, const RealVector &domain, RealMatrix &result)
Construct a d-dimensional mesh on a hyper-rectangle. The meshes are equidistant with respect to each coordinate direction.
void get_multi_dimensional_polynomial_subspace_indices (IntMatrix &B, int *elems, int len_elems, int *pos, int len_pos, int choices_made, int first_pos, int order, int &col)
void get_multi_dimensional_polynomial_indices (int num_dims, int degree, IntMatrix &result)
Get all the multi-dimensional indices of a multi-dimensional polynomial basis with a specified degree sum.
int get_total_degree_from_num_samples (int num_dims, int num_samples)
Get the smallest degree of the total degree polynomial such that the number of terms in the basis is larger than or equal to num_samples.
void set_hypercube_domain (RealVector &result, int num_dims, Real a, Real b)
Get the multi-dimensional hypercube .
void get_permutations (IntMatrix &permutations, int M, int N, unsigned int seed)
Perturb the columns of a matrix.
void compute_hyperbolic_level_subdim_indices (int num_dims, int level, int num_active_dims, Real p, IntMatrix &indices)
void compute_hyperbolic_level_indices (int num_dims, int level, Real p, IntMatrix &indices)
void compute_hyperbolic_indices (int num_dims, int level, Real p, IntMatrix &indices)
void compute_anisotropic_hyperbolic_indices (int num_dims, int level, Real p, RealVector &weights, IntMatrix &indices)
template<typename T >
int argmin (int n, T *x)
Return the index of the element of x with the minimum value.
template<typename T >
int argmax (int n, T *x)
Return the index of the element of x with the maximum value.
template<typename T >
int magnitude_argmax (int n, T *x)
template<typename T >
T sum (int n, T *x)
Return the sum of the elements in the array x.
template<typename O , typename T >
T sum (Teuchos::SerialDenseVector< O, T > &v)
Return the sum of the elements in the vector x.
Real mean (int n, Real *x)
Return the mean of the array x.
Real variance (int n, Real *x, int ddof=1)
Return the sample variance of the array x.
void lp_error (RealMatrix &reference_values, RealMatrix &approximate_values, std::vector< lp_norm > error_norms, RealMatrix &error, IntVector &active_columns, bool normalise=false)
Calculate one of several different types of error norms of a set of vectors.
void latin_hypercube_design (int num_pts, int num_dims, RealMatrix &result, int seed)
Construct a Latin Hyperube Design (LHD)
void compute_next_combination (int num_dims, int level, IntVector &index, bool &extend, int &h, int &t)
void compute_combinations (int num_dims, int level, IntMatrix &indices)
template<typename T >
int sgn (T x)
template<typename T >
int num_non_zeros (T *data, int n)
template<typename T >
double median (std::vector< T > &v)
return the median of a std::vector
template<typename O , typename T >
double median (Teuchos::SerialDenseVector< O, T > &v)
return the median of a RealVector.
template<typename O , typename T >
double pnorm (Teuchos::SerialDenseVector< O, T > &v, double p)
template<typename O , typename T >
O num_nonzeros (Teuchos::SerialDenseVector< O, T > &v)
template<typename O , typename T >
void nonzero (Teuchos::SerialDenseVector< O, T > &v, IntVector &result)
void lhs_indices (int num_dims, int num_pts, int duplication, int seed, IntMatrix &result)
void ilhs (int num_dims, int num_pts, int duplication, int seed, RealMatrix &result)
Construct the improved distributed hypercube sample.
void lhs (int num_dims, int num_pts, int seed, RealMatrix &result)
Construct basic random hypercube sample.
template<typename O , typename T >
void argsort (const Teuchos::SerialDenseVector< O, T > &values, IntVector &result)
template<typename O , typename T >
void argsort (Teuchos::SerialDenseVector< O, T > &v, Teuchos::SerialDenseVector< O, T > &result_0, IntVector &result_1)
template<typename O , typename T >
void magnitude_argsort (const Teuchos::SerialDenseVector< O, T > &values, IntVector &result)
template<typename O , typename T >
int binary_search (T target, Teuchos::SerialDenseVector< O, T > &data)
find the interval containing a target value. Assumes data is in ascending order
template<typename O , typename T >
void reverse (Teuchos::SerialDenseVector< O, T > &v)
Reverse the contents of a vector.
template<typename O , typename T >
void set_difference_matrix_columns (const Teuchos::SerialDenseMatrix< O, T > &A, const Teuchos::SerialDenseMatrix< O, T > &B, IntVector &result)
template<typename MatrixType >
void extract_submatrix_from_column_indices (const MatrixType &A, const IntVector &column_indices, MatrixType &submatrix)
template<typename MatrixType >
void copy_matrix (const MatrixType &source, MatrixType &dest, int num_rows, int num_cols, int start_row=0, int start_col=0)
template<typename VectorType >
void copy_vector (const VectorType &source, VectorType &dest, int num_rows, int start_row=0)
template<typename MatrixType >
void hstack (const MatrixType &source1, const MatrixType &source2, MatrixType &dest)
template<typename O , typename T >
void convert (T a[], int m, int n, std::vector< Teuchos::SerialDenseVector< O, T > > &v)
template<typename O , typename T >
void convert (T a[], int m, int n, std::set< Teuchos::SerialDenseVector< O, T > > &s)
template<typename O , typename T >
void convert (const std::vector< Teuchos::SerialDenseVector< O, T > > &V, Teuchos::SerialDenseMatrix< O, T > &M)
Convert a std::vector of vectors to a matrix.
template<typename T , typename Operator >
void accumulate (const std::vector< std::vector< T > > &vectors, std::vector< T > &result, Operator op)
template<typename T >
bool is_nan_or_inf (T x)
template<typename O , typename T >
bool has_nan_or_inf (const Teuchos::SerialDenseMatrix< O, T > &matrix)
void get_column_norms (RealMatrix &A, RealVector &result)
Detailed Description
Miscelaneous math functions.
Author
John D. Jakeman
Date
31 October 2011
Function Documentation
void ind2sub (const IntVector & sizes, int index, int num_elems, IntVector & result)
Map a scalar index of a flat 1D array to the equivalent d-dimensional index.
Example:
Parameters
sizes the number of elems in each dimension. For a 2D index sizes = [numRows, numCols]
index the scalar index
num_elems the total number of elements in the d-dimensional matrix
Returns
result the d-dimensional index
int sub2ind (const IntVector & sizes, const IntVector & multi_index)
Map a d-dimensional index to the scalar index of the equivalent flat 1D array.
Example:
Parameters
sizes the number of elems in each dimension. For a 2D index sizes = [numRows, numCols]
multi_index the d-dimensional index
Returns
scalar_index the scalar index of the flat array
void Pecos::cartesian_product (const std::vector< Teuchos::SerialDenseVector< O, T > > & input_sets, Teuchos::SerialDenseMatrix< O, T > & result, int elem_size)
Compute the cartesian product of an arbitray number of sets.
These sets can consist of numbers of be themselves sets of vectors
Parameters
inputSets the sets to be used in the cartesian product
elem_size the size of the vectors within each set.
Returns
the cartesian product
References Pecos::cartesian_product().
Referenced by Pecos::cartesian_product(), and RegressOrthogPolyApproximation::gridSearchFunction().
void Pecos::outer_product (const std::vector< Teuchos::SerialDenseVector< O, T > > & input_sets, Teuchos::SerialDenseVector< O, T > & result)
Construct the outer product of an arbitray number of sets.
Example:
Parameters
input_sets "Vector.hpp" of sets to be used in the outer product
Returns
result the outer product
References Pecos::outer_product().
Referenced by Pecos::outer_product().
void Pecos::range (Teuchos::SerialDenseVector< O, T > & result, T m, T n, T incr = 1)
Build a vector containing all integers in [m,n) seperated by incr.
E.g Range(1, 10, 2) -> [1,3,5,7,9]
References Pecos::range().
Referenced by RegressOrthogPolyApproximation::compressed_sensing(), LoguniformRandomVariable::dz_ds_factor(), BetaRandomVariable::pdf(), TriangularRandomVariable::pdf_gradient(), Pecos::range(), Pecos::reverse(), LoguniformRandomVariable::standard_deviation(), BetaRandomVariable::update_boost(), LoguniformRandomVariable::variance(), UniformRandomVariable::variance(), and BetaRandomVariable::variance().
void linspace (RealVector & result, Real a, Real b, int n)
Generate a vector whose n elements are equidistantly spaced in the interval [a,b].
Parameters
[a,b] the range
n the number of times the interval [a,b] is divided
Returns
vec n numbers equidistant is [a,b]
int nearest_integer (Real x)
Return the nearest integer to x.
Parameters
x the value return int the neartest integer to x
Real factorial (int n)
Calulate n!
Parameters
n the factorial of interest
Returns
n!
int nchoosek (int n, int k)
Return the number of possible combinations of k elements that can be chosen from n elements.
Parameters
n number of elements
k the number of elements to be chosen. k<=n.
Returns
the total number of combinations.
Real rescale (Real x, Real a, Real b, int dir)
Transform a point x in the interval [a,b] onto the interval [0,1] and vice versa.
Parameters
x the value to be transformed
[a,b] the new/old interval
dir specifies whether to map to [a,b] or from [a,b]. That is dir=0 returns [0,1] -> [a,b] dir!=0 returns [a,b] -> [0,1]
Returns
the rescaled value
void rescale (RealMatrix & x, const RealVector & domain, int dir)
Transform a point x in the interval onto the hypercube interval and vice versa.
Parameters
x the value to be transformed
[a,b] the new/old interval
dir specifies whether to map to [a,b] or from [a,b]. That is dir=0 returns [0,1] -> [a,b] dir!=0 returns [a,b] -> [0,1]
Returns
the rescaled value
void mesh_grid (const IntVector & num_pts_1d, const RealVector & domain, RealMatrix & result)
Construct a d-dimensional mesh on a hyper-rectangle. The meshes are equidistant with respect to each coordinate direction.
Parameters
num_pts_1d array specifying the number of meshpoints for each dimension
domain the min and max value of each dimension. That is
Returns
the multi-dimensional mesh coordinates. (num_dims x num_pts) array. num_pts = num_pts_1d[0]*...*num_pts_1d[d-1]
void get_multi_dimensional_polynomial_subspace_indices (IntMatrix & B, int * elems, int len_elems, int * pos, int len_pos, int choices_made, int first_pos, int order, int & row)
Get all the multi-dimensional indices of a multi-dimensional polynomial basis with a specified degree sum. A cleaner interface is provided by GetMultiDimensionalPolynomial_indices()
Returns
B the multi-dimensional indices
void get_multi_dimensional_polynomial_indices (int num_dims, int degree, IntMatrix & result)
Get all the multi-dimensional indices of a multi-dimensional polynomial basis with a specified degree sum.
Parameters
num_dims the dimensionailty
degree the degree sum of the polynomial indices wanted
Returns
B the multi-dimensional polynomial_indices
void set_hypercube_domain (RealVector & result, int num_dims, Real a, Real b)
Get the multi-dimensional hypercube .
Parameters
num_dims the dimension of the computational domain.
int Pecos::argmin (int n, T * x)
Return the index of the element of x with the minimum value.
References Pecos::argmin().
Referenced by Pecos::argmin().
int Pecos::argmax (int n, T * x)
Return the index of the element of x with the maximum value.
References Pecos::argmax().
Referenced by Pecos::argmax().
T Pecos::sum (int n, T * x)
Return the sum of the elements in the array x.
References Pecos::sum().
Referenced by NumericGenOrthogPolynomial::cc_bounded_integral(), NumericGenOrthogPolynomial::fejer_semibounded_integral(), NumericGenOrthogPolynomial::fejer_unbounded_integral(), OrthogonalPolynomial::gauss_check(), NumericGenOrthogPolynomial::hermite_unbounded_integral(), NumericGenOrthogPolynomial::inner_product(), NumericGenOrthogPolynomial::laguerre_semibounded_integral(), NumericGenOrthogPolynomial::legendre_bounded_integral(), HistogramBinRandomVariable::mean(), Pecos::median(), Pecos::sum(), and LagrangeInterpPolynomial::type1_gradient().
T Pecos::sum (Teuchos::SerialDenseVector< O, T > & v)
Return the sum of the elements in the vector x.
This will not return the same result as sum(int n, T* x) if the vector is a subvector of another vector. That is stride does not equal the number of rows.
References Pecos::sum().
Real mean (int n, Real * x)
Return the mean of the array x.
Real variance (int n, Real * x, int ddof = 1)
Return the sample variance of the array x.
Parameters
ddof Delta Degrees of Freedom (ddof). The divisor used in calculations is , where $fN$f represents the number of elements. By default ddof is one.
void lp_error (RealMatrix & reference_values, RealMatrix & approximate_values, std::vector< lp_norm > error_norms, RealMatrix & error, IntVector & active_columns, bool normalise = false)
Calculate one of several different types of error norms of a set of vectors.
Each column of the reference_values matrix is considered independently with the correpsonding column in the approximation_values. The error between the each set of two columns tested is returned.
Parameters
reference_values a matrix containing the reference values
approximate_values a matrix containig the approximate values
active_columns specifies which set of columns to consider. If empty all columns are considered normalise if true the error norms are normalised. The l_inf norm is normalised by the half the range of the data in the reference_values column. The L_2 norm is normalised by the standard deviation of the data in the reference values column.
int Pecos::sgn (T x)
Return the sign of x.
Returns
1 if the corresponding element of x is greater than zero; 0 if the corresponding element of X equals zero; -1 if the corresponding element of X is less than zero
References Pecos::sgn().
Referenced by Pecos::sgn().
void Pecos::reverse (Teuchos::SerialDenseVector< O, T > & v)
Reverse the contents of a vector.
Useful for changing an ordered array to/from ascending/descending order
References Pecos::range(), Pecos::reshape(), Pecos::resize(), and Pecos::reverse().
Referenced by Pecos::reverse().
void Pecos::convert (T a[], int m, int n, std::vector< Teuchos::SerialDenseVector< O, T > > & v)
Convert a static array to a "Vector.hpp" of vectors.
Parameters
a array to be converted
n the number of vectors
m the size of each "Vector.hpp"
Returns
v the "Vector.hpp" of vectors
References Pecos::convert().
Referenced by Pecos::convert().
void Pecos::convert (T a[], int m, int n, std::set< Teuchos::SerialDenseVector< O, T > > & s)
Convert a static array to a weakly ordered multiset of vectors. Set allows for multiple keys with the same value.
Parameters
a array to be converted
n the number of vectors
m the size of each "Vector.hpp"
Returns
s the set
References Pecos::convert().
void Pecos::convert (const std::vector< Teuchos::SerialDenseVector< O, T > > & V, Teuchos::SerialDenseMatrix< O, T > & M)
Convert a std::vector of vectors to a matrix.
Each element of the std::vector becomes a column of the matrix
References Pecos::convert().
void Pecos::accumulate (const std::vector< std::vector< T > > & vectors, std::vector< T > & result, Operator op)
Add a set of vectors together.
Parameters
vectors set of vectors to be added
result the accumualted values
References Pecos::accumulate().
Referenced by Pecos::accumulate().